<?php
/**
 * @var Shopworks_Billink_Block_Fee_Checkout_Total_Fee $this
 */
?>

<?php if ($this->getDisplayMode() === Shopworks_Billink_Block_Fee_Checkout_Total_Fee::DISPLAY_MODE_BOTH): ?>
    <tr>
        <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
            <strong>
                <?php endif; ?>
                <?php echo $this->escapeHtml($this->getTotal()->getTitle()); ?> <?php echo $this->getTaxLabel(false); ?>
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
            </strong>
        <?php endif; ?>
        </td>
        <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
            <strong>
                <?php endif; ?>
                <?php echo $this->helper('checkout')->formatPrice($this->getValue(false)) ?>
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
            </strong>
        <?php endif; ?>
        </td>
    </tr>
    <tr>
        <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
            <strong>
                <?php endif; ?>
                <?php echo $this->escapeHtml($this->getTotal()->getTitle()); ?> <?php echo $this->getTaxLabel(true); ?>
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
            </strong>
        <?php endif; ?>
        </td>
        <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
            <strong>
                <?php endif; ?>
                <?php echo $this->helper('checkout')->formatPrice($this->getValue(true)) ?>
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
            </strong>
        <?php endif; ?>
        </td>
    </tr>
<?php else: ?>
    <?php if ($this->getDisplayMode() === Shopworks_Billink_Block_Fee_Checkout_Total_Fee::DISPLAY_MODE_EXCL): ?>
        <?php $_value = $this->getValue(false); ?>
    <?php else: ?>
        <?php $_value = $this->getValue(true); ?>
    <?php endif; ?>
    <tr>
        <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
            <strong>
                <?php endif; ?>
                <?php echo $this->escapeHtml($this->getTotal()->getTitle()); ?>
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
            </strong>
        <?php endif; ?>
        </td>
        <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
            <strong>
                <?php endif; ?>
                <?php echo $this->helper('checkout')->formatPrice($_value) ?>
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
            </strong>
        <?php endif; ?>
        </td>
    </tr>
<?php endif; ?>
