#!/usr/bin/env bash

: "---------------------------------------------------------------------------------------------------------------
${HOME}/workspace/openmage/shell/om-generate-phpini                                           # 2 sec
-----------------------------------------------------------------------------------------------------------------"

# This script takes the system-configured php.ini for the PHP version that is applicable to this app, and adds our modifications into a new php.ini

# set -e      # Exit immediately if a command exits with a non-zero status
set -u      # Treat unset variables as an error when substituting

# Set User Environment
. ${HOME}/.profile || die "Failed to source ${HOME}/.profile"

cm

TARGET_PHP_INI=./etc/php.ini
COPY_PHP_INI=./php.ini
TARGET_USER_INI=_user.ini
PHP_VERSION=$(php -c etc/php.ini -r "echo phpversion();") || {
  echo "Fatal error: Unable to determine PHP version"
  exit 1
}

# Backup php.ini
PHP_INI_BACKUP="./etc/php.ini.bak-$(date +%F_%H%M%S)"

if [ ! -f ${TARGET_PHP_INI} ]; then
  echo "${TARGET_PHP_INI} does not exist, so it will not be backed up."
else
  echo "Backing up existing ${TARGET_PHP_INI} to ${PHP_INI_BACKUP}"
  cp ${TARGET_PHP_INI} ${PHP_INI_BACKUP}
  
  if [ $? -ne 0 ]; then
    echo "Fatal error: Failed to backup ${TARGET_PHP_INI}. Keeping current configuration."
    exit
  fi
  echo "Existing ${TARGET_PHP_INI} backed up to ${PHP_INI_BACKUP}";
fi

# Backup _user.ini
USER_INI_BACKUP="./etc/${TARGET_USER_INI}.bak-$(date +%F_%H%M%S)"

if [ ! -f ${TARGET_USER_INI} ]; then
  echo "${TARGET_USER_INI} does not exist, so it will not be backed up."
else
  echo "Backing up existing ${TARGET_USER_INI} to ${USER_INI_BACKUP}"
  cp ${TARGET_USER_INI} ${USER_INI_BACKUP}
  
  if [ $? -ne 0 ]; then
    echo "Fatal error: Failed to backup ${TARGET_USER_INI}. Keeping current configuration."
    exit
  fi
  echo "Existing ${TARGET_USER_INI} backed up to ${USER_INI_BACKUP}";
fi

# Create new php.ini
SHARED_PHP_INI=$(pwd)/etc/php-dist.ini
LOCAL_PHP_INI=$(pwd)/etc/php-local.ini
NOW=`date`

# Truncate:
: > ${TARGET_PHP_INI}

printf "; File: ${TARGET_PHP_INI}\n" >> ${TARGET_PHP_INI}
printf "; This file is created automatically, do not edit\n" >> ${TARGET_PHP_INI}
printf "; PHP version: ${PHP_VERSION}\n" >> ${TARGET_PHP_INI}
printf "; Created: %s\n" "$NOW" >> ${TARGET_PHP_INI}

printf "\n; ---------------------- ${SHARED_PHP_INI} ----------------------\n\n" >> ${TARGET_PHP_INI}
cat ${SHARED_PHP_INI} >> ${TARGET_PHP_INI}

printf "\n; ---------------------- ${LOCAL_PHP_INI} ----------------------\n\n" >> ${TARGET_PHP_INI}
cat ${LOCAL_PHP_INI} >> ${TARGET_PHP_INI}

# Sometimes the OS INI has no unix line endings
dos2unix -k ${TARGET_PHP_INI}

# Copy to new location
cp ${TARGET_PHP_INI} ${COPY_PHP_INI}

# Create new _user.ini
SHARED_USER_INI=$(pwd)/etc/.user-dist.ini
LOCAL_USER_INI=$(pwd)/etc/.user-local.ini
NOW=`date`

# Truncate:
: > ${TARGET_USER_INI}

printf "; File: ${TARGET_USER_INI}\n" >> ${TARGET_USER_INI}
printf "; This should be used as Additional PHP Directives in Plesk\n" >> ${TARGET_USER_INI}
printf "; This file is created automatically, do not edit\n" >> ${TARGET_USER_INI}
printf "; PHP version: ${PHP_VERSION}\n" >> ${TARGET_USER_INI}
printf "; Created: %s\n" "$NOW" >> ${TARGET_USER_INI}

printf "\n; ---------------------- ${SHARED_USER_INI} ----------------------\n\n" >> ${TARGET_USER_INI}
cat ${SHARED_USER_INI} >> ${TARGET_USER_INI}

printf "\n; ---------------------- ${LOCAL_USER_INI} ----------------------\n\n" >> ${TARGET_USER_INI}
cat ${LOCAL_USER_INI} >> ${TARGET_USER_INI}

# Sometimes the OS INI has no unix line endings
dos2unix -k ${TARGET_USER_INI}

echo "Done"
