#!/bin/bash

: '---------------------------------------------------------------------------------------------------------------
${HOME}/workspace/openmage/shell/om-sync-feeds                                                # 0 sec

- Sync media feeds from media to root and protected/
- @todo: Automated upstream instead of this script
-----------------------------------------------------------------------------------------------------------------'

export NO_DEV=1

. ${HOME}/.profile || die "Failed to load ~/.profile"
cm || die "Failed to go to the openmage directory"
. ./shell/cron-bootstrap.sh || die "Failed to run ./shell/cron-bootstrap.sh"

rsync -rhi --times --update --stats --perms --info=progress2  ./media/feedsA9B1/*.xml*  ./
rsync -rhi --times --update --stats --perms --info=progress2  ./media/feedsA9B1/*.xml*  ./protected/

. ./shell/cron-wrapup.sh
