~/httpdocs/deheerhoreca-magento/var/log/*.log {
  daily
  copytruncate
  dateext
  rotate 7
  missingok
  notifempty
}

~/httpdocs/deheerhoreca-magento/var/log/*.err {
  daily
  copytruncate
  dateext
  rotate 7
  missingok
  notifempty
}

~/httpdocs/deheerhoreca-magento/var/log/*.jsonl {
  daily
  copytruncate
  dateext
  rotate 7
  missingok
  notifempty
}
