/var/www/vhosts/chefstore.nl/httpdocs/deheerhoreca-magento/var/log/*.log {
    size 10M
    copytruncate
    create
    dateext
    rotate 4
    compress
}

/var/www/vhosts/chefstore.nl/httpdocs/deheerhoreca-magento/var/log/*.jsonl {
    size 10M
    copytruncate
    create
    dateext
    rotate 4
    compress
}
