log_errors_max_len                                      = 0
display_errors                                          = On
display_startup_errors                                  = On
log_errors                                              = On
error_log                                               = ./log/php_error.log
error_reporting                                         = -1
max_execution_time                                      = 7200
memory_limit                                            = 4g

# Sometimes we have big stuff. Also needs to be added to open_basedir
upload_tmp_dir                                          = /tmp_intel
sys_temp_dir                                            = /tmp_intel

; # Elastic APM 1.12.0 on PHP 8.1 -- BROKEN?
; extension=/var/www/vhosts/chefstore.nl/apm_agent_php/apm_agent_php-1.12.0/opt/elastic/apm-agent-php/extensions/elastic_apm-20210902.so
; elastic_apm.bootstrap_php_part_file=/var/www/vhosts/chefstore.nl/apm_agent_php/apm_agent_php-1.12.0/opt/elastic/apm-agent-php/src/bootstrap_php_part.php

; elastic_apm.enabled                                   = 1
; elastic_apm.environment                               = production
; elastic_apm.log_level_syslog                          = "INFO"
; elastic_apm.log_level_stderr                          = "WARNING"
; elastic_apm.log_file                                  = "/var/log/elastic_apm_php.log"
; elastic_apm.secret_token                              = trekpopbierslet
; elastic_apm.server_url                                = https://rum.chefstore.nl:8200
; elastic_apm.service_name                              = chefstore_nl_cmd
; elastic_apm.server_timeout                            = 10s
; elastic_apm.transaction_max_spans                     = 250
; elastic_apm.verify_server_cert                        = 0
