<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Block_Adminhtml_Setup extends Mage_Adminhtml_Block_Widget_Form_Container
{
    public function __construct()
    {
        parent::__construct();
        $this->_objectId   = 'euvat_setup';
        $this->_blockGroup = 'euvatgrouper';
        $this->_controller = 'adminhtml';
        $this->_mode       = 'setup';

        $this->_removeButton('back');
        $this->_removeButton('save');

        $this->_addButton('save', array(
            'label'     => Mage::helper('adminhtml')->__('Run Setup'),
            'onclick'   => 'setupForm.submit();',
            'class'     => 'save',
        ), 1);
    }

    public function getHeaderText()
    {
        return Mage::helper('euvatgrouper')->__('EU VAT Enhanced Setup');
    }

    public function getHeaderCssClass()
    {
        return 'head-' . strtr($this->_controller, '_', '-');
    }

}