<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Model_Tax_Calculation extends Mage_Tax_Model_Calculation {

	/**
	 * Get request object with information necessary for getting tax rate
	 * Request object contain:
	 *  country_id (->getCountryId())
	 *  region_id (->getRegionId())
	 *  postcode (->getPostcode())
	 *  customer_class_id (->getCustomerClassId())
	 *  store (->getStore())
	 *
	 * @param   null|false|Varien_Object $shippingAddress
	 * @param   null|false|Varien_Object $billingAddress
	 * @param   null|int $customerTaxClass
	 * @param   null|int $store
	 * @return  Varien_Object
	 */
	public function getRateRequest(
		$shippingAddress = null,
		$billingAddress = null,
		$customerTaxClass = null,
		$store = null)
	{
		if ($shippingAddress === false && $billingAddress === false && $customerTaxClass === false) {
			return $this->getRateOriginRequest($store);
		}
		$address = new Varien_Object();
		$customer = $this->getCustomer();
		$basedOn = Mage::getStoreConfig(Mage_Tax_Model_Config::CONFIG_XML_PATH_BASED_ON, $store);

		if (($shippingAddress === false && $basedOn == 'shipping')
		    || ($billingAddress === false && $basedOn == 'billing')
		) {
			$basedOn = 'default';
		} else {
			if ((($billingAddress === false || is_null($billingAddress) || !$billingAddress->getCountryId())
			     && $basedOn == 'billing')
			    || (($shippingAddress === false || is_null($shippingAddress) || !$shippingAddress->getCountryId())
			        && $basedOn == 'shipping')
			) {
				if ($customer) {
					$defBilling = $customer->getDefaultBillingAddress();
					$defShipping = $customer->getDefaultShippingAddress();

					if ($basedOn == 'billing' && $defBilling && $defBilling->getCountryId()) {
						$billingAddress = $defBilling;
					} else if ($basedOn == 'shipping' && $defShipping && $defShipping->getCountryId()) {
						$shippingAddress = $defShipping;
					} else {
						$basedOn = 'default';
					}
				} else {
					$basedOn = 'default';
				}
			}
		}

		switch ($basedOn) {
			case 'billing':
				$address = $billingAddress;
				break;
			case 'shipping':
				$address = $shippingAddress;
				break;
			case 'origin':
				$address = $this->getRateOriginRequest($store);
				break;
			case 'default':
				$address
					->setCountryId(Mage::getStoreConfig(
						Mage_Tax_Model_Config::CONFIG_XML_PATH_DEFAULT_COUNTRY,
						$store))
					->setRegionId(Mage::getStoreConfig(Mage_Tax_Model_Config::CONFIG_XML_PATH_DEFAULT_REGION, $store))
					->setPostcode(Mage::getStoreConfig(
						Mage_Tax_Model_Config::CONFIG_XML_PATH_DEFAULT_POSTCODE,
						$store));
				break;
		}

		if (is_null($customerTaxClass) && $customer) {
			$customerTaxClass = $customer->getTaxClassId();
		} elseif (($customerTaxClass === false) || !$customer) {
			$customerTaxClass = Mage::getModel('customer/group')
			                        ->getTaxClassId(Mage_Customer_Model_Group::NOT_LOGGED_IN_ID);
		}

		$request = new Varien_Object();
		$request
			->setCountryId($address->getCountryId())
			->setRegionId($address->getRegionId())
			->setPostcode($address->getPostcode())
			->setStore($store)
			->setCustomerClassId($customerTaxClass);

		$request = $this->requestModification($address, $request, $basedOn);

		return $request;
	}

	public function requestModification($address, $request, $basedOn)
	{
		if(Mage::helper('euvatgrouper')->isModuleActive() && !Mage::helper('euvatgrouper')->isAdmin())
		{
			/** @var Geissweb_Euvatgrouper_Helper_Data $dataHelper */
			$dataHelper = Mage::helper('euvatgrouper');
			$debug = $dataHelper->isDebugMode();
			if($basedOn=='default' || $basedOn=='origin') {
				if($debug) Mage::log("Just returned", null, 'euvatenhanced.log');
				return $request;
			}

			/** @var $request Varien_Object */
			if($debug) Mage::log("Request is: ".get_class($request)."::".json_encode($request->debug()), null, 'euvatenhanced.log');
			$customerSession = Mage::getSingleton('customer/session');

			try {

				// Collect and evaluate the data
				$customer = $customerSession->getCustomer();
				$shopCc = $dataHelper->getShopVatCc(); // Shop Country Code (Shipping from)
				$preCheck = false;

				// Check for shipping to multiple addresses
				/** @var Mage_Sales_Model_Quote $quote */
				//$quote = Mage::getSingleton('checkout/session')->getQuote();
				//if($debug) Mage::log("Quote is: ".json_encode($quote->debug()), null, 'euvatenhanced.log');
				//if($quote->getIsMultiShipping()) {
					/*
					$address = $dataHelper->getCurrentMultiShippingAddress($request, $quote);
					if($address == false) {
						if($debug) Mage::log("Unable to get proper multi shipping quote address.", null, 'euvatenhanced.log');
						return;
					}
					*/
				//}

				// Allow regular Magento tax class application for special customer groups
				if(in_array($customer->getGroupId(), $dataHelper->getRegularTaxCalculationGroups())) {
					if($debug) Mage::log("customer group is set for regular Magento tax calculation: ".$customer->getGroupId(), null, 'euvatenhanced.log');
					return $request;
				}

				//if($debug) Mage::log("basedOn address: ".json_encode($address->debug()), null, 'euvatenhanced.log');

				if(!is_null($address->getCountryId())) {
					$basedOnCc = $address->getCountryId();
				} else {
					if($address->getAddressType()=='shipping') {
						$basedOnCc = Mage::helper('euvatgrouper/customer')->getShippingCountry($customer);
					} else {
						$basedOnCc = Mage::helper('euvatgrouper/customer')->getBillingCountry($customer);
					}
				}
				$customerVatIdCc = (!is_null($address->getVatId())) ? strtoupper(substr($address->getVatId(), 0, 2)) : $basedOnCc;
				if($debug) Mage::log("taxCalc basedOnCC is: $basedOnCc | shopCc is: $shopCc | customerVatIdCc is: $customerVatIdCc", null, 'euvatenhanced.log');

				// Dirty fix for Greece country prefix
				if( $customerVatIdCc == "EL" ) $customerVatIdCc = "GR";

				// We only need to modify the rate request for the "based on" country
				if($request->getCountryId() == $basedOnCc)
				{
					$taxExemptClassId = $dataHelper->getTaxExemptClassId();
					$taxIncludingClassId = $dataHelper->getTaxIncludingClassId();
					$taxIncludingClassIdBusiness = $dataHelper->getTaxIncludingClassIdBusiness();
					if($debug) Mage::log("Current customer group: ".$customer->getGroupId(), null, 'euvatenhanced.log');

					// Change calculation country for MOSS
					if($dataHelper->getUseMossBasedOnVatNumber()
					   && $request->getProductClassId() == $dataHelper->getMossProductsClassId()
					   && $address->getVatId() != ''
					   && ($address->getVatIsValid() == true)
					   && !empty($customerVatIdCc)
					) {
						$request->setCountryId($customerVatIdCc);
						$basedOnCc = $customerVatIdCc;
						if($this->_debug) Mage::log("[EUVAT] MOSS exception VAT according to VAT number country prefix (basedOnCC=$basedOnCc)", null, 'euvatenhanced.log');
					}

					// Prevent using a (billing) VAT-ID not matching the billing country
					if(!empty($basedOnCc) && $customerVatIdCc != $basedOnCc) {
						$preCheck = true;
					}

					if( $address->getVatId() != ''
					    && ($address->getVatIsValid() == true)
					    && ($basedOnCc != '' && $shopCc != $basedOnCc)
					    && $dataHelper->isEuCountry($basedOnCc) )
					{
						//Customer has valid VAT-ID and is not domestic
						if(!$preCheck) {
							$request->setCustomerClassId($taxExemptClassId);
							if($debug) Mage::log("Valid VAT exempt - $basedOn country: $basedOnCc - vatIsValid: ".$address->getVatIsValid()." ClassID: $taxExemptClassId", null, 'euvatenhanced.log');
						} else {
							$request->setCustomerClassId($taxIncludingClassIdBusiness);
							if($debug) Mage::log("Prevention ($customerVatIdCc) $basedOn country: $basedOnCc - vatIsValid: ".$address->getVatIsValid()." ClassID: $taxIncludingClassId", null, 'euvatenhanced.log');
						}

						//Customer has valid VAT-ID and is domestic
					} elseif($address->getVatId() != ''
					          && ($address->getVatIsValid() == true)
					          && ($basedOnCc != '' && $shopCc == $basedOnCc)
                    ){
						$request->setCustomerClassId($taxIncludingClassIdBusiness);
						if($debug) Mage::log("Same $basedOn and shop country - $basedOn country: $basedOnCc - vatIsValid: ".$address->getVatIsValid()." ClassID: $taxIncludingClassId", null, 'euvatenhanced.log');

                        //But exception for MOSS, ToDo: Validate correct taxation
                        if($dataHelper->getUseMossBasedOnVatNumber()
                           && $request->getProductClassId() == $dataHelper->getMossProductsClassId()
                        ) {
                            $request->setCustomerClassId($taxExemptClassId);
                            if($debug) Mage::log("MOSS exception allows domestic billing address", null, 'euvatenhanced.log');
                        }

						//Customer from outside EU
					} elseif ($basedOnCc != '' && !$dataHelper->isEuCountry($basedOnCc)) {
						//$request->setCustomerClassId($taxExemptClassId);
						if($debug) Mage::log("Out of EU from $shopCc - $basedOn country: $basedOnCc - vatIsValid: ".$address->getVatIsValid()." ClassID: $taxExemptClassId", null, 'euvatenhanced.log');

						//Customer is Enduser
					} else {
						if($debug) Mage::log("Enduser/Default (".$customer->getTaxClassId()."|".$request->getCustomerClassId().") - $basedOn country: $basedOnCc - vatIsValid: ".$address->getVatIsValid()." ClassID: $taxIncludingClassId", null, 'euvatenhanced.log');
						$request->setCustomerClassId($taxIncludingClassId);
					}

					// Allow tax free groups without VAT validation
					if( in_array($customer->getGroupId(), $dataHelper->getExcludedTaxGroups()) )
					{
						if($debug) Mage::log("Is excluded tax group: ".$customer->getGroupId(), null, 'euvatenhanced.log');
						$request->setCustomerClassId($taxExemptClassId);
					}

				} elseif ($request->getCountryId() == $shopCc
				          && $dataHelper->isCbtEnabled()
				          && $dataHelper->getDisableCbtForEuBusiness()
				          && $dataHelper->isThresholdCountry($basedOnCc)
				) {
					if($debug) Mage::log("CBT enabled and threshold country.", null, 'euvatenhanced.log');
					$request->setCountryId($basedOnCc);
				}

				if($debug) {
					Mage::log("CBT enabled: ".$dataHelper->isCbtEnabled(), null, 'euvatenhanced.log');
					Mage::log("DisableCbtForEuBusiness: ".$dataHelper->getDisableCbtForEuBusiness(), null, 'euvatenhanced.log');
					Mage::log("isThresholdCountry: ".$dataHelper->isThresholdCountry($basedOnCc), null, 'euvatenhanced.log');
				}


			} catch (Exception $e) {
				Mage::logException($e);
			}

			if($debug) Mage::log("requestModification END.", null, 'euvatenhanced.log');
		}

		return $request;
	}

}