<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Model_Tax_Config extends Geissweb_Euvatgrouper_Model_Tax_Rewrite
{
	protected $_debug = false;

	/**
	 * Geissweb_Euvatgrouper_Model_Tax_Config constructor.
	 */
	public function __construct()
	{
		$this->_debug = Mage::helper('euvatgrouper')->isDebugMode();
	}

	/**
	 * Return the config value for self::CONFIG_XML_PATH_CROSS_BORDER_TRADE_ENABLED
	 * IF we have Magento >= 1.9.x
	 * @param int|null $store
	 * @return int
	 */
	public function crossBorderTradeEnabled($store = null)
	{
		if (version_compare(Mage::getVersion(), '1.9', '>='))
		{
			$cbtEnabled = $this->_getStoreConfig(self::CONFIG_XML_PATH_CROSS_BORDER_TRADE_ENABLED, $store);
			if($this->_debug) Mage::log('crossBorderTradeEnabled: '.$cbtEnabled, null, 'euvatenhanced.log');

			if($cbtEnabled && !Mage::helper('euvatgrouper')->isAdmin())
			{
                if(Mage::getSingleton('checkout/session')->hasQuote()) {
                    $billingAddress = Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress();
                    $shippingAddress = Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress();
                    $basedOnAddress = Mage::helper('euvatgrouper')->getVatBasedOnAddress($billingAddress, $shippingAddress);
                    $billingCountryId = $basedOnAddress ? $basedOnAddress->getCountryId() : null;
                    if(empty($billingCountryId)) {
                        $customer = Mage::getSingleton('customer/session')->getCustomer();
                        $billingCountryId = Mage::helper('euvatgrouper/customer')->getBillingCountry($customer);
                    }
                }

			} elseif($cbtEnabled && Mage::helper('euvatgrouper')->isAdmin()) {
				$adminQuoteId = Mage::getModel('adminhtml/session_quote')->getQuoteId();
				if(!empty($adminQuoteId)) {
					/** @var Mage_Adminhtml_Model_Session_Quote $quote */
					$quote           = Mage::getModel('adminhtml/session_quote')->getQuote();
					$shippingAddress = $quote->getShippingAddress();
					$billingAddress  = $quote->getBillingAddress();
					$basedOnAddress   = Mage::helper('euvatgrouper')->getVatBasedOnAddress($billingAddress, $shippingAddress, true);
					$billingCountryId = $basedOnAddress ? $basedOnAddress->getCountryId() : null;
				}
			}

			if(isset($billingCountryId) && !Mage::helper('euvatgrouper')->isEuCountry($billingCountryId) )
			{
				if($this->_debug) Mage::log('crossBorderTradeEnabledAdmin exception: NON-EU', null, 'euvatenhanced.log');
				if(Mage::helper('euvatgrouper')->getDisableCbtForOutOfEurope())
					return false;
			} elseif(isset($billingCountryId) && $basedOnAddress && $basedOnAddress->getVatIsValid() ) {
				if($this->_debug) Mage::log('crossBorderTradeEnabledAdmin exception: valid VAT Number', null, 'euvatenhanced.log');
				if(Mage::helper('euvatgrouper')->getDisableCbtForEuBusiness())
					return false;
			}

			return $cbtEnabled;

		} else {
			if($this->_debug) Mage::log('crossBorderTrade is not available in Mage version: ' . Mage::getVersion(), null, 'euvatenhanced.log');
		}

		return false;
	}
}