<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

if( Mage::helper('core')->isModuleEnabled('FireGento_MageSetup') ) {
	class Geissweb_Euvatgrouper_Model_Tax_Rewrite extends FireGento_MageSetup_Model_Tax_Config {}
} elseif( Mage::helper('core')->isModuleEnabled('FireGento_GermanSetup') ) {
	class Geissweb_Euvatgrouper_Model_Tax_Rewrite extends FireGento_GermanSetup_Model_Tax_Config {}
} elseif( Mage::helper('core')->isModuleEnabled('Anowave_TaxSwitch') ) {
	class Geissweb_Euvatgrouper_Model_Tax_Rewrite extends Anowave_TaxSwitch_Model_Config {}
} elseif( Mage::helper('core')->isModuleEnabled('CKonsult_Taxswitcher') ) {
	class Geissweb_Euvatgrouper_Model_Tax_Rewrite extends CKonsult_Taxswitcher_Model_Config {}
} else {
	class Geissweb_Euvatgrouper_Model_Tax_Rewrite extends Mage_Tax_Model_Config {}
}