<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */
class Geissweb_Euvatgrouper_Helper_Abstract extends Mage_Core_Helper_Abstract
{
    /**
     * @var bool
     */
	protected $_debug;

	/**
	 * @var Mage_Core_Model_Store
	 */
	var $_store;

	/**
	 * Geissweb_Euvatgrouper_Helper_Abstract constructor.
	 */
	public function __construct()
	{
		try {
			$this->_store = Mage::app()->getStore();
			$this->_debug = (bool)Mage::getStoreConfig('euvatgrouper/extension_info/debug_mode', $this->_store->getId());
		} catch(Exception $e) {
			Mage::logException($e);
		}
	}

	/**
	 * Returns whether debug mode is turned on
	 * @return bool
	 */
	public function isDebugMode()
	{
		return $this->_debug;
	}

	/**
	 * Gets a list of all current EU member states
	 * @return array
	 */
	public function getEuCountries()
	{
		return explode(",", Mage::getStoreConfig('general/country/eu_countries', $this->_store->getId()));
	}

    /**
     * Used in Setup
     * @return array
     */
    public function getEuCountriesOptionArray()
    {
	    return Mage::getResourceModel('directory/country_collection')
            ->addCountryCodeFilter($this->getEuCountries(), 'iso2')
            ->loadData()
            ->toOptionArray($this->__('--- Please Select ---'));
    }

	/**
	 * Gets the CC from system config
	 * @return string
	 */
	public function getMerchantCountryId()
	{
        return $this->getStoreCountryCode();
        /*
		if(Mage::getStoreConfig('general/store_information/merchant_country') != '')
		{
			return strtoupper(Mage::getStoreConfig('general/store_information/merchant_country'));
		} else {
			return $this->getStoreCountryCode();
		}
        */
	}


	/**
	 * @param $cc : 2-letter country code
	 * @return bool
	 */
	public function isEuCountry($cc)
	{
		if($cc == 'EL') $cc = 'GR';
		if (in_array($cc, $this->getEuCountries()))
			return true;
		return false;
	}


	/**
	 * @param null $vatid
	 *
	 * @return bool|null|string
	 */
	public function cleanCustomerVatId($vatid=NULL)
	{
		if($vatid != NULL)
		{
			$vatid = trim(str_replace(array(" ", ".", ",", "-", "|", "/"), "", $vatid));
			return strtoupper($vatid);
		}
		return false;
	}

	/**
	 * Return country code of a VAT number
	 * @param $vatId
	 * @return string
	 */
	public function getVatIdCc($vatId)
	{
		$vatId = substr($vatId, 0, 2);
		switch($vatId) {
			case 'EL':
				$vatId = 'GR';
				break;
			default:
				break;
		}
		return strtoupper($vatId);
	}


	/**
	 * Gets the groups which shall be excluded from group assignment feature
	 * @return array
	 */
	public function getExcludedGroups()
	{
		return explode(",", Mage::getStoreConfig('euvatgrouper/group_assignment/excluded_groups', $this->_store->getId()));
	}

	/**
	 * Gets the groups which shall be excluded from Euvatgrouper tax calculation
	 * @return array
	 */
	public function getExcludedTaxGroups()
	{
		return explode(",", Mage::getStoreConfig('euvatgrouper/vat_settings/excluded_groups_taxcalc', $this->_store->getId()));
	}

    /**
     * Gets the groups which should follow regular Magento tax calculation
     * @return array
     */
    public function getRegularTaxCalculationGroups()
    {
        return explode(",", Mage::getStoreConfig('euvatgrouper/vat_settings/regular_tax_groups', $this->_store->getId()));
    }

	/**
	 * Gets the group ID
	 * @return int
	 */
	public function getValidEuVatGroupId()
	{
		return (int)Mage::getStoreConfig('euvatgrouper/group_assignment/target_group', $this->_store->getId());
	}

	/**
	 * Gets the group ID
	 * @return int
	 */
	public function getSameCountryGroupId()
	{
		return (int)Mage::getStoreConfig('euvatgrouper/group_assignment/target_group_same_cc', $this->_store->getId());
	}

	/**
	 * Gets the group ID
	 * @return int
	 */
	public function getOutsideEuGroupId()
	{
		return (int)Mage::getStoreConfig('euvatgrouper/group_assignment/target_group_outside', $this->_store->getId());
	}

	/**
	 * Gets the group ID
	 * @return int
	 */
	public function getDefaultGroupId()
	{
		return (int)Mage::getStoreConfig('customer/create_account/default_group', $this->_store->getId());
	}

    /**
     * Gets the group ID
     * @return int
     */
    public function getInvalidGroupId()
    {
       return (int)Mage::getStoreConfig('euvatgrouper/group_assignment/target_group_invalid', $this->_store->getId());
    }

    /**
     * Gets the group ID
     * @return int
     */
    public function getErrorGroupId()
    {
        return (int)Mage::getStoreConfig('euvatgrouper/group_assignment/target_group_errors', $this->_store->getId());
    }


	/**
	 * Gets the tax class ID for a given group ID
	 *
	 * @param $group_id
	 * @return int
	 */
	public function getTaxClassIdForGroup($group_id)
	{
		return (int)Mage::getSingleton('customer/group')->load($group_id)->getTaxClassId();
	}

	/**
	 * Gets the tax class ID for VAT exempt customers
	 * @return int
	 */
	public function getTaxExemptClassId() {
		return (int)Mage::getStoreConfig('euvatgrouper/vat_settings/tax_class_excluding', $this->_store->getId());
	}

	/**
	 * Gets the tax class ID for VAT customers
	 * @return int
	 */
	public function getTaxIncludingClassId() {
		return (int)Mage::getStoreConfig('euvatgrouper/vat_settings/tax_class_including', $this->_store->getId());
	}

    /**
     * Gets the tax class ID for VAT customers
     * @return int
     */
    public function getTaxIncludingClassIdBusiness() {
        return (int)Mage::getStoreConfig('euvatgrouper/vat_settings/tax_class_including_business', $this->_store->getId());
    }

	/**
	 * Gets the default country from Store Config
	 * @return bool
	 */
	public function getOfflineValidate()
	{
		return (bool)Mage::getStoreConfig('euvatgrouper/vat_settings/offline_validation', $this->_store->getId());
	}

	/**
	 * @return bool
	 */
	public function isModifyOrderGroup()
	{
		return (bool)Mage::getStoreConfig('euvatgrouper/group_assignment/modify_order_group', $this->_store->getId());
	}

    /**
     * @return bool
     */
    public function isAutovalidationEnabled()
    {
        return (bool)Mage::getStoreConfig('euvatgrouper/vat_settings/autovalidate_on_each_login', $this->_store->getId());
    }

    /**
     * @return bool
     */
    public function getAutovalidationPeriod()
    {
        return Mage::getStoreConfig('euvatgrouper/vat_settings/autovalidate_period', $this->_store->getId());
    }

    /**
     * @return bool
     */
    public function isModifyGroupOnCheckout()
    {
        return (bool)Mage::getStoreConfig('euvatgrouper/group_assignment/modify_group_on_checkout', $this->_store->getId());
    }

    /**
     * @return bool
     */
    public function isSyncCustomerAccountWithOrderGroup()
    {
        return (bool)Mage::getStoreConfig('euvatgrouper/group_assignment/sync_customer_group_with_order_group', $this->_store->getId());
    }

	/**
	 * Gets the default country from Store Config
	 * @return bool
	 */
	public function getAccountingFix()
	{
		return (bool)Mage::getStoreConfig('euvatgrouper/group_assignment/force_general_on_vat', $this->_store->getId());
	}

	/**
	 * Gets the default country from Store Config
	 * @return bool
	 */
	public function getStoreCountryCode()
	{
		return Mage::getStoreConfig('general/country/default', $this->_store->getId());
	}

	/**
	 * Determines if the validation of VAT-IDs is enabled
	 * @return int
	 */
	public function isModuleActive()
	{
		return (bool)Mage::getStoreConfig('euvatgrouper/vat_settings/validate_vatid', $this->_store->getId());
	}

	/**
	 * Gets the full store VAT-ID
	 * @return int
	 */
	public function getShopVatId()
	{
		return Mage::getStoreConfig('euvatgrouper/vat_settings/own_vatid', $this->_store->getId());
	}

    /**
     * Gets the CC from VAT-ID
     * @return string
     */
    public function getShopVatCc()
    {
        return strtoupper(substr(Mage::getStoreConfig('euvatgrouper/vat_settings/own_vatid', $this->_store->getId()), 0, 2));
    }

	/**
	 * Gets the mail sender address
	 * @return int
	 */
	public function doSendValidationMail()
	{
		return (bool)Mage::getStoreConfig('euvatgrouper/email_settings/send_mail', $this->_store->getId());
	}


	/**
	 * Gets the mail sender address
	 * @return int
	 */
	public function getMailSender()
	{
		return Mage::getStoreConfig('euvatgrouper/email_settings/mail_sender', $this->_store->getId());
	}

	/**
	 * Gets the mail recipient address
	 * @return int
	 */
	public function getMailRecipient()
	{
		return Mage::getStoreConfig('euvatgrouper/email_settings/mail_recipient', $this->_store->getId());
	}

	/**
	 * Gets the mail template
	 * @return int
	 */
	public function getMailTemplate()
	{
		return Mage::getStoreConfig('euvatgrouper/email_settings/mail_template', $this->_store->getId());
	}

	/**
	 * Returns whether debug mode is turned on
	 * @return bool
	 */
	public function isIPv6Mode()
	{
		return Mage::getStoreConfig('euvatgrouper/extension_info/ipv6_mode', $this->_store->getId());
	}
	/**
	 * Returns the IPv4 address to bind on
	 * @return bool
	 */
	public function getIPv4ToBindOn()
	{
		return Mage::getStoreConfig('euvatgrouper/extension_info/ipv4_addr', $this->_store->getId());
	}

	/**
	 * Should Cross-Border-Trade be disabled for EU B2B customers
	 * @return int
	 */
	public function getDisableCbtForEuBusiness()
	{
		return (bool)Mage::getStoreConfig('euvatgrouper/vat_settings/disable_cbt_eub2b', $this->_store->getId());
	}

	/**
	 * Should Cross-Border-Trade be disabled for customers from out of Europe
	 * @return int
	 */
	public function getDisableCbtForOutOfEurope()
	{
		return (bool)Mage::getStoreConfig('euvatgrouper/vat_settings/disable_cbt_noneu', $this->_store->getId());
	}

	/**
	 * @return bool
	 */
	public function isCbtEnabled()
	{
		return (bool)Mage::getStoreConfig('tax/calculation/cross_border_trade_enabled', $this->_store->getId());
	}

	/**
	 * @param $countryCode
	 *
	 * @return bool
	 */
	public function isThresholdCountry($countryCode)
	{
		$countriesConfigured = explode(",", Mage::getStoreConfig('euvatgrouper/vat_settings/threshold_countries', $this->_store->getId()));
		if(in_array($countryCode, $countriesConfigured)) {
			return true;
		}
		return false;
	}

    /**
     * Check if a valid VAT number is required to checkout
     * @return int
     */
    public function getIsVatNumberRequired()
    {
        return (int)Mage::getStoreConfig('euvatgrouper/integration/require_valid_number_to_checkout', $this->_store->getId());
    }

	/**
	 * Checks if the current scope is adminhtml
	 * @return bool
	 */
	public function isAdmin()
	{
		if($this->_store->isAdmin())
			return true;

		if(Mage::getDesign()->getArea() == 'adminhtml')
			return true;

		return false;
	}

	/**
	 * Get Tax based on setting
	 * @return mixed (billing|shipping|origin)
	 */
	public function getVatBasedOn()
	{
		return Mage::getStoreConfig(Mage_Tax_Model_Config::CONFIG_XML_PATH_BASED_ON, $this->_store->getId());
	}

	/**
	 * @return bool
	 */
    public function getIsTakeoverVatToAccount()
    {
        return (bool)Mage::getStoreConfig('euvatgrouper/integration/takeover_vat_to_account', $this->_store->getId());
    }

	/**
	 * @return bool
	 */
	public function getUseMossBasedOnVatNumber()
	{
		return (bool)Mage::getStoreConfig('euvatgrouper/moss_settings/use_moss_based_on_vat_number', $this->_store->getId());
	}

	/**
	 * @return int
	 */
	public function getMossProductsClassId()
	{
		return (int)Mage::getStoreConfig('euvatgrouper/moss_settings/digital_products_class_id', $this->_store->getId());
	}
	/**
	 * @return bool
	 */
    public function getLicenseStatus()
    {
        $key = Mage::getStoreConfig('euvatgrouper/extension_info/license_key', $this->_store->getId());
        if($key=='')
            return false;

        return true;
    }
}