<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Helper_Admin extends Geissweb_Euvatgrouper_Helper_Abstract
{

	public function getYearRange()
	{
		$first = date("Y", strtotime(Mage::getModel('sales/order')->getCollection()->setOrder('entity_id', 'ASC')->getFirstItem()->getCreatedAt()));
		$last = date("Y", strtotime(Mage::getModel('sales/order')->getCollection()->setOrder('entity_id', 'DESC')->getFirstItem()->getCreatedAt()));
		$years = array();
		for($i=$first; $i<=$last; $i++)
		{
			$years[$i] = $i;
		}
		return $years;
	}

	public function getMonthsArray()
	{
		return array(
			'01' => '01',
			'02' => '02',
			'03' => '03',
			'04' => '04',
			'05' => '05',
			'06' => '06',
			'07' => '07',
			'08' => '08',
			'09' => '09',
			'10' => '10',
			'11' => '11',
			'12' => '12',
			'1q' => Mage::helper('euvatgrouper')->__('1st Quarter'),
			'2q' => Mage::helper('euvatgrouper')->__('2nd Quarter'),
			'3q' => Mage::helper('euvatgrouper')->__('3rd Quarter'),
			'4q' => Mage::helper('euvatgrouper')->__('4th Quarter'),
			'yy' => Mage::helper('euvatgrouper')->__('Yearly'),
		);
	}
}