<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Adminhtml_Vatreport_OrdersController extends Mage_Adminhtml_Controller_Action
{

    public function indexAction()
    {
        $this->_title($this->__('Sales'))->_title($this->__('EU VAT Orders Report'));
        $this->loadLayout();
        $this->_setActiveMenu('report/sales');
        //$this->_addContent($this->getLayout()->createBlock('euvatgrouper/adminhtml_report_moss_filter'));

        $this->_addContent($this->getLayout()->createBlock('euvatgrouper/adminhtml_report_orders'));

        $this->renderLayout();
    }

    public function gridAction()
    {
        $this->loadLayout();
        $this->getResponse()->setBody(
            $this->getLayout()->createBlock('euvatgrouper/adminhtml_report_orders')->toHtml()
        );
    }

    public function exportCsvAction()
    {
        $fileName = 'euvat_report.csv';
        $grid = $this->getLayout()->createBlock('euvatgrouper/adminhtml_report_orders_grid');
        $this->_prepareDownloadResponse($fileName, $grid->getCsvFile());
    }

    public function exportXmlAction()
    {
        $fileName = 'euvat_report.xml';
        $grid = $this->getLayout()->createBlock('euvatgrouper/adminhtml_report_orders_grid');
        $this->_prepareDownloadResponse($fileName, $grid->getXmlFile($fileName));
    }

    /**
     * @return bool
     */
    public function _isAllowed()
    {
	    return Mage::getSingleton('admin/session')->isAllowed('report/euvatreport_orders');
    }
}