<?php

// some helpers
$_helper = $this->helper('catalog/output');
$store = Mage::app()->getStore();
$storeId = $store->getId();
$catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);

// get all products that are marked as featured
$collection = Mage::getModel('catalog/product')
  ->getCollection()
  ->addAttributeToSelect('*')
  ->addFieldToFilter([['attribute' => 'featured', 'eq' => TRUE]])
  ->addOrder('name', 'ASC')
  ->setPageSize(16)
  ->setCurPage(1)
  ->load();

$productBlock           = $this->getLayout()->createBlock('catalog/product_price');
$parent_categories_ids  = [];
$catid                  = null;
?>
<style>
  #featured-products-list li.item {
    margin: 5px 2px;
    min-height: 555px;
    width: 24%!important;
    list-style: none;
  }

  #featured-products-list ul.miniflist li {
    margin-left: 0;
    list-style: none;
  }

  #featured-products-list li:nth-child(4n) {
    margin-right: 0!important;
  }

  #featured-products-list a.product-image {
    display: block;
    min-height: 189px;
    text-align: center;
  }

  #featured-products-list p {
    margin: 0!important;
  }

  #featured-products-list div.actions button.button.btn-cart {
    padding-right: 5px;
    padding-left: 5px;
    font-size: 24px;
  }

  #featured-products-list div.price-box p.special-price span.price {
    font-weight: bolder;
    font-size: 24px;
  }

  #featured-products-list div.price-box p.old-price span.price {
    font-weight: 400;
    font-size: 17px;
  }

  #featured-products-list .actions {
    bottom: -36px;
    display: block;
    min-height: 45px;
  }

  #featured-products-list .product-image img {
    max-width: 244px;
    max-height: 244px;
  }

  @media screen and (max-width: 767px) {
    .products-grid > li:nth-child(3n+1) {
      clear: none;
    }
    #featured-products-list li.item {
      width: 49% !important;
    }
  }

  @media screen and (max-width: 990px) {
    #featured-products-list li:nth-child(5n) {
      margin-right: 1% !important;
    }
    #featured-products-list li.item {
      width: 32% !important;
    }
  }

  @media screen and (max-width: 680px) {
    #featured-products-list li.item {
      width: calc(100% - 2em) !important;
      list-style: none;
      min-height: 350px;
      margin: 0 1em 3em 1em !important;
      padding: 0 !important;
    }
  }
</style>
<span class='h1 center' style='margin-bottom: 1em;'>Hardlopers:</span>

<?php
$i = 0;
$_columnCount = 4;

$collection = Mage::getModel('catalog/product')
  ->getCollection()
  ->addAttributeToSelect('*')
  ->addFieldToFilter([['attribute' => 'featured', 'eq' => true]])
  ->addAttributeToFilter('status', ['eq' => Mage_Catalog_Model_Product_Status::STATUS_ENABLED])
  ->addOrder('name', 'ASC')
  ->setPageSize(16)
  ->setCurPage(1)
  ->load();

if($collection->getSize() > 0) { ?>
<div class="product-collateral category-products">
  <?php
  echo "<ul class='html5-grid html5-grid-4-col'>";
  foreach ($collection->getItems() as $_product) {
    $i++;
    ?>
    <li class="item<?php if(($i-1) % $_columnCount == 0): ?> first<?php elseif($i % $_columnCount == 0): ?> last<?php endif; ?>">
      <?php
      $options = [
        "skip_usps"               => false,
        "skip_info"               => false,
        "display"                 => "mini",
        "image_size"              => 210,
        "_blank"                  => false,
        "use_short_product_names" => true,
        "show_category_link"      => true,
      ];
      echo Mage::helper("deheerhoreca_util/util")->getProductGridHtml($_product, $productBlock, $options);
    echo "</li>";
  }
  ?>
</ul></div>
<?php }
