<?php

declare(strict_types=1);

/** @var DeHeerHoreca_Util_Helper_Util */
$dhh_util_helper              = Mage::helper('deheerhoreca_util/util');

/** @var Mage_CatalogInventory_Model_Stock */
$mage_stock_model             = Mage::getModel("cataloginventory/stock");

/** @var Mage_Catalog_Helper_Output */
$_helper                      = $this->helper("catalog/output");

$freeshipping_from            = (float) Mage::getStoreConfig("carriers/freeshipping/free_shipping_subtotal");
$show_ups_block               = false;
$show_black_friday            = false;
$show_actions                 = false;
$store                        = Mage::app()->getStore();
$storeId                      = $store->getId();
$catalog                      = $this->getLayout()->createBlock("catalog/product_list")->setStoreId($storeId);
$product_block                = $this->getLayout()->createBlock("catalog/product_price");
$attributes                   = $dhh_util_helper::getProductAttributes("listview", ["popularity", "featured"]);

// Block of semi-random recommended products
$_columnCount             = 5;
$displaySize              = 175;
$_imgSize                 = 1 * $displaySize;
$limit                    = 5;
$options                  = [
  "_blank"                  => false,
  "prefer_rewrite_table"    => true,
  "display"                 => "normal",
  "fast_stock"              => true,
  "skip_actions"            => true,
  "skip_usps"               => false,
  "use_short_product_names" => true,
];
$_products = Mage::getModel("catalog/product")->getCollection()
  ->addAttributeToSelect($attributes)
  ->addFieldToFilter([["attribute" => "status", "eq" => Mage_Catalog_Model_Product_Status::STATUS_ENABLED]])
  ->addFieldToFilter([["attribute" => "stock_status", "eq" => 2746]])
  ->addFieldToFilter([["attribute" => "featured", "eq" => 1]])
  ->addFinalPrice() // Necessary to respect sale price end date
  ->setPage(1, $limit);
$_products->getSelect()->order("rand()");
$_products->load();
$mage_stock_model->addItemsToProducts($_products);

if($_products->getFirstItem()) { ?>
  <div id="promo-products" class="category-products mt-5 pb-0 mb-3">
    <ul class="products-grid products-grid--max-<?=$_columnCount?>-col"><?php
      $i = 0;
      foreach($_products as $_product) {
        echo "<li class='item'>";
        $dhh_util_helper->getProductGridHtml($_product, $product_block, $options);
        echo "</li>";
        $i++;
        if($i === $limit) break;
      } ?>
    </ul>
  </div><?php
}
unset($_products);

// Dynamic block of bestsellers
// Get 4x the top products by popularity and take a random sample out of those

/*
 * Bugfix: Using require_stock_items there was a bug that lead
 * to wrong stock info on listview during flat index rebuild.
 * addItemsToProducts() seems to add stock data correctly even during a reindex
 *
 * However, with addItemsToProducts() we are missing essential stock data like
 * manage_stock, leading to wrong results.
 *
 * We now use both as an experiment...
 */

$limit          = 10;
$_columnCount   = 5;
$displaySize    = 175;
$_imgSize       = 1 * $displaySize;
$_products      = Mage::getModel("catalog/product")->getCollection()
  ->addAttributeToSelect($attributes)
  ->addAttributeToFilter("status", ["eq" => Mage_Catalog_Model_Product_Status::STATUS_ENABLED])
  ->addAttributeToFilter("stock_status", ["eq" => 2746])
  ->addAttributeToFilter("popularity", ["notnull" => true]) // Do not match new products that have no data yet
  ->addAttributeToFilter("featured", ["neq" => 1])          // Do not match products that are already in the other frontpage block
  ->addAttributeToSort("popularity", "ASC")                 // Can't move away from popularity sort because the subset is way too big otherwise.
  ->addPriceData()                                          // Necessary to respect sale price end date
  ->setPage(1, $limit * 5);                                 // Get more products than needed to have some variety in the random selection
$_products->load();
$mage_stock_model->addItemsToProducts($_products);

if($_products->getFirstItem()) { ?>
  <div id="popular-products" class="category-products mt-5 pb-0 mb-3">
    <h2 class="center py-1 my-3">Hardlopers</h2><hr>
    <ul class="products-grid products-grid--max-<?=$_columnCount?>-col"><?php
      $i = 0;
      foreach($_products as $_product) {
        echo "<li class='item'>";
        $dhh_util_helper->getProductGridHtml($_product, $product_block, $options);
        echo "</li>";
        $i++;
        if($i === $limit) {
          break;
        }
      } ?>
    </ul>
  </div><?php
}

// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if($this->getChild('after')) {
  $_afterChildren = $this->getChild('after')->getSortedChildren();
  foreach($_afterChildren as $_afterChildName) {
    $_afterChild = $this->getChild('after')->getChild($_afterChildName);
    // set product collection on after blocks
    $_afterChild->setProductCollection($_products);
    echo $_afterChild->toHtml();
  }
}
