<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */

$_productCollection          = $this->getLoadedProductCollection();
$_helper                     = $this->helper('catalog/output');
$category                    = $this->getRequest()->getControllerName();
$catid                       = null;
$carct                       = Mage::registry('current_category');
$amschk                      = $this->getRequest()->getRouteName();
$haschild                    = false;
$short_name_cats             = [10, 119, 434, 174, 24, 38, 23];
$max_product_info_items      = 3;
$max_product_highlight_items = 6;
$category_thumbs_dimensions  = 300;
$parent_categories_ids       = [];

$_productCollection->setFlag('require_stock_items', true);

/*
 * If the sorting is by position, put the recommended products on top
 * http://www.rob-st.com/2016/11/29/sort-magento-category-multiple-values-keep-newest-products-top/
 */

$currentOrder = $this->getChild('toolbar')->getCurrentOrder();
$currentDirection = $this->getChild('toolbar')->getCurrentDirection();

if($currentOrder === "position") {
  $query = $_productCollection->getSelect()->__toString();
  //printr($query);
  if(strstr($query, "tagline") !== false) { // if somehow this field is not there
    $sortByRcm = "IF(e.tagline = '' OR e.tagline IS NULL, 1, 0) ASC";
    $_productCollection->getSelect()->reset(Zend_Db_Select::ORDER);
    $_productCollection->getSelect()->order(new Zend_Db_Expr($sortByRcm));
    $_productCollection->getSelect()->order($currentOrder.' '.$currentDirection);
    //printr($_productCollection->getSelect()->__toString());
     
    // Collection was loaded already...reloading...(yeah I know)
    $_productCollection->clear();
    $_productCollection->load();
  }
}

$_collectionSize = $_productCollection->count();

/* CATEGORY HEADER & SEO */

if($carct && ($category === 'category')) {
  $catid = (int) $carct->getId();
  $category_name = $carct->getName();
  $category_name_lwr = strtolower($category_name);
  $category_desc = $carct->getDescription();
  $parent_categories = $carct->getParentCategories();
  
  if(strlen($category_desc) < 5) {
    $category_desc = "<h1>{$category_name}</h1>";
  }
  
  foreach($parent_categories as $parent) {
    $parent_categories_ids[] = (int) $parent->getEntityId();
  }
  $parent_categories_ids[] = $catid;
  
  // In case of shop-by-brand, do not show another H1
  if(defined("CTDESC_H1_SENT") === true) {
    $category_desc = str_ireplace("h1>", "h2>", $category_desc);
  }

  echo "<div class='ctdesc std' id='ctdesc'>";
  if(empty($category_desc) === false) {

    /* Augment category description */
    
    $manufacturers = Mage::helper("deheerhoreca_util/util")->getBrandsPerCategory($catid);
    if(is_array($manufacturers) === true && sizeof($manufacturers) > 0) {
      $category_desc .= "<p>Prokoeling.nl verkoopt o.a. ";
      $n = sizeof($manufacturers);
      $i = 0;
      foreach($manufacturers as $manufacturer) {
        if(strlen($manufacturer) < 3) continue;
        $category_desc .= "{$manufacturer} {$category_name_lwr}";
        $i++;
        if($i === $n-1) {
          $category_desc .= " en ";
        } elseif($i < $n) {
          $category_desc .= ", ";
        } else {
          $category_desc .= ".";
        }
      }
      $category_desc .= " Veelal uit voorraad en dus vaak binnen 24 of 48 uur al leverbaar.</p>";
    }
    
    if(Mage::helper("deheerhoreca_util/util")->getAvgPrice($_productCollection) > 500) {
      $category_desc .= "<h2>Dit is Prokoeling.nl:</h2><p>Wij bieden u een breed assortiment keukenapparatuur voor de horeca keuken. Bekijk alle soorten {$category_name_lwr} in ons aanbod en bestel vandaag. Bijna alle items kunnen wij uit voorraad leveren en binnen 24 tot 48 uur leveren. Bij Prokoeling.nl kunt u ook {$category_name_lwr} leasen. Wenst u meer informatie of hulp bij het kiezen van {$category_name_lwr} dan kunt u altijd contact opnemen via <a href='tel:+31850441003' title='Bel ons'>085-0441003</a>, <a href=\"javascript:\$zopim.livechat.window.show();\">chat</a> of <a href='mailto:klantenservice@prokoeling.nl' title='Bel ons'>e-mail</a>.</p>";
    } else {
      $category_desc .= "<h2>Prokoeling.nl:</h2><p>Wij bieden u een breed assortiment keukenapparatuur voor de horeca keuken. Bekijk alle soorten {$category_name_lwr} in ons aanbod en bestel vandaag. Bijna alle items kunnen wij uit voorraad leveren en binnen 24 tot 48 uur leveren. Wenst u meer informatie of hulp bij het kiezen van {$category_name_lwr} dan kunt u altijd contact opnemen via <a href='tel:+31850441003' title='Bel ons'>085-0441003</a>, <a href=\"javascript:\$zopim.livechat.window.show();\">chat</a> of <a href='mailto:klantenservice@prokoeling.nl' title='Bel ons'>e-mail</a>.</p>";
    }
    
    if(strlen($category_desc) < 1000) {
      echo "<div id='cat-text'>{$category_desc}</div>";
    } else {
      echo "<div id='cat-text' class='short'>{$category_desc}</div>";
      ?>
      <button id="toggle-cat-text"><i id="cat-btn-arrow" class="fa fa-arrow-down" aria-hidden="true"></i>&nbsp;<span>Lees meer</span></button>
      <script>
        jQuery(document).ready(function(){
          jQuery(document).on('click', '#toggle-cat-text', function(){
            if(jQuery('#cat-text').hasClass("short")) {
              jQuery('#ctdesc .short').addClass('full');
              jQuery('#ctdesc .short').removeClass('short');
              jQuery('#cat-btn-arrow').addClass('fa-arrow-up');
              jQuery('#cat-btn-arrow').removeClass('fa-arrow-down');
              jQuery('#toggle-cat-text span').html('Minder');
            } else {
              jQuery('#ctdesc .full').addClass('short');
              jQuery('#ctdesc .full').removeClass('full');
              jQuery('#cat-btn-arrow').addClass('fa-arrow-down');
              jQuery('#cat-btn-arrow').removeClass('fa-arrow-up');
              jQuery('#toggle-cat-text span').html('Lees meer');
            }
          });
        });
      </script>
      <?php
    }
  }
  echo "</div>";
}

/* SUBCATEGORIES */

if(empty($carct) === false && $amschk !== 'amshopby') {

  $layer = Mage::getSingleton('catalog/layer');
  $_category = $layer->getCurrentCategory();
  $currentCategoryId = $_category->getId();
  $media_url = Mage::getBaseUrl('media');
  $media_path = Mage::getBaseDir('media');
  $subcategories = Mage::getModel('catalog/category')->getCategories($currentCategoryId);
  
  ?>
  <ul class="category-grid">
  <?php
  foreach($subcategories as $category) {
    $haschild       = true;
    $category       = Mage::getModel('catalog/category')->load($category->getId());
    $categoryName   = $category->getName();
    $image          = $category->getImage();
    $measurements   = null;
    $img_url        = "{$media_url}/catalog/category/{$image}";
    $img_path       = "{$media_path}/catalog/category/{$image}";
    
    if(is_file($img_path) === true) {
      try {
        $meta = getimagesize($img_path);
        $measurements = $meta[3];
      } catch (Exception $e) {
        $image = null;
        Mage::log("Error while trying to getimagesize() on {$img_file}: ".$e->getMessage(), null, 'system.log', true);
      }
    } else {
      $image = null;
    }
    ?>
    <li>
      <a href="<?php echo $category->getUrl() ?>" title='<?php echo $categoryName; ?>'>
        <?php if(empty($image) === false) echo "<img class='lazy category-thumb' data-src='{$img_url}' alt='{$categoryName}' title='{$categoryName}' {$measurements} />"; ?>
        <strong><?php echo $categoryName; ?></strong>
      </a>
    </li>
    <?php
  }
  echo "</ul>";
  if($haschild === true) {
    echo "<style>#sidebar-nav {display: block;}</style>";
  }
}

/* CHILD CATEGORY, SHOW PRODUCTS */

//if($catid === 4 || ($amschk === 'amshopby' || ($haschild === false || $catid === 544))) {
if($_collectionSize > 0) {
?>
  <div class="category-products">
    <div class="top_toolbar"><?php echo $this->getToolbarHtml() ?></div>
    <?php
    $_columnCount = 3;
    $displaySize = 280;
    $_imgSize = 1 * $displaySize;
    
    echo "<ul class='products-grid products-grid--max-{$_columnCount}-col'>";
    
    $i = 0;
    foreach($_productCollection as $_product) {
      $i++;
      $html = null;
      
      $productUrl = false;
      // If a product is present in multiple categories, we don't want to change that in this view
      //$productUrl = Mage::helper("deheerhoreca_util/util")->getFullProductUrlFromRewrites($_product);
      if($productUrl === false) {
        $productUrl = $_product->getProductUrl(); //fallback
      }
      
      // Yeah, I know. Sucks. But, otherwise we cannot get the stock info we need
      $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product);
      
      $stock_status = $stock_message = null;
      $stock_qty    = (int) $stock->getQty();
      $in_stock     = $stock->getIsInStock();
      
      // Block also exists in catalogproductview.phtml and featured.phtml
      if($in_stock === true) {
        if($stock_qty < 1 && $stock->getBackorders() !== Mage_CatalogInventory_Model_Stock::BACKORDERS_NO) {
          $stock_message = "Bestelbaar";
          $stock_status = "EMPTY";
        } else {
          if($stock_qty === 100) { //100 is a special value
            $stock_message = "Op voorraad";
          } elseif($stock_qty > 10) {
            $stock_message = "10+ op voorraad";
          } elseif($stock_qty > 1) {
            $stock_message = "{$stock_qty} op voorraad";
          } else {
            $stock_message = "Op voorraad";
          }
          $stock_status = "IN_STOCK";
        }
      } else {
        $stock_message = "Niet op voorraad";
        $stock_status = "DISABLED";
      }
      
      $energy_rating = $_product->getAttributeText('energieklasse');
      $productlabel = $_product->getProductLabel();
      $gnvalue = $_product->getAttributeText("gn"); // can be an array if multiselect
      $tagline = $_product->getTagline();
      
      /* Listview Info */
      $product_info = [];
              
      $width = $attribute_value = $_product->getBreedte();
      $height = $attribute_value = $_product->getHoogte();
      $depth = $attribute_value = $_product->getDiepte();
      
      $width = $width + 0;
      $height = $height + 0;
      $depth = $depth + 0;
      
      $width /= 10;
      $height /= 10;
      $depth /= 10;
      
      if($width > 10) $width = round($width);
      if($depth > 10) $depth = round($depth);
      if($height > 10) $height = round($height);
      
      if($width > 0 && $height > 0 && $depth > 0) {
        $product_info[] = "B: {$width}cm D: {$depth}cm H: {$height}cm";
      } else {
        $attribute_value = $_product->getBreedte();
        if($attribute_value != '' && $attribute_value > 0) {
          $product_info[] = "Breedte: ".($attribute_value/10)."cm";
        }
      }

      $attribute_value = $_product->getAttributeText('type_koeling');
      if($attribute_value != ''){
        $product_info[] = "Koelmethode: {$attribute_value}";
      }

      if($catid === 72) {
        $attribute_value = $_product->getInhoudAantalGn();
        if($attribute_value !='') {
          $product_info[] = "{$attribute_value} x {$gnvalue}";
        }
      }
      
      $attribute_value = (int) $_product->getData('eenheid');
      if($attribute_value > 1) {
        $product_info[] = "{$attribute_value} stuks";
      }
      
      $attribute_value = $_product->getAttributeText('size');
      if(is_scalar($attribute_value) && strlen($attribute_value) > 0) {
        $product_info[] = "Maat: {$attribute_value}";
      }
      
      $attribute_value = $_product->getData('materiaal');
      if(strlen($attribute_value) > 0) {
        $product_info[] = "{$attribute_value}";
      }
      
      $attribute_value = $_product->getData('serie');
      if(strlen($attribute_value) > 0) {
        $product_info[] = "Serie: {$attribute_value}";
      }
      
      $code = "uitvoering";
      $attribute_value = $_product->getResource()->getAttribute($code)->getFrontend()->getValue($_product);
      if(strlen($attribute_value) > 0) {
        $product_info[] = "Uitvoering: {$attribute_value}";
      }
      
      $stock_class = null;
      switch($stock_status) {
        case "IN_STOCK":
          $stock_class = "green_checkbox_before";
          break;
        case "EMPTY":
          $stock_class = "orange_circle_before";
          break;
        case "DISABLED":
          $stock_class = "red_x_before";
          break;
      }
      
      /* Listview USPs */
      $usps = [];
      
      /* Afsluitbaar */
      $attribute_value = $_product->getAttributeText("afsluitbaar");
      if($attribute_value === "Ja") {
        $usps[] = "Afsluitbaar";
      }
      
      /* Blikjes */
      $attribute_value = (int) $_product->getData("aantal_blikjes");
      if($attribute_value > 0) {
        $usps[] = "{$attribute_value}x 33cl";
      }
      
      /* Flessen */
      $attribute_value = (int) $_product->getData("aantal_flessen");
      if($attribute_value > 0) {
        $usps[] = "{$attribute_value} flessen";
      }
      
      /* Capacity: Wine Bottels */
      $attribute_value = (int) $_product->getData("capacity_wine_bottles");
      if($attribute_value > 0) {
        $usps[] = "{$attribute_value} flessen";
      }
      
      /* GN maat if not in a GN category */
      if(empty($gnvalue) === false
        && empty($category_name) === false
        && strstr($category_name, "GN") === false) {
          if(is_array($gnvalue)) {
            $gnvalue = implode(" ", $gnvalue);
          }
          $usps[] = "{$gnvalue} GN";
      }
      
      /* Custom highlights */
      $attribute_value = $_product->getData("custom_highlights");
      $parts = explode(",", $attribute_value);
      if(sizeof($parts) > 0) {
        foreach($parts as $part) {
          $part = trim($part);
          if(strlen($part) > 0) {
            $usps[] = trim($part);
          }
        }
      }            
      
      /* Inhoud */
      $attribute_value = $_product->getInhoudLiters();
      if(strlen($attribute_value) > 0) {
        $usps[] = round($attribute_value, 2)." liter";
      }
      
      /* Vermogen */
      if(in_array(3, $parent_categories_ids) === false) { // skip "Koelingen" and everything underneath
        $attribute_value = $_product->getVermogen();
        if(empty($attribute_value) === false) {
          if($attribute_value < 3) {
            $attribute_value *= 1000;
            $usps[] = "{$attribute_value} Watt";
          } else {
            //$attribute_value = str_replace(".", null, $attribute_value);
            //$attribute_value = str_replace(",", ".", $attribute_value);
            $attribute_value = number_format($attribute_value, 1, ",", ".");
            $attribute_value = str_replace(",0", null, $attribute_value);
            $usps[] = "{$attribute_value} kW";
          }
        }
      }
      
      /* Gas Vermogen */
      $attribute_value = $_product->getVermogenKw();
      if(empty($attribute_value) === false) {
        if($attribute_value < 3) {
          $attribute_value *= 1000;
          $usps[] = "{$attribute_value} Watt";
        } else {
          $attribute_value = number_format($attribute_value, 1, ",", ".");
          $attribute_value = str_replace(",0", null, $attribute_value);
          $usps[] = "{$attribute_value} kW";
        }
      }
      
      /* M3/hour capacity */
      $attribute_value = $_product->getAantalM3Uur();
      if(strlen($attribute_value) > 0) {
        $usps[] = round($attribute_value, 2)." m3";
      }
      
      /* Warranty */
      $attribute_value = $_product->getAttributeText('garantie');
      if($attribute_value === "24 maanden") {
        $usps[] = "24M Garantie";
      }
      
      /* Cooling Zones */
      $attribute_code = "number_of_cooling_zones";
      $attribute_value = (int) $_product->getResource()->getAttribute($attribute_code)->getFrontend()->getValue($_product);
      if($attribute_value === 2) {
        $usps[] = "Dual-Zone";
      } elseif($attribute_value === 3) {
        $usps[] = "Triple-Zone";
      } elseif($attribute_value > 3) {
        $usps[] = "{$attribute_value} Zones";
      }
      
      /* ------------------------------------- */
      
      /* Price Block */
      $price_html = $this->getPriceHtml($_product, true);
      $price_html = str_replace(",00", ",-", $price_html);
      $price_html = str_replace("€", null, $price_html);
      
      /* Automatic Label: Product */
      if(isset($productlabel) === true) {
        $html .= "<span class=\"lblprolist\">{$productlabel}</span>";
      }

      /* Automatic Label: Energy */
      if(isset($energy_rating) === true) {
        $enclz = null;
        switch ($energy_rating) {
          case 'A++++': $enclz = 'enrgclz1';  break;
          case 'A+++':  $enclz = 'enrgclz2';  break;
          case 'A++':   $enclz = 'enrgclz3';  break;
          case 'A+':    $enclz = 'enrgclz4';  break;
          case 'A':     $enclz = 'enrgclz5';  break;
          case 'B':     $enclz = 'enrgclz6';  break;
          default: break;
        }
        if(isset($enclz) === true) {
          $html .= "<span class='lblenergylabel {$enclz}' title='Energielabel {$energy_rating}'>{$energy_rating}</span>";
        }
      }
      
      /* Product name */
      $product_name = $_helper->productAttribute($_product, $_product->getName(), 'name');
      $product_short_name = $_product->getData("name_short");
      if(in_array($catid, $short_name_cats) === true && strlen($product_short_name) > 0) {
        $product_name = $product_short_name;
      }
      
      ?>
      <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
        <?php echo $html; ?>
        <a href="<?php echo $productUrl; ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
        <?php
          echo "<img class='lazy' id='product-collection-image-{$_product->getId()}'
            data-src='{$this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize)}'
            alt='{$this->stripTags($this->getImageLabel($_product, 'small_image'), null, true)}'
            width='{$displaySize}' height='{$displaySize}' />";
        ?>
        </a>
        <div class="product-info">
          <div class="info">
            <h2 class='product-name'>
              <a href='<?php echo $productUrl; ?>' title='<?php echo $this->stripTags($product_name);?> kopen'><?php echo $product_name; ?></a>
            </h2>
            <?php
            if($this->getChild('name.after')) {
              $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
              foreach ($_nameAfterChildren as $_nameAfterChildName) {
                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                $_nameAfterChild->setProduct($_product);
                echo $_nameAfterChild->toHtml();
              }
            }
            ?>
          
            <?php
            if(isset($tagline) === true) {
              echo "<div class='product-list-tagline'>{$tagline}</div>";
            }
            
            if(sizeof($product_info) > 0) {
              echo "<ul>";
              foreach($product_info as $key => $item) {
                if($key === $max_product_info_items) break;
                echo "<li class='angle_before'>{$item}</li>";
              }
              echo "</ul>";
            }
            
            if(sizeof($usps) > 0) {
              echo "<ul class='product-list-highlights'>";
              foreach($usps as $usp) {
                echo "<li>{$usp}</li>";
              }
              echo "</ul>";
            }
            ?>
          </div>
          <?php
          echo $price_html;
          if(0 && $_product->getRatingSummary()) {
            echo $this->getReviewsSummaryHtml($_product, 'short');
          }
          ?>
          <div class="actions">
            <div class="float-left" style="padding-top: 5px;">
              <span class="<?php echo $stock_class; ?>"><?php echo $stock_message; ?></span>
            </div>
            <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
            <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart float-right" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i></span></span></button>
            <?php else: ?>
            <a title="<?php echo $this->quoteEscape($this->__("Productdetails")) ?>" class="float-right" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__("Productdetails") ?></a>
            <?php endif; ?>
          </div>
        </div>
      </li>

    <?php
    if(($i === 3 OR ($i - 3) % 6 === 0) AND $_collectionSize > $i) { ?>
      </ul>
        <div class="new-tab-contant-text mobile-hide">
          <div class="col-md-3 new-contant">
            <p><i class="fa fa-check"></i>Altijd de beste prijs</p>
            <p><i class="fa fa-check"></i>Advies door professionals</p>
          </div>
          <div class="col-md-3 new-contant">
            <p><i class="fa fa-check"></i>Wij vergelijken de prijzen</p>
            <p><i class="fa fa-check"></i>Gratis verzending vanaf &euro;150,-</p>
          </div>
          <div class="col-md-3 new-contant">
            <p><i class="fa fa-check"></i>Professionele apparatuur</p>
            <p><i class="fa fa-check"></i>Snelle levering</p>
          </div>
        </div>
      <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
    <?php
    }
  }
  ?>
  </ul>
  <!-- <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script> -->

    <?php /* PRODUCTADVIES BLOCK */ ?>

    <div class="new-tab-contant mobile-hide">
      <div class="col-md-3 image-box">
        <img height="100" width="100" src="/skin/frontend/rwd/dhh/images/ditzijnwij.png" alt="Prokoeling.nl service">
      </div>
      <div class="col-md-5 contant-box" style="width:40%">
        <h2>Productadvies nodig?</h2>
        <p>Heb je hulp nodig bij het uitzoeken van het juiste product? Onze adviseurs helpen je graag.<br />Prokoeling.nl - Klantenteam</p>
      </div>
      <div class="col-md-4 mail-box" style="width:45%">
        <p>Bel ons: <a href="tel:+3180441003">(+31) (0)850441003</a></p>
        <p>Of <a href="mailto:klantenservice@prokoeling.nl">E-mail Ons</a></p>
      </div>
    </div>

    <?php /* TOOLBAR (PAGINATION) BLOCK */ ?>

    <div class="toolbar-bottom">
      <?php echo $this->getToolbarHtml() ?>
    </div>
  </div>
  <?php

  // Provides a block where additional page components may be attached, primarily good for in-page JavaScript
  if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
      $_afterChild = $this->getChild('after')->getChild($_afterChildName);
      //set product collection on after blocks
      $_afterChild->setProductCollection($_productCollection);
      echo $_afterChild->toHtml();
    }
  }
}
