<?php
/**
 * Template for displaying product price in different places (products grid, product view page etc)
 *
 * @see Mage_Catalog_Block_Product_Abstract
 */

$controller_name          = Mage::app()->getRequest()->getControllerName(); // "category", "index", "product"
$dhh_debug                = false;
$debug_lines              = [];

// printr($controller_name);

/*
Known configurations:
- Product listview:
  - With special price (MSRP + special price): Context 11
  - Without special price (MSRP + regular price): Context 3
- Product detailview: "Discount. Context ?"
- Featured list: ?
- Related products without a discount: Context 3
- Cart: ?

Tests:
- Context 4: https://www.chefstore.nl/koelingen/koelwerkbanken-saladettes/pizzawerkbanken/pizzawerkbank-rvs-444-liter-saro-ps300g-323-1106.html?nofpc
- Context 13: https://www.chefstore.nl/koelingen/koelwerkbanken-saladettes/pizzawerkbanken/koelwerkbank-rvs-saro-sh2500-323-1125.html?nofpc
- Context 13 with both start and end date: https://www.chefstore.nl/apparatuur-1/koffiemachines/koffiezetapparaten/bartscher-volautomatisch-koffiezetappa-kv1-190052.html?nofpc

Contexts:

- Non-Grouped products:
  - No special price:
    - Display both incVAT and exVAT:
      - Context: 0    => Not used, WEEE-related
      - Context: 1    => Not used, WEEE-related
      - Context: 2    => Not used, WEEE-related
      - Context: 3    => Not used, WEEE-related
      - Context: 4    => Used
        - Listview without special price
        - Detailview without special price
        - Related products without special price
    - Don't display both prices, only exVAT:
      - Context: 5    => Not used, WEEE-related
      - Context: 6    => Not used, WEEE-related
      - Context: 7    => Not used, WEEE-related
      - Context: 8    => Non-WEEE
  - Special price:
      - Context: 9    => Not used, WEEE-related
      - Context: 10   => Not used, WEEE-related
      - Context: 11   => Not used, WEEE-related
      - Context: 12   => Not used, WEEE-related
      - Context: 13   => Used
        - Listview with special price
        - Related products with special price
        - Detailview with special price
        - Related products with special price
  
  - Context: 14   => Optional minimal price, used in case of volume discount
- Grouped Products:
  - Context: 15   => Grouped products, Used
*/

/* Functions need to be declared only once and before use */

if(function_exists('_fixPrice') === false) {
  function _fixPrice($price, $keep_sign = false) {
    if($keep_sign === false) {
      $price = str_replace(["€", "&nbsp;"], "", (string) $price);    // Remove euro symbol
    }
    $price = str_replace(",00", ",-", (string) $price);                // Trim zero cents
    $price = str_replace(".", "", $price);                    // Remove thousand separator
    $price = preg_replace("/(^\s+)|(\s+$)/us", "", $price);   // An utf8 trim()
    $price = strip_tags(trim((string) $price));
    
    return $price;
  }
}

if(function_exists('_displayMsrp') === false) {
  function _displayMsrp($msrp_formatted, $msrpStoreLabel, $id) {
    return "<div class='old-price'><span>{$msrpStoreLabel}: </span><span class='price strike' id='old-price-{$id}'>{$msrp_formatted}</span></div>";
  }
}

if(function_exists('_displayRegularPriceDuringSpecialPrice') === false) {
  function _displayRegularPriceDuringSpecialPrice($price_formatted) {
    return "<div class='my-2 old-price bit-bigger'><span>Normaal: </span><span class='price strike'>{$price_formatted}</span></div>";
  }
}

if(function_exists('_displayDiscount') === false) {
  function _displayDiscount($_discount_abs_formatted, $discount_perc, $id) {
    return "<div class='productdetail__discount'>Bespaar <span class=strong>{$_discount_abs_formatted}</span></div>";
  }
}

if(function_exists('_displayPriceDates') === false) {
  function _displayPriceDates($store, $_special_price_from_date, $_special_price_to_date) {
    
    if(empty($_special_price_to_date)) return null;
    
    if(Mage::app()->getLocale()->isStoreDateInInterval($store, $_special_price_from_date, $_special_price_to_date)) {
      setlocale(LC_TIME, "nl_NL");
      $_special_price_to_ts = strtotime((string) $_special_price_to_date);
      $display_date = strftime("%A %e %B", $_special_price_to_ts);
      return "<div class='special_price_dates pt-1'>SALE eindigt <strong>{$display_date}</strong></div>";
    }
    
    return null;
  }
}

$_product                 = $this->getProduct();

if($_product->getAttributeText("eol") !== "Ja") {

  $showMinPrice             = $this->getDisplayMinimalPrice();

  $_coreHelper              = $this->helper('core');
  $_weeeHelper              = $this->helper('weee');
  $_taxHelper               = $this->helper('tax');

  $_storeId                 = $_product->getStoreId();
  $_store                   = $_product->getStore();
  $_id                      = $_product->getId();
  $_weeeSeparator           = '';
  $_simplePricesTax         = ($_taxHelper->displayPriceIncludingTax() || $_taxHelper->displayBothPrices());
  $_minimalPriceValue       = $_product->getMinimalPrice();
  $_minimalPriceValue       = $_store->roundPrice($_store->convertPrice($_minimalPriceValue));
  $_minimalPrice            = $_taxHelper->getPrice($_product, $_minimalPriceValue, $_simplePricesTax);
  $_convertedFinalPrice     = $_store->roundPrice($_store->convertPrice($_product->getFinalPrice()));
  $_specialPriceStoreLabel  = $this->getProductAttribute('special_price')->getStoreLabel();
  $_msrpStoreLabel          = $this->getProductAttribute('msrp')->getStoreLabel();
  $_special_price_from_date = $_product->getSpecialFromDate();
  $_special_price_to_date   = $_product->getSpecialToDate();

  $_special_price_from_ts   = empty($_special_price_from_date) ? null : strtotime((string) $_special_price_from_date);
  $_special_price_to_ts     = empty($_special_price_to_date)   ? null : strtotime((string) $_special_price_to_date);

  if(!$_product->isGrouped()) {
    $_weeeTaxAmount           = $_weeeHelper->getAmountForDisplay($_product);
    $_weeeTaxAttributes       = $_weeeHelper->getProductWeeeAttributesForRenderer($_product, null, null, null, true);
    $_weeeTaxAmountInclTaxes  = $_weeeTaxAmount;
    if($_weeeHelper->isTaxable()) {
      $_weeeTaxAmountInclTaxes = $_weeeHelper->getAmountInclTaxes($_weeeTaxAttributes);
    }

    $_weeeTaxAmount           = $_store->roundPrice($_store->convertPrice($_weeeTaxAmount));
    $_weeeTaxAmountInclTaxes  = $_store->roundPrice($_store->convertPrice($_weeeTaxAmountInclTaxes));
    $_convertedPrice          = $_store->roundPrice($_store->convertPrice($_product->getPrice()));

    $used_msrp                = $_product->getMsrpDisplayed();
    if(empty($used_msrp)) {
      $used_msrp                = $_product->getMsrp();
    }
    $used_msrp                = $_store->convertPrice($used_msrp);

    $_msrp                    = $_taxHelper->getPrice($_product, $used_msrp);
    $_price                   = $_taxHelper->getPrice($_product, $_convertedPrice);
    $_regularPrice            = $_taxHelper->getPrice($_product, $_convertedPrice, $_simplePricesTax);
    $_finalPrice              = $_taxHelper->getPrice($_product, $_convertedFinalPrice);
    $_finalPriceInclTax       = $_taxHelper->getPrice($_product, $_convertedFinalPrice, true);
    $_weeeDisplayType         = $_weeeHelper->getPriceDisplayType();

    $_discount                = ($_finalPrice - $_msrp) * 1;

    // Prep for display, no more calcs
    $_msrp_formatted              = _fixPrice($_coreHelper->formatPrice($_msrp, false));
    $_discount_abs_formatted      = _fixPrice($_coreHelper->formatPrice($_discount * -1, false), true);
    $_price_formatted             = _fixPrice($_coreHelper->formatPrice($_price, false));
    $_finalPrice_formatted        = _fixPrice($_coreHelper->formatPrice($_finalPrice, false));
    $_finalPriceInclTax_formatted = _fixPrice($_coreHelper->formatPrice($_finalPriceInclTax, false));

    $_discount_pct = $_discount_pct_formatted = null;
    if($_price != 0) {
      $_discount_pct = ($_discount / $_price) * 100 * -1;
      $_discount_pct_formatted  = number_format($_discount_pct, 0);
    }
    ?>

    <div class="price-box nowrap">

    <?php
    if($_finalPrice >= $_price) {
      if($_taxHelper->displayBothPrices()) {

        // CONTEXT 0 -- NOT USED

        if($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 0)) { // including
          $debug_lines[] = "Context: 0";
          ?>
          <span class="price-excluding-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:'); ?></span>
            <span class="price">
              <?php echo $_coreHelper->formatPrice($_price + $_weeeTaxAmount, false); ?>
            </span>
          </span>
          <span class="price-including-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
            <span class="price">
              <?php echo $_coreHelper->formatPrice($_finalPriceInclTax + $_weeeTaxAmountInclTaxes, false) ?>
            </span>
          </span>
          <?php

        // CONTEXT 1 -- NOT USED

        } elseif($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 1)) { // incl. + weee
          $debug_lines[] = "Context: 1";
          ?>
          <span class="price-excluding-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
            <span class="price">
              <?php echo $_coreHelper->formatPrice($_price + $_weeeTaxAmount, false) ?>
            </span>
          </span>
          <span class="weee">(
            <?php foreach($_weeeTaxAttributes as $_weeeTaxAttribute):
              echo $_weeeSeparator;
              echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount(), true, true);
              $_weeeSeparator = ' + ';
            endforeach; ?>
            )</span>
          <span class="price-including-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
            <span class="price">
              <?php echo $_coreHelper->formatPrice($_finalPriceInclTax + $_weeeTaxAmountInclTaxes, false) ?>
            </span>
          </span>
          <?php

        // CONTEXT 2 -- NOT USED

        } elseif($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 4)) { // incl. + weee
          $debug_lines[] = "Context: 2";
          ?>
          <span class="price-excluding-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
            <span class="price">
              <?php echo $_coreHelper->formatPrice($_price + $_weeeTaxAmount, false) ?>
            </span>
          </span>
          <span class="price-including-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
            <span class="price">
              <?php echo $_coreHelper->formatPrice($_finalPriceInclTax + $_weeeTaxAmountInclTaxes, false) ?>
            </span>
            <span class="weee">(
              <?php foreach($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                <?php echo $_weeeSeparator; ?>
                <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount() + $_weeeTaxAttribute->getTaxAmount(), true, true); ?>
                <?php $_weeeSeparator = ' + '; ?>
              <?php endforeach; ?>
              )</span>
          </span>
          <?php

        // CONTEXT 3 -- NOT USED

        } elseif($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 2)) { // excl. + weee + final
          $debug_lines[] = "Context: 3";
          ?>
          <span class="price-excluding-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
            <span class="price">
              <?php echo $_coreHelper->formatPrice($_price, false) ?>
            </span>
          </span>
          <?php
          foreach($_weeeTaxAttributes as $_weeeTaxAttribute) { ?>
            <span class="weee">
              <?php echo $_weeeTaxAttribute->getName(); ?>
              : <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount() + $_weeeTaxAttribute->getTaxAmount(), true, true); ?>
            </span>
          <?php
          }
          ?>
          <span class="price-including-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
            <span class="price">
              <?php echo $_coreHelper->formatPrice($_finalPriceInclTax + $_weeeTaxAmountInclTaxes, false) ?>
            </span>
          </span>
          <?php
        }

        // CONTEXT: 4 => Used:
        // - Listview without special price
        // - Detailview without special price
        // - Related products without special price

        else {
          $debug_lines[] = "Context: 4";

          // MSRP
          if($_msrp > $_finalPrice && $_discount_pct > 1 && $controller_name !== "category"
          && $controller_name !== "cart" && $controller_name !== "index") {
            echo _displayMsrp($_msrp_formatted, $_msrpStoreLabel, $_id.$this->getIdSuffix());
          }
          ?>
          <span class="price-excluding-tax not-special">
            <?php
            if($_product->canConfigure()) {
              echo "<span class='from_price_conf'>Vanaf</span>";
            }
            if($_finalPrice == $_price) {
              $tmp = $_price_formatted;
            } else {
              $tmp = $_finalPrice_formatted;
            }
            // <span class="label">$this->helper('tax')->__('Excl. Tax:')</span>
            ?>
            <span class="price"><?php echo $tmp; ?></span>
          </span>

          <?php
          if($controller_name !== "category" && $controller_name !== "cart" && $controller_name !== "index") { ?>
            <span class="price-including-tax not-special italic small">
              <span class="price">
                <?php echo $_finalPriceInclTax_formatted; ?>
              </span>
              <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
            </span>
            <?php
          }

          // SHOW DISCOUNT IF >2%
          if($_discount_pct > 2 && $controller_name !== "category" && $controller_name !== "cart" && $controller_name !== "index") {
            echo _displayDiscount($_discount_abs_formatted, $_discount_pct_formatted, $_id.$this->getIdSuffix());
          }
        }

      } else { // $_taxHelper->displayBothPrices()

        // CONTEXT 5 -- NOT USED

        if($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, array(0, 1))) { // including
          $debug_lines[] = "Context: 5";
          $weeeAmountToDisplay = $_taxHelper->displayPriceIncludingTax() ? $_weeeTaxAmountInclTaxes : $_weeeTaxAmount;
          ?>
          <span class="regular-price">
            <?php echo $_coreHelper->currency($_price + $weeeAmountToDisplay, true, true) ?>
          </span>

          <?php if($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 1)): // show description ?>
            <span class="weee">(
              <?php foreach($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                <?php echo $_weeeSeparator; ?>
                <?php echo $_weeeTaxAttribute->getName(); ?>
                : <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount() + ($_taxHelper->displayPriceIncludingTax() ? $_weeeTaxAttribute->getTaxAmount() : 0), true, true); ?>
                <?php $_weeeSeparator = ' + '; ?>
              <?php endforeach; ?>
              )</span>
<?php endif;

        /* CONTEXT 6 */

        } elseif($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 4)) { // incl. + weee
          $debug_lines[] = "Context: 6";
          ?>
          <span class="regular-price">
            <?php echo $_coreHelper->formatPrice($_price + $_weeeTaxAmount, true) ?>
          </span>
          <span class="weee">(
            <?php foreach($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
              <?php echo $_weeeSeparator; ?>
              <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount() + $_weeeTaxAttribute->getTaxAmount(), true, true); ?>
              <?php $_weeeSeparator = ' + '; ?>
            <?php endforeach; ?>
            )</span>
        <?php

        /* CONTEXT 7 */

        } elseif($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 2)) { // excl. + weee + final
          $debug_lines[] = "Context: 7";
          ?>
          <span class="regular-price"><?php echo $_coreHelper->formatPrice($_price, true) ?></span><br/>
          <?php $weeeAmountToDisplay = $_taxHelper->displayPriceIncludingTax() ? $_weeeTaxAmountInclTaxes : $_weeeTaxAmount ?>
          <?php foreach($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
            <span class="weee">
             <?php echo $_weeeTaxAttribute->getName(); ?>
              : <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount() + ($_taxHelper->displayPriceIncludingTax() ? $_weeeTaxAttribute->getTaxAmount() : 0), true, true); ?>
            </span>
          <?php endforeach; ?>
          <span class="regular-price" id="product-price-weee-<?php echo $_id.$this->getIdSuffix(); ?>">
            <?php echo $_coreHelper->currency($_price + $weeeAmountToDisplay, true, true) ?>
          </span>
          <?php

        /* CONTEXT 8 */

        } else {
          $debug_lines[] = "Context: 8"; ?>
          <span class="regular-price">
            <?php if($_finalPrice == $_price): ?>
              <?php echo $_coreHelper->formatPrice($_price, true); ?>
            <?php else: ?>
              <?php echo $_coreHelper->formatPrice($_finalPrice, true); ?>
            <?php endif; ?>
          </span>
        <?php
        }
      }
    } else { // if($_finalPrice == $_price):
      $_originalWeeeTaxAmount = $_weeeHelper->getOriginalAmount($_product);
      $_originalWeeeTaxAmount = $_store->roundPrice($_store->convertPrice($_originalWeeeTaxAmount));

      // CONTEXT 9 -- NOT USED

      if($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 0)) { // including
        $debug_lines[] = "Context: 9";
        ?>
        <p class="old-price">
          <span class="price-label"><?php echo $this->__('Regular Price:') ?></span>
          <span class="price">
            <?php echo $_coreHelper->formatPrice($_regularPrice + $_originalWeeeTaxAmount, false) ?>
          </span>
        </p>

        <?php
        if($_taxHelper->displayBothPrices()) {
          ?>
          <p class="special-price">
            <span class="price-label"><?php echo $_specialPriceStoreLabel ?></span>
            <span class="price-excluding-tax">
              <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
              <span class="price">
                <?php echo $_coreHelper->formatPrice($_finalPrice + $_weeeTaxAmount, false) ?>
              </span>
            </span>
          <span class="price-including-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
            <span class="price">
              <?php echo $_coreHelper->formatPrice($_finalPriceInclTax + $_weeeTaxAmountInclTaxes, false) ?>
            </span>
          </span>
          </p>
          <?php
        } else {
          ?>
          <p class="special-price">
            <span class="price-label"><?php echo $_specialPriceStoreLabel ?></span>
          <span class="price">
            <?php echo $_coreHelper->formatPrice($_finalPrice + $_weeeTaxAmountInclTaxes, false) ?>
          </span>
          </p>
        <?php
        }

      // CONTEXT 10 -- NOT USED

      } elseif($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 1)) { // incl. + weee
        $debug_lines[] = "Context: 10"; ?>
        <p class="old-price">
          <span class="price-label"><?php echo $this->__('Regular Price:') ?></span>
          <span class="price">
            <?php echo $_coreHelper->formatPrice($_regularPrice + $_originalWeeeTaxAmount, false) ?>
          </span>
        </p>

        <p class="special-price">
        <?php if($_taxHelper->displayBothPrices()): ?>
          <span class="price-label"><?php echo $_specialPriceStoreLabel ?></span>
          <span class="price-excluding-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
            <span class="price">
            <?php echo $_coreHelper->formatPrice($_finalPrice + $_weeeTaxAmount, false) ?>
            </span>
          </span>
          <span class="weee">(
            <?php foreach($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
              <?php echo $_weeeSeparator; ?>
              <?php echo $_weeeTaxAttribute->getName(); ?>
              : <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount(), true, true); ?>
              <?php $_weeeSeparator = ' + '; ?>
            <?php endforeach; ?>
            )</span>
          <span class="price-including-tax">
          <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
          <span class="price">
            <?php echo $_coreHelper->formatPrice($_finalPriceInclTax + $_weeeTaxAmountInclTaxes, false) ?>
          </span>
          </span>
        <?php else: ?>
          <span class="price-label"><?php echo $this->__('Special Price:') ?></span>
          <span class="price">
            <?php echo $_coreHelper->formatPrice($_finalPrice + $_weeeTaxAmountInclTaxes, false) ?>
          </span>
          <span class="weee">(
            <?php foreach($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
              <?php echo $_weeeSeparator; ?>
              <?php echo $_weeeTaxAttribute->getName(); ?>
              : <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount(), true, true); ?>
              <?php $_weeeSeparator = ' + '; ?>
            <?php endforeach; ?>
            )</span>
        <?php endif; ?>
        </p>
      <?php

      // CONTEXT 11 -- NOT USED

      } elseif($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 4)) { // incl. + weee ?>
        <?php $debug_lines[] = "Context: 11"; ?>
        <p class="old-price">
          <span class="price-label"><?php echo $this->__('Regular Price:') ?></span>
          <span class="price">
            <?php echo $_coreHelper->formatPrice($_regularPrice + $_originalWeeeTaxAmount, false) ?>
          </span>
        </p>

        <p class="special-price">
          <span class="price-label"><?php echo $_specialPriceStoreLabel ?></span>
          <span class="price-excluding-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
            <span class="price">
              <?php echo $_coreHelper->formatPrice($_finalPrice + $_weeeTaxAmount, false) ?>
            </span>
          </span>
        <span class="weee">(
          <?php foreach($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
            <?php echo $_weeeSeparator; ?>
            <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount() + $_weeeTaxAttribute->getTaxAmount(), true, true); ?>
            <?php $_weeeSeparator = ' + '; ?>
          <?php endforeach; ?>
          )</span>
        <span class="price-including-tax">
          <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
          <span class="price">
            <?php echo $_coreHelper->formatPrice($_finalPriceInclTax + $_weeeTaxAmountInclTaxes, false) ?>
          </span>
        </span>
        </p>
      <?php

      // CONTEXT 12 -- NOT USED

      } elseif($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 2)) { // excl. + weee + final ?>
      <?php $debug_lines[] = "Context: 12"; ?>
        <p class="old-price">
          <span class="price-label"><?php echo $this->__('Regular Price:') ?></span>
          <span class="price">
            <?php echo $_coreHelper->formatPrice($_regularPrice, false) ?>
          </span>
        </p>

        <p class="special-price">
          <span class="price-label"><?php echo $_specialPriceStoreLabel ?></span>
          <span class="price-excluding-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
            <span class="price">
              <?php echo $_coreHelper->formatPrice($_finalPrice, false) ?>
            </span>
          </span>
          <?php foreach($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
            <span class="weee">
              <?php echo $_weeeTaxAttribute->getName(); ?>
              : <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount(), true, true); ?>
            </span>
          <?php endforeach; ?>
          <span class="price-including-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
            <span class="price">
              <?php echo $_coreHelper->formatPrice($_finalPriceInclTax + $_weeeTaxAmountInclTaxes, false) ?>
            </span>
          </span>
        </p>

<?php

      }

      // CONTEXT 13 -- USED:
      // - Listview with special price
      // - Related products with special price
      // - Detailview with special price
      // - Related products with special price

      else {

        // MSRP
        if($_msrp > $_finalPrice && $_discount_pct > 1 && $controller_name !== "category" && $controller_name !== "cart" && $controller_name !== "index") {
          echo _displayMsrp($_msrp_formatted, $_msrpStoreLabel, $_id.$this->getIdSuffix());
        }

        if(Mage::app()->getLocale()->isStoreDateInInterval($_store, $_special_price_from_date, $_special_price_to_date)) {
          $debug_lines[] = "Context: 13A";
          // if($_msrp > $_price) {
            // echo _displayRegularPriceDuringSpecialPrice($_price_formatted);
          // }
        } else {
          $debug_lines[] = "Context: 13B";
        }

        // SPECIAL PRICE
        if($_taxHelper->displayBothPrices()) {
          ?>
          <div class="special-price">
            <span class="price-excluding-tax">
              <span class="price">
                <?php echo _fixPrice($_coreHelper->formatPrice($_finalPrice, false)) ?>
              </span>
            </span>
            <?php
            if($controller_name !== "category" && $controller_name !== "cart" && $controller_name !== "index") { ?>
              <span class="price-including-tax italic small">
                <span class="price">
                  <?php echo _fixPrice($_coreHelper->formatPrice($_finalPriceInclTax, false)) ?>
                </span>
              <span class="label">incl. btw</span>
              </span>
              <?php
            } ?>
          </div>
          <?php
        } else {
          ?>
          <div class="special-price">
            <span class="price-label"><?php echo $_specialPriceStoreLabel ?></span>
            <span class="price">
            <?php echo _fixPrice($_coreHelper->formatPrice($_finalPrice, false)) ?>
            </span>
          </div>
        <?php
        }

        // SHOW DISCOUNT IF >2%
        if($_discount_pct > 2 && $controller_name !== "category" && $controller_name !== "cart" && $controller_name !== "index") {
          echo _displayDiscount($_discount_abs_formatted, $_discount_pct_formatted, $_id.$this->getIdSuffix());
        }

        if($controller_name !== "category" && $controller_name !== "cart" && $controller_name !== "index") {
          echo _displayPriceDates($_store, $_special_price_from_date, $_special_price_to_date);
        }
      } 
    } /* if($_finalPrice == $_price): */

    /* CONTEXT 14 -- Volume discount */

    if($showMinPrice && $_minimalPriceValue && $_minimalPriceValue < $_convertedFinalPrice) {
      $debug_lines[] = "Context 14";
      $_minimalPriceDisplayValue = $_minimalPrice;
      if($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, [0, 1, 4])) {
        $_minimalPriceDisplayValue = $_minimalPrice + $_weeeTaxAmount;
      }

      if($this->getUseLinkForAsLowAs()) {
        echo "<a href='{$_product->getProductUrl()}' class='minimal-price-link'>";
      } else {
        echo "<span class='minimal-price-link'>";
      }
      ?>
      <span class='label'><?php echo $this->__("As low as:") ?></span>
      <span class='price hidden' id='product-minimal-price-<?php echo $_id.$this->getIdSuffix(); ?>'>
        <?php echo $_coreHelper->formatPrice($_minimalPriceDisplayValue, false); ?>
      </span>
      <?php
      if($this->getUseLinkForAsLowAs()) {
        echo "</a>";
      } else {
        echo "</span>";
      }
    }
    ?>
    </div>

  <?php

  /* CONTEXT: 15 -- Grouped Products */

  } else { /* if(!$_product->isGrouped()): */
    $debug_lines[] = "Context 15";

    if($showMinPrice && $_minimalPriceValue) {
      $_exclTax = $_taxHelper->getPrice($_product, $_minimalPriceValue);
      $_inclTax = $_taxHelper->getPrice($_product, $_minimalPriceValue, true);
      $price = $showMinPrice ? $_minimalPriceValue : 0;
    } else {
      $price = $_convertedFinalPrice;
      $_exclTax = $_taxHelper->getPrice($_product, $price);
      $_inclTax = $_taxHelper->getPrice($_product, $price, true);
    }

    if($price) {
      ?>
      <div class="price-box nowrap">
        <p<?php if($showMinPrice): ?> class="minimal-price"<?php endif ?>>
          <?php if($showMinPrice): ?>
            <span class="price-label"><?php echo $this->__('Starting at:') ?></span>
          <?php endif ?>
          <?php if($_taxHelper->displayBothPrices()) { ?>
            <span class="price-excluding-tax">
              <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
              <span class="price">
                <?php echo _fixPrice($_coreHelper->formatPrice($_exclTax, false)) ?>
              </span>
            </span>
            <?php
            if($controller_name !== "category" && $controller_name !== "cart" && $controller_name !== "index") { ?>
              <span class="price-including-tax italic small">
                <span class="price">
                  <?php echo _fixPrice($_coreHelper->formatPrice($_inclTax, false)) ?>
                </span>
              <span class="label">incl. btw</span>
              </span>
              <?php
            }
          } else {
            $_showPrice = $_inclTax;
            if(!$_taxHelper->displayPriceIncludingTax()) {
              $_showPrice = $_exclTax;
            }
            ?>
            <span class="price" id="product-minimal-price-<?php echo $_id.$this->getIdSuffix(); ?>">
            <?php echo $_coreHelper->formatPrice($_showPrice, false) ?>
          </span>
          <?php } ?>
        </p>
      </div>
    <?php
    }
  }

  // if(_dhh_debug()) {

    // $debug_lines[] = "displayBothPrices() = {$_taxHelper->displayBothPrices()}";
    // $debug_lines[] = "_simplePricesTax: {$_simplePricesTax}";
    // $debug_lines[] = "_minimalPriceValue: {$_minimalPriceValue}";
    // $debug_lines[] = "_minimalPrice: {$_minimalPrice}";
    // $debug_lines[] = "_convertedFinalPrice: {$_convertedFinalPrice}";
    // $debug_lines[] = "_specialPriceStoreLabel: {$_specialPriceStoreLabel}";
    // $debug_lines[] = "_msrpStoreLabel: {$_msrpStoreLabel}";
    // $debug_lines[] = "_msrp: {$_msrp}";
    // $debug_lines[] = "_price: {$_price}";
    // $debug_lines[] = "_regularPrice: {$_regularPrice}";
    // $debug_lines[] = "_finalPrice: {$_finalPrice}";
    // $debug_lines[] = "_finalPriceInclTax: {$_finalPriceInclTax}";
    // $debug_lines[] = "_special_price_from_date: {$_special_price_from_date}";
    // $debug_lines[] = "_special_price_to_date: {$_special_price_to_date}";
    // $debug_lines[] = "_special_price_from_ts: {$_special_price_from_ts}";
    // $debug_lines[] = "_special_price_to_ts: {$_special_price_to_ts}";

    // echo "<pre>";
    // foreach($debug_lines as $line) {
      // echo $line.PHP_EOL;
    // }
    // echo "</pre>";
  // }
}
