<?php
/* @var $this Mage_Core_Block_Template */
$_helper = $this->helper('deheerhoreca_fpc'); /* @var $_helper Aoe_ClassPathCache_Helper_Data */
?>
<table class="form-list">
    <tr>
        <td class="scope-label" style="width:220px;">
            <button onclick="setLocation('<?php echo $_helper->getUrl() ?>')" type="button" class="scalable">
                <span><span><span><?php echo Mage::helper('adminhtml')->__('Flush DHH FPC') ?></span></span></span>
            </button>
        </td>
        <td class="scope-label">
            <span>De full page cache helemaal leeggooien</span>
        </td>
    </tr>
</table>
