<?php $this->setBlockData()?>
<?php $_code = $this->getMethodCode(); ?>
<?php $_helper = $this->helper('afterpay');?>
<?php $isEnterprise = (bool) Mage::getConfig()->getModuleConfig("Enterprise_Enterprise")->version;?>

<div id="payment-errors" class="validation-advice" style="display:none;"></div>

<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code; ?>" style="display:none;">
        <li>
            <?php if ($this->showGender()): ?>
            <div class="field">
                <label for="<?php echo $_code; ?>_gender" class = "required"><em>*</em><?php echo $_helper->__('Gender:'); ?></label>
                <div class="input-box" id="">
                    <input type="radio" name="payment[<?php echo $_code; ?>][gender]" value="V" id="<?php echo $_code?>_gender_v" checked="checked">
                    <label style="float:none" for="<?php echo $_code?>_gender_v"><?php echo $_helper->__('Female'); ?></label>
                    <input type="radio" name="payment[<?php echo $_code; ?>][gender]" value="M" id="<?php echo $_code?>_gender_m">
                    <label style="float:none" for="<?php echo $_code?>_gender_m"><?php echo $_helper->__('Male'); ?></label>
                </div>
            </div>
            <?php endif; ?>
        <?php if ($isEnterprise): ?>
        </li>
        <li>
        <?php endif;?>
            <?php if (!$this->isB2B()): ?>
            <?php if ($this->showDob()): ?>
            <div class="field">
                <?php 
                echo $this->getLayout()->createBlock('afterpay/customer_widget_dob')
                                       ->setFieldIdFormat($_code . ':billing:%s')
                                       ->setFieldNameFormat('payment[' . $_code . '][%s]')
                                       ->setIsRequired(true)
                                       ->setPaymentMethodCode($_code)
                                       ->toHtml() 
                ?>
            </div>
        </li>
        <?php endif; ?>
        <?php if ($this->showBankcode()): ?>
            <li>
                <div class="field">
                    <label for="<?php echo $_code; ?>_bankcode" class="required"><em>*</em><?php echo $_helper->__('BIC / Swift-Code:'); ?></label>
                    <div class="input-box">
                        <input type="text" class="required-entry" id="<?php echo $_code; ?>_bankcode" name="payment[<?php echo $_code; ?>][bankcode]" style="">
                    </div>
                </div>
            </li>
        <?php endif; #showBankcode ?>
        <?php if ($this->showBankaccount()): ?>
        <li> 
            <div class="field">
                <label for="<?php echo $_code; ?>_bankaccount" class="required"><em>*</em><?php echo $_helper->__('Bank account number:'); ?></label>
                <div class="input-box">
                    <input type="text" class="required-entry" id="<?php echo $_code; ?>_bankaccount" name="payment[<?php echo $_code; ?>][bankaccount]" style="">
                </div>
            </div>
        </li>
        <?php endif; ?>
        <?php endif; ?>
        <?php if ($this->isB2B()): ?>
        <li>
            <div class="field">
                <label for="<?php echo $_code; ?>_companyname" class="required"><em>*</em><?php echo $_helper->__('Company name:'); ?></label>
                <div class="input-box">
                    <input type="text" value="<?php echo $this->getCompany(); ?>" class="required-entry" id="<?php echo $_code; ?>_companyname" name="payment[<?php echo $_code; ?>][companyname]">
                </div>
            </div>
        </li>
        <li>
            <div class="field">
                <label for="<?php echo $_code; ?>_coc" class="required"><em>*</em><?php echo $_helper->__('Coc number:'); ?></label>
                <div class="input-box">
                    <input type="text" class="required-entry" id="<?php echo $_code; ?>_coc" name="payment[<?php echo $_code; ?>][coc]">
                </div>
            </div>
        </li>
        <?php endif; ?>
        <?php if ($this->showPhonenumber()): ?>
        <li> 
            <div class="field">
                <label for="<?php echo $_code; ?>_phonenumber" class="required"><em>*</em><?php echo $_helper->__('Phone number'); ?>:</label>
                <div class="input-box">
                    <input type="text" class="required-entry" id="<?php echo $_code; ?>_phonenumber" name="payment[<?php echo $_code; ?>][phonenumber]">
                </div>
            </div>
        </li>
        <?php endif; ?>
        <?php if ($this->showSsn()): ?>
        <li> 
            <div class="field">
                <label for="<?php echo $_code; ?>_ssn" class="required"><em>*</em><?php echo $_helper->__('Social security number'); ?>:</label>
                <div class="input-box">
                    <input type="text" class="required-entry" id="<?php echo $_code; ?>_ssn" name="payment[<?php echo $_code; ?>][ssn]">
                </div>
            </div>
        </li>
        <?php endif; ?>
        <?php if ($this->useProfiletracking()): ?>
            <?php // Get the Magento session for profile tracking. ?>
            <?php $session_id = Mage::getSingleton('core/session')->getEncryptedSessionId(); ?>
            <input type="hidden" id="<?php echo $_code; ?>_session" name="payment[<?php echo $_code; ?>][session]" value="<?php echo $session_id; ?>" />
            <script type="text/javascript">
                var _itt = {
                c: '<?php echo $this->getProfiletrackingClientId(); ?>',
                s: '<?php echo $session_id; ?>',
                t: 'CO'};(function() {
                var a = document.createElement('script');
                a.type = 'text/javascript'; a.async = true;
                a.src = '//uc8.tv/7982.js';
                var b = document.getElementsByTagName('script')[0]; b.parentNode.insertBefore(a, b);
                })();
            </script>
            <noscript>
                <img src="//uc8.tv/img/7982/<?php echo $session_id; ?>" border=0 height=0 width=0 />
            </noscript>
        <?php endif; ?>
        <li>
            <input type="checkbox" class="checkbox required-entry" id="<?php echo $_code; ?>_termsAndConditions" name="payment[<?php echo $_code; ?>][conditions]">
            <label for="<?php echo $_code; ?>_termsAndConditions" class="required" style="float:none;">
                <em>*</em>
                <?php if ($this->country == 'nlnl' || $this->country == 'benl' || $this->country == 'befr' ): ?>
                <?php echo $_helper->__(
                    'I have read and accepted the AfterPay %sTerms and Conditions%s.',
                    $this->paymentConditionsUrl,
                    $this->anchorClose
                );?>
                <?php else : ?>
                <?php echo $_helper->__(
                    'I have read the %sTerms & Conditions%s and the %sPrivacy Policy%s of AfterPay and do accept them.',
                    $this->paymentConditionsUrl,
                    $this->anchorClose,
                    $this->privacyStatementUrl,
                    $this->anchorClose
                );?>
                <?php endif; ?>
            </label>
        </li>
    </ul>
</fieldset>