<?php

/* DHH PREP */

// If a watermarked image exists, we inject it at the very end, keeping all logic intact

const WATERMARKED_DIR = "haha/";
const FILENAME_SECRET = "sterfmetjescraper";

$use_cdn = true;

// Logic exists in multiple places, keep in sync:
// - deheerhoreca-magento/app/design/frontend/rwd/dhh/template/magiczoomplus/media.phtml
//   - USES realpath() NOT get_absolute_path()
// - deheerhoreca-intel/lib/intel.inc.php
//   - USES get_absolute_path() NOT realpath()
// Allows for arbitrary number of dashes in the SKU
function _extract_data_from_optimized_image_name($optimized_image, string $dhh_sku = "NO_SKU") {
  $filename = pathinfo((string) $optimized_image, PATHINFO_FILENAME);
  $parts    = explode("-", $filename);
  $count    = sizeof($parts);
  
  if($count >= 5) {
    
    $optimized_image_data = [
      "input"       => $optimized_image,
      "path"        => null,
      "supplier"    => $parts[0],
      // "sku"         => $parts[1],
      "nr"          => $parts[$count-3],
      "type"        => $parts[$count-2],
      "hash"        => $parts[$count-1],
    ];
    
    // get_absolute_path() on intel, realpath() in OpenMage
    if(function_exists("get_absolute_path")) {
      $optimized_image_data["path"] = get_absolute_path($optimized_image);
    } else {
      $optimized_image_data["path"] = realpath($optimized_image);
    }
    
    if($optimized_image_data["path"] === $filename) {
      $msg = "{$dhh_sku} ".__FUNCTION__." failed: Need full image path, not ".var_export($optimized_image, true);
      if(function_exists("logger")) {
        logger($msg, "ERROR");
      } else {
        Mage::log($msg, null, "system.log", true);
      }
      if(function_exists("im")) {
        im("imgs_extract_data_failed");
      }
      return false;
    }
    
    $replaces = [
      "{$optimized_image_data["path"]}-",
      "{$optimized_image_data["supplier"]}-",
      "-{$optimized_image_data["nr"]}",
      "-{$optimized_image_data["type"]}-", // Watch this... "-a" or "-b" matches the hash sometimes
      "{$optimized_image_data["hash"]}",
    ];
    $optimized_image_data["sku"] = str_replace($replaces, "", $filename);
    
    $msg = "{$dhh_sku} Extract data from ".var_export($optimized_image, true)." OK";
    if(function_exists("logger")) {
      logger($msg, "VERBOSE");
    } else {
      if(_dhh_debug()) {
        Mage::log($msg, null, "verbose.txt", true);
      }
    }
    if(function_exists("im")) {
      im("imgs_extract_data_ok");
    }    
    return $optimized_image_data;    
  } else {
    $msg = "{$dhh_sku} Failed to extract data from ".var_export($optimized_image, true).", was the image named correctly?";
    if(function_exists("logger")) {
      logger($msg, "NOTICE");
    } else {
      Mage::log($msg, null, "system.log", true);
    }
    if(function_exists("im")) {
      im("imgs_extract_data_failed");
    }
  }
  return false;
}

// Logic exists in multiple places, keep in sync:
// - deheerhoreca-magento/app/design/frontend/rwd/dhh/template/magiczoomplus/media.phtml
// - deheerhoreca-intel/actions/pushers/catalog-magento1/functions-products.inc.php
function _get_watermarked_image_filename($optimized_image, string $dhh_sku = "UNKNOWN_SKU") {
  
  $result = _extract_data_from_optimized_image_name($optimized_image, $dhh_sku);
  
  if($result === false) {
    $path = $optimized_image;
    if(function_exists("get_absolute_path")) {
      $path = get_absolute_path($optimized_image);
    }
    $msg = "{$dhh_sku} Failed to extract data from ".var_export($path, true).", was the image named correctly?";
    if(function_exists("logger")) {
      logger($msg, "NOTICE");
    } else {
      Mage::log($msg, null, "system.log", true);
    }
    if(function_exists("im")) {
      im("imgs_get_watermark_image_nok");
    }
    return false;
  }
  
  $supplier    = $result["supplier"];
  $sku         = $result["sku"];
  $nr          = $result["nr"];
  $type        = $result["type"];
  $hash        = $result["hash"];
  
  $extension   = pathinfo((string) $optimized_image, PATHINFO_EXTENSION);
  $hash        = substr(md5($nr.$sku.FILENAME_SECRET), 0, 4);
  $wm_path     = "{$supplier}-{$sku}-{$nr}-a-{$hash}.{$extension}";
  
  $msg = "{$dhh_sku} ".__FUNCTION__.": ".var_export(basename((string) $optimized_image), true)." => ".var_export($wm_path, true);
  if(function_exists("logger")) {
    logger($msg, "VERBOSE");
  } else {
    if(_dhh_debug()) {
      Mage::log($msg, null, "verbose.txt", true);
    }
  }
  
  if(function_exists("im")) {
    im("imgs_get_watermark_image_ok");
  }
  
  return $wm_path;
}














/* END DHH PREP */

/* @var $this Mage_Catalog_Block_Product_View_Media */

$magicToolboxHelper   = Mage::helper('magiczoomplus/settings');
$mtDataHelper         = Mage::helper('magiczoomplus');
$templateFilename     = $magicToolboxHelper->getTemplateFilename('product.info.media');
$tool                 = $magicToolboxHelper->loadTool('product');

if($tool->params->checkValue('enable-effect', 'No')) {
  require($templateFilename);
  return;
}

$productModel         = $this->getProduct();
$productBaseImage     = $productModel->getImage();
$isBaseImageIncluded  = false; // NOTE: is product base image not excluded from gallery
$galleryImages        = [];
$galleryImagesCount   = 0;
$productVideos        = $productModel->getData('product_videos');
$productVideos        = empty($productVideos) ? [] : $magicToolboxHelper->getSerializer()->unserialize($productVideos);
$productImages        = [];
$imageFileOverride    = [];

if($productBaseImage == 'no_selection') {
  $productBaseImage   = null;
}
if(!$this->_isGalleryDisabled) {
  $galleryImages      = $this->getGalleryImages();
  $galleryImagesCount = count($galleryImages->getItems());
}

$dhh_sku = $productModel->getSku();

if($galleryImagesCount) {

  foreach($galleryImages as $galleryImage) {
    if (!$mtDataHelper->isGalleryImageVisible($productModel, $galleryImage)) {
      continue;
    }
    // DHH: Somehow, isGalleryImageVisible() does not catch disabled images
    if($galleryImage->getData('disabled_default') === "1" && $galleryImage->getData('disabled_default') === "1") {
      continue;
    }
    $imagePath = $galleryImage->getPath();
    
    // DHH -- See if there is a watermarked counterpart
    $wm_filename = _get_watermarked_image_filename($imagePath, $dhh_sku);
    $wm_path   = dirname((string) $imagePath)."/../../".WATERMARKED_DIR."{$wm_filename}";
    
    // $msg = "";
    if(is_file($wm_path) === true) {
      $imagePath = $wm_path;
      $imageFileOverride[$galleryImage->getFile()] = DS.WATERMARKED_DIR."{$wm_filename}";
      // $msg = "{$dhh_sku} Watermarked image found at ".var_export($wm_path, true);
    } else {
      // $msg = "{$dhh_sku} Watermarked image not found at ".var_export($wm_path, true);
    }
    // END DHH
    
    // DHH EDITS:
    if(file_exists($imagePath)) {
      $imageFile    = $galleryImage->getFile();
      $isBaseImage  = ($imageFile == $productBaseImage);
      
      try {
        $image_size = getimagesize($imagePath);
      } catch(Exception) {
        Mage::log("{$dhh_sku} getimagesize() failed on ".var_export($imagePath, true), null, "system.log", true);
        continue; // Assume that it's a fucked image and skip it
      }
      $productImages[]  = [
        'image-size'      => $image_size,
        'image-file'      => $imageFile,
        'image-label'     => $galleryImage->getLabel(),
        'is-base-image'   => $isBaseImage,
      ];
      if($isBaseImage) {
        $isBaseImageIncluded = true;
      }
    } else {
      $msg = "{$dhh_sku} Product image does not exist: ".var_export($imagePath, true);
      Mage::log($msg, null, "system.log", true);
    }
    // END DHH
  }
}

// if(_dhh_debug()) {
  // dump($productImages);
  // dump($imageFileOverride);
// }

if(!count($productImages)) {
  if(!$productBaseImage && empty($productVideos)) {
    $tool->params->setValue('enable-effect', 'No');
    require($templateFilename);
    return;
  }
}

$productId               = $productModel->getId();

$outputHelper            = $this->helper('catalog/output');
$imageHelper             = $this->helper('catalog/image');

$productTitle            = $this->htmlEscape($productModel->getName());
$productDescription      = $this->htmlEscape($outputHelper->productAttribute($productModel, $productModel->getDescription(), 'description'));
$productShortDescription = $this->htmlEscape($outputHelper->productAttribute($productModel, nl2br((string) $productModel->getShortDescription()), 'short_description'));
$productAlt              = $this->htmlEscape($productModel->getImageLabel());

$createSquareImages      = $tool->params->checkValue('square-images', 'Yes');
$useIndividualTitles     = $tool->params->checkValue('use-individual-titles', 'Yes');
$ignoreMagentoCSSclass   = $tool->params->checkValue('ignore-magento-css', 'Yes') ? 'ignore-magento-css' : '';
$scrollEnabled           = $tool->params->checkValue('magicscroll', 'Yes');
$eventName               = $tool->params->getValue('selectorTrigger');
if($eventName == 'hover') {
  $eventName = 'mouseover';
}

$mainHTML                    = '';
$defaultContainerId          = 'zoom';
$containersData              = [
  'zoom'                   => '',
  '360'                    => '',
  //'video'                => '',
];
$productImagesHTML           = [];
$associatedProductImagesHTML = [];
$hiddenImagesHTML            = [];
$scriptHTML                  = '';

$media_url            = rtrim(Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA), "/");
$media_dir            = rtrim(Mage::getBaseDir(Mage_Core_Model_Store::URL_TYPE_MEDIA), "/");

$cdn_img_options      = [
  "identifier"          => $dhh_sku,
  "add_mod_time"        => true,
  "relative_url"        => true,
  "url_only"            => true,
];

foreach($productImages as &$productImage) {
  
  $productImage['alt'] = $this->htmlEscape($productImage['image-label']);
  $productImage['title'] = $productTitle;
  if($useIndividualTitles) {
    $productImage['title'] = empty($productImage['alt']) ? $productTitle : $productImage['alt'];
  }
  
  // Override the non-watermarked OpenMage image with the watermarked one, if it exists
  if(isset($imageFileOverride[$productImage['image-file']])) {
    $productImage['image-file'] = $imageFileOverride[$productImage['image-file']];
  }
  
  $image_url                  = "{$media_url}/catalog/product{$productImage['image-file']}";
  $image_path                 = "{$media_dir}/catalog/product{$productImage['image-file']}";
  
  $cdn_img_options["fs_path"] = $image_path;
  $cdn_img_options["url"]     = $image_url;
  
  // Try CDN
  $bigImage         = null;
  $thumbImage       = null;
  $mediumImage      = null;
  if(is_file($image_path) === true) {
    
    $extension = strtolower((string) pathinfo($image_path, PATHINFO_EXTENSION));
    
    $cdn_img_options["width"] = 2048;
    $cdn_img_options["height"] = 2048;
    $cdn_img_options["quality"] = 85;
    // @todo $cdn_img_options["2x"] = true;
    $cdn_img_options["fit"] = "scale-up";
    
    // GIFs are very slow in imagekit and lead to timeouts if not made smaller
    if($extension === "gif") {
      $cdn_img_options["width"]   /= 2;
      $cdn_img_options["height"]  /= 2;
      // $cdn_img_options["quality"] = 85;
    }
    
    $bigImage = Mage::helper("deheerhoreca_util/util")->_cdn_img($cdn_img_options);
    
    [$w, $h] = $magicToolboxHelper->magicToolboxGetSizes('selector', $productImage['image-size']);
    $cdn_img_options["width"] = $w;
    $cdn_img_options["height"] = $h;
    $cdn_img_options["quality"] = 75;
    $thumbImage = Mage::helper("deheerhoreca_util/util")->_cdn_img($cdn_img_options);
    
    [$w, $h] = $magicToolboxHelper->magicToolboxGetSizes('thumb', $productImage['image-size']);
    $cdn_img_options["width"] = $w;
    $cdn_img_options["height"] = $h;
    $cdn_img_options["quality"] = 75;
    $mediumImage = Mage::helper("deheerhoreca_util/util")->_cdn_img($cdn_img_options);
  }
  
  // Fallback to resize()
  if($bigImage === null) {
    $bigImage = $imageHelper->init($productModel, 'image', $productImage['image-file'])->__toString();
    if($createSquareImages) {
      $bigImageSize = min($cdn_img_options["width"], max($productImage['image-size'][0], $productImage['image-size'][1]));
      $bigImage = $imageHelper->watermark(null, null)->resize($bigImageSize)->__toString();
    }
  }
  if($thumbImage === null) {
    [$w, $h] = $magicToolboxHelper->magicToolboxGetSizes('selector', $productImage['image-size']);
    $thumbImage = $imageHelper->init($productModel, 'thumbnail', $productImage['image-file'])->resize($w, $h)->__toString();
  }
  if($mediumImage === null) {
    [$w, $h] = $magicToolboxHelper->magicToolboxGetSizes('thumb', $productImage['image-size']);
    $mediumImage = $imageHelper->watermark(null, null)->resize($w, $h)->__toString();
  }
  
  $config     = [
    'id'        => $productId,
    'group'     => 'product-page',
    'img'       => $bigImage,
    'medium'    => $mediumImage,
    'thumb'     => $thumbImage,
    'alt'       => $productImage['alt'],
    'title'     => $productImage['title'],
    "width"     => 60,
    "height"    => 60,
  ];
  // if(_dhh_debug()) {
  //   printr($config);
  // }
  $aHtml = $tool->getSelectorTemplate($config);
  $aHtml = str_replace('<a ', '<a on'.$eventName.'="magicToolboxOnChangeSelector(this);" ', (string) $aHtml);
  if($ignoreMagentoCSSclass) {
    $aHtml = str_replace('<a ', '<a class="'.$ignoreMagentoCSSclass.'" ', $aHtml);
    $aHtml = str_replace('<img ', '<img class="'.$ignoreMagentoCSSclass.'" ', $aHtml);
  }
  $aHtml = str_replace('<a ', '<a data-magic-slide-id="zoom" ', $aHtml);
  
  $productImagesHTML[] = $aHtml.PHP_EOL;
  
  if($productImage['is-base-image']) {
    $containersData['zoom'] = $tool->getMainTemplate(array(
      'id' => $productId,
      'img' => $bigImage,
      'thumb' => $mediumImage,
      'alt' => $productImage['alt'],
      'title' => $productImage['title'],
      'description' => $productDescription,
      'shortDescription' => $productShortDescription,
    ));
  }
}

//NOTE: if base image exluded from gallery
if(empty($containersData['zoom'])) {

    if($productBaseImage) {
        $bigImage = $imageHelper->init($productModel, 'image', $productBaseImage)->__toString();
        $productBaseImageSize = $imageHelper->getOriginalSizeArray();
        $productBaseImageAlt = $productAlt;
        $productBaseImageTitle = $productTitle;
    } else {
        $bigImage = $imageHelper->init($productModel, 'image', $productImages[0]['image-file'])->__toString();
        $productBaseImageSize = $productImages[0]['image-size'];
        $productBaseImageAlt = $productImages[0]['alt'];
        $productBaseImageTitle = $productImages[0]['title'];
        $isBaseImageIncluded = true;
    }

    if($createSquareImages) {
        $bigImageSize = ($productBaseImageSize[0] > $productBaseImageSize[1]) ? $productBaseImageSize[0] : $productBaseImageSize[1];
        $bigImage = $imageHelper->watermark(null, null)->resize($bigImageSize)->__toString();
    }

    [$w, $h] = $magicToolboxHelper->magicToolboxGetSizes('thumb', $productBaseImageSize);
    $mediumImage = $imageHelper->watermark(null, null)->resize($w, $h)->__toString();

    $containersData['zoom'] = $tool->getMainTemplate(array(
        'id' => $productId,
        'img' => $bigImage,
        'thumb' => $mediumImage,
        'alt' => $productBaseImageAlt,
        'title' => $productBaseImageTitle,
        'description' => $productDescription,
        'shortDescription' => $productShortDescription,
    ));
}

//NOTE: product videos
$videoIndex = 1;
//$maxWidth = (int)$tool->params->getValue('thumb-max-width', 'product');
//$maxHeight = (int)$tool->params->getValue('thumb-max-height', 'product');
$sMaxWidth = (int)$tool->params->getValue('selector-max-width', 'product');
$sMaxHeight = (int)$tool->params->getValue('selector-max-height', 'product');
foreach ($productVideos as $videoUrl => $videoData) {
    if($videoData['youtube']) {
        $dataVideoType = 'youtube';
        $containersData['video-'.$videoIndex] = '<iframe src="https://www.youtube.com/embed/'.$videoData['code'].'?enablejsapi=1"';
    } else {
        $dataVideoType = 'vimeo';
        $containersData['video-'.$videoIndex] = '<iframe src="https://player.vimeo.com/video/'.$videoData['code'].'?byline=0&portrait=0"';
    }
    $containersData['video-'.$videoIndex] .=
        //' width="'.$maxWidth.'" height="'.$maxHeight.'"'.
        ' frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen data-video-type="'.$dataVideoType.'"></iframe>';

    $productImagesHTML[] =
        '<a data-magic-slide-id="video-'.$videoIndex.'" data-video-type="'.$dataVideoType.'" class="video-selector" href="#" onclick="return false">'.
        '<img src="'.$videoData['thumb'].'" alt="video"'.($scrollEnabled ? '' : ' style="max-width: '.$sMaxWidth.'px; max-height: '.$sMaxHeight.'px;"').'/>'.
        '</a>'.PHP_EOL;
    $videoIndex++;
}

//NOTE: for cooperative mode with Magic 360
$magic360ClassName = Mage::registry('magic360ClassName');
$magic360Images = $magic360ClassName ? Mage::registry('magic360Images') : [];
$usedMagic360 = false;
if(count($magic360Images)) {
    $magic360Helper = Mage::helper($magic360ClassName.'/settings');
    $magic360Tool = $magic360Helper->loadTool('product');
    if($magic360Tool->params->checkValue('enable-effect', 'Yes')) {
        $magic360ImageHelper = Mage::helper($magic360ClassName.'/image');
        $baseDir = Mage::getBaseDir('media').DS.'magictoolbox'.DS.$magic360ClassName;
        $createSquare360Images = $magic360Tool->params->checkValue('square-images', 'Yes');
        $magic360ImagesData = [];
        $magic360Selector = null;

        foreach($magic360Images as $magic360Image) {

            if(!file_exists($baseDir.$magic360Image['file'])) {
                continue;
            }

            $bigImage = $magic360ImageHelper->init($magic360Image['file'])->__toString();

            //NOTE: for speed up (issue #75916)
            //$magic360Image['size'] = $magic360ImageHelper->getOriginalSizeArray();
            $magic360Image['size'] = getImageSize($baseDir.$magic360Image['file']);

            if($createSquare360Images) {
                $bigImageSize = ($magic360Image['size'][0] > $magic360Image['size'][1]) ? $magic360Image['size'][0] : $magic360Image['size'][1];
                $bigImage = $magic360ImageHelper->setWatermarkFile(null)->resize($bigImageSize)->__toString();
            }

            [$w, $h] = $magic360Helper->magicToolboxGetSizes('thumb', $magic360Image['size']);
            $mediumImage = $magic360ImageHelper->setWatermarkFile(null)->resize($w, $h)->__toString();

            $magic360ImagesData[] = array(
                'img' => $bigImage,
                'medium' => $mediumImage
            );

            if(!$magic360Selector) {
                $magic360Selector = array(
                    'file' => $magic360Image['file'],
                    'size' => $magic360Image['size']
                );
            }
        }

        if(count($magic360ImagesData)) {

            $icon = $magic360Tool->params->getValue('icon');
            if(!empty($icon) && file_exists(BP.DS.$icon)) {
                $magic360Selector = array(
                    'file' => $icon,
                    'size' => getimagesize(BP.DS.$icon)
                );
            }

            $magic360ImageHelper->init($magic360Selector['file'])
                ->setBaseDir(BP)
                ->setWatermarkFile(Mage::getStoreConfig("design/watermark/thumbnail_image"))
                ->setWatermarkImageOpacity(Mage::getStoreConfig("design/watermark/thumbnail_imageOpacity"))
                ->setWatermarkPosition(Mage::getStoreConfig("design/watermark/thumbnail_position"))
                ->setWatermarkSize(Mage::getStoreConfig("design/watermark/thumbnail_size"))
                ->__toString();

            if($createSquare360Images) {
                $bigImageSize = ($magic360Selector['size'][0] > $magic360Selector['size'][1]) ? $magic360Selector['size'][0] : $magic360Selector['size'][1];
                $magic360ImageHelper->setWatermarkFile(null)->resize($bigImageSize)->__toString();
            }

            [$w, $h] = $magicToolboxHelper->magicToolboxGetSizes('selector', $magic360Selector['size']);
            $thumbImage = $magic360ImageHelper->resize($w, $h)->__toString();

            array_unshift(
                $productImagesHTML,
                '<a data-magic-slide-id="360" class="m360-selector '.$ignoreMagentoCSSclass.'" title="360" href="#" onclick="return false;"><img class="'.$ignoreMagentoCSSclass.'" src="'.$thumbImage.'" alt="360"></a>'.PHP_EOL
            );

            $containersData['360'] = $magic360Tool->getMainTemplate($magic360ImagesData, array('id' => 'productMagic360'));
            //$defaultContainerId = '360';
            $usedMagic360 = true;
        }

    }
}

//NOTE: for configurable product
if($productModel->getTypeId() == 'configurable' && $tool->params->checkValue('show-associated-product-images', 'Yes')) {

    $scriptHTML = 'var useAssociatedProductImages = true;';
    $selectorsVisibility = $tool->params->checkValue('load-associated-product-images', 'within a gallery');

    //$associatedProducts = $productModel->loadByAttribute('sku', $productModel->getSku())->getTypeInstance()->getUsedProducts();
    $associatedProducts = $productModel->getTypeInstance(true)->getUsedProducts(null, $productModel);//#67892

    foreach($associatedProducts as $associatedProduct) {

        $associatedProductId = $associatedProduct->getId();

        $associatedProductBaseImage = $associatedProduct->getImage();

        if(!$associatedProductBaseImage || $associatedProductBaseImage == 'no_selection') {
            continue;
        }

        $bigImage = $imageHelper->init($associatedProduct, 'image', $associatedProductBaseImage)->__toString();

        $originalSizeArray = $imageHelper->getOriginalSizeArray();
        if($createSquareImages) {
            $bigImageSize = ($originalSizeArray[0] > $originalSizeArray[1]) ? $originalSizeArray[0] : $originalSizeArray[1];
            $bigImage = $imageHelper->watermark(null, null)->resize($bigImageSize)->__toString();
        }

        [$w, $h] = $magicToolboxHelper->magicToolboxGetSizes('thumb', $originalSizeArray);
        $mediumImage = $imageHelper->watermark(null, null)->resize($w, $h)->__toString();

        [$w, $h] = $magicToolboxHelper->magicToolboxGetSizes('selector', $originalSizeArray);
        $thumbImage = $imageHelper->init($associatedProduct, 'thumbnail', $associatedProductBaseImage)->resize($w, $h)->__toString();

        $imageAlt = $this->htmlEscape($associatedProduct->getImageLabel());
        if($useIndividualTitles) {
            $imageTitle = empty($imageAlt) ? $productTitle : $imageAlt;
        } else {
            $imageTitle = $productTitle;
        }

        $aHtml = $tool->getSelectorTemplate(array(
            'id' => $productId,
            'img' => $bigImage,
            'thumb' => $thumbImage,
            'medium' => $mediumImage,
            'alt' => $imageAlt,
            'title' => $imageTitle,
        ));

        $aHtml = str_replace('<a ', '<a data-magic-slide-id="zoom" data-id="'.$associatedProductId.'" on'.$eventName.'="magicToolboxOnChangeSelectorConfigurable(this);" ', (string) $aHtml).PHP_EOL;
        $aHtml = str_replace('<img ', '<img id="imageConfigurable'.$associatedProductId.'" ', $aHtml);

        if($selectorsVisibility) {
            $aHtml = str_replace('<a ', '<a class="'.$ignoreMagentoCSSclass.'" ', $aHtml);
            if($scrollEnabled) {
                $hiddenImagesHTML[] = $aHtml;
                $associatedProductImagesHTML[] = $aHtml;
            } else {
                $associatedProductImagesHTML[] = $aHtml;
            }
        } else {
            $aHtml = str_replace('<a ', '<a class="hidden-selector '.$ignoreMagentoCSSclass.'" ', $aHtml);
            if($scrollEnabled) {
                $hiddenImagesHTML[] = $aHtml;
            } else {
                $associatedProductImagesHTML[] = $aHtml;
            }
        }
    }
}

//NOTE: get product options data
$productOptions = $productModel->getOptions();
if($productOptions) {
    foreach($productOptions as $productOption) {
        $optionType = $productOption->getType();
        if($optionType == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DROP_DOWN || $optionType == Mage_Catalog_Model_Product_Option::OPTION_TYPE_RADIO) {
            $optionValues = [];
            foreach($productOption->getValues() as $optionValue) {
                $optionValues[$optionValue->getOptionTypeId()] = strtolower(trim($optionValue->getTitle()));
            }
            $scriptHTML .= ' optionLabels[\''.$productOption->getId().'\'] = '.Mage::helper('core')->jsonEncode($optionValues).';'.
                           ' optionTitles[\''.$productOption->getId().'\'] = \''.strtolower(trim($productOption->getTitle())).'\'; ';
        }
    }
}

//NOTE: if only one base image in the gallery
if(count($productImagesHTML) == 1 && $isBaseImageIncluded && (empty($associatedProductImagesHTML) || !$selectorsVisibility)) {
    $productImagesHTML = [];
}

$moreViewsCaption = $this->__('More Views');
//NOTE: if the gallery has no images
if(empty($productImagesHTML) && (empty($associatedProductImagesHTML) || !$selectorsVisibility)) {
    $moreViewsCaption = '';
}

$productImagesHTML = array_merge($productImagesHTML, $associatedProductImagesHTML);

if($usedMagic360) {
    foreach($productImagesHTML as &$productImageHTML) {
        if(preg_match('#(<a\b[^>]*?\bclass=")([^"]*+")#i', $productImageHTML, $matches)) {
            $productImageHTML = str_replace($matches[0], $matches[1].'zoom-with-360 '.$matches[2], $productImageHTML);
        } else {
            $productImageHTML = str_replace('<a ', '<a class="zoom-with-360" ', $productImageHTML);
        }
    }
}

if(!empty($hiddenImagesHTML)) {
    echo '<div style="display: none !important;">'.implode('', $hiddenImagesHTML).'</div>';
}

$thumb_h = 400;
foreach($containersData as $containerId => $containerHTML) {
  $activeClass = $defaultContainerId == $containerId ? ' mt-active' : '';
  $mainHTML .= "<div class=\"magic-slide{$activeClass}\" data-magic-slide=\"{$containerId}\" style=\"height:{$thumb_h}px;line-height:{$thumb_h}px;vertical-align:middle;\">{$containerHTML}</div>".PHP_EOL;
}

$scroll = $magicToolboxHelper->loadScroll();
$magicscrollOptions = '';
if($scrollEnabled && $scroll) {
    $magicscrollOptions = $scroll->params->serialize(false, '', 'product-magicscroll-options');
    $magicscrollOptions .= 'autostart:false;';
}

echo MagicToolboxTemplateHelperClass::render(array(
    'main' => $mainHTML,
    'thumbs' => $productImagesHTML,
    'magicscrollOptions' => $magicscrollOptions,
    'pid' => $productId,
    'moreViewsCaption' => $moreViewsCaption
));

//NOTE: for exluded images
$labeledImageUrls = $mtDataHelper->getUsedLabeledImageUrls($productModel, true);
$scriptHTML .= 'mtLabeledImageUrls = '.Mage::helper('core')->jsonEncode($labeledImageUrls).';';

if($scriptHTML) {
    echo '<script>'.$scriptHTML.'</script>';
}

echo '<img id="image" src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" alt="placeholder" class="invisible">';

//NOTE: small fix for amconf extension
if(preg_match('/amconf\/ajax\/index\//ims', (string) $_SERVER['REQUEST_URI'])) {
    echo '<script>MagicZoom.start();magicToolboxPrepareOptions();</script>';
}
