<?php
/**
 * ||GEISSWEB| Invoice Auto Send
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL:
 * https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @category    Geissweb
 * @package     Geissweb_InvoiceAutoSend
 * @copyright   Copyright (c) 2015-2017 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_InvoiceAutoSend_Block_Adminhtml_System_Info extends Mage_Adminhtml_Block_System_Config_Form_Fieldset
{
    public function render(Varien_Data_Form_Element_Abstract $element)
    {

        $html = '
					<tr>
						<td class="label">Extension Version</td>
						<td class="value">'.Mage::getConfig()->getNode('modules/Geissweb_InvoiceAutoSend')->version.'</td>
						<td></td>
					</tr>
					<tr>
						<td class="label">Links</td>
						<td class="value"><a href="https://www.geissweb.de/docs/doku.php/start" target="_blank">Documentation</a></td>
						<td></td>
					</tr>

		';
        return $html;
    }

}
