<?php
/** @var Mage_Page_Block_Html_Topmenu_Renderer $this */
/** @var Varien_Data_Tree_Node $menuTree */
/** @var string $childrenWrapClass */

// For editing, refresh Blocks Cache (and FPC)

$html = '';

$children = $menuTree->getChildren();
$parentLevel = $menuTree->getLevel();
$childLevel = is_null($parentLevel) ? 0 : $parentLevel + 1;

$counter = 1;
$childrenCount = $children->count();

$parentPositionClass = $menuTree->getPositionClass();
$itemPositionClassPrefix = $parentPositionClass ? $parentPositionClass . '-' : 'nav-';

foreach ($children as $child) {
  $child->setLevel($childLevel);
  $child->setIsFirst($counter == 1);
  $child->setIsLast($counter == $childrenCount);
  $child->setPositionClass($itemPositionClassPrefix . $counter);

  $outermostClassCode = 'level'. $childLevel;
  $_hasChildren = ($child->hasChildren()) ? 'has-children' : '';
  
  $classes = null;
  if($childLevel==1) {
    $classes = "mheadttl ";
  }

  $html .= '<li '. $this->_getRenderedMenuItemAttributes($child) .'>';

  $html .= '<a title="Ga naar '.$this->escapeHtml($this->__($child->getName())).'" href="'. $child->getUrl() .'" class="'.$classes. $outermostClassCode .' '. $_hasChildren .'">';
	
  //if($childLevel == 1) {
	    //$ctis = str_replace('category-node-','',$child->getId());
	    //$categoryxim = Mage::getModel('catalog/category')->load($ctis);
	    //$pctimg = $categoryxim->getCategoryIcon();
      /* DHH */
      //if(strlen($pctimg) > 0) {
	    //  $html .= "<img src='//www.prokoeling.nl/media/catalog/category/".$pctimg."' alt=''>";
      //}
      //$html .= "<span>";
  //}
	
  $html .= $this->escapeHtml($this->__($child->getName()));

	//if ($childLevel == 1) {
	  //$html .=' </span>';
	//}
  $html .='</a>';

  if (!empty($childrenWrapClass)) {
      $html .= '<div class="'. $childrenWrapClass .'">';
  }

  $nextChildLevel = $childLevel + 1;

  if(!empty($_hasChildren)) {
      $html .= '<ul class="level'. $childLevel .'">';
      $html .=     $this->render($child, $childrenWrapClass);
     /*    $html .=     '<li class="level'. $nextChildLevel .' view-all">';
      $html .=         '<a class="level'. $nextChildLevel .'" href="'. $child->getUrl() .'">';
      $html .=             '... '.$this->__('alle categorieën') . ' ' ; //$this->escapeHtml($this->__($child->getName()))
      $html .=         '</a>';
      $html .=     '</li>';*/
      $html .= '</ul>';
  }

  if(!empty($childrenWrapClass)) {
      $html .= '</div>';
  }

  $html .= '</li>';

  $counter++;
}

return $html;
