<?php
/** @var Mage_Page_Block_Html_Topmenu_Renderer $this */
/** @var Varien_Data_Tree_Node $menuTree */
/** @var string $childrenWrapClass */

// After editing, refresh Blocks Cache (and FPC)

$html                     = '';

$children                 = $menuTree->getChildren();
$parentLevel              = $menuTree->getLevel();
$childLevel               = is_null($parentLevel) ? 0 : $parentLevel + 1;

$counter                  = 1;
$topLeveChildrenCount     = (int) $children->count();

$parentPositionClass      = $menuTree->getPositionClass();
$itemPositionClassPrefix  = $parentPositionClass ? $parentPositionClass . '-' : 'nav-';

$base_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);

foreach($children as $child) {
  
  if($childLevel > 2) return;
  
  $child->setLevel($childLevel);
  $child->setIsFirst($counter === 1);
  $child->setIsLast($counter === $topLeveChildrenCount);
  $child->setPositionClass($itemPositionClassPrefix . $counter);
  
  $url = str_replace($base_url, "/", $child->getUrl());

  $outermostClassCode = 'level'. $childLevel;
  $_hasChildren       = $child->hasChildren();
  $has_children_class = ($_hasChildren && $childLevel < 1) ? ' has-children' : '';
  $category_name      = $this->escapeHtml($this->__($child->getName()));
  if(strpos($category_name, "[SKIPMENU]") !== false) {
    continue;
  }
  $category_name      = Mage::helper("deheerhoreca_util/util")->cleanCategoryName($category_name);
  
  if($childLevel < 2) $html .= "<li {$this->_getRenderedMenuItemAttributes($child)}>";
  $html .= "<a title=\"{$category_name}\" href='{$url}' class='{$outermostClassCode}{$has_children_class}'>{$category_name}</a>";

  if($_hasChildren) {
    if($childLevel < 1) $html .= "<ul class='level{$childLevel}'>";
    $html .= $this->render($child, $childrenWrapClass);
    if($childLevel < 1) $html .= "</ul>";
  }

  if($childLevel < 2) $html .= "</li>";
  
  $html .= PHP_EOL;
  $counter++;
}

return $html;
