<?php
/** @var Mage_Page_Block_Html_Topmenu_Renderer $this */
/** @var Varien_Data_Tree_Node $menuTree */
/** @var string $childrenWrapClass */

// For editing, refresh Blocks Cache (and FPC)

$html                     = '';

$children                 = $menuTree->getChildren();
$parentLevel              = $menuTree->getLevel();
$childLevel               = is_null($parentLevel) ? 0 : $parentLevel + 1;

$counter                  = 1;
$topLeveChildrenCount     = $children->count();

$parentPositionClass      = $menuTree->getPositionClass();
$itemPositionClassPrefix  = $parentPositionClass ? $parentPositionClass . '-' : 'nav-';

$base_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);

foreach($children as $child) {
  
  if($childLevel > 2) return;
  
  $child->setLevel($childLevel);
  $child->setIsFirst($counter == 1);
  $child->setIsLast($counter == $topLeveChildrenCount);
  $child->setPositionClass($itemPositionClassPrefix . $counter);
  
  $url = str_replace($base_url, "/", $child->getUrl());

  $outermostClassCode = 'level'. $childLevel;
  $_hasChildren = $child->hasChildren();
  $has_children_class = ($_hasChildren && $childLevel < 1) ? ' has-children' : '';
  $title = $this->escapeHtml($this->__($child->getName()));
  $name  = $this->escapeHtml($this->__($child->getName()));

  if($childLevel < 2) $html .= "<li {$this->_getRenderedMenuItemAttributes($child)}>";
  $html .= "<a title=\"{$title}\" href='{$url}' class='{$outermostClassCode}{$has_children_class}'>{$title}</a>";

  if($_hasChildren) {
    if($childLevel < 1) $html .= "<ul class='level{$childLevel}'>";
    $html .= $this->render($child, $childrenWrapClass);
    if($childLevel < 1) $html .= "</ul>";
  }

  if($childLevel < 2) $html .= "</li>";
  $counter++;
}

return $html;
