<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Model_Observer extends Mage_Checkout_Model_Observer
{
	protected $_debug = false;

	/**
	 * Geissweb_Euvatgrouper_Model_Observer constructor
	 */
    public function __construct() {
        $this->_debug = Mage::helper('euvatgrouper')->isDebugMode();
    }

	/**
	 * Set default billing and shipping addresses on customer login to quote
	 * Validate VAT number on the fly if needed
	 * @param Varien_Event_Observer $observer
	 */
	public function customerLogin(Varien_Event_Observer $observer)
	{
		if($this->_debug) Mage::log("EVENT START customerLogin", null, 'euvatenhanced.log');

		/** @var Mage_Customer_Model_Customer $customer */
		$customer = $observer->getEvent()->getCustomer();
		$billingAddress = $customer->getDefaultBillingAddress();
		$shippingAddress = $customer->getDefaultShippingAddress();

		$quote = Mage::getSingleton('checkout/session')->getQuote();
		$doValidateBilling = false;
		$doValidateShipping = false;
		$billingVatNumber = null;
		$shippingVatNumber = null;

		if($billingAddress instanceof Mage_Customer_Model_Address)
		{
			if($billingAddress->getVatId() != '' && $billingAddress->getVatRequestSuccess() != true
                || (Mage::helper('euvatgrouper')->isValidationOnEachLogin($billingAddress->getVatRequestDate()) && $billingAddress->getVatId() != '') )
            {
            	$doValidateBilling = true;
	            $billingVatNumber = $billingAddress->getVatId();

			} elseif($customer->getTaxvat() != ''
                     && $billingAddress->getVatId() == ''
                     && Mage::helper('euvatgrouper')->isVatNumberContainsCc($customer->getTaxvat())
					 && Mage::helper('euvatgrouper')->isCountryMatch($customer->getTaxvat(), $billingAddress->getCountryId())
			) {
				$doValidateBilling = true;
				$billingVatNumber = $customer->getTaxvat();
			}

			if($this->_debug) Mage::log("customerLogin: doValidateBilling: $doValidateBilling (".$billingVatNumber.")", null, 'euvatenhanced.log');

			if($doValidateBilling) {
				if($this->_debug) Mage::log("customerLogin: quickValidate: ".$billingVatNumber, null, 'euvatenhanced.log');
				$validatedAddress = Mage::helper('euvatgrouper')->quickValidate($billingVatNumber, $billingAddress);
				if(is_object($validatedAddress) && $validatedAddress->getVatRequestSuccess() == true) {
					$billingAddress = $validatedAddress;
					$billingAddress->save();
					if($this->_debug) Mage::log("customerLogin: quote bill address is now: ".var_export($quote->getBillingAddress()->debug(),true), null, 'euvatenhanced.log');
				}
			}
			$quote->setBillingAddress(Mage::getSingleton('sales/quote_address')->importCustomerAddress($billingAddress));
		} else {
			if($this->_debug) Mage::log("customerLogin: billingAddress is not Mage_Customer_Model_Address", null, 'euvatenhanced.log');
		}


		if($shippingAddress instanceof Mage_Customer_Model_Address)
		{
			if($shippingAddress->getVatId() != '' && $shippingAddress->getVatRequestSuccess() != true
                || (Mage::helper('euvatgrouper')->isValidationOnEachLogin($shippingAddress->getVatRequestDate())
                    && $shippingAddress->getVatId() != '')
			) {
	            $doValidateShipping = true;
	            $shippingVatNumber = $shippingAddress->getVatId();

			} elseif($customer->getTaxvat() != ''
                     && $shippingAddress->getVatId() == ''
                     && Mage::helper('euvatgrouper')->isVatNumberContainsCc($customer->getTaxvat())
                     && Mage::helper('euvatgrouper')->isCountryMatch($customer->getTaxvat(), $shippingAddress->getCountryId())
			) {
				$doValidateShipping = true;
				$shippingVatNumber = $customer->getTaxvat();
			}

			if($this->_debug) Mage::log("customerLogin: doValidateShipping: $doValidateShipping (".$shippingVatNumber.")", null, 'euvatenhanced.log');

			if($doValidateShipping) {
				if($this->_debug) Mage::log("customerLogin: quickValidate: ".$shippingVatNumber, null, 'euvatenhanced.log');
				$validatedAddress = Mage::helper('euvatgrouper')->quickValidate($shippingVatNumber, $shippingAddress);
				if(is_object($validatedAddress) && $validatedAddress->getVatRequestSuccess() == true) {
					$shippingAddress = $validatedAddress;
					$shippingAddress->save();
					if($this->_debug) Mage::log("customerLogin: quote ship address is now: ".var_export($quote->getShippingAddress()->debug(),true), null, 'euvatenhanced.log');
				}
			}

			$quote->setShippingAddress(Mage::getSingleton('sales/quote_address')->importCustomerAddress($shippingAddress));
		} else {
			if($this->_debug) Mage::log("customerLogin: shippingAddress is not Mage_Customer_Model_Address", null, 'euvatenhanced.log');
		}

		if($doValidateShipping || $doValidateBilling) {
			$quote->setTotalsCollectedFlag(false)->collectTotals()->save();
		}

		if($this->_debug) Mage::log("EVENT END customerLogin", null, 'euvatenhanced.log');
	}

	/**
	 * sets the customer group
	 * @var Varien_Event_Observer
	 */
	public function customerSaveBefore(Varien_Event_Observer $observer)
	{
		if(Mage::helper('euvatgrouper')->isModuleActive())
		{
			if($this->_debug) Mage::log("EVENT RUNNING: salesConvertQuoteToOrder ----------", null, 'euvatenhanced.log');
			/** @var $customer Mage_Customer_Model_Customer */
			$customer = $observer->getCustomer();
            if($customer->getGroupId() == null && $customer->getEntityId() > 0) {
                $customerExisting = Mage::getSingleton('customer/customer')->load($customer->getEntityId());
                if($this->_debug) Mage::log("Loading existing customer group: ".$customerExisting->getGroupId(), null, 'euvatenhanced.log');
                $customer->setGroupId($customerExisting->getGroupId());
            }
			if($this->_debug) Mage::log("customerSaveBefore Customer Information: ".var_export($customer->debug(),true), null, 'euvatenhanced.log');
			//$taxvatCc = ($customer->getTaxvat() != '') ? strtoupper(substr($customer->getTaxvat(), 0, 2)) : null;
			$billingCc = Mage::helper('euvatgrouper/customer')->getBillingCountry($customer);

			// Just return when admin tries manually to change the customer to another group,
			// group is in excluded list or unable to get customer_cc
			if ( Mage::helper('euvatgrouper')->isAdmin()
				|| in_array($customer->getGroupId(), Mage::helper('euvatgrouper')->getExcludedGroups())
				|| $billingCc == false
				|| $customer->getDisableAutoGroupChange() == 1 ) {
				if($this->_debug) Mage::log("EVENT END: customerSaveBefore (just returned) - ".(string)Mage::helper('euvatgrouper')->isAdmin()."-".in_array($customer->getGroupId(), Mage::helper('euvatgrouper')->getExcludedGroups())."-".$billingCc."-".$customer->getDisableAutoGroupChange()."----", null, 'euvatenhanced.log');
				return;
			}

			try {

                $tempVatValidation = Mage::getSingleton('customer/session')->getData('temp_vat_validation');
                if( Mage::registry('euvat_group_assignment_group') != false )
                {
                    $customer->setGroupId((int)Mage::registry('euvat_group_assignment_group'));
                    Mage::unregister('euvat_group_assignment_group');

                } elseif( (Mage::registry('euvat_checkout_group_id') != false) && (Mage::helper('euvatgrouper')->isSyncCustomerAccountWithOrderGroup()) ) {
                    $group_id = Mage::registry('euvat_checkout_group_id');
                    $customer->setGroupId($group_id);
                    if ($this->_debug) Mage::log("Customer Group Assignment: using checkout group: $group_id ($billingCc)", null, 'euvatenhanced.log');
                    Mage::unregister('euvat_checkout_group_id');

                } elseif( is_object($customer->getDefaultBillingAddress()) ) {
                    $group_id = Mage::helper('euvatgrouper/customer')->getCustomerGroupForAccount($customer->getDefaultBillingAddress()->toArray());
                    if( $this->_debug ) Mage::log("Customer Group Assignment: Using DefaultBillingAddress: $group_id ($billingCc)", null, 'euvatenhanced.log');
                    if( is_int($group_id) )
                        $customer->setGroupId($group_id);

                } elseif(is_object($tempVatValidation)) {
                    $group_id = Mage::helper('euvatgrouper/customer')->getCustomerGroupForAccount($tempVatValidation->toArray());
                    if ($this->_debug) Mage::log("Customer Group Assignment: using tempVatValidation, Group: $group_id ($billingCc)", null, 'euvatenhanced.log');
                    if(is_int($group_id))
                        $customer->setGroupId($group_id);

				} elseif( !Mage::helper('euvatgrouper')->isEuCountry($billingCc) ) {
                    $customer->setGroupId( Mage::helper('euvatgrouper')->getOutsideEuGroupId() );
                    if ($this->_debug) Mage::log("Customer Group Assignment: NON-EU Country: $billingCc", null, 'euvatenhanced.log');
                }

			} catch (Exception $e) {
				Mage::logException($e);
			}

			if($this->_debug) Mage::log("EVENT END: customerSaveBefore ----------", null, 'euvatenhanced.log');
		}
	}

	/**
	 * Add VAT validation details to new customer address
	 * @param Varien_Event_Observer $observer
	 */
	public function customerAddressSaveBefore(Varien_Event_Observer $observer)
	{
		if($this->_debug) Mage::log("EVENT START: customerAddressSaveBefore ------", null, 'euvatenhanced.log');

		try {
			/** @var Mage_Customer_Model_Address $address */
			$address = $observer->getCustomerAddress();
			$tempValidation = Mage::getSingleton('customer/session')->getData('temp_vat_validation');
			if($this->_debug) Mage::log("customerAddressSaveBefore address is:".var_export($address->debug(),true)." and tempValidation is:".var_export($tempValidation,true), null, 'euvatenhanced.log');

			//Update validation data on existing address
			if($tempValidation != null &&
			   Mage::helper('euvatgrouper')->cleanCustomerVatId($tempValidation->getVatId()) == Mage::helper('euvatgrouper')->cleanCustomerVatId($address->getVatId())
			) {
				Mage::helper('euvatgrouper')->setValidationResultOnAddress($tempValidation, $address);
				Mage::getSingleton('customer/session')->unsetData('temp_vat_validation');
			}
			if($address->getEntityId() > 0 && !$address->hasData('vat_request_success')) {
				if($this->_debug) Mage::log("[EUVAT]customerAddressSaveBefore no vat_request_success", null, 'euvatenhanced.log');
				$savedAddress = Mage::getSingleton('customer/address')->load($address->getEntityId());
				if($savedAddress->hasData('vat_request_success')
				   && Mage::helper('euvatgrouper')->cleanCustomerVatId($savedAddress->getVatId()) == Mage::helper('euvatgrouper')->cleanCustomerVatId($address->getVatId())) {
					$address = Mage::helper('euvatgrouper')->setValidationResultOnAddress($savedAddress,$address);
				}
			}

			//Customer group change when default billing address was changed
			if(!$address->getIsCustomerSaveTransaction()
			   && intval($address->getCustomerId()) > 0
			   && !$address->getIsVatValidationTransaction()
			) {
				$customer = Mage::getSingleton('customer/customer')->load($address->getCustomerId());
				if(is_object($customer->getDefaultBillingAddress())
				   && $customer->getDefaultBillingAddress()->getEntityId() == $address->getEntityId()
				) {
					$newGroupId = Mage::helper('euvatgrouper/customer')->getCustomerGroupForAccount($address->toArray(), $address->getCountry());
					if($newGroupId != $customer->getGroupId() && !in_array($customer->getGroupId(), Mage::helper('euvatgrouper')->getExcludedGroups()) && $customer->getDisableAutoGroupChange()==0) {
						if($this->_debug) Mage::log("customerAddressSaveBefore: Group change needed!", null, 'euvatenhanced.log');
						try {
							Mage::register('euvat_group_assignment_group', $newGroupId);
						} catch(Mage_Core_Exception $e) {
							Mage::logException($e);
						}
						$customer->setGroupId($newGroupId)->save();
					}
				}
			}

		} catch(Exception $e) {
			Mage::logException($e);
		}

		if($this->_debug) Mage::log("EVENT END: customerAddressSaveBefore --------", null, 'euvatenhanced.log');
	}

    /**
     * Observer for VAT-field "onchange"
     * Update quote and session data
     * @var Varien_Event_Observer
     */
    public function vatCheckAfter(Varien_Event_Observer $observer)
    {
        if(Mage::helper('euvatgrouper')->isModuleActive())
        {
            try {
                $result = $observer->getEvent()->getResult();
                $addressId = $observer->getEvent()->getAddressId();
                if($this->_debug) Mage::log("EVENT RUNNING: vatCheckAfter (address_id: ".$addressId.")", null, 'euvatenhanced.log');

                // Save validation information to address (from admin or customer account)
                if(is_object($result))
                {
                    //Register the temporary validation object
                    if(is_object(Mage::registry('tempVatValidation')))
                        Mage::unregister('tempVatValidation');

                    Mage::register('tempVatValidation', $result);
                    if($this->_debug) Mage::log("vatCheckAfter Validation result: " . var_export($result, true), null, 'euvatenhanced.log');

                    // Update address data from customer address edit
                    if( !empty($addressId) && $addressId != 'undefined' )
                    {
                        $address = Mage::getModel('customer/address')->load((int)$addressId);
                        if( $address instanceof Mage_Customer_Model_Address ) {
                            if( $this->_debug ) Mage::log("vatCheckAfter saving Validation result on address ID: $addressId", null, 'euvatenhanced.log');
                            $address->setIsVatValidationTransaction(true);
                            $address = Mage::helper('euvatgrouper')->setValidationResultOnAddress($result, $address);
                            $address->save();

                            // Set validation data to session
                            if(!Mage::helper('euvatgrouper')->isAdmin()) {
                                $this->_setVatSessionData($address, $address->getAddressType());
                                Mage::getSingleton('customer/session')->setData('temp_vat_validation', $result);
                            }
                        }

                    } else {
                        // Set validation data to session
                        if(!Mage::helper('euvatgrouper')->isAdmin()) {
                            $this->_setVatSessionData($result, $result->getAddressType());
                            Mage::getSingleton('customer/session')->setData('temp_vat_validation', $result);
                        } else {
                            if( $this->_debug ) Mage::log("vatCheckAfter on ADMIN Validation", null, 'euvatenhanced.log');
                            Mage::getSingleton('adminhtml/session_quote')->setData('temp_vat_validation', $result);
                        }
                    }

                    // Update customer
                    if(Mage::getSingleton('customer/session')->isLoggedIn())
                    {
                        $customer = Mage::getSingleton('customer/session')->getCustomer();
                        if($result->getGroup() != $customer->getGroupId() && !in_array($customer->getGroupId(), Mage::helper('euvatgrouper')->getExcludedGroups()) && $customer->getDisableAutoGroupChange()==0) {
                            if($this->_debug) Mage::log("Customer group change needed", null, 'euvatenhanced.log');
                            $customer->setGroupId($result->getGroup());
                            $customer->save();
                        }
                    }

                    //Send successmail for all not-domestic valid vat validations from customers
                    if(($result->getVatIsValid() == true))
                    {
                        Mage::dispatchEvent('vat_check_success_email', array(
                            'result' => $result
                        ));
                    }
                }
                if($this->_debug) Mage::log("EVENT END: vatCheckAfter -----------------", null, 'euvatenhanced.log');

            } catch (Exception $e) {
                Mage::logException($e);
            }
        }

    }

	/**
	 * Set active validation data to customers quote
	 * @param $address
	 * @param $addressType
	 */
	private function _setVatSessionData($address, $addressType)
	{
		if(Mage::helper('euvatgrouper')->isModuleActive())
		{
			if($this->_debug) Mage::log("Function RUNNING: _setVatSessionData($addressType) -- Address is instanceof ".get_class($address)." | vat_is_valid:".$address->getVatIsValid(), null, 'euvatenhanced.log');
			if(is_object($address))
			{
				try {
					$vatDataUpdate = array(
						'vat_id' 				=> Mage::helper('euvatgrouper')->cleanCustomerVatId($address->getVatId()),
						'vat_is_valid' 			=> (bool)$address->getVatIsValid(),
						'vat_request_success'	=> (bool)$address->getVatRequestSuccess(),
						'vat_trader_name'		=> $address->getVatTraderName(),
						'vat_trader_address'	=> $address->getVatTraderAddress(),
						'vat_trader_company_type'=> $address->getVatTraderCompanyType(),
						'vat_request_id'		=> $address->getVatRequestId(),
						'vat_request_date'		=> $address->getVatRequestDate(),
					);
					if($this->_debug) Mage::log("data is ".var_export($vatDataUpdate,true), null, 'euvatenhanced.log');

					if(Mage::helper('euvatgrouper')->isAdmin()) {
						$quote = Mage::getSingleton('adminhtml/session_quote')->getQuote();
						if($this->_debug) Mage::log("_setVatSessionData($addressType) -- AdminQuote!", null, 'euvatenhanced.log');
					} else {
						/** @var Mage_Sales_Model_Quote $quote */
						$quote = Mage::getSingleton('checkout/session')->getQuote();
					}
					$billAddress = $quote->getBillingAddress();
					$shipAddress = $quote->getShippingAddress();

					if($addressType=='billing') {
						if($this->_debug) Mage::log("setting billing", null, 'euvatenhanced.log');
						$billAddress = Mage::helper('euvatgrouper')->setValidationResultOnAddress(new Varien_Object($vatDataUpdate), $billAddress);
						$quote->setBillingAddress($billAddress);
						if($shipAddress->getSameAsBilling() || $billAddress->getUseForShipping()){
							if($this->_debug) Mage::log("AND setting shipping", null, 'euvatenhanced.log');
							$shipAddress = Mage::helper('euvatgrouper')->setValidationResultOnAddress(new Varien_Object($vatDataUpdate), $shipAddress);
							$quote->setShippingAddress($shipAddress);
						}
					} elseif($addressType=='shipping') {
						if($this->_debug) Mage::log("setting shipping", null, 'euvatenhanced.log');
						$shipAddress = Mage::helper('euvatgrouper')->setValidationResultOnAddress(new Varien_Object($vatDataUpdate), $shipAddress);
						$quote->setShippingAddress($shipAddress);
					}
					$quote->setTotalsCollectedFlag(false)->collectTotals()->save();

				} catch(Exception $e) {
					Mage::logException($e);
				}


			} else {
				if($this->_debug) Mage::log("No address", null, 'euvatenhanced.log');
			}
			if($this->_debug) Mage::log("Function END: _setVatSessionData", null, 'euvatenhanced.log');
		}

	}

	/**
	 * Simulates temporary VAT calculation based on available data
	 * @param Varien_Event_Observer $observer
	 */
	public function salesQuoteAddressCollectTotalsBefore(Varien_Event_Observer $observer)
	{
		$dataHelper = Mage::helper('euvatgrouper');
        if($dataHelper->isModuleActive())
        {
            if($this->_debug) Mage::log("EVENT RUNNING: salesQuoteAddressCollectTotalsBefore", null, 'euvatenhanced.log');
            $address = $observer->getEvent()->getQuoteAddress();

	        //Simulate customer default country until quote is available
	        if($dataHelper->isPlainQuote($address) && Mage::getSingleton('customer/session')->isLoggedIn()) {
                $customer = Mage::getSingleton('customer/session')->getCustomer();
                if($address->getAddressType()=='shipping') {
                    $customerDefault = $customer->getDefaultShippingAddress();
                } else {
                    $customerDefault = $customer->getDefaultBillingAddress();
                }
                if($customerDefault instanceof Mage_Customer_Model_Address) {
                    $address = $dataHelper->setValidationResultOnAddress($customerDefault, $address);
                    $address->setCountryId($customerDefault->getCountry());
                    if($this->_debug) Mage::log("salesQuoteAddressCollectTotalsBefore isPlainQuote!", null, 'euvatenhanced.log');
                }

            //Make sure no VAT validation fragments persist on the quote address if no VAT number is used
            } elseif($address->getVatId()=='') {
                if($this->_debug) Mage::log("Clearing VAT Info from Address!", null, 'euvatenhanced.log');
                $address = $dataHelper->clearVatInfoFromAddress($address);

            //See if we have temporary Ajax Validation data
            } else {
                //Frontend
                $tempValidation = Mage::getSingleton('customer/session')->getData('temp_vat_validation');
                if($tempValidation != false && $tempValidation->getVatId() == $address->getVatId()) {
                    $address = $dataHelper->setValidationResultOnAddress($tempValidation, $address);
                }
                //Admin
                $adminTempValidation = Mage::getSingleton('adminhtml/session_quote')->getData('temp_vat_validation');
                if($adminTempValidation != false && $adminTempValidation->getVatId() == $address->getVatId() ) {
                    if($this->_debug) Mage::log("Setting admin validation data to address.", null, 'euvatenhanced.log');
                    $address = $dataHelper->setValidationResultOnAddress($adminTempValidation, $address);
                }
            }

            $observer->getEvent()->setQuoteAddress($address);
            if($this->_debug) Mage::log("EVENT END: salesQuoteAddressCollectTotalsBefore", null, 'euvatenhanced.log');
        }

	}

	/**
	 * Observer for tax calculation
	 * @var Varien_Event_Observer
	 */
	public function taxRateDataFetch(Varien_Event_Observer $observer)
	{
		if(Mage::helper('euvatgrouper')->isModuleActive()) {
			if($this->_debug) Mage::log("EVENT RUNNING: taxRateDataFetch", null, 'euvatenhanced.log');
			/** @var Varien_Object $request */
			$request = $observer->getEvent()->getRequest();
			if($this->_debug) Mage::log("Request is: ".var_export($request->debug(),true), null, 'euvatenhanced.log');
			/** @var Geissweb_Euvatgrouper_Helper_Data $dataHelper */
			$dataHelper = Mage::helper('euvatgrouper');
			/** @var Mage_Customer_Model_Session $customerSession */
			$customerSession = Mage::getSingleton('customer/session');
			$shopCc = $dataHelper->getShopVatCc();
			$isAdmin = $dataHelper->isAdmin();
			$preCheck = false;

			try {

				// Ensure tax calc based on shipping address
				$vatBasedOn = Mage::getStoreConfig(Mage_Tax_Model_Config::CONFIG_XML_PATH_BASED_ON, Mage::app()->getStore()->getId());
				if($vatBasedOn=='default' || $vatBasedOn=='origin') {
					if($this->_debug) Mage::log("Just returned. Need address based VAT calculation", null, 'euvatenhanced.log');
					return;
				}

				// Admin or Frontend Switch
				if($isAdmin) {
					$adminQuoteId = Mage::getModel('adminhtml/session_quote')->getQuoteId();
					if(!empty($adminQuoteId)) {
						/** @var Mage_Adminhtml_Model_Session_Quote $quote */
						$quote = Mage::getModel('adminhtml/session_quote')->getQuote();
						$customer = Mage::getModel('adminhtml/session_quote')->getCustomer();
						$shippingAddress = $quote->getShippingAddress();
						$billingAddress = $quote->getBillingAddress();
					} else {
						if($this->_debug) Mage::log("No admin Quote found.", null, 'euvatenhanced.log');
						return;
					}
				} else {
					if(!Mage::getSingleton('checkout/session')->hasQuote()) {
						if($this->_debug) Mage::log("No Quote found.", null, 'euvatenhanced.log');
						return;
					}
					/** @var Mage_Sales_Model_Quote $quote */
					$quote = Mage::getSingleton('checkout/session')->getQuote();
					$customer = $customerSession->getCustomer();
					$billingAddress = $quote->getBillingAddress();
					$shippingAddress = $quote->getShippingAddress();
				}

				// Allow regular Magento tax class application for special customer groups
				if($customer->getGroupId() != ''
				   && in_array($customer->getGroupId(), $dataHelper->getRegularTaxCalculationGroups())
				) {
					if($this->_debug) Mage::log("customer group is set for regular Magento tax calculation: ".var_export($customer->getGroupId(),true), null, 'euvatenhanced.log');
					return;
				}

				// Check for shipping to multiple addresses
				if($quote->getIsMultiShipping()) {
					$basedOnAddress = $dataHelper->getCurrentMultiShippingAddress($request, $quote);
					if($basedOnAddress == false) {
						if($this->_debug) Mage::log("Unable to get proper multi shipping quote address.", null, 'euvatenhanced.log');
						return;
					}
				} else {
					$basedOnAddress = $dataHelper->getVatBasedOnAddress($billingAddress, $shippingAddress, $isAdmin);
				}

                // Use existing customer default addresses if quote has currently no address set and customer is logged in
                if($dataHelper->isPlainQuote($basedOnAddress) && $dataHelper->isPlainAddress($basedOnAddress)) {
	                if($this->_debug) Mage::log("Got plain quote and address.", null, 'euvatenhanced.log');
                    if(!$isAdmin && $customerSession->isLoggedIn()) {
                        $billingAddressId = (int)$customerSession->getCustomer()->getDefaultBilling();
                        if(intval($billingAddressId) > 0) {
                            $billingAddress = Mage::getModel('customer/address')->load($billingAddressId);
                        }
                        $shippingAddressId = (int)$customerSession->getCustomer()->getDefaultShipping();
                        if(intval($shippingAddressId) > 0) {
                            $shippingAddress = Mage::getModel('customer/address')->load($shippingAddressId);
                        }
                        $basedOnAddress = $dataHelper->getVatBasedOnAddress($billingAddress, $shippingAddress);
                    }
                }

                /* If the (custom) checkout kills the VAT address fields
                if($basedOnAddress->getData('customer_address_id') > 0 && $basedOnAddress->getVatId()=='') {
                    $savedAddress = Mage::getModel('customer/address')->load($basedOnAddress->getData('customer_address_id'));
                    if($savedAddress->getVatId()!='' && $savedAddress->getVatRequestSuccess() == '1')
                        $basedOnAddress = $dataHelper->setValidationResultOnAddress($savedAddress, $basedOnAddress);
                }*/

				if(!is_null($basedOnAddress->getCountryId())) {
					$basedOnCc = $basedOnAddress->getCountryId();
				} else {
					if($basedOnAddress->getAddressType()=='shipping') {
						$basedOnCc = Mage::helper('euvatgrouper/customer')->getShippingCountry($customer);
					} else {
						$basedOnCc = Mage::helper('euvatgrouper/customer')->getBillingCountry($customer);
					}
				}

				$taxExemptClassId = $dataHelper->getTaxExemptClassId();
				$taxIncludingClassId = $dataHelper->getTaxIncludingClassId();
				$taxIncludingClassIdBusiness = $dataHelper->getTaxIncludingClassIdBusiness();

				$customerVatIdCc = (!is_null($basedOnAddress->getVatId())) ? strtoupper(substr($basedOnAddress->getVatId(), 0, 2)) : $basedOnCc;
				if($this->_debug) Mage::log('taxCalc basedOnCC is: '.$basedOnCc." | customerVatIdCc is: ".$customerVatIdCc." | basedOnAddress is: ".var_export($dataHelper->debugAddress($basedOnAddress->getData()),true), null, 'euvatenhanced.log');

				// Simple global fix for Greece country prefix
				if( $customerVatIdCc == "EL" ) $customerVatIdCc = "GR";

				// We only need to modify the rate request for the "based on" country
				if($request->getCountryId() == $basedOnCc)
				{
                    if($this->_debug) Mage::log("Current customer group: ".$customer->getGroupId(), null, 'euvatenhanced.log');

					// Change calculation country for MOSS
					if($dataHelper->getUseMossBasedOnVatNumber()
					    && $request->getProductClassId() == $dataHelper->getMossProductsClassId()
						&& $basedOnAddress->getVatId() != ''
					    && ($basedOnAddress->getVatIsValid() == true)
						&& !empty($customerVatIdCc)
					) {
						$request->setCountryId($customerVatIdCc);
						$basedOnCc = $customerVatIdCc;
						if($this->_debug) Mage::log("MOSS exception VAT according to VAT number country prefix (basedOnCC=$basedOnCc)", null, 'euvatenhanced.log');
					}

					// Prevent using a VAT-ID not matching the address country
					if(strlen($basedOnCc) >= 2 && $customerVatIdCc != $basedOnCc) {
						$preCheck = true;
					}

					// Apply the matching customer tax class
					if( $basedOnAddress->getVatId() != ''
						&& ($basedOnAddress->getVatIsValid() == true)
						&& ($basedOnCc != '' && $shopCc != $basedOnCc)
						&& $dataHelper->isEuCountry($basedOnCc)
						&& !$dataHelper->isThresholdCountry($basedOnCc)
					) {
						if(!$preCheck) { //Customer has valid VAT-ID and is not domestic
							$request->setCustomerClassId($taxExemptClassId);
							if($this->_debug) Mage::log("Valid VAT exempt - $vatBasedOn country: $basedOnCc - vatIsValid: ".$basedOnAddress->getVatIsValid()." ClassID: $taxExemptClassId", null, 'euvatenhanced.log');
						} else {
							$request->setCustomerClassId($taxIncludingClassIdBusiness);
							if($this->_debug) Mage::log("Prevention ($customerVatIdCc) $vatBasedOn country: $basedOnCc - vatIsValid: ".$basedOnAddress->getVatIsValid()." ClassID: $taxIncludingClassId", null, 'euvatenhanced.log');
						}

                    //Customer has valid VAT-ID and is domestic
					} elseif( $basedOnAddress->getVatId() != ''
						&& ($basedOnAddress->getVatIsValid() == true)
						&& (($basedOnCc != '' && $shopCc == $basedOnCc) || $dataHelper->isThresholdCountry($basedOnCc))
					) {
						$request->setCustomerClassId($taxIncludingClassIdBusiness);
						if($this->_debug) Mage::log("Same $vatBasedOn and shop country - $vatBasedOn country: $basedOnCc - vatIsValid: ".$basedOnAddress->getVatIsValid()." ClassID: $taxIncludingClassId", null, 'euvatenhanced.log');

						//But exception for MOSS, ToDo: Validate correct taxation
						if($dataHelper->getUseMossBasedOnVatNumber()
						   && $request->getProductClassId() == $dataHelper->getMossProductsClassId()
						) {
							$request->setCustomerClassId($taxExemptClassId);
							if($this->_debug) Mage::log("MOSS exception allows domestic billing address", null, 'euvatenhanced.log');
						}

                    //Customer from outside EU
					} elseif ($basedOnCc != '' && !$dataHelper->isEuCountry($basedOnCc)) {
						//Don't need to set because there should be no tax rate for these countries anyway
						//$request->setCustomerClassId($taxExemptClassId);
						if ($this->_debug) Mage::log("Out of EU from $shopCc - $vatBasedOn country: $basedOnCc - vatIsValid: " . $basedOnAddress->getVatIsValid() . " ClassID: $taxExemptClassId", null, 'euvatenhanced.log');

                    //Customer is Enduser
					} else {
						if($this->_debug) Mage::log("Enduser/Default (".$customer->getTaxClassId()."|".$request->getCustomerClassId().") - $vatBasedOn country: $basedOnCc - vatIsValid: ".$basedOnAddress->getVatIsValid()." ClassID: $taxIncludingClassId", null, 'euvatenhanced.log');
						$request->setCustomerClassId($taxIncludingClassId);
					}

                    // Allow tax free groups without VAT validation
                    if( in_array($customer->getGroupId(), $dataHelper->getExcludedTaxGroups()) )
                    {
                        if($this->_debug) Mage::log("Is excluded tax group: ".$customer->getGroupId(), null, 'euvatenhanced.log');
                        $request->setCustomerClassId($taxExemptClassId);
                    }

				} elseif ($request->getCountryId() == $shopCc
				         && $dataHelper->isCbtEnabled()
				         && $dataHelper->getDisableCbtForEuBusiness()
				         && $dataHelper->isThresholdCountry($basedOnCc)
				) {
					if($this->_debug) Mage::log("CBT enabled and threshold country.", null, 'euvatenhanced.log');
					$request->setCountryId($basedOnCc);
				}

				if($this->_debug) {
					Mage::log("CBT enabled: ".$dataHelper->isCbtEnabled(), null, 'euvatenhanced.log');
					Mage::log("DisableCbtForEuBusiness: ".$dataHelper->getDisableCbtForEuBusiness(), null, 'euvatenhanced.log');
					Mage::log("DisableCbtForOutOfEurope: ".$dataHelper->getDisableCbtForOutOfEurope(), null, 'euvatenhanced.log');
					Mage::log("isThresholdCountry: ".$dataHelper->isThresholdCountry($basedOnCc), null, 'euvatenhanced.log');
				}

			} catch(Mage_Core_Model_Store_Exception $e) {
				Mage::logException($e);
			} catch (Exception $e) {
				Mage::logException($e);
			}

			if($this->_debug) Mage::log("EVENT END: taxRateDataFetch", null, 'euvatenhanced.log');
			if($this->_debug) Mage::log("Request after: ".get_class($request)."::".var_export($request->debug(),true), null, 'euvatenhanced.log');

		}

	}

    /**
     * Observer for sending validation email to shop owner
     * @var Varien_Event_Observer
     */
    public function sendSuccessMail(Varien_Event_Observer $observer)
    {
    	$dataHelper = Mage::helper('euvatgrouper');
		if($dataHelper->isModuleActive())
		{
			if($this->_debug) Mage::log("EVENT RUNNING: send_success_mail -- 
			SMTP: ".Mage::getStoreConfigFlag('system/smtp/disable'), null, 'euvatenhanced.log');

			if($dataHelper->doSendValidationMail())
			{
				$customer = Mage::getSingleton('customer/session')->getCustomer();
				$results = $observer->getEvent()->getResult()->getData();
				foreach ($results as $id => $res) {
					$customer->setData("vies_" . $id, $res);
				}

				$sender = array('name' => Mage::getStoreConfig('trans_email/ident_'.$dataHelper->getMailSender().'/name'),
								'email' => Mage::getStoreConfig('trans_email/ident_'.$dataHelper->getMailSender().'/email'));
				$vars = array('customer' => $customer);

				$translate = Mage::getSingleton('core/translate');
				$template = Mage::getModel('core/email_template');
				try {
					$template->sendTransactional(
						$dataHelper->getMailTemplate(),
						$sender,
						$dataHelper->getMailRecipient(),
						null, //Recipient Name
						$vars,
						Mage::app()->getStore()->getId()
					);
				} catch(Exception $e) {
					Mage::logException($e);
				}
				$translate->setTranslateInline(true);
				if($this->_debug) Mage::log("Validation email sent.", null, 'euvatenhanced.log');
			} else {
				if($this->_debug) Mage::log("Disabled sending validation email.", null, 'euvatenhanced.log');
			}

			if($this->_debug) Mage::log("EVENT END: send_success_mail", null, 'euvatenhanced.log');
		}

    }

	/**
     * Sets the customer group on order object (can be different as group on customer account)
     * @var Varien_Event_Observer
     */
    public function salesConvertQuoteToOrder(Varien_Event_Observer $observer)
    {
    	$dataHelper = Mage::helper('euvatgrouper');
		if($dataHelper->isModuleActive() /*&& !$dataHelper->isAdmin()*/)
		{
			if($this->_debug) Mage::log("EVENT RUNNING: salesConvertQuoteToOrder", null, 'euvatenhanced.log');
			//if ($dataHelper->isAdmin() || $observer->getEvent()->getQuote()->getIsSuperMode()) return;

			/** @var Mage_Sales_Model_Quote $quote */
			$quote = $observer->getEvent()->getQuote();
			// Collect validation data
			$billingAddress = $quote->getBillingAddress();
			$shippingAddress = $quote->getShippingAddress();
			//if($this->_debug) Mage::log('salesConvertQuoteToOrder billing:'.var_export($dataHelper->debugAddress($billingAddress->debug()),true), null, 'euvatenhanced.log');
			//if($this->_debug) Mage::log('salesConvertQuoteToOrder shipping:'.var_export($dataHelper->debugAddress($shippingAddress->debug()),true), null, 'euvatenhanced.log');
			$basedOnAddress = $dataHelper->getVatBasedOnAddress($billingAddress, $shippingAddress, $dataHelper->isAdmin());
			if($this->_debug) Mage::log("salesConvertQuoteToOrder Using basedOnAddress: ".var_export($dataHelper->debugAddress($basedOnAddress->debug()),true), null, 'euvatenhanced.log');

			// Set the customer group for the specific order according to VAT status
			$orderGroupId = Mage::helper('euvatgrouper/customer')->getCustomerGroupForOrder($basedOnAddress);
			if(is_int($orderGroupId) && !$quote->getIsMultiShipping()) {
				$groupName = Mage::getModel('customer/group')->load($orderGroupId)->getCustomerGroupCode();
				if($this->_debug) Mage::log("salesConvertQuoteToOrder Setting customer group id on order: ".$orderGroupId." ($groupName)", null, 'euvatenhanced.log');
				$observer->getEvent()->getOrder()->setCustomerGroupId($orderGroupId);
                if(!Mage::registry('euvat_checkout_group_id')) {
	                try {
		                Mage::register('euvat_checkout_group_id', $orderGroupId);
	                } catch(Mage_Core_Exception $e) {
	                	Mage::logException($e);
	                }
                }

			}

			if($this->_debug) Mage::log("EVENT END: salesConvertQuoteToOrder", null, 'euvatenhanced.log');
		}
	}

    /**
     * Checks if valid VAT number is required to checkout
     * @param Varien_Event_Observer $observer
     *
     * @throws Mage_Core_Exception
     */
	public function salesOrderPlaceBefore(Varien_Event_Observer $observer)
	{
		$dataHelper = Mage::helper('euvatgrouper');
        if($dataHelper->isModuleActive() && !$dataHelper->isAdmin())
        {
            if($this->_debug) Mage::log("EVENT RUNNING: sales_order_place_before", null, 'euvatenhanced.log');

            $order = $observer->getEvent()->getOrder();
            $billingAddress = $order->getBillingAddress();
            $shippingAddress = $order->getShippingAddress();
            $basedOnAddress = Mage::helper('euvatgrouper')->getVatBasedOnAddress($billingAddress, $shippingAddress);

            //Check if valid VAT number is required to checkout
            if( ($dataHelper->getIsVatNumberRequired() === 2 || $dataHelper->getIsVatNumberRequired() === 3)
               && $basedOnAddress->getVatIsValid() != true
            ) {
                if($this->_debug) Mage::log("Valid VAT number is required to checkout, but not provided", null, 'euvatenhanced.log');
                Mage::throwException($dataHelper->__('Your VAT Number is invalid. Please provide a valid VAT Number to place your order.'));
            }

            if($this->_debug) Mage::log("EVENT END: sales_order_place_before", null, 'euvatenhanced.log');
        }
	}


	/**
	 * Saves the validation details to the order comments
	 * @param Varien_Event_Observer $observer
	 */
	public function salesOrderPlaceAfter(Varien_Event_Observer $observer)
	{
		if(Mage::helper('euvatgrouper')->isModuleActive())
		{
			if($this->_debug) Mage::log("EVENT RUNNING: sales_order_place_after", null, 'euvatenhanced.log');

			// set order comment
			try {
				/** @var $orderInstance Mage_Sales_Model_Order */
				$orderInstance = $observer->getOrder();
				$dataHelper = Mage::helper('euvatgrouper');
				/** @var $orderAddress Mage_Sales_Model_Order_Address */
				$orderAddress = $dataHelper->getVatBasedOnAddress(
					$orderInstance->getBillingAddress(),
					$orderInstance->getShippingAddress(),
					$dataHelper->isAdmin()
				);

				if(!($orderAddress instanceof Mage_Sales_Model_Order_Address)) {
					return;
				}
				if($this->_debug) Mage::log("Tax address is: ".var_export($orderAddress->debug(),true), null, 'euvatenhanced.log');

				$vatId = Mage::helper('euvatgrouper')->cleanCustomerVatId($orderAddress->getVatId());
				$vatTraderName = $orderAddress->getVatTraderName();
				$vatTraderAddress = $orderAddress->getVatTraderAddress();
				$vatIsValid = $orderAddress->getVatIsValid();
				$vatReqSuccess = $orderAddress->getVatRequestSuccess();
                $vatReqId = $orderAddress->getVatRequestId();
                $vatReqDate = $orderAddress->getVatRequestDate();

				$comment = '';
				if(!empty($vatId))
				{
					$comment .= Mage::helper('euvatgrouper')->__('VAT number').": ".$vatId."<br/>";

					if(!empty($vatTraderName)) {
						$comment .= Mage::helper('euvatgrouper')->__('VAT Trader Name').": ".$vatTraderName."<br/>";
					}
					if(!empty($vatTraderAddress)) {
						$comment .= Mage::helper('euvatgrouper')->__('VAT Trader Address').": ".$vatTraderAddress."<br/>";
					}
					$comment .= Mage::helper('euvatgrouper')->__('VAT Number is valid').": ";
					$comment .= ($vatIsValid) ? Mage::helper('euvatgrouper')->__('Valid') : Mage::helper('euvatgrouper')->__('Invalid');
					$comment .= "<br/>";
					$comment .= Mage::helper('euvatgrouper')->__('VAT Request success').": ";
					$comment .= ($vatReqSuccess) ? Mage::helper('euvatgrouper')->__('Yes') : Mage::helper('euvatgrouper')->__('No');
					$comment .= "<br/>";
                    if(!empty($vatReqId)) {
                        $comment .= Mage::helper('euvatgrouper')->__('VAT Request Identifier').": ";
                        $comment .= $vatReqId;
                        $comment .= "<br/>";
                    }
                    if(!empty($vatReqDate)) {
                        $comment .= Mage::helper('euvatgrouper')->__('VAT Request Date') . ": ";
                        $comment .= $vatReqDate;
                        $comment .= "<br/>";
                    }
				}

				if($comment != '')
					$orderInstance->addStatusHistoryComment($comment, false);

				// Takeover the VAT number of the address to the customers account
				if(!empty($vatId) && Mage::helper('euvatgrouper')->getIsTakeoverVatToAccount()) {
					if($this->_debug) Mage::log("Setting account based VAT field: ".$vatId, null, 'euvatenhanced.log');

					if(intval($orderInstance->getCustomerId()) > 0) {
						if($this->_debug) Mage::log("Saving to customer.", null, 'euvatenhanced.log');
						$customer = Mage::getModel('customer/customer')->load($orderInstance->getCustomerId());
						$customer->setTaxvat($vatId)->save();
					}

					if($this->_debug) Mage::log("Saving to order.", null, 'euvatenhanced.log');
					$orderInstance->setCustomerTaxvat($vatId);
				}

			} catch(Exception $e) {
				if($this->_debug) Mage::log($e->getMessage(), null, 'euvatenhanced.log');
				Mage::logException($e);
			}

			if($this->_debug) Mage::log("EVENT END: sales_order_place_after", null, 'euvatenhanced.log');
		}

	}

	/**
	 * Adds massactions to customer grid
	 *
	 * @param Varien_Event_Observer $observer
	 */
	public function adminhtmlBlockHtmlBefore(Varien_Event_Observer $observer)
	{
        if(Mage::helper('euvatgrouper')->isModuleActive()) {
            $block = $observer->getEvent()->getBlock();
            if ($block instanceof Mage_Adminhtml_Block_Customer_Grid
                || $block instanceof Company_Adminhtml_Block_Customer_Grid
                || $block instanceof Mxperts_NoRegion_Block_Customer_Grid)
            {
                $block->getMassactionBlock()->addItem('validate_accountbased', array(
                    'label' => Mage::helper('euvatgrouper')->__('Migrate account based VAT-ID'),
                    'url' => $block->getUrl('adminhtml/euvat/validateAccount'),
                ));
            }
        }
	}

	/**
	 * FixFunction to avoid doubling the quote totals after
	 * admin assigns a customer to a new group
	 * @var Varien_Event_Observer
	 */
	public function adminhtmlCustomerSaveAfter(Varien_Event_Observer $observer)
	{
		if(Mage::helper('euvatgrouper')->isModuleActive()) {
			$customer = $observer->getEvent()->getCustomer();
			$customer_quote = Mage::getModel('sales/quote')->getCollection()
				->addFieldToFilter('customer_id', array('eq'=>$customer->getId()))
				->addOrder('updated_at', 'desc');
			if($customer_quote->getSize() > 0) {
				foreach($customer_quote as $quote) {
					/** Mage_Sales_Model_Quote $quote */
					$quote->removeAllAddresses()->setTotalsCollectedFlag(false)->collectTotals()->save();
				}
			}
		}
	}

	/**
	 * Observer to check for the latest version of EU VAT Enhanced and support informations
	 * @var Varien_Event_Observer
	 */
	public function geissweb_check_for_updates(Varien_Event_Observer $observer)
	{
		$feed = Mage::getSingleton("euvatgrouper/feed");
		$feed->checkUpdate();
	}

}