<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Model_Observer extends Mage_Checkout_Model_Observer
{
	protected $_debug = false;

	/**
	 * Geissweb_Euvatgrouper_Model_Observer constructor
	 */
    public function __construct() {
        $this->_debug = Mage::helper('euvatgrouper')->isDebugMode();
    }

	/**
	 * Set default billing and shipping addresses on customer login to quote
	 * Validate VAT number on the fly if needed
	 * @param Varien_Event_Observer $observer
	 */
	public function customerLogin(Varien_Event_Observer $observer)
	{
		if($this->_debug) Mage::log("[EUVAT] EVENT START customerLogin", null, 'euvatenhanced.log');

		/** @var Mage_Customer_Model_Customer $customer */
		$customer = $observer->getEvent()->getCustomer();
		$billingAddress = $customer->getDefaultBillingAddress();
		$shippingAddress = $customer->getDefaultShippingAddress();

		$quote = Mage::getSingleton('checkout/session')->getQuote();
		$doValidateBilling = false;
		$doValidateShipping = false;
		$billingVatNumber = null;
		$shippingVatNumber = null;

		if($billingAddress instanceof Mage_Customer_Model_Address)
		{
			if($billingAddress->getVatId() != '' && $billingAddress->getVatRequestSuccess() != true
                || Mage::helper('euvatgrouper')->isValidationOnEachLogin($billingAddress->getVatRequestDate()) )
            {
            	$doValidateBilling = true;
	            $billingVatNumber = $billingAddress->getVatId();

			} elseif($customer->getTaxvat() != ''
                     && $billingAddress->getVatId() == ''
                     && Mage::helper('euvatgrouper')->isVatNumberContainsCc($customer->getTaxvat())
					 && Mage::helper('euvatgrouper')->isCountryMatch($customer->getTaxvat(), $billingAddress->getCountryId())
			) {
				$doValidateBilling = true;
				$billingVatNumber = $customer->getTaxvat();
			}

			if($this->_debug) Mage::log("[EUVAT] customerLogin: doValidateBilling: $doValidateBilling (".$billingVatNumber.")", null, 'euvatenhanced.log');

			if($doValidateBilling) {
				if($this->_debug) Mage::log("[EUVAT] customerLogin: quickValidate: ".$billingVatNumber, null, 'euvatenhanced.log');
				$validatedAddress = Mage::helper('euvatgrouper')->quickValidate($billingVatNumber, $billingAddress);
				if(is_object($validatedAddress) && $validatedAddress->getVatRequestSuccess() == true) {
					$billingAddress = $validatedAddress;
					$billingAddress->save();
					if($this->_debug) Mage::log("[EUVAT] customerLogin: quote bill address is now: ".var_export($quote->getBillingAddress()->debug(),true), null, 'euvatenhanced.log');
				}
			}
			$quote->setBillingAddress(Mage::getSingleton('sales/quote_address')->importCustomerAddress($billingAddress));
		} else {
			if($this->_debug) Mage::log("[EUVAT] customerLogin: billingAddress is not Mage_Customer_Model_Address", null, 'euvatenhanced.log');
		}


		if($shippingAddress instanceof Mage_Customer_Model_Address)
		{
			if(($shippingAddress->getVatId() != '' && $shippingAddress->getVatRequestSuccess() != true
                || Mage::helper('euvatgrouper')->isValidationOnEachLogin($shippingAddress->getVatRequestDate())))
            {
	            $doValidateShipping = true;
	            $shippingVatNumber = $shippingAddress->getVatId();

			} elseif($customer->getTaxvat() != ''
                     && $shippingAddress->getVatId() == ''
                     && Mage::helper('euvatgrouper')->isVatNumberContainsCc($customer->getTaxvat())
                     && Mage::helper('euvatgrouper')->isCountryMatch($customer->getTaxvat(), $shippingAddress->getCountryId())
			) {
				$doValidateShipping = true;
				$shippingVatNumber = $customer->getTaxvat();
			}

			if($this->_debug) Mage::log("[EUVAT] customerLogin: doValidateShipping: $doValidateShipping (".$shippingVatNumber.")", null, 'euvatenhanced.log');

			if($doValidateShipping) {
				if($this->_debug) Mage::log("[EUVAT] customerLogin: quickValidate: ".$shippingVatNumber, null, 'euvatenhanced.log');
				$validatedAddress = Mage::helper('euvatgrouper')->quickValidate($shippingVatNumber, $shippingAddress);
				if(is_object($validatedAddress) && $validatedAddress->getVatRequestSuccess() == true) {
					$shippingAddress = $validatedAddress;
					$shippingAddress->save();
					if($this->_debug) Mage::log("[EUVAT] customerLogin: quote ship address is now: ".var_export($quote->getShippingAddress()->debug(),true), null, 'euvatenhanced.log');
				}
			}

			$quote->setShippingAddress(Mage::getSingleton('sales/quote_address')->importCustomerAddress($shippingAddress));
		} else {
			if($this->_debug) Mage::log("[EUVAT] customerLogin: shippingAddress is not Mage_Customer_Model_Address", null, 'euvatenhanced.log');
		}

		if($doValidateShipping || $doValidateBilling) {
			$quote->setTotalsCollectedFlag(false)->collectTotals()->save();
		}

		if($this->_debug) Mage::log("[EUVAT] EVENT END customerLogin", null, 'euvatenhanced.log');
	}

	/**
	 * sets the customer group
	 * @var Varien_Event_Observer
	 */
	public function customerSaveBefore(Varien_Event_Observer $observer)
	{
		if(Mage::helper('euvatgrouper')->isModuleActive())
		{
			if($this->_debug) Mage::log("[EUVAT] EVENT RUNNING: salesConvertQuoteToOrder ----------", null, 'euvatenhanced.log');
			/** @var $customer Mage_Customer_Model_Customer */
			$customer = $observer->getCustomer();
            if($customer->getGroupId() == null && $customer->getEntityId() > 0) {
                $customerExisting = Mage::getSingleton('customer/customer')->load($customer->getEntityId());
                if($this->_debug) Mage::log("[EUVAT] Loading existing customer group: ".$customerExisting->getGroupId(), null, 'euvatenhanced.log');
                $customer->setGroupId($customerExisting->getGroupId());
            }
			if($this->_debug) Mage::log("[EUVAT] customerSaveBefore Customer Information: ".var_export($customer->debug(),true), null, 'euvatenhanced.log');
			//$taxvatCc = ($customer->getTaxvat() != '') ? strtoupper(substr($customer->getTaxvat(), 0, 2)) : null;
			$billingCc = Mage::helper('euvatgrouper/customer')->getBillingCountry($customer);

			// Just return when admin tries manually to change the customer to another group,
			// group is in excluded list or unable to get customer_cc
			if ( Mage::helper('euvatgrouper')->isAdmin()
				|| in_array($customer->getGroupId(), Mage::helper('euvatgrouper')->getExcludedGroups())
				|| $billingCc == false
				|| $customer->getDisableAutoGroupChange() == 1 ) {
				if($this->_debug) Mage::log("[EUVAT] EVENT END: customerSaveBefore (just returned) - ".(string)Mage::helper('euvatgrouper')->isAdmin()."-".in_array($customer->getGroupId(), Mage::helper('euvatgrouper')->getExcludedGroups())."-".$billingCc."-".$customer->getDisableAutoGroupChange()."----", null, 'euvatenhanced.log');
				return;
			}

			try {

                $tempVatValidation = Mage::getSingleton('customer/session')->getData('temp_vat_validation');

                /**/
                if( Mage::registry('euvat_group_assignment_group') != false )
                {
                    $customer->setGroupId((int)Mage::registry('euvat_group_assignment_group'));
                    Mage::unregister('euvat_group_assignment_group');

                } elseif( (Mage::registry('euvat_checkout_group_id') != false) && (Mage::helper('euvatgrouper')->isSyncCustomerAccountWithOrderGroup()) ) {
                    $group_id = Mage::registry('euvat_checkout_group_id');
                    $customer->setGroupId($group_id);
                    if ($this->_debug) Mage::log("[EUVAT] Customer Group Assignment: using checkout group: $group_id ($billingCc)", null, 'euvatenhanced.log');
                    Mage::unregister('euvat_checkout_group_id');

                } elseif( is_object($customer->getDefaultBillingAddress()) ) {
                    $group_id = Mage::helper('euvatgrouper/customer')->getCustomerGroupForAccount($customer->getDefaultBillingAddress()->toArray());
                    if( $this->_debug ) Mage::log("[EUVAT] Customer Group Assignment: Using DefaultBillingAddress: $group_id ($billingCc)", null, 'euvatenhanced.log');
                    if( is_int($group_id) )
                        $customer->setGroupId($group_id);

                } elseif(is_object($tempVatValidation)) {
                    $group_id = Mage::helper('euvatgrouper/customer')->getCustomerGroupForAccount($tempVatValidation->toArray());
                    if ($this->_debug) Mage::log("[EUVAT] Customer Group Assignment: using tempVatValidation, Group: $group_id ($billingCc)", null, 'euvatenhanced.log');
                    if(is_int($group_id))
                        $customer->setGroupId($group_id);

				} elseif( !Mage::helper('euvatgrouper')->isEuCountry($billingCc) ) {
                    $customer->setGroupId( Mage::helper('euvatgrouper')->getOutsideEuGroupId() );
                    if ($this->_debug) Mage::log("[EUVAT] Customer Group Assignment: NON-EU Country: $billingCc", null, 'euvatenhanced.log');
                }

			} catch (Exception $e) {
				Mage::logException($e);
			}

			if($this->_debug) Mage::log("[EUVAT] EVENT END: customerSaveBefore ----------", null, 'euvatenhanced.log');
		}
	}

	/**
	 * Add VAT validation details to new customer address
	 * @param Varien_Event_Observer $observer
	 */
	public function customerAddressSaveBefore(Varien_Event_Observer $observer)
	{
		if($this->_debug) Mage::log("[EUVAT] EVENT START: customerAddressSaveBefore ------", null, 'euvatenhanced.log');
		/** @var Mage_Customer_Model_Address $address */
		$address = $observer->getCustomerAddress();
		$tempValidation = Mage::getSingleton('customer/session')->getData('temp_vat_validation');
		if($this->_debug) Mage::log("[EUVAT] customerAddressSaveBefore address is:".var_export($address->debug(),true)." and tempValidation is:".var_export($tempValidation,true), null, 'euvatenhanced.log');

        //Update validation data on existing address
		if($tempValidation != null &&
            Mage::helper('euvatgrouper')->cleanCustomerVatId($tempValidation->getVatId()) == Mage::helper('euvatgrouper')->cleanCustomerVatId($address->getVatId()) )
        {
			Mage::helper('euvatgrouper')->setValidationResultOnAddress($tempValidation, $address);
			Mage::getSingleton('customer/session')->unsetData('temp_vat_validation');
		}
        if($address->getEntityId() > 0 && !$address->hasData('vat_request_success'))
        {
            if($this->_debug) Mage::log("[EUVAT]customerAddressSaveBefore no vat_request_success", null, 'euvatenhanced.log');
            $savedAddress = Mage::getSingleton('customer/address')->load($address->getEntityId());
            if($savedAddress->hasData('vat_request_success')
                && Mage::helper('euvatgrouper')->cleanCustomerVatId($savedAddress->getVatId()) == Mage::helper('euvatgrouper')->cleanCustomerVatId($address->getVatId())) {
                $address = Mage::helper('euvatgrouper')->setValidationResultOnAddress($savedAddress,$address);
            }
        }

        //Customer group change when default billing address was changed
        if(!$address->getIsCustomerSaveTransaction()
            && $address->getCustomerId() > 0
            && !$address->getIsVatValidationTransaction())
        {
            $customer = Mage::getSingleton('customer/customer')->load($address->getCustomerId());
            if(is_object($customer->getDefaultBillingAddress())
                && $customer->getDefaultBillingAddress()->getEntityId() == $address->getEntityId())
            {
                $newGroupId = Mage::helper('euvatgrouper/customer')->getCustomerGroupForAccount($address->toArray(), $address->getCountry());
                if($newGroupId != $customer->getGroupId() && !in_array($customer->getGroupId(), Mage::helper('euvatgrouper')->getExcludedGroups()) && $customer->getDisableAutoGroupChange()==0) {
                    if($this->_debug) Mage::log("[EUVAT] customerAddressSaveBefore: Group change needed!", null, 'euvatenhanced.log');
                    Mage::register('euvat_group_assignment_group', $newGroupId);
                    $customer->setGroupId($newGroupId)->save();
                }
            }
        }

		if($this->_debug) Mage::log("[EUVAT] EVENT END: customerAddressSaveBefore --------", null, 'euvatenhanced.log');
	}

    /**
     * Observer for VAT-field "onchange"
     * Update quote and session data
     * @var Varien_Event_Observer
     */
    public function vatCheckAfter(Varien_Event_Observer $observer)
    {
        if(Mage::helper('euvatgrouper')->isModuleActive())
        {
            try {
                $result = $observer->getEvent()->getResult();
                $addressId = $observer->getEvent()->getAddressId();
                if($this->_debug) Mage::log("[EUVAT] EVENT RUNNING: vatCheckAfter (address_id: ".$addressId.")", null, 'euvatenhanced.log');

                // Save validation information to address (from admin or customer account)
                if(is_object($result))
                {
                    //Register the temporary validation object
                    if(is_object(Mage::registry('tempVatValidation')))
                        Mage::unregister('tempVatValidation');

                    Mage::register('tempVatValidation', $result);
                    if($this->_debug) Mage::log("[EUVAT] vatCheckAfter Validation result: " . var_export($result, true), null, 'euvatenhanced.log');

                    // Update address data from customer address edit
                    if( !empty($addressId) && $addressId != 'undefined' )
                    {
                        $address = Mage::getModel('customer/address')->load((int)$addressId);
                        if( $address instanceof Mage_Customer_Model_Address ) {
                            if( $this->_debug ) Mage::log("[EUVAT] vatCheckAfter saving Validation result on address ID: $addressId", null, 'euvatenhanced.log');
                            $address->setIsVatValidationTransaction(true);
                            $address = Mage::helper('euvatgrouper')->setValidationResultOnAddress($result, $address);
                            $address->save();

                            // Set validation data to session
                            if(!Mage::helper('euvatgrouper')->isAdmin()) {
                                $this->_setVatSessionData($address, $address->getAddressType());
                                Mage::getSingleton('customer/session')->setData('temp_vat_validation', $result);
                            }
                        }

                    } else {
                        // Set validation data to session
                        if(!Mage::helper('euvatgrouper')->isAdmin()) {
                            $this->_setVatSessionData($result, $result->getAddressType());
                            Mage::getSingleton('customer/session')->setData('temp_vat_validation', $result);
                        } else {
                            if( $this->_debug ) Mage::log("[EUVAT] vatCheckAfter on ADMIN Validation", null, 'euvatenhanced.log');
                            Mage::getSingleton('adminhtml/session_quote')->setData('temp_vat_validation', $result);
                        }
                    }

                    // Update customer
                    if(Mage::getSingleton('customer/session')->isLoggedIn())
                    {
                        $customer = Mage::getSingleton('customer/session')->getCustomer();
                        if($result->getGroup() != $customer->getGroupId() && !in_array($customer->getGroupId(), Mage::helper('euvatgrouper')->getExcludedGroups()) && $customer->getDisableAutoGroupChange()==0) {
                            if($this->_debug) Mage::log("[EUVAT] Customer group change needed", null, 'euvatenhanced.log');
                            $customer->setGroupId($result->getGroup());
                            $customer->save();
                        }
                    }

                    //Send successmail for all not-domestic valid vat validations from customers
                    if(($result->getVatIsValid() == true))
                    {
                        Mage::dispatchEvent('vat_check_success_email', array(
                            'result' => $result
                        ));
                    }
                }
                if($this->_debug) Mage::log("[EUVAT] EVENT END: vatCheckAfter -----------------", null, 'euvatenhanced.log');

            } catch (Exception $e) {
                Mage::logException($e);
            }
        }

    }

	/**
	 * Set active validation data to customers quote
	 * @param $address
	 * @param $addressType
	 */
	private function _setVatSessionData($address, $addressType)
	{
		if(Mage::helper('euvatgrouper')->isModuleActive())
		{
			if($this->_debug) Mage::log("[EUVAT] Function RUNNING: _setVatSessionData($addressType) -- Address is instanceof ".get_class($address)." | vat_is_valid:".$address->getVatIsValid(), null, 'euvatenhanced.log');
			if(is_object($address))
			{
				$vatDataUpdate = array(
					'vat_id' 				=> Mage::helper('euvatgrouper')->cleanCustomerVatId($address->getVatId()),
					'vat_is_valid' 			=> (bool)$address->getVatIsValid(),
					'vat_request_success'	=> (bool)$address->getVatRequestSuccess(),
					'vat_trader_name'		=> $address->getVatTraderName(),
					'vat_trader_address'	=> $address->getVatTraderAddress(),
					'vat_trader_company_type'=> $address->getVatTraderCompanyType(),
					'vat_request_id'		=> $address->getVatRequestId(),
					'vat_request_date'		=> $address->getVatRequestDate(),
				);
				if($this->_debug) Mage::log("[EUVAT] data is ".var_export($vatDataUpdate,true), null, 'euvatenhanced.log');

                if(Mage::helper('euvatgrouper')->isAdmin()) {
                    $quote = Mage::getSingleton('adminhtml/session_quote')->getQuote();
                    if($this->_debug) Mage::log("[EUVAT] _setVatSessionData($addressType) -- AdminQuote!", null, 'euvatenhanced.log');
                } else {
                    /** @var Mage_Sales_Model_Quote $quote */
                    $quote = Mage::getSingleton('checkout/session')->getQuote();
                }
				$billAddress = $quote->getBillingAddress();
				$shipAddress = $quote->getShippingAddress();

				if($addressType=='billing') {
					if($this->_debug) Mage::log("[EUVAT] setting billing", null, 'euvatenhanced.log');
					$billAddress = Mage::helper('euvatgrouper')->setValidationResultOnAddress(new Varien_Object($vatDataUpdate), $billAddress);
					$quote->setBillingAddress($billAddress);
					if($shipAddress->getSameAsBilling() || $billAddress->getUseForShipping()){
						if($this->_debug) Mage::log("[EUVAT] AND setting shipping", null, 'euvatenhanced.log');
						$shipAddress = Mage::helper('euvatgrouper')->setValidationResultOnAddress(new Varien_Object($vatDataUpdate), $shipAddress);
						$quote->setShippingAddress($shipAddress);
					}
				} elseif($addressType=='shipping') {
					if($this->_debug) Mage::log("[EUVAT] setting shipping", null, 'euvatenhanced.log');
					$shipAddress = Mage::helper('euvatgrouper')->setValidationResultOnAddress(new Varien_Object($vatDataUpdate), $shipAddress);
					$quote->setShippingAddress($shipAddress);
				}
				$quote->setTotalsCollectedFlag(false)->collectTotals()->save();

			} else {
				if($this->_debug) Mage::log("[EUVAT] No address", null, 'euvatenhanced.log');
			}
			if($this->_debug) Mage::log("[EUVAT] Function END: _setVatSessionData", null, 'euvatenhanced.log');
		}

	}

	/**
	 * Make sure no VAT validation fragments persist on the quote address if no VAT number is used
	 * @param Varien_Event_Observer $observer
	 */
	public function salesQuoteAddressCollectTotalsBefore(Varien_Event_Observer $observer)
	{
        if(Mage::helper('euvatgrouper')->isModuleActive())
        {
            if($this->_debug) Mage::log("[EUVAT] EVENT RUNNING: salesQuoteAddressCollectTotalsBefore", null, 'euvatenhanced.log');
            $address = $observer->getEvent()->getQuoteAddress();
            //if($this->_debug) Mage::log("[EUVAT] Class of address is: ".get_class($address), null, 'euvatenhanced.log');
            //$quote = $address->getQuote();
            //if($this->_debug) Mage::log("[EUVAT] salesQuoteAddressCollectTotalsBefore address is: ".var_export($address->debug(),true), null, 'euvatenhanced.log');
            if(Mage::helper('euvatgrouper')->isPlainQuote($address) && Mage::getSingleton('customer/session')->isLoggedIn())
            {
                $customer = Mage::getSingleton('customer/session')->getCustomer();

                if($address->getAddressType()=='shipping') {
                    $customerDefault = $customer->getDefaultShippingAddress();
                } else {
                    $customerDefault = $customer->getDefaultBillingAddress();
                }
                if($customerDefault instanceof Mage_Customer_Model_Address)
                {
                    $address = Mage::helper('euvatgrouper')->setValidationResultOnAddress($customerDefault, $address);
                    $address->setCountryId($customerDefault->getCountry());
                    if($this->_debug) Mage::log("[EUVAT] salesQuoteAddressCollectTotalsBefore isPlainQuote!", null, 'euvatenhanced.log');
                }

            } elseif($address->getVatId()=='') {
                if($this->_debug) Mage::log("[EUVAT] Clearing VAT Info from Address!", null, 'euvatenhanced.log');
                $address = Mage::helper('euvatgrouper')->clearVatInfoFromAddress($address);
            } else {
                //Frontend
                $tempValidation = Mage::getSingleton('customer/session')->getData('temp_vat_validation');
                if($tempValidation != false && $tempValidation->getVatId() == $address->getVatId()) {
                    $address = Mage::helper('euvatgrouper')->setValidationResultOnAddress($tempValidation, $address);
                }
                //Admin
                $adminTempValidation = Mage::getSingleton('adminhtml/session_quote')->getData('temp_vat_validation');
                if($adminTempValidation != false && $adminTempValidation->getVatId() == $address->getVatId()) {
                    if($this->_debug) Mage::log("[EUVAT] Setting admin validation data to address.", null, 'euvatenhanced.log');
                    $address = Mage::helper('euvatgrouper')->setValidationResultOnAddress($adminTempValidation, $address);
                    Mage::getSingleton('adminhtml/session_quote')->unsetData('temp_vat_validation');
                }
            }
            $observer->getEvent()->setQuoteAddress($address);
            if($this->_debug) Mage::log("[EUVAT] EVENT END: salesQuoteAddressCollectTotalsBefore", null, 'euvatenhanced.log');
        }

	}

	/**
	 * Observer for tax calculation
	 * @var Varien_Event_Observer
	 */
	public function taxRateDataFetch(Varien_Event_Observer $observer)
	{
		if(Mage::helper('euvatgrouper')->isModuleActive() && !Mage::helper('euvatgrouper')->isAdmin())
		{
			$vatBasedOn = Mage::getStoreConfig(Mage_Tax_Model_Config::CONFIG_XML_PATH_BASED_ON, Mage::app()->getStore()->getId());
			if($this->_debug) Mage::log("[EUVAT] EVENT RUNNING: taxRateDataFetch -- Tax on: $vatBasedOn ", null, 'euvatenhanced.log');
			if($vatBasedOn=='default' || $vatBasedOn=='origin') {
				if($this->_debug) Mage::log("[EUVAT] Just returned", null, 'euvatenhanced.log');
				return;
			}

			/** @var $request Varien_Object */
			$request = $observer->getEvent()->getRequest();
            if($this->_debug) Mage::log("[EUVAT] Request is: ".get_class($request)."::".var_export($request->debug(),true), null, 'euvatenhanced.log');

            /** @var Geissweb_Euvatgrouper_Helper_Data $dataHelper */
            $dataHelper = Mage::helper('euvatgrouper');
            $customerSession = Mage::getSingleton('customer/session');

			try {
				if(!Mage::getSingleton('checkout/session')->hasQuote()) {
					if($this->_debug) Mage::log("[EUVAT] No Quote found.", null, 'euvatenhanced.log');
					return;
				}
				/** @var Mage_Sales_Model_Quote $quote */
				$quote = Mage::getSingleton('checkout/session')->getQuote();
				//if($this->_debug) Mage::log("[EUVAT] Quote is: ".var_export($quote->debug(),true), null, 'euvatenhanced.log');
                $customer = $customerSession->getCustomer();
				$shopCc = $dataHelper->getShopVatCc();
				$billingAddress = $quote->getBillingAddress();
				$shippingAddress = $quote->getShippingAddress();
				$preCheck = false;

				// Allow regular Magento tax class application for special customer groups
				if(in_array($customer->getGroupId(), $dataHelper->getRegularTaxCalculationGroups())) {
					if($this->_debug) Mage::log("[EUVAT] customer group is set for regular Magento tax calculation: ".$customer->getGroupId(), null, 'euvatenhanced.log');
					return;
				}

				// Check for shipping to multiple addresses
				if($quote->getIsMultiShipping()) {
					$basedOnAddress = $dataHelper->getCurrentMultiShippingAddress($request, $quote);
					if($basedOnAddress == false) {
						if($this->_debug) Mage::log("[EUVAT] Unable to get proper multi shipping quote address.", null, 'euvatenhanced.log');
						return;
					}
				} else {
					$basedOnAddress = $dataHelper->getVatBasedOnAddress($billingAddress, $shippingAddress);
				}

                // Use existing customer default addresses if quote has currently no address set and customer is logged in
                if($dataHelper->isPlainQuote($basedOnAddress)
                   && $dataHelper->isPlainAddress($basedOnAddress)
                ) {
	                if($this->_debug) Mage::log("[EUVAT] Got plain quote and address.", null, 'euvatenhanced.log');
                    if($customerSession->isLoggedIn())
                    {
                        $billingAddressId = (int)$customerSession->getCustomer()->getDefaultBilling();
                        if(intval($billingAddressId) > 0) {
                            $billingAddress = Mage::getModel('customer/address')->load($billingAddressId);
                        }
                        $shippingAddressId = (int)$customerSession->getCustomer()->getDefaultShipping();
                        if(intval($shippingAddressId) > 0) {
                            $shippingAddress = Mage::getModel('customer/address')->load($shippingAddressId);
                        }
                        $basedOnAddress = $dataHelper->getVatBasedOnAddress($billingAddress, $shippingAddress);
                    }
                }

                /* If the (custom) checkout kills the VAT address fields
                if($basedOnAddress->getData('customer_address_id') > 0 && $basedOnAddress->getVatId()=='') {
                    $savedAddress = Mage::getModel('customer/address')->load($basedOnAddress->getData('customer_address_id'));
                    if($savedAddress->getVatId()!='' && $savedAddress->getVatRequestSuccess() == '1')
                        $basedOnAddress = $dataHelper->setValidationResultOnAddress($savedAddress, $basedOnAddress);
                }*/
				//if($this->_debug) Mage::log("[EUVAT] basedOn address: ".var_export($basedOnAddress->debug(),true), null, 'euvatenhanced.log');

				if(!is_null($basedOnAddress->getCountryId())) {
					$basedOnCc = $basedOnAddress->getCountryId();
				} else {
					if($basedOnAddress->getAddressType()=='shipping') {
						$basedOnCc = Mage::helper('euvatgrouper/customer')->getShippingCountry($customer);
					} else {
						$basedOnCc = Mage::helper('euvatgrouper/customer')->getBillingCountry($customer);
					}
				}
				$customerVatIdCc = (!is_null($basedOnAddress->getVatId())) ? strtoupper(substr($basedOnAddress->getVatId(), 0, 2)) : $basedOnCc;
				if($this->_debug) Mage::log('[EUVAT] taxCalc basedOnCC is: '.$basedOnCc." | customerVatIdCc is: ".$customerVatIdCc, null, 'euvatenhanced.log');

				// Simple global fix for Greece country prefix
				if( $customerVatIdCc == "EL" ) $customerVatIdCc = "GR";

				// We only need to modify the rate request for the "based on" country
				if($request->getCountryId() == $basedOnCc)
				{
					$taxExemptClassId = $dataHelper->getTaxExemptClassId();
					$taxIncludingClassId = $dataHelper->getTaxIncludingClassId();
                    $taxIncludingClassIdBusiness = $dataHelper->getTaxIncludingClassIdBusiness();
                    if($this->_debug) Mage::log("[EUVAT] Current customer group: ".$customer->getGroupId(), null, 'euvatenhanced.log');

					// Change calculation country for MOSS
					if($dataHelper->getUseMossBasedOnVatNumber()
					    && $request->getProductClassId() == $dataHelper->getMossProductsClassId()
						&& $basedOnAddress->getVatId() != ''
					    && ($basedOnAddress->getVatIsValid() == true)
						&& !empty($customerVatIdCc)
					) {
						$request->setCountryId($customerVatIdCc);
						$basedOnCc = $customerVatIdCc;
						if($this->_debug) Mage::log("[EUVAT] MOSS exception VAT according to VAT number country prefix (basedOnCC=$basedOnCc)", null, 'euvatenhanced.log');
					}

					// Prevent using a VAT-ID not matching the address country
					if(strlen($basedOnCc) >= 2 && $customerVatIdCc != $basedOnCc) {
						$preCheck = true;
					}

					// Apply the matching customer tax class
					if( $basedOnAddress->getVatId() != ''
						&& ($basedOnAddress->getVatIsValid() == true)
						&& ($basedOnCc != '' && $shopCc != $basedOnCc)
						&& $dataHelper->isEuCountry($basedOnCc)
					) {
						if(!$preCheck) { //Customer has valid VAT-ID and is not domestic
							$request->setCustomerClassId($taxExemptClassId);
							if($this->_debug) Mage::log("[EUVAT] Valid VAT exempt - $vatBasedOn country: $basedOnCc - vatIsValid: ".$basedOnAddress->getVatIsValid()." ClassID: $taxExemptClassId", null, 'euvatenhanced.log');
						} else {
							$request->setCustomerClassId($taxIncludingClassIdBusiness);
							if($this->_debug) Mage::log("[EUVAT] Prevention ($customerVatIdCc) $vatBasedOn country: $basedOnCc - vatIsValid: ".$basedOnAddress->getVatIsValid()." ClassID: $taxIncludingClassId", null, 'euvatenhanced.log');
						}

                    //Customer has valid VAT-ID and is domestic
					} elseif( $basedOnAddress->getVatId() != ''
						&& ($basedOnAddress->getVatIsValid() == true)
						&& ($basedOnCc != '' && $shopCc == $basedOnCc) )
					{
						$request->setCustomerClassId($taxIncludingClassIdBusiness);
						if($this->_debug) Mage::log("[EUVAT] Same $vatBasedOn and shop country - $vatBasedOn country: $basedOnCc - vatIsValid: ".$basedOnAddress->getVatIsValid()." ClassID: $taxIncludingClassId", null, 'euvatenhanced.log');

						/*
						//But exception for MOSS
						if($dataHelper->getUseMossBasedOnVatNumber()
						   && $request->getProductClassId() == $dataHelper->getMossProductsClassId()
						) {
							$request->setCustomerClassId($taxExemptClassId);
							if($this->_debug) Mage::log("[EUVAT] MOSS exception allows domestic billing address", null, 'euvatenhanced.log');
						}
						*/

                    //Customer from outside EU
					} elseif ($basedOnCc != '' && !$dataHelper->isEuCountry($basedOnCc)) {
						//$request->setCustomerClassId($taxExemptClassId);
						if($this->_debug) Mage::log("[EUVAT] Out of EU from $shopCc - $vatBasedOn country: $basedOnCc - vatIsValid: ".$basedOnAddress->getVatIsValid()." ClassID: $taxExemptClassId", null, 'euvatenhanced.log');

                    //Customer is Enduser
					} else {
						if($this->_debug) Mage::log("[EUVAT] Enduser/Default (".$customer->getTaxClassId()."|".$request->getCustomerClassId().") - $vatBasedOn country: $basedOnCc - vatIsValid: ".$basedOnAddress->getVatIsValid()." ClassID: $taxIncludingClassId", null, 'euvatenhanced.log');
						$request->setCustomerClassId($taxIncludingClassId);
					}

                    // Allow tax free groups without VAT validation
                    if( in_array($customer->getGroupId(), $dataHelper->getExcludedTaxGroups()) )
                    {
                        if($this->_debug) Mage::log("[EUVAT] Is excluded tax group: ".$customer->getGroupId(), null, 'euvatenhanced.log');
                        $request->setCustomerClassId($taxExemptClassId);
                    }

				} elseif ($request->getCountryId() == $shopCc
				         && $dataHelper->isCbtEnabled()
				         && $dataHelper->getDisableCbtForEuBusiness()
				         && $dataHelper->isThresholdCountry($basedOnCc)
				) {
					if($this->_debug) Mage::log("[EUVAT] CBT enabled and threshold country.", null, 'euvatenhanced.log');
					$request->setCountryId($basedOnCc);
				}

				if($this->_debug) {
					Mage::log("[EUVAT] CBT enabled: ".$dataHelper->isCbtEnabled(), null, 'euvatenhanced.log');
					Mage::log("[EUVAT] DisableCbtForEuBusiness: ".$dataHelper->getDisableCbtForEuBusiness(), null, 'euvatenhanced.log');
					Mage::log("[EUVAT] isThresholdCountry: ".$dataHelper->isThresholdCountry($basedOnCc), null, 'euvatenhanced.log');
				}


			} catch (Exception $e) {
				Mage::logException($e);
			}

			if($this->_debug) Mage::log("[EUVAT] EVENT END: taxRateDataFetch", null, 'euvatenhanced.log');
			if($this->_debug) Mage::log("[EUVAT] Request after: ".get_class($request)."::".var_export($request->debug(),true), null, 'euvatenhanced.log');
		}

	}


    /**
     * Observer for sending validation email to shop owner
     * @var Varien_Event_Observer
     */
    public function sendSuccessMail(Varien_Event_Observer $observer)
    {
		if(Mage::helper('euvatgrouper')->isModuleActive() && !Mage::helper('euvatgrouper')->isAdmin())
		{
			if($this->_debug) Mage::log("[EUVAT] EVENT RUNNING: send_success_mail -- SMTP: ".Mage::getStoreConfigFlag('system/smtp/disable'), null, 'euvatenhanced.log');

			if(Mage::helper('euvatgrouper')->doSendValidationMail())
			{
				$customer = Mage::getSingleton('customer/session')->getCustomer();
				$results = $observer->getEvent()->getResult()->getData();
				foreach ($results as $id => $res) {
					$customer->setData("vies_" . $id, $res);
				}

				$sender = array('name' => Mage::getStoreConfig('trans_email/ident_' . Mage::helper('euvatgrouper')->getMailSender() . '/name'),
								'email' => Mage::getStoreConfig('trans_email/ident_' . Mage::helper('euvatgrouper')->getMailSender() . '/email'));
				$vars = array('customer' => $customer);

				$translate = Mage::getSingleton('core/translate');
				$template = Mage::getModel('core/email_template');
				$template->sendTransactional(
					Mage::helper('euvatgrouper')->getMailTemplate(),
					$sender,
					Mage::helper('euvatgrouper')->getMailRecipient(),
					null, //Recipient Name
					$vars,
					Mage::app()->getStore()->getId()
				);
				$translate->setTranslateInline(true);
				if($this->_debug) Mage::log("[EUVAT] Validation email sent.", null, 'euvatenhanced.log');
			} else {
				if($this->_debug) Mage::log("[EUVAT] Disabled sending validation email.", null, 'euvatenhanced.log');
			}

			if($this->_debug) Mage::log("[EUVAT] EVENT END: send_success_mail -----", null, 'euvatenhanced.log');
		}

    }

	/**
     * Sets the customer group on order object (can be different as group on customer account)
     * @var Varien_Event_Observer
     */
    public function salesConvertQuoteToOrder(Varien_Event_Observer $observer)
    {
		if(Mage::helper('euvatgrouper')->isModuleActive() && !Mage::helper('euvatgrouper')->isAdmin())
		{
			if($this->_debug) Mage::log("[EUVAT] EVENT RUNNING: salesConvertQuoteToOrder--------------------", null, 'euvatenhanced.log');
			if (Mage::helper('euvatgrouper')->isAdmin() || $observer->getEvent()->getQuote()->getIsSuperMode()) return;

			/** @var Mage_Sales_Model_Quote $quote */
			$quote = $observer->getEvent()->getQuote();
			// Collect validation data
			$billingAddress = $quote->getBillingAddress();
			$shippingAddress = $quote->getShippingAddress();
			$basedOnAddress = Mage::helper('euvatgrouper')->getVatBasedOnAddress($billingAddress, $shippingAddress);
			if($this->_debug) Mage::log("[EUVAT] Using basedOnAddress: ".var_export($basedOnAddress->debug(),true), null, 'euvatenhanced.log');

			// Set the customer group for the specific order according to VAT status
			$orderGroupId = Mage::helper('euvatgrouper/customer')->getCustomerGroupForOrder($basedOnAddress);
			if(is_int($orderGroupId) && !$quote->getIsMultiShipping()) {
				$groupName = Mage::getModel('customer/group')->load($orderGroupId)->getCustomerGroupCode();
				if($this->_debug) Mage::log("[EUVAT] Setting customer group id on order: ".$orderGroupId." ($groupName)", null, 'euvatenhanced.log');
				$observer->getEvent()->getOrder()->setCustomerGroupId($orderGroupId);
                if(!Mage::registry('euvat_checkout_group_id'))
				    Mage::register('euvat_checkout_group_id', $orderGroupId);
			}

			if($this->_debug) Mage::log("[EUVAT] EVENT END: salesConvertQuoteToOrder--------------------", null, 'euvatenhanced.log');
		}
	}

    /**
     * Checks if valid VAT number is required to checkout
     * @param Varien_Event_Observer $observer
     *
     * @throws Mage_Core_Exception
     */
	public function salesOrderPlaceBefore(Varien_Event_Observer $observer)
	{
        if(Mage::helper('euvatgrouper')->isModuleActive() && !Mage::helper('euvatgrouper')->isAdmin())
        {
            if($this->_debug) Mage::log("[EUVAT] EVENT RUNNING: sales_order_place_before -------------------", null, 'euvatenhanced.log');

            $order = $observer->getEvent()->getOrder();
            $billingAddress = $order->getBillingAddress();
            $shippingAddress = $order->getShippingAddress();
            $basedOnAddress = Mage::helper('euvatgrouper')->getVatBasedOnAddress($billingAddress, $shippingAddress);

            //Check if valid VAT number is required to checkout
            if( (Mage::helper('euvatgrouper')->getIsVatNumberRequired() == 2 || Mage::helper('euvatgrouper')->getIsVatNumberRequired() == 3)
               && $basedOnAddress->getVatIsValid() != true
            ) {
                if($this->_debug) Mage::log("[EUVAT] Valid VAT number is required to checkout, but not provided", null, 'euvatenhanced.log');
                Mage::throwException(Mage::helper('euvatgrouper')->__('Your VAT Number is invalid. Please provide a valid VAT Number to place your order.'));
            }

            if($this->_debug) Mage::log("[EUVAT] EVENT END: sales_order_place_before -------------------", null, 'euvatenhanced.log');
        }
	}


	/**
	 * Saves the validation details to the order comments
	 * @param Varien_Event_Observer $observer
	 */
	public function salesOrderPlaceAfter(Varien_Event_Observer $observer)
	{
		if(Mage::helper('euvatgrouper')->isModuleActive())
		{
			if($this->_debug) Mage::log("[EUVAT] EVENT RUNNING: sales_order_place_after--------------------", null, 'euvatenhanced.log');

			// set order comment
			try {
				/** @var $orderInstance Mage_Sales_Model_Order */
				$orderInstance = $observer->getOrder();
				/** @var $orderAddress Mage_Sales_Model_Order_Address */
				$VatBasedOn = Mage::getStoreConfig(Mage_Tax_Model_Config::CONFIG_XML_PATH_BASED_ON, Mage::app()->getStore()->getId());
				$orderAddress = null;
				switch ($VatBasedOn)
				{
					case 'shipping':
						$orderAddress = $orderInstance->getShippingAddress();
						break;
					default:
						$orderAddress = $orderInstance->getBillingAddress();
				}
				if(!($orderAddress instanceof Mage_Sales_Model_Order_Address)) {
					return;
				}
				if($this->_debug) Mage::log("[EUVAT] Tax address is: ".var_export($orderAddress->debug(),true), null, 'euvatenhanced.log');

				$vatId = Mage::helper('euvatgrouper')->cleanCustomerVatId($orderAddress->getVatId());
				$vatTraderName = $orderAddress->getVatTraderName();
				$vatTraderAddress = $orderAddress->getVatTraderAddress();
				$vatIsValid = $orderAddress->getVatIsValid();
				$vatReqSuccess = $orderAddress->getVatRequestSuccess();
                $vatReqId = $orderAddress->getVatRequestId();
                $vatReqDate = $orderAddress->getVatRequestDate();

				$comment = '';
				if(!empty($vatId))
				{
					$comment .= Mage::helper('euvatgrouper')->__('VAT number').": ".$vatId."<br/>";

					if(!empty($vatTraderName)) {
						$comment .= Mage::helper('euvatgrouper')->__('VAT Trader Name').": ".$vatTraderName."<br/>";
					}
					if(!empty($vatTraderAddress)) {
						$comment .= Mage::helper('euvatgrouper')->__('VAT Trader Address').": ".$vatTraderAddress."<br/>";
					}
					$comment .= Mage::helper('euvatgrouper')->__('VAT Number is valid').": ";
					$comment .= ($vatIsValid) ? Mage::helper('euvatgrouper')->__('Valid') : Mage::helper('euvatgrouper')->__('Invalid');
					$comment .= "<br/>";
					$comment .= Mage::helper('euvatgrouper')->__('VAT Request success').": ";
					$comment .= ($vatReqSuccess) ? Mage::helper('euvatgrouper')->__('Yes') : Mage::helper('euvatgrouper')->__('No');
					$comment .= "<br/>";
                    if(!empty($vatReqId)) {
                        $comment .= Mage::helper('euvatgrouper')->__('VAT Request Identifier').": ";
                        $comment .= $vatReqId;
                        $comment .= "<br/>";
                    }
                    if(!empty($vatReqDate)) {
                        $comment .= Mage::helper('euvatgrouper')->__('VAT Request Date') . ": ";
                        $comment .= $vatReqDate;
                        $comment .= "<br/>";
                    }
				}

				if($comment != '')
					$orderInstance->addStatusHistoryComment($comment, false);

				// Takeover the VAT number of the address to the customers account
				if(!empty($vatId) && Mage::helper('euvatgrouper')->getIsTakeoverVatToAccount())
				{
					if($this->_debug) Mage::log("[EUVAT] Setting account based VAT field: ".$vatId, null, 'euvatenhanced.log');
					$customer = Mage::getModel('customer/customer')->load($orderInstance->getCustomerId());
					$customer->setTaxvat($vatId)->save();
				}

			} catch(Exception $e) {
				Mage::logException($e);
			}

			if($this->_debug) Mage::log("[EUVAT] EVENT END: sales_order_place_after--------------------", null, 'euvatenhanced.log');
		}

	}

	/**
	 * Adds massactions to customer grid
	 *
	 * @param Varien_Event_Observer $observer
	 */
	public function adminhtmlBlockHtmlBefore(Varien_Event_Observer $observer)
	{
        if(Mage::helper('euvatgrouper')->isModuleActive()) {
            $block = $observer->getEvent()->getBlock();
            if ($block instanceof Mage_Adminhtml_Block_Customer_Grid
                || $block instanceof Company_Adminhtml_Block_Customer_Grid
                || $block instanceof Mxperts_NoRegion_Block_Customer_Grid)
            {
                $block->getMassactionBlock()->addItem('validate_accountbased', array(
                    'label' => Mage::helper('euvatgrouper')->__('Migrate account based VAT-ID'),
                    'url' => $block->getUrl('adminhtml/euvat/validateAccount'),
                ));
            }
        }
	}

	/**
	 * FixFunction to avoid doubling the quote totals after
	 * admin assigns a customer to a new group
	 * @var Varien_Event_Observer
	 */
	public function adminhtmlCustomerSaveAfter(Varien_Event_Observer $observer)
	{
		if(Mage::helper('euvatgrouper')->isModuleActive()) {
			$customer = $observer->getEvent()->getCustomer();
			$customer_quote = Mage::getModel('sales/quote')->getCollection()
				->addFieldToFilter('customer_id', array('eq'=>$customer->getId()))
				->addOrder('updated_at', 'desc');
			if($customer_quote->getSize() > 0) {
				foreach($customer_quote as $quote) {
					$quote->removeAllAddresses()->setTotalsCollectedFlag(false)->collectTotals()->save();
				}
			}
		}
	}

	/**
	 * Observer to check for the latest version of EU VAT Enhanced and support informations
	 * @var Varien_Event_Observer
	 */
	public function geissweb_check_for_updates(Varien_Event_Observer $observer)
	{
		$feed = Mage::getSingleton("euvatgrouper/feed");
		$feed->checkUpdate();
	}

}