<?php
$collection   = $this->getItems();
$_columnCount = 5;
$i            = 0;
$max_items    = $_columnCount;

if($collection->count()) {
  $options = [
    "image_size"              => 125,
    "_blank"                  => false,
    "use_short_product_names" => true,
    "display"                 => "mini",
    "skip_actions"            => true,
    "fast_stock"              => true,
  ];
  
  if(!isset($options["fast_stock"]) || $options["fast_stock"] === false) {
    Mage::getModel('cataloginventory/stock')->addItemsToProducts($collection);
  }
  // @todo ???
  Mage::getModel('cataloginventory/stock')->addItemsToProducts($collection); ?>
  <div id="related-products" class="product-collateral category-products">
    <h2 class='tableftheader'>Gerelateerde Producten</h2>
    <ul class='products-grid products-grid-mini'><?php
      foreach($collection as $_product) {
        if($i === $max_items) break;
        $i++; ?>
        <li class="item<?php if(($i-1) % $_columnCount == 0): ?> first<?php elseif($i % $_columnCount == 0): ?> last<?php endif; ?>">
          <?=getOmDhhUtilHelper()->getProductGridHtml($_product, $this, $options)?>
        </li><?php
      } ?>
    </ul>
  </div><?php
}
