<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */

$limits = $this->getAvailableLimit();

if($this->getCollection()->getSize()) {
  echo "<div class='toolbar'>";
  if($this->isExpanded() && defined("DHH_SORTING_BLOCK_PRINTED") === false) { ?>
    <div class="sorter">
      <div class="sort-by">
        <label for="select_sort"><?php echo $this->__("Sort By") ?></label>
        <div class="selwrapper">
        <select id="select_sort" onchange="setLocation(this.value)" title="<?=Mage::helper("core")->quoteEscape($this->__("Sort By"))?>">
          <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
            <option value="<?php echo $this->getOrderUrl($_key, "asc") ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
              <?php echo $this->__($_order) ?>
            </option>
          <?php endforeach; ?>
        </select>
        </div>
        <?php if($this->getCurrentDirection() == "desc"): ?>
          <a href="<?php echo $this->getOrderUrl(null, "asc") ?>" class="no-transition sort-by-switcher sort-by-switcher--desc" title="<?php echo Mage::helper("core")->quoteEscape($this->__("Set Ascending Direction")) ?>"><?php echo $this->__("Set Ascending Direction") ?></a>
        <?php else: ?>
          <a href="<?php echo $this->getOrderUrl(null, "desc") ?>" class="no-transition sort-by-switcher sort-by-switcher--asc" title="<?php echo Mage::helper("core")->quoteEscape($this->__("Set Descending Direction")) ?>"><?php echo $this->__("Set Descending Direction") ?></a>
        <?php endif; ?>
      </div>
    </div>
    <?php
  }
  
  if(defined("DHH_SORTING_BLOCK_PRINTED") === false) {
    $size_human = $this->getCollection()->getSize();
    $size_postfix = "";
    if($size_human > 100) {
      $size_human = "Meer dan 100";
      $size_postfix = ". Gebruik meer filters om gemakkelijk je ideale keuze te maken";
    }
    echo "<div class='sorter'><p><strong>{$size_human}</strong> producten{$size_postfix}</p></div>";
  }
  ?>
  <div class="pager">  
    <div class="count-container">
      <?php if(sizeof($limits) > 1) { ?>
        <div class="limiter">
          <label><?php echo $this->__("Toon") ?></label>
          <select onchange="setLocation(this.value)" title="<?php echo Mage::helper("core")->quoteEscape($this->__("Results per page")); ?>">
          <?php foreach ($limits as $_key => $_limit): ?>
            <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
              <?php echo $_limit ?>
            </option>
          <?php endforeach; ?>
          </select>
        </div>
      <?php } ?>
    </div>
    <?php
    // @todo fix upstream
    $pager_html = $this->getPagerHtml();
    // $pager_html = str_replace("?p=1&", "?", $pager_html); // Remove ?p=1 for FPC
    $pager_html = str_replace("?p=1\"", "\"", (string) $pager_html); // Remove ?p=1 for FPC
    // $pager_html = str_replace("&p=1", "", $pager_html); // Remove &p=1 for FPC
    echo $pager_html;
    ?>
  </div>
</div>
<?php
}
