<?php

$collection   = $this->getItemCollection();
$_columnCount = 4;
$i            = 0;
$max_items    = $_columnCount;

if($collection->count()) {
  $options = [
    "image_size"              => 125,
    "_blank"                  => false,
    "use_short_product_names" => true,
    "display"                 => "mini",
    "fast_stock"              => true,
  ];
  if(!isset($options["fast_stock"]) || $options["fast_stock"] === false) {
    Mage::getModel("cataloginventory/stock")->addItemsToProducts($collection);
  } ?>
  <div id="upsell-products" class="product-collateral category-products">
    <h2 class="tableftheader">Alternatieven</h2>
    <ul class="products-grid products-grid-mini"><?php
      foreach($collection as $_product) {
        if($i === $max_items) break;
        $i++; ?>
        <li class="item<?php if(($i-1) % $_columnCount == 0): ?> first<?php elseif($i % $_columnCount == 0): ?> last<?php endif; ?>">
          <?= Mage::helper("deheerhoreca_util/util")->getProductGridHtml($_product, $this, $options) ?>
        </li><?php
      } ?>
    </ul>
  </div><?php
}
