<?php
/**
 * Shopping cart template
 *
 * @var $this Mage_Checkout_Block_Cart
 */

//echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_page_banner')->toHtml();

echo $this->getLayout()->createBlock('cms/block')->setBlockId('firecheckout_header')->toHtml();

$_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price'; ?>

<div class="cart <?php echo $_priceDisplay; ?>">
  <div class="page-title title-buttons">
    <h1><?php echo $this->__('Shopping Cart') ?></h1>
    <?php if(0 && !$this->hasError()): ?>
      <ul class="checkout-types top">
      <?php foreach ($this->getMethods('top_methods') as $method): ?>
          <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
          <li><?php echo $methodHtml; ?></li>
          <?php endif; ?>
      <?php endforeach; ?>
      </ul>
    <?php endif; ?>
  </div>
  <?php echo $this->getMessagesBlock()->toHtml() ?>
  <div class="pgcrtleft">
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <table id="shopping-cart-table" class="cart-table data-table">
            <col width="120" />
            <col width="200" />
            <col width="100" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
              <col width="1" />
              <col width="1" />
            <?php endif; ?>

        <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
            <thead>
                <tr>
                    <th rowspan="<?php echo $mergedCells; ?>" class="nobr">&nbsp;</th>
                    <th rowspan="<?php echo $mergedCells; ?>"  class="nobr"><?php echo $this->__('Product') ?></th>
                    <th class="align-right cart-price-head" colspan="<?php echo $mergedCells; ?>">
                      <?php echo $this->__('Price') ?>
                    </th>
                    <th rowspan="<?php echo $mergedCells; ?>" class="a-center">
                        <?php echo $this->__('Qty') ?>
                        <?php /*if ($this->helper('wishlist')->isAllowInCart()) : ?>
                            <span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span>
                        <?php endif*/ ?>
                    </th>
                    <th class="a-center cart-total-head" colspan="<?php echo $mergedCells; ?>">
                            <?php echo $this->__('Subtotal') ?>
                    </th>
                </tr>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
                <?php endif; ?>
            </thead>
            
            <tbody>
            <?php foreach($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('shopping-cart-table')</script>
    </form>


	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_left_bottom')->toHtml(); ?>
	</div>
</div>

<div class="pgcrtright">
  <div class="pgcrtrightinner">
    <h1 class="shopcrtrsidehd">Besteloverzicht</h1>
      <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
      <div class="cart-forms">
          <?php /* Extensions placeholder */ ?>
          <?php echo $this->getChildHtml('checkout_cart_widget') ?>
          <?php echo $this->getChildHtml('coupon') ?>
          <?php echo $this->getChildHtml('checkout.cart.extra') ?>
          <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
      </div>
      <div class="cart-totals-wrapper">
      <script src ="https://form.jotform.com/static/feedback2.js" type="text/javascript"></script>
      <script type="text/javascript">
        var JFL_200152323289044 = new JotformFeedback({
          formId: '200152323289044',
          base: 'https://form.jotform.com/',
          windowTitle: 'Aanvraag lease',
          background: '#f08324',
          fontColor: '#FFFFFF',
          type: 'false',
          height: 600,
          width: 700,
          openOnLoad: false
        });
      </script>
          <div class="cart-totals">
              <?php echo $this->getChildHtml('totals'); ?>
              <?php if(!$this->hasError()): ?>
                <ul class="checkout-types bottom">
                  <?php
                  foreach ($this->getMethods('methods') as $method) {
                    if ($methodHtml = $this->getMethodHtml($method)) {
                      echo '<li class="method-'.preg_replace("/[^_a-zA-Z0-9-]/", '-', $method).'">'.$methodHtml.'</li>';
                    }
                  }
                  ?>
                  <?php
                  $buttonTitle_lease = $this->__('Lease aanvragen');
                  ?>
                  <li class="method-checkout-cart-methods-fire">
                    <button type="button" title="Lease aanvragen" class="button btn-cart btn lightbox-200152323289044" style="background-color:#2a71db; display: block; float: none; margin: 1em auto 1em auto; width: 92%; text-transform: uppercase;">
                      <span>
                        <?php echo $buttonTitle_lease; ?>
                        <span class="float-right big" style="margin: 0 1em;">
                          <i class="fa fa-chevron-right"></i>
                        </span>
                      </span>
                    </button>
                  </li>
                </ul>              
              <?php endif; ?>
          </div>
      </div>

    <?php
    //echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_page_right_bottom_1')->toHtml();
    ?>
  </div>
  <?php
  echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_page_right_bottom_2')->toHtml();
  ?>
</div>
	<div style="clear: both; height: 9px;">&nbsp;</div>
		<?php
 //echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_page_bottom')->toHtml();
?>



    <?php echo $this->getChildHtml('crosssell') ?>
</div>
