<?php
/**
 * Shopping cart template
 *
 * @var $this Mage_Checkout_Block_Cart
 */

//echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_page_banner')->toHtml();
?>

<style>
.shadow {
  -webkit-border-radius: 0% 0% 100% 100% / 0% 0% 8px 8px;
  -webkit-box-shadow: rgba(0, 0, 0,.30) 0 2px 3px;
}
.container {
  margin: 0 auto;
  width: 100%;
  background: #f9f9f9 0 0;
  border: 1px solid #ccc;
  box-shadow: 1px 1px 2px #fff inset,
              -1px -1px 2px #fff inset;
  border-radius: 3px/6px;
  padding: .5em;
}

ul.tile-grid {
  display:grid;
  display: -ms-grid;
  grid-template-columns: 100%;
  grid-column-gap: 0;
  -ms-grid-columns: 100%;
  grid-template-rows: auto auto auto auto;
  grid-row-gap: 5px;
  -ms-grid-rows: auto 5px auto 5px auto 5px auto;
  margin: 1em 0;
  flex-flow: row wrap;
}

@media (min-width: 48em) {
  ul.tile-grid {
    grid-template-columns:calc(50% - 7.5px) calc(50% - 7.5px);
    grid-column-gap: 15px;
    -ms-grid-columns: calc(50% - 7.5px) 15px calc(50% - 7.5px);
    grid-template-rows: auto auto;
    grid-row-gap: 15px;
    -ms-grid-rows: auto 15px auto
  }
}

@media (min-width: 62em) {
  
  ul.tile-grid li {
    height: 50px;
  }
  
  ul.tile-grid li a {
    flex-flow: column nowrap;
    padding-bottom: 40px;
  }
}

@media (min-width: 75em) {
  ul.tile-grid {
    grid-template-columns:calc(25% - 11.25px) calc(25% - 11.25px) calc(25% - 11.25px) calc(25% - 11.25px);
    grid-column-gap: 15px;
    -ms-grid-columns: calc(25% - 11.25px) 15px calc(25% - 11.25px) 15px calc(25% - 11.25px) 15px calc(25% - 11.25px);
    grid-template-rows: auto;
    grid-row-gap: 15px;
    -ms-grid-rows: auto;
  }
}

div.usp-icon {
  margin: 0 .5em;
}

</style>

<div class="f">
  <ul class="tile-grid">
     <li class="container">
      <div class="float-left usp-icon">
        <img alt="Gratis verzending" src="/skin/frontend/rwd/dhh/images/trolley.svg" width="32" height="32"></div>
      <div>
        <span class="usp_text"><strong class="extra_special">Gratis</strong> verzending</span><br />
        <span class="small">In Nederland &amp; België vanaf &euro; 150</span>
      </div>
    </li>
     <li class="container">
      <div class="float-left usp-icon">
        <img alt="De beste prijs" src="/skin/frontend/rwd/dhh/images/euro.svg" width="32" height="32">
      </div>
      <div class="inline">
        <span class="usp_text">Ergens goedkoper gezien?</span><br />
        <span class="small"><a href="/klantenservice">Vertel het ons</a></span>
      </div>
    </li>
     <li class="container">
      <div class="float-left usp-icon">
        <img alt="Advies voor professionals" src="/skin/frontend/rwd/dhh/images/superhero.svg" width="32" height="32">
      </div>
      <div class="inline">
        <span class="usp_text">Advies door professionals</span><br />
        <span class="small">Klaas staat klaar</span>
      </div>
    </li>
     <li class="container">
      <div class="float-left usp-icon">
        <img alt="Snelle levrering" src="/skin/frontend/rwd/dhh/images/fast_delivery_truck.svg" width="32" height="32">
      </div>
      <div class="inline"><span class="usp_text">Snelle levering</span></div>
    </li>
  </ul>
  
</div>

<?php
$pageIdentifier = Mage::app()->getFrontController()->getAction()->getFullActionName();
if($pageIdentifier=='checkout_cart_index'){

}
$_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price'; ?>

<div class="cart <?php echo $_priceDisplay; ?>">
  <div class="page-title title-buttons">
    <h1><?php echo $this->__('Shopping Cart') ?></h1>
    <?php if(!$this->hasError()): ?>
    <ul class="checkout-types top">
    <?php foreach ($this->getMethods('top_methods') as $method): ?>
        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
        <li><?php echo $methodHtml; ?></li>
        <?php endif; ?>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>
  </div>
  <?php echo $this->getMessagesBlock()->toHtml() ?>
  <div class="pgcrtleft">


    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <table id="shopping-cart-table" class="cart-table data-table">
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1" />
            <col width="1" />
            <?php endif; ?>

        <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
            <thead>
                <tr>
                    <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php //echo $this->__('Product') ?></span></th>
                    <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                    <th class="align-right cart-price-head" colspan="<?php echo $mergedCells; ?>">
                      <?php echo $this->__('Price') ?>
                    </th>
                    <th rowspan="<?php echo $mergedCells; ?>" class="a-center">
                        <?php echo $this->__('Qty') ?>
                        <?php /*if ($this->helper('wishlist')->isAllowInCart()) : ?>
                            <span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span>
                        <?php endif*/ ?>
                    </th>
                    <th class="a-center cart-total-head" colspan="<?php echo $mergedCells; ?>">
                            <?php echo $this->__('Subtotal') ?>
                    </th>
                </tr>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
                <?php endif; ?>
            </thead>
            
            <tbody>
            <?php foreach($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('shopping-cart-table')</script>
    </form>


	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_left_bottom')->toHtml(); ?>
	</div>
</div>

<div class="pgcrtright">
  <div class="pgcrtrightinner">
    <h1 class="shopcrtrsidehd">Besteloverzicht</h1>
      <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
      <div class="cart-forms">
          <?php /* Extensions placeholder */ ?>
          <?php echo $this->getChildHtml('checkout_cart_widget') ?>
          <?php echo $this->getChildHtml('coupon') ?>
          <?php echo $this->getChildHtml('checkout.cart.extra') ?>
          <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
      </div>
      <div class="cart-totals-wrapper">
      <script src ="https://form.jotform.com/static/feedback2.js" type="text/javascript"></script>
      <script type="text/javascript">
        var JFL_200152323289044 = new JotformFeedback({
          formId: '200152323289044',
          base: 'https://form.jotform.com/',
          windowTitle: 'Aanvraag lease',
          background: '#f08324',
          fontColor: '#FFFFFF',
          type: 'false',
          height: 600,
          width: 700,
          openOnLoad: false
        });
      </script>
          <div class="cart-totals">
              <?php echo $this->getChildHtml('totals'); ?>
              <?php if(!$this->hasError()): ?>
                <ul class="checkout-types bottom">
                  <?php
                  foreach ($this->getMethods('methods') as $method) {
                    if ($methodHtml = $this->getMethodHtml($method)) {
                      echo '<li class="method-'.preg_replace("/[^_a-zA-Z0-9-]/", '-', $method).'">'.$methodHtml.'</li>';
                    }
                  }
                  ?>
                  <?php
                  $buttonTitle_lease = $this->__('Lease aanvragen');
                  ?>
                  <li class="method-checkout-cart-methods-fire">
                    <button type="button" title="Lease aanvragen" class="button btn-cart btn lightbox-200152323289044" style="background-color:#2a71db; display: block; float: none; margin: 1em auto 1em auto; width: 92%; text-transform: uppercase;">
                      <span>
                        <?php echo $buttonTitle_lease; ?>
                        <span class="float-right big" style="margin: 0 1em;">
                          <i class="fa fa-chevron-right"></i>
                        </span>
                      </span>
                    </button>
                  </li>
                </ul>              
              <?php endif; ?>
          </div>
      </div>

    <?php
    //echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_page_right_bottom_1')->toHtml();
    ?>
  </div>
  <?php
  echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_page_right_bottom_2')->toHtml();
  ?>
</div>
	<div style="clear: both; height: 9px;">&nbsp;</div>
		<?php
 //echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_page_bottom')->toHtml();
?>



    <?php echo $this->getChildHtml('crosssell') ?>
</div>
