<?php
# KEEP IN SYNC:
# - app/design/frontend/rwd/dhh/template/paysafecash/success.phtml @deprecated
# - app/design/frontend/rwd/dhh/template/checkout/success.phtml
?>

<style>
  @media screen and (min-width: 1200px) {
    .info-box-cart-success {
      background: url(https://www.chefstore.nl/skin/frontend/rwd/dhh/images/topklaas.jpg) 99% 90% no-repeat;
      background-size: contain;
    }
  }
</style>
<div class="info-box info-box-cart-success">
  <div class="info-box-inner">
    <h1 class="xxl">Bedankt!</h1>
    <p>Alles is goed gegaan, dank je wel voor je bestelling!</p>
    <h1 style="padding-top: 1em;">Wat gaan wij nu doen?</h1>
    <ol class="disc-list">
      <li>We sturen je order direct naar het magazijn of de leverancier</li>
      <li>Indien nodig nemen wij contact op om de details van de order en/of de levering door te nemen</li>
      <li>Indien het pakket mee kan met de postbode, dan zal het via reguliere pakketpost komen. Het kan ook zijn dat het item met een transporteur wordt bezorgd. De meeste transporteurs ondersteunen Track &amp; Trace, en die krijg je van ons zodra wij hem hebben.</li>

    <?php if ($this->getOrderId()):?>
      <?php if ($this->getCanViewOrder()) :?>
        <li><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></li>
      <?php else :?>
        <li><strong><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></strong></p>
      <?php endif;?>
        <li>Je krijgt een e-mail met je orderbevestiging. Natuurlijk sturen wij ook order updates daarnaartoe</li>
      <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
        <li>
          <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
          <?php echo $this->getChildHtml() ?>
        </li>
      <?php endif;?>
    <?php endif;?>

    <?php if ($this->getAgreementRefId()): ?>
      <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
    <?php endif;?>

    <?php if ($profiles = $this->getRecurringProfiles()):?>
      <p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
      <ul class="disc">
        <?php foreach($profiles as $profile):?>
          <?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
          <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
        <?php endforeach;?>
      </ul>
    <?php endif;?>
    </ol>

    <button type="button" style="margin: 2em auto;" class="center button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?>" onclick="window.location='<?php echo $this->getUrl() ?>'">
      Naar Chefstore.nl
    </button>

  </div>
</div>

<?php
/* Clickcease.com Conversion tracking */
?>

<script>
  ccConVal = 0;
  var script = document.createElement("script");
  script.async = true;
  script.src = '//www.clickcease.com/monitor/cccontrack.js';
  var elem = document.head;
  elem.appendChild(script);
</script>

<?php
/* Bing Conversion tracking */

$order_id             = $this->getOrderId();
$_order               = Mage::getModel("sales/order")->loadByIncrementId($order_id);
$grand_total          = $_order->getGrandTotal() ?? null;
if(is_numeric($grand_total)) {
  $grand_total         /= 1.21;
}
?>
<script>
  window.uetq = window.uetq || [];
  window.uetq.push('event', '', {'revenue_value': <?php echo $grand_total; ?>, 'currency': 'EUR'});
</script>

<?php
/* Datatrics Conversion tracking */

// @see https://app.datatrics.com/integrations/datatrics-tracker/46731568013430307066

$shipping_total       = $_order->getShippingAmount();
$tax_info             = $_order->getFullTaxInfo();
$tax_total            = $tax_info[0]["amount"] ?? null;
$total_no_shipping    = ($grand_total - $shipping_total);
$discount_offered     = json_encode(!(empty($_order->getCouponCode())));
$_items               = $_order->getAllItems();
$datatrics_js         = "";
foreach($_items as $_item) {
  // printr($_item->getData());
  // printr(get_class_methods($_item));
  $_product         = $_item->getProduct();
  // printr($_product->getData());
  $category_ids       = $_product->getCategoryIds();
  $_categories        = $_product->getCategoryCollection();
  // printr($cats);
  // printr(_get_product_attribute($_product, "product_type"));
  // printr($_product->getResource()->getAttribute('product_type')->getFrontend()->getValue($_product));

  $sku              = $_item->getSku();
  $name             = $_item->getName();
  $price            = (float) $_item->getPrice();
  $qty              = (int) $_item->getQtyOrdered();
  $categories       = [];

  if($_product && empty(_get_product_attribute($_product, "product_type") === false)) {
    $categories[]     = _get_product_attribute($_product, "product_type");
  }
  foreach($category_ids as $category_id) {
    $_category        = Mage::getModel('catalog/category')->load($category_id);
    $categories[]     = Mage::helper("deheerhoreca_util/util")->cleanCategoryName($_category->getName());
  }
  $categories_json  = json_encode($categories); // Maybe add JSON_UNESCAPED_UNICODE
  $datatrics_js    .= "_paq.push(['addEcommerceItem', '{$sku}', '{$name}', {$categories_json}, {$price}, {$qty}]);".PHP_EOL;
}
?>
<script>
  var _paq = _paq || [];
  if(window.location.hostname == "www.chefstore.nl") {
    <?php echo $datatrics_js ?>
    _paq.push(['trackEcommerceOrder', '<?php echo $order_id ?>', <?php echo $grand_total; ?>, <?php echo $total_no_shipping; ?>, <?php echo $tax_total; ?>, <?php echo $shipping_total; ?>, <?php echo $discount_offered; ?>]);
    <?php
    // This already happens ealier, probably not needed
    // _paq.push(['trackPageView']);
    ?>
  }
</script>
