<?php
/** @var Mage_Core_Block_Template $this */
/** @var Profitmetrics_MagentoIntegration_Helper_Data $profitmetricsHelper */
$profitmetricsHelper = Mage::helper('profitmetrics');
?>
<?php if ($profitmetricsHelper->isEnabled() && !$profitmetricsHelper->getIsHeadlessModeActive()): ?>
<script type="text/javascript">
    var includeJsFile = function (url) {
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=url; s.parentNode.insertBefore(g,s);
    };

    window._pm_TPTrackEndpoint = '<?php echo Mage::getUrl('profitmetrics/tracking/index', array('_secure' => true)); ?>';

    includeJsFile('<?php echo $this->getSkinUrl($this->getData('skin_js'), array('_secure' => true)); ?>?v=1');
</script>
    <?php if (!$profitmetricsHelper->isOrderSuccessPage() && ($trackingCodeJs = $profitmetricsHelper->getTrackingCodeJs())): ?>
        <?php if (strpos($trackingCodeJs, '<script') === false): ?>
            <script type="text/javascript"><?= $trackingCodeJs ?></script>
        <?php else: ?>
            <?= $trackingCodeJs ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($googleAdsConversionId = $profitmetricsHelper->getGoogleAdsConversionId()): ?>
        <!-- ProfitMetrics Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=<?= $this->escapeUrl($googleAdsConversionId) ?>"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '<?= $this->jsQuoteEscape($googleAdsConversionId) ?>');
        </script>
    <?php endif; ?>
<?php endif; ?>