<?php
/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */

// Taken from https://community.magento.com/t5/Magento-1-x-Programming/How-to-display-Attribute-Group-Name-on-Product-page/td-p/12156
$_helper              = $this->helper("catalog/output");
$_product             = $this->getProduct();

// Tooltips
$attr_tooltips = [
  "koeltemperatuur"     => "De behaalde temperatuur kan variëren. Factoren die van invloed zijn, zijn onder andere: koelmethode, omgevingstemperatuur, open-frequentie, ventilatie rondom het apparaat, de klimaatklasse, en de koelcyclus",
  "aantal_blikjes"      => "Het exacte aantal kan iets variëren met de exacte grootte",
  "deur_omkeerbaar"     => "Indien de draairichting van de deur wordt omgedraaid is het slot niet altijd meer bruikbaar en zijn eventuele afbeeldingen op de deur omgekeerd.",
  "temp_range_from_c"   => "De behaalde temperatuur kan iets variëren, afhankelijk van omgevingsfactoren.",
];
$attr_tooltips["vriestemperatuur"]      = $attr_tooltips["koeltemperatuur"];
$attr_tooltips["aantal_flessen"]        = $attr_tooltips["aantal_blikjes"];
$attr_tooltips["capacity_wine_bottles"] = $attr_tooltips["aantal_blikjes"];
$attr_tooltips["temp_range_to_c"]       = $attr_tooltips["temp_range_from_c"];

// No decimals, with number formatting
$attr_remove_decimals = [
  "hoogte_intern", "breedte_intern", "diepte_intern", 
  "diameter", "breedte", "hoogte", "diepte", "magnetron_output_watt", 
  "grill_output_watt", "aantal_m3_uur", "aantal_deuren", "aantal_roosters", 
  "aantal_kippen", "aantal_kuipen", "aantal_platen", "aantal_borden",
  "aantal_bakken", "aantal_zetsystemen", "aantal_manden", "aantal_pizzas",
  "aantal_elementen", "aantal_etages", "aantal_filters",
  "aantal_borden_korven", "aantal_glas_korven", "aantal_snelheden",
  "aantal_blikjes", "aantal_wasprogrammas", "eenheid", "capacity_wine_bottles",
  "geluidsniveau", "number_of_cooling_zones", "aantal_flessen",
  "cooking_zones", "gross_weight_gram", "length_mm", "isolatiedikte",
  "number_of_slots", "max_geleiders", "package_height_mm", "package_width_mm",
  "package_depth_mm", "shipping_weight_gram", "temp_range_from_c", "temp_range_to_c",
  "thickness_mm",
];

// No zero decimals, with number formatting
$attr_trim_decimals   = ["inhoud_liters", "inhoud_m3", "voorraadbunker_kg",
  "inhoud_wastank_liter", "vermogen_boiler", "weight", "volume_freezer_liter",
  "volume_refrigerator_liter","volume_net_liter", "ijs_productie", "ijs_bunker",
  "annual_energy_consumption_kwh", "capaciteit_boiler", "laadhoogte", "weight_fabric",
  "gewicht_vlees_max", "water_verbruik", "water_verbruik_cyclus",
];

// Allow to show "No" values for these attributes
$attr_show_no         = ["microwave_safe", "oven_safe", "dishwasher_safe"];

$attr_hide_zero       = array_merge($attr_trim_decimals, $attr_remove_decimals);

// Do not show these values
$value_skip           = ["N.v.t.", "n.v.t.", "Geen / n.v.t."];

// Do not retrieve these attribute_codes
$skipped_attributes   = [];

// Do not show these attribute_codes
$hidden_attributes    = ["external_documents_json"];

// Track to-be-deleted attributes
$delete_these         = [];

// Main attribute output array
$attributes           = [];

if($_additionalgroup = $this->getAdditionalDataCustom($skipped_attributes)) {
  $attr_remove_decimals = array_flip($attr_remove_decimals);
  $attr_trim_decimals   = array_flip($attr_trim_decimals);
  $attr_hide_zero       = array_flip($attr_hide_zero);
  
  // Optionally delete other attributes if certain ones are filled
  foreach($_additionalgroup as $_additional) {    
    foreach($_additional["items"] as $_data) {
      switch($_data["code"]) {
        case "gn_capacity":                 $delete_these[] = "inhoud_aantal_gn";         break;
        case "energy_efficiency_class_a_g": $delete_these[] = "energieklasse";            break;
        
        case "temp_range_from_c":
        case "temp_range_to_c":
          $delete_these[] = "koeltemperatuur";
          $delete_these[] = "vriestemperatuur";
          break;
      }
    }
  }
  
  foreach($_additionalgroup as $_additional) {
    
    foreach($_additional["items"] as $_data) {
      $values         = $_data["value"];
      $code           = $_data["code"];
      $output_values  = [];
      $link           = null;
      
      foreach($values as $value) {
      
        if(strlen($value) < 1 || in_array($value, $value_skip, true)) {
          continue;
        }
        
        if(strlen($code) < 1 || in_array($code, $hidden_attributes, true)) {
          continue;
        }
        
        /* Pre-processing individual attributes */
        switch($code) {
          case "eenheid":
            if(($value > 1) === false) {
              continue 2;
            }
            break;
          
          case "ean":
            $eans = _getAlternativeEans($value);
            $value = implode(", ", $eans);
            break;
          
          case "manufacturer":
          case "brand_series":
            if(empty($_data["option_id"]) === false) {
              $link = "/shop?{$_data["code"]}={$_data["option_id"]}";
            }
            break;
        }
        
        $label = $this->htmlEscape($this->__($_data["label"]));
        $prefix  = "";
        $postfix = "";
        
        /* Processing individual attributes */
       
        switch($code) {
          
          // "°C" postfix
          case "temp_range_from_c":
          case "temp_range_to_c":
          case "temp_resistance_from":
          case "temp_resistance_to":
            if($value > 0) {
              $prefix = "+";
            }
            $postfix = " °C";
            break;
          
          // "kg" postfix
          case "voorraadbunker_kg":
          case "ijs_productie":
          case "ijs_bunker":
            $postfix = " kg";
            break;
          
          // "liter" postfix
          case "inhoud_liters":
          case "volume_net_liter":
          case "volume_freezer_liter":
          case "volume_refrigerator_liter":
            $postfix = " liter";
            break;
          
          // "m3" postfix"
          case "inhoud_m3":
            $postfix = " m³";
            break;
          
          // "mm" postfix
          case "hoogte":
          case "breedte":
          case "diepte":
          case "diameter":
          case "hoogte_intern":
          case "breedte_intern":
          case "diepte_intern":
          case "thickness_mm":
          case "insulation_thickness_mm":
          case "isolatiedikte":
          case "breedte_deur":
          case "length_mm":
          case "package_height_mm":
          case "package_width_mm":
          case "package_depth_mm":
            $postfix = " mm";
            break;
          
          // Other
          
          case "vermogen_kw":
          case "vermogen":
            if($value < 5) {
              $value *= 1000;
              $postfix = " Watt";
            } else {
              $value = number_format($value, 2, ",", ".");
              $postfix = " kW";
            }
            break;
          
          case "total_power_watt":
            if($value  >= 5000) {
              $value   /= 1000;
              $value    = number_format($value, 2, ",", ".");
              $postfix  = " kW";
            } else {
              $value = (int) number_format($value, 0, ",", "");
              $postfix = " Watt";
            }
            break;
            
          case "shipping_weight_gram":
          case "weight":
            if($value < 3) {
              $value *= 1000;
              $postfix = " g";
            } else {
              $postfix = " kg";
            }
            break;
          
          case "warranty_remarks":
            $supplier = strtolower($_product->getAttributeText("supplier"));
            if($supplier === "combisteel") {
              $postfix = " <a href='/garantievoorwaarden-combisteel' target='_blank' class='small'>Aanvullende Garantievoorwaarden</a>";
            }
            break;
          
          default:
            $value = $_helper->productAttribute($_product, $value, $code);
        }
        
        if(isset($attr_hide_zero[$code]) && $value == 0) {
          continue;
        }
        
        if(isset($attr_remove_decimals[$code])) {
          $value = (int) number_format($value, 0, ",", "");
        }
        
        if(isset($attr_trim_decimals[$code])) {
          $value = Mage::helper("deheerhoreca_util/util")->trim_decimals($value);
        }
      
        /* Post-processing individual attributes */
        switch($code) {
          case "number_of_cooling_zones":
            if($value === 1) $value .= " (Single-Zone)";
            elseif($value === 2) $value .= " (Dual-Zone)";
            elseif($value === 3) $value .= " (Triple-Zone)";
            break;
        }
        
        /* Post-processing all attributes */
        if($value === "Nee" && in_array($code, $attr_show_no, true) === false) {
          $value = "-";
        }
        
        if(empty($link) === false) {
          $output_values[] = "<a href='{$link}'>{$prefix}{$value}{$postfix}</a>";
        } else {
          $output_values[] = "{$prefix}{$value}{$postfix}";
        }
      }
      
      $output_values = array_unique($output_values);
      $_output_value = implode("<i style='font-size:8px;color:#adadad;padding:0 5px;' class='fa fa-minus' aria-hidden='true'></i>", $output_values);
      
      $tooltip = "";
      if(isset($attr_tooltips[$code]) === true) {
        $tooltip = $attr_tooltips[$code];
      }
      
      if(strlen($_output_value) > 0 && in_array($code, $delete_these, true) === false) {
        $attributes[$this->__($_additional["title"])][$code] = [
          "label"     => $label,
          "value"     => $_output_value,
          "tooltip"   => $tooltip,
        ];
      }
    }
  }
}

// if(_dhh_debug()) {
  // echo "<pre>";
  // print_r($delete_these);
  // print_r($attributes);
  // echo "</pre>";
// }

if($attributes !== []) {
  echo "<div class='box-collateral box-additional bxgroupifo product-specs'>";
  foreach($attributes as $group => $subattributes) {
    echo "<span class='clzattrgname'>{$this->__($group)}</span>";
    foreach($subattributes as $key => $attr) {
      $tooltip = "";
      if(empty($attr["tooltip"]) === false) {
        $tooltip = "<span class='tooltip-wrapper'><span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg has-tooltip' aria-hidden='true'></i><span class='tooltiptext clztoptoolc'>{$attr["tooltip"]}</span></span></span>";
      }
      echo "<dl><dt>{$tooltip}{$attr["label"]}</dt><dd>{$attr["value"]}</dd></dl>".PHP_EOL;
    }
  }
  echo "</div>";
}

function _getAlternativeEans($ean) {
  $eans = [$ean];
  if(strlen($ean) === 13) {
    $eans[] = sprintf("%014d", $ean);
  }
  if(substr($ean, 0, 1) === "0") {
    $eans[] = substr($ean, 1);
  }
  if(substr($ean, 0, 2) === "00") {
    $eans[] = substr($ean, 2);
  }
  if(substr($ean, 0, 3) === "000") {
    $eans[] = substr($ean, 3);
  }
  
  return $eans;
}
