<?php
/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */

// Taken from https://community.magento.com/t5/Magento-1-x-Programming/How-to-display-Attribute-Group-Name-on-Product-page/td-p/12156
$_helper              = $this->helper('catalog/output');
$_product             = $this->getProduct();

/* No decimals, with number formatting */
$attr_remove_decimals = [
  "hoogte_intern", "breedte_intern", "diepte_intern", 
  "diameter", "breedte", "hoogte", "diepte", "magnetron_output_watt", 
  "grill_output_watt", "aantal_m3_uur", "aantal_deuren", "aantal_roosters", 
  "aantal_kippen", "aantal_kuipen", "aantal_platen", "aantal_borden",
  "aantal_bakken", "aantal_zetsystemen", "aantal_manden", "aantal_pizzas",
  "aantal_elementen", "aantal_etages", "aantal_filters", "aantal_branders",
  "aantal_borden_korven", "aantal_glas_korven", "aantal_snelheden",
  "aantal_blikjes", "aantal_wasprogrammas", "eenheid", "capacity_wine_bottles",
  "geluidsniveau", "number_of_cooling_zones", "aantal_flessen",
  "cooking_zones","gross_weight_gram",
];

/* No zero decimals, with number formatting */
$attr_trim_decimals   = ["inhoud_liters", "inhoud_m3", "voorraadbunker_kg",
  "inhoud_wastank_liter", "vermogen_boiler", "weight", "volume_freezer_liter",
  "volume_refrigerator_liter",
];

/* Do not show these values */
$value_skip           = ["N.v.t.", "n.v.t.", "Geen / n.v.t."];

/* Do not show these attribute_codes */
$code_skip            = [];

$attributes           = [];

if($_additionalgroup = $this->getAdditionalDataCustom()) {
  $attr_remove_decimals = array_flip($attr_remove_decimals);
  $attr_trim_decimals   = array_flip($attr_trim_decimals);
  
  foreach($_additionalgroup as $_additional) {
    
    foreach($_additional['items'] as $_data) {
      $values         = $_data['value'];
      $code           = $_data['code'];
      $output_values  = [];
      
      foreach($values as $value) {
      
        if(empty($value) || in_array($value, $value_skip, true)) {
          continue;
        }
        
        if(empty($code) || in_array($code, $code_skip, true)) {
          continue;
        }
        
        /* Pre-processing individual attributes */
        switch($code) {
          case "eenheid":
            if(($value > 1) === false) {
              continue 2;
            }
            break;
        }
        
        $label = $this->htmlEscape($this->__($_data['label']));
        $postfix = null;
       
        switch($code) {
          case "vermogen_kw":
          case "vermogen":
            if($value < 5) {
              $value *= 1000;
              $postfix = " Watt";
            } else {
              $value = number_format($value, 2, ",", ".");
              $postfix = " kW";
            }
            break;
          
          case "total_power_watt":
            if($value  >= 5000) {
              $value   /= 1000;
              $value    = number_format($value, 2, ",", ".");
              $postfix  = " kW";
            } else {
              $value = (int) number_format($value, 0, ",", "");
              $postfix = " Watt";
            }
            break;
          
          case "weight":
            if($value < 3) {
              $value *= 1000;
              $postfix = " g";
            } else {
              $value = number_format($value, 2, ",", ".");
              $postfix = " kg";
            }
            break;
          
          case "inhoud_liters":
          case "volume_freezer_liter":
          case "volume_refrigerator_liter":
            $postfix = " liter";
            break;
          
          case "hoogte":
          case "breedte":
          case "diepte":
          case "diameter":
          case "hoogte_intern":
          case "breedte_intern":
          case "diepte_intern":
            $postfix = " mm";
            break;

          default:
            $value = $_helper->productAttribute($_product, $value, $code);
        }
        
        if(isset($attr_remove_decimals[$code])) {
          $value = (int) number_format($value, 0, ",", "");
        }
        
        if(isset($attr_trim_decimals[$code])) {
          $value = number_format($value, 2, ",", ".");
          $value = str_replace(",00", null, $value);
        }
      
        /* Post-processing individual attributes */
        switch($code) {
          case "number_of_cooling_zones":
            if($value === 1) $value .= " (Single-Zone)";
            elseif($value === 2) $value .= " (Dual-Zone)";
            elseif($value === 3) $value .= " (Triple-Zone)";
            break;
        }
        
        /* Post-processing all attributes */
        if($value === "Nee") {
          $value = "-";
        }
        
        $output_values[] = $value.$postfix;
      }
      
      $output_values = array_unique($output_values);
      $_output_value = implode("<i style='font-size:8px;color:#adadad;padding:0 5px;' class='fa fa-minus' aria-hidden='true'></i>", $output_values);
      
      if(empty($_output_value) === false) {
        $attributes[$this->__($_additional['title'])][$label] = $_output_value;
      }
    }
  }
}

// if($_SERVER["REMOTE_ADDR"] === "185.127.111.251") {
  // echo "<pre>";
  // print_r($attributes);
  // echo "</pre>";
// }  

if($attributes !== []) {
  echo '<div class="box-collateral box-additional bxgroupifo product-specs">';
  foreach($attributes as $group => $subattributes) {
    echo "<span class='clzattrgname'>{$this->__($group)}</span>";
    foreach($subattributes as $label => $value) {
      echo "<dl><dt>{$label}</dt><dd>{$value}</dd></dl>";
    }
  }
  echo "</div>";
}
