<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */

$htbrand                = $brand = null;
$_helper                = $this->helper("catalog/output");
$_product               = $this->getProduct();
$brand_name             = $_product->getAttributeText("manufacturer");
$brand_id               = $_product->getData("manufacturer");
$sku                    = $_product->getData("sku");
$brand_logo             = null;
$brand_slug             = Mage::helper("deheerhoreca_util/util")->getBrandUrlSlug($brand_name);
$brand_link             = "/shop?manufacturer={$brand_id}";
$_store                 = $_product->getStore();
$skn                    = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$anchors                = [];
$in3_minimum            = 100 / 1.21;
$in3_maximum            = 3000 / 1.21;
$billink_minimum        = 10;
$billink_maximum        = 3500;
$biller_minimum         = 10;
$biller_maximum         = 5000;
$_taxHelper             = $this->helper("tax");
$categoryIds            = $_product->getCategoryIds();

// Find the category this product belongs to
if(count($categoryIds)) {
  $firstCategoryId = $categoryIds[0];
  $_category = Mage::getModel("catalog/category")->load($firstCategoryId);
  $categoryUrl = $_category->getUrl();
  $categoryName = $_category->getName();
}

$max_highlighted_attributes = 10;

// Attributes used in multiple places
$nofrost_method         = $_product->getResource()->getAttribute("ontdooisysteem")->getFrontend()->getValue($_product);
$energy_rating          = $_product->getResource()->getAttribute("energieklasse")->getFrontend()->getValue($_product);
$shoutout               = $_product->getResource()->getAttribute("product_label")->getFrontend()->getValue($_product);
$productTitle           = $_helper->productAttribute($_product, $_product->getName(), "name");
$product_title_short    = $_product->getResource()->getAttribute("name_short")->getFrontend()->getValue($_product);
$pvideo                 = $_product->getResource()->getAttribute("product_video")->getFrontend()->getValue($_product);
$_price                 = $_product->getPrice(); //Mage::getModel("catalog/product")->load($_product->getId())->getNormalPrice();
$_finalPrice            = $_product->getFinalPrice();
$tagline                = $_product->getTagline();
$supplier_name          = $_product->getAttributeText("supplier");
$product_description_md = trim($_product->getDescription());
$product_description    = "";

// Availability, Stock
$stock_data             = Mage::helper("deheerhoreca_util/util")->getStockInfo($_product);
$stock_message          = $stock_data["stock_message"];
$stock_tooltip          = $stock_data["stock_tooltip"];
$txtcltcz               = $stock_data["txtcltcz"];
$stock_qty              = $stock_data["stock_qty"];
$in_stock               = $stock_data["in_stock"];
$backorders             = $stock_data["backorders"];
$saleable               = $stock_data["saleable"];
$eol                    = $stock_data["eol"];
$eol_replacement_sku    = $stock_data["eol_replacement_sku"];
$manage_stock           = $stock_data["manage_stock"];
$extra_delivery_time    = $stock_data["extra_delivery_time"];
$overall_stock_status   = $stock_data["overall_stock_status"];
$txtstockdate           = $stock_data["txtstockdate"];
$levertijd              = $stock_data["levertijd"];
$levertijd_tmp_override = $stock_data["levertijd_tmp_override"];
$bestelartikel          = $stock_data["bestelartikel"];
$min_sale_qty           = $stock_data["min_sale_qty"];

// Fulfilment, Financials
$used_levertijd         = empty($levertijd_tmp_override) ? $levertijd : $levertijd_tmp_override;
$freeshipping_from      = (float) Mage::getStoreConfig("carriers/freeshipping/free_shipping_subtotal");
$_finalPriceInclTax     = $_taxHelper->getPrice($_product, $_finalPrice, true);

// Add +/- symbol unless it's "op aanvraag"
if(stristr($used_levertijd, "aanvraag") === false && $used_levertijd !== "1 werkdag" && empty($used_levertijd) === false) {
  $used_levertijd = "&plusmn; {$used_levertijd}";
}

if($used_levertijd === "1 werkdag") {
  $delivery_time_tooltip = "Op werkdagen voor 15:00 besteld, de volgende werkdag bezorgd. Het is in een enkel geval mogelijk dat door omstandigheden de bezorging vertraagd is. Natuurlijk houden we u altijd op de hoogte van de status van uw bestelling.";
} else {
  $delivery_time_tooltip = "We doen er alles aan om dit artikel op tijd te bezorgen. Het is in een enkel geval mogelijk dat door omstandigheden de bezorging vertraagd is. Natuurlijk houden we u altijd op de hoogte van de status van uw bestelling.";
}

/* BUYBLOCK CONTENT */

$buyblock_free_delivery_content = "";
$buyblock_free_delivery = false;

if($_finalPriceInclTax >= $freeshipping_from && $_product->isSaleable() === true && $overall_stock_status !== "eol") {
  $buyblock_free_delivery_content .= "<div class='buyblock-usp fw-normal'><strong class=green>Gratis</strong> bezorgd</div>";
  $buyblock_free_delivery = true;
}

// Stock level
$stock_message_tooltip = "";
if(empty($stock_tooltip) === false) {
  $stock_message_tooltip = "<span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='true'></i><span class='tooltiptext clztoptoolc'>{$stock_tooltip}</span></span>";
}

// Delivery time
$delivery_text = "";
if($bestelartikel === "Ja") {
  $delivery_text .= "Bestelartikel</strong><span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='true'></i><span class='tooltiptext clztoptoolc'>Dit artikel wordt op bestelling gemaakt en geleverd</span>";
} elseif($overall_stock_status === "not_sellable" || $overall_stock_status === "backorder" || $manage_stock === false) {
  if(empty($txtstockdate) === false) {
    $delivery_text .= "Verwacht: <strong>{$txtstockdate}</strong><span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='true'></i><span class='tooltiptext clztoptoolc'>Dit is de meest accurate inschatting die wij hebben. Door omstandigheden kan dit soms wijzigen.</span>";
  } elseif($manage_stock !== false) {
    $delivery_text .= "Levertijd op aanvraag<span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='true'></i><span class='tooltiptext clztoptoolc'>Spoedig weer op voorraad, maar wij hebben nog geen exacte datum. U kunt een pre-order plaatsen.</span>";
  }
} elseif($overall_stock_status === "in_stock" && !empty($used_levertijd)) {
  $delivery_text .= "{$used_levertijd}<span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='false'></i> <span class='tooltiptext clztoptoolc'>{$delivery_time_tooltip}</span></span>";
}
if(empty($delivery_text) === false) {
  $delivery_li = "<li class='my-1'><i class='fa-li fa fa-clock-o'></i>{$delivery_text}</li>";
}

// MOQ content
$moq_li = "";
if(empty($min_sale_qty) !== true && $min_sale_qty > 1) {
  $moq_li = "<li class='my-1'><i class='fa-li fa fa-bars'></i>Ordergrootte vanaf <strong>{$min_sale_qty}</strong> stuks</li>";
}

// Qantity step content
$qs_content = "";
$qty_increments = $_product->getStockItem()->getQtyIncrements();
if($qty_increments > 0) {
  $qs_content = "<li class='my-1'><i class='fa-li fa fa-bars'></i>Wordt verkocht in stappen van <strong>".intval($qty_increments)."</strong> stuks</li>";
}

// Help content
$help_content = "<h4 class='black mt-3'>Hulp nodig?</h4><ul class='fa-ul'>
  <li class=my-1>
    <i class='fa-li fa fa-question'></i>
    <a data-fancybox data-type='iframe' data-iframe='{\"preload\":false}' data-width=500 data-height=650 href='https://form.jotform.com/213136047906049?sku=".urlencode($sku)."&product=".urlencode($productTitle)."'>Stel een vraag</a>
  </li>
  <li class=my-1>
    <i class='fa-li fa fa-phone' title='Bellen'></i>
    <a data-fancybox data-type='iframe' href='/media/static/contact.php'>Contact opnemen</a></i>
  </li>
</ul>";

// Our USPs content
$our_usps = [
  "De beste prijzen",
  "Veilig online winkelen",
  "Klanten beoordelen ons met een <strong class=orange>9.2/10</strong>",
  "We zitten klaar voor uw vragen",
];
if(empty($our_usps) === false) {
  $our_usps_content = "<ul class='fa-ul'>";
  foreach($our_usps as $text) {
    $our_usps_content .= "<li class='my-1'><i class='fa-li fa fa-check green'></i>{$text}</li>";
  }
  $our_usps_content .= "</ul>";
  $our_usps_content = "<h4 class='black mt-3'>Onze voordelen:</h4>{$our_usps_content}";
}

// Payment methods content
if($overall_stock_status === "in_stock" || $overall_stock_status === "backorder") {
  
  $payment_methods_texts = [];
  
  if($_finalPrice >= $biller_minimum && $_finalPrice <= $biller_maximum) {
    $text = "Betaal gratis <strong>achteraf</strong> met Biller";
    $payment_methods_texts[] = "<a data-fancybox data-type='iframe' href='/media/static/biller.php'>{$text}</a>";
  }
  
  if($_finalPrice >= $billink_minimum && $_finalPrice <= $billink_maximum) {
    $text = "Betaal <strong>achteraf</strong> met Billink of AfterPay";
    $payment_methods_texts[] = "<a data-fancybox data-type='iframe' href='/media/static/billink.php'>{$text}</a>";
  }

  if($_finalPrice >= $in3_minimum && $_finalPrice <= $in3_maximum) {    
    if($this->hasOptions()) {
      $text = "Betaal in <strong>3 termijnen</strong> met In3";
    } else {
      $payment = number_format($_finalPrice / 3, 2, ",", ".");
      $payment = str_replace(",00", ",-", $payment);
      $text = "<strong>3 termijnen</strong> van €{$payment} zonder rente met In3";
    }
    $payment_methods_texts[] = "<a data-fancybox data-type='iframe' href='/media/static/in3.php'>{$text}</a>";
  }
  
  if(empty($payment_methods_texts) === false) {
    $payment_methods_content = "<ul class='fa-ul'>";
    foreach($payment_methods_texts as $text) {
      $payment_methods_content .= "<li class='my-1'><i class='fa-li fa fa-info-circle'></i>{$text}</li>";
    }
    $payment_methods_content .= "</ul>";
    $payment_methods_content = "<h4 class='black mt-3'>Betaalbaar voor iedereen!</h4>{$payment_methods_content}";
  }
}

// Buyblock EOL text
if($overall_stock_status === "eol") {
  $eol_text = "Wij helpen u graag met het vinden van een geschikt vervangend product.";
  if(empty($eol_replacement_sku) === false) {
    $replacement_product = Mage::getModel('catalog/product')->loadByAttribute('sku', $eol_replacement_sku);
    if($replacement_product !== false) {
      $name             = $_helper->productAttribute($replacement_product, $replacement_product->getName(), 'name');
      $url              = Mage::helper("deheerhoreca_util/util")->getFullProductUrlSafe($replacement_product);
      $eol_text         = "<strong>Kijkt u naar het vervangend product:</strong><br /><a href='{$url}'>{$name}</a>";
    }
  }
}

// Product Documents (uploaded & external)
$suppliers_external_docs_preferred = ["bartscher", "combiSteel", "diamond", "domest", "gastro-Inox", "gastronoble", "emga", "hendi", "saro", "scancool"];
$suppliers_external_docs_blocked = []; // case-sensitive

if(in_array($supplier_name, $suppliers_external_docs_blocked) === false) {
  // @todo something strange is going on -- external_documents_json is not part of the product after loading
  $external_documents_json = Mage::getResourceModel("catalog/product")->getAttributeRawValue($_product->getId(), "external_documents_json", $_store->getId());

  if(empty($external_documents_json) === true || in_array(strtolower($supplier_name), $suppliers_external_docs_preferred) === false) {
    $files = Mage::getModel("staempfli_productattachment/file")
      ->getFilesByProductId($this->getProduct()->getId(), Mage::app()->getStore()->getStoreId(), false, true)
      ->getData();
    
    if(empty($files) === false) {
      $external_documents_json = "";
    }
  }
} else {
  $external_documents_json = "";
}

// Energy Label -- only certain values are shown as a product label
if(empty($energy_rating) === false) {
  $enclz = null;
  switch($energy_rating) {
    case "A":     $enclz = "enrgclz1";  break;
    case "B":     $enclz = "enrgclz2";  break;
    case "C":     $enclz = "enrgclz3";  break;
    case "D":     $enclz = "enrgclz4";  break;
    case "E":     $enclz = "enrgclz5";  break;
  }
}

// Product USPs
$highlights = [];
$i = 0;

$dimension_pair_set = false;
if($i < $max_highlighted_attributes) {
  $id = "dimensions";
  $attribute_names = ["breedte", "diepte", "hoogte"];
  $image = "{$skn}frontend/rwd/dhh/images/measurement.svg";
  $title = "Afmetingen (b x d x h)";
  $name  = "Afmetingen";
  foreach($attribute_names as $attribute_name) {
    $values[$attribute_name] = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
    if(empty($values[$attribute_name]) === false) {
      $values[$attribute_name] = (int) ($values[$attribute_name] / 10);
    } else {
      unset($values[$attribute_name]);
    }
  }
  if(sizeof($values) === sizeof($attribute_names)) {
    $text = implode("x", $values)." cm";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
      "name"  => $name,
    ];
    $i++;
    $dimension_pair_set = true;
  }
}

if($dimension_pair_set !== true && $i < $max_highlighted_attributes) {
  $attribute_names = ["breedte", "hoogte"];
  $image = "{$skn}frontend/rwd/dhh/images/measurement.svg";
  $title = "Afmetingen (b x l)";
  foreach($attribute_names as $attribute_name) {
    $values[$attribute_name] = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
    if(empty($values[$attribute_name]) === false) {
      $values[$attribute_name] = (int) ($values[$attribute_name] / 10);
    } else {
      unset($values[$attribute_name]);
    }
  }
  if(sizeof($values) === sizeof($attribute_names)) {
    $text = implode("x", $values)." cm";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "diameter";
  $image = "{$skn}frontend/rwd/dhh/images/diameter.svg";
  $title = "Diameter";
  $text = (int) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => "{$text} mm",
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "afsluitbaar";
  $image = "{$skn}frontend/rwd/dhh/images/key.svg";
  $title = "Afsluitbaar";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if($text === "Ja") {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
      "name"  => $title,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "size";
  $image = "{$skn}frontend/rwd/dhh/images/size.svg";
  $title = "Maat";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if($text === "Ja") {
    $text = "Afsluitbaar";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "type_koeling";
  $image = "{$skn}frontend/rwd/dhh/images/forced_cooling.svg";
  $title = "Koelmethode";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if($text === "Geforceerd" OR $text === "Recirculatie" OR $text === "Statisch met ventilator") {
    $text = "{$text}";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "inhoud_liters";
  $image = "{$skn}frontend/rwd/dhh/images/liters.svg";
  $title = "Inhoud";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $text = round($text, 2)." liter";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $image = "{$skn}frontend/rwd/dhh/images/freezer.svg";
  $title = "Ontdooisysteem";
  if($nofrost_method === "Automatisch") {
    $nofrost_method = "Auto defrost";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "aantal_roosters";
  $image = "{$skn}frontend/rwd/dhh/images/shelf.svg";
  $title = "Roosters";
  $text = (int) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $text = "{$text}";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "garantie";
  $image = "{$skn}frontend/rwd/dhh/images/guarantee.svg";
  $title = "Garantie";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text !== "12 maanden") {
    $text = "{$text}";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "vermogen";
  $image = "{$skn}frontend/rwd/dhh/images/watt.svg";
  $title = "Vermogen";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    if(ctype_alnum($text) || is_numeric($text)) {
      $text = str_replace(",", ".", $text);
      $text = (double) $text;
      if($text < 3) {
        $text = (int) ($text * 1000)." W";
      } else {
        $text = number_format($text, 1, ",", ".");
        $text = str_replace(",0", null, $text);
        $text = "{$text} kW";
      }
    } else {
      // For non-numbers like "2 x 3"
    }
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $code   = "voltage";
  $image  = "{$skn}frontend/rwd/dhh/images/volt.svg";
  $title  = "Voltage";
  $text   = $_product->getResource()->getAttribute($code)->getFrontend()->getValue($_product);
  if(empty($text) === false && strtolower($text) !== "n.v.t.") {
    $highlights[] = [
      "image"   => $image,
      "title"   => $title,
      "text"    => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "aantal_omwentelingen_minuut";
  $image = "{$skn}frontend/rwd/dhh/images/rpm.svg";
  $title = "RPM";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $text = "{$text}";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "vermogen_kw";
  $image = "{$skn}frontend/rwd/dhh/images/flame.svg";
  $title = "Vermogen (gas)";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $text = number_format($text, 1, ",", ".");
    $text = str_replace(",0", null, $text);
    if(strstr(strtolower($text), "V") === false) {
      $text = "{$text} kW";
    }
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "geluidsniveau";
  $image = "{$skn}frontend/rwd/dhh/images/quiet.svg";
  $title = "Stil apparaat";
  $text = (int) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text < 50) {
    $text = "{$text} dB";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "verlichting";
  $image = "{$skn}frontend/rwd/dhh/images/light.svg";
  $title = "Verlichting";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text === "Ja") {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
      "name"  => $title,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "aantal_flessen";
  $image = "{$skn}frontend/rwd/dhh/images/wine.svg";
  $title = "Flesjes";
  $text = (int) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text !== "Nee") {
    $text = "{$text} X";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "capacity_wine_bottles";
  $image = "{$skn}frontend/rwd/dhh/images/wine.svg";
  $title = "Aantal 75cl Wijnflessen";
  $text = (int) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text !== "Nee") {
    $text = "{$text} x 75cl.";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "cooking_zones";
  $image = "{$skn}frontend/rwd/dhh/images/stove.svg";
  $title = "Kookzones";
  $text = (int) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text !== "Nee") {
    $text = "{$text} X";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "glas";
  $image = "{$skn}frontend/rwd/dhh/images/doubleglass.svg";
  $title = "Dubbel glas";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if($text === "dubbel glas") {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "refrigerant";
  $image = "{$skn}frontend/rwd/dhh/images/refrigerant.svg";
  $title = "Koelmiddel";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text ) === false) {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "eenheid";
  $image = "{$skn}frontend/rwd/dhh/images/amount.svg";
  $title = "Verpakkingseenheid";
  $text = (double) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text > 1) {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text." stuks",
    ];
    $i++;
  }
}

$hlstr = null;
foreach($highlights as $key => $highlight) {
  $name = $highlight["name"] ?? $highlight["title"];
  $hlstr .= "<li><span class='key small gray mb-1'>{$name}:</span><img class='lazy no-transition' id='hl-{$key}' data-src='{$highlight["image"]}' title='{$highlight["title"]}' /><span class='value'>{$highlight["text"]}</span></li>";
}

/* Impossible to influence the cross sell query, so filtering out EOLs afterwards */
$_crossSellProducts = $_product->getCrossSellProducts();
foreach($_crossSellProducts as $key => $_crossSellProduct) {
  // print_r($_crossSellProduct->getId());
  
  $cross_sell_product = Mage::getModel('catalog/product')->load($_crossSellProduct->getId());
  if($cross_sell_product->getAttributeText("eol") === "Ja") {
    unset($_crossSellProducts[$key]);
  } else {
    $_crossSellProducts[$key] = $cross_sell_product;
  }
}

$additional_attributes = $_product->getData("additional_attributes");
$additional_attributes = Mage::helper("deheerhoreca_util/util")->markdownExtraToHtml($additional_attributes);

/** PRODUCT DESCRIPTION **/

/* Configurable products only */
if($saleable === true && $this->hasOptions()) {
  $product_description .= "<h3>Varianten</h3>";
  $product_description .= "<p class='py-0'>De {$product_title_short} kent meerdere varianten. Configureer het product eenvoudig voordat je het koopt.</p>";
  $product_description .= _print_configurable_table($_product);
}

if(strlen($product_description_md) > 0) {
  $product_description .= Mage::helper("deheerhoreca_util/util")->markdownToHtmlSafe($product_description_md);
} else {
  $product_description .= $_product->getResource()->getAttribute("supplier_description")->getFrontend()->getValue($_product);
}

if(strtolower($nofrost_method) === 'Automatisch') {
  $product_description .= '<div class="std">'.$this->getLayout()->createBlock('cms/block')->setBlockId('productpage_ontdooisysteem_automatisch')->toHtml().'</div>';
}

$code = "voltage";
$text = $_product->getResource()->getAttribute($code)->getFrontend()->getValue($_product);
if($text === "400") {
  $product_description .= '<div class="std">'.$this->getLayout()->createBlock('cms/block')->setBlockId('productpage_aansluitspanning_400')->toHtml().'</div>';
}

$attributekoelmiddel = $_product->getResource()->getAttribute('refrigerant');
$attribute_valuekoelmiddel = $attributekoelmiddel->getFrontend()->getValue($_product);
if($attribute_valuekoelmiddel === "R290") {
  $product_description .= '<div class="std">'.$this->getLayout()->createBlock('cms/block')->setBlockId('productpage_koelmiddel_r290')->toHtml().'</div>';
}

// if(empty($_crossSellProducts) === false) {
  // $product_description .= "<p class='py-2'>De {$product_title_short} heeft één of meer door de leverancier <a href='#accessoires'>geselecteerde accessoires en/of verbruiksproducten.</a></p>";
// }

if(strlen($product_description) === 0) {
  $product_description = "&nbsp;";
}

/** PRODUCT LINKS **/

$related_products_block = $this->getChildHtml("related_products");
$product_additional_data_block = $this->getChildHtml("product_additional_data");
$alternative_products_block = $this->getChildHtml("upsell_products");
if(empty($alternative_products_block) === true) {
  $upsell_products_block = $this->getLayout()->createBlock('awautorelated/blocks')->setBlockId(1)->toHtml();
}

/** ANCHOR LINKS **/

// $anchors["photos"] = "Foto's";
if(empty($pvideo) === false)                        $anchors["video"]               = "Productvideo";
if(strlen($product_description) > 10)               $anchors["description"]         = "Productbeschrijving";
if(empty($_crossSellProducts) === false)            $anchors["accessoires"]         = "Opties & Accessoires";
if(empty($alternative_products_block) === false)    $anchors["alternatives"]        = "Alternatieven";
if(empty($product_additional_data_block) === false) $anchors["specs"]               = "Specificaties";
if(strlen($additional_attributes) > 10)             $anchors["additional"]          = "Extra Productinformatie";
if(empty($files) === false)                         $anchors["documents"]           = "Documantatie";
if(empty($external_documents_json) === false)       $anchors["external-documents"]  = "Externe Documentatie";
if(empty($upsell_products_block) === false)         $anchors["upsells"]             = "Bekijk Ook";
if(empty($related_products_block) === false)        $anchors["related"]             = "Gerelateerde Producten";

/** CALCULATED/DERIVED FIELDS **/

// If the backorder is expected to take >= 7 days, and we have alternatives, make a shoutout
if($stock_data["overall_stock_status"] === "backorder"
&& empty($stock_data["stock_date_days_left"]) === false
&& $stock_data["stock_date_days_left"] >= 7
&& empty($shoutout) === true) {
  $shoutout = "Alternatieven beschikbaar";
}

/** START RENDERING **/

?>
<script>var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view">
  
  <?php /* PRODUCT IMAGES */ ?>
  
  <div class="proleftdv">
  
  <div class="product-name clearfix">
    <h1><?php echo $productTitle; ?></h1>
    <div class="float-left" style="margin-right:2em;">
      <a href="<?php echo $brand_link; ?>"><?php echo $brand_name; ?></a>
    </div>
    <?php echo $this->getReviewsSummaryHtml($_product, "short", false); ?>
  </div>
  
    <div class="product-img-box">
      <span class="anchor" id="photos"></span>
      <?php
        // Product label
        if(empty($shoutout) === false) {
          echo "<span class='lblprolistviewpg'>{$shoutout}</span>";
        }
        
        // Black friday
        // if($overall_stock_status === "in_stock" || $overall_stock_status === "backorder") {
          // echo "<span class='bf-banner-detail'></span>";
        // }
        
        // Package quantity
        $package_quantity = (int) $_product->getData("eenheid");
        if($package_quantity > 1) {
          echo "<span class='product-label-right bg-blue bit-bigger'>{$package_quantity} X</span>";
        }
        
        // Energy rating
        if(empty($enclz) === false) {
          echo "<span class='lblenergylabel {$enclz}' title='Energielabel {$enclz}'>{$energy_rating}</span>";
        }
        
        echo $this->getChildHtml("media");
      ?>
    </div>
  </div>
  
  <div class="product-essential">
    <div id="sticky-container">
      <div class="product-shop">
        
        <?php /* Add to Cart Block */ ?>
        
        <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
          <?php echo $this->getBlockHtml('formkey') ?>
          <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
          <input type="hidden" name="related_product" id="related-products-field" value="" />
          <div class="prodetailtopright">
            
            <?php
            echo $this->getChildHtml("alert_urls");
            echo $this->getChildHtml("other");
            ?>
            <div class="add-to-cart-wrapper">
              <?php
              
              // Configurable products
              
              if($saleable === true && $this->hasOptions()) {
                echo $this->getChildChildHtml('container1', '', true, true);
                ?>
                <div class="add-to-box">
                  <div class="price-info">
                    <?php
                      // The _clone version needs to be present for JS update to work, but we don't want it shown
                      echo "<div style='display:none;'>";
                      echo $this->getlayout()->createBlock('catalog/product_view')->setTemplate('catalog/product/view/price_clone.phtml')->toHtml();
                      echo "</div>";
                      echo $this->getPriceHtml($_product);
                      echo $this->getChildHtml("bundle_prices");
                      echo $this->getTierPriceHtml();
                    ?>
                  </div>
                  <?php
                  echo $buyblock_free_delivery_content;
                  echo $this->getChildHtml("addtocart");
                  echo $this->getChildHtml("addto");
                  ?>
                </div>
                
                <?php                
                if($eol === true) {
                  echo "<div>Dit product is helaas niet meer leverbaar.</div>";
                  if(empty($eol_text) !== true) {
                    echo "<div class=eol_text>{$eol_text}</div>";
                  }
                }
                if(empty($delivery_text) !== true) {
                  echo "<div class='clzdelvlb'><span class='delivery-logo'>&nbsp;</span>{$delivery_text}</div>";
                }
                
                echo $our_usps_content;
                echo $payment_methods_content;
                echo $help_content;
                
                echo $this->getChildHtml("extra_buttons");
              }
              
              // All products
              
              echo $this->getChildHtml("product_type_data");
              echo $this->getChildHtml("extrahint");
              
              // Non-configurable products
              
              if(!$this->hasOptions()) {
                ?>
                <div class="add-to-box">
                  <div class="price-info">
                    <?php
                      echo $this->getPriceHtml($_product);
                      echo $this->getChildHtml("bundle_prices");
                      echo $this->getTierPriceHtml();
                    ?>
                  </div>
                  <?php
                  echo "<div class='{$txtcltcz}'>{$stock_message}{$stock_message_tooltip}</div>";
                  echo $buyblock_free_delivery_content;
                  echo "<ul class='fa-ul'>";
                  if(empty($delivery_li) !== true) {
                    echo $delivery_li;
                  }
                  if(empty($moq_li) !== true) {
                    echo $moq_li;
                  }
                  if(empty($qs_content) !== true) {
                    echo $qs_content;
                  }
                  echo "</ul>";
                  echo $this->getChildHtml("addtocart");
                  echo $this->getChildHtml("addto");
                  ?>
                </div>
                <?php
                if($eol === true) {
                  if(empty($eol_text) !== true) {
                    echo "<div class=eol_text>{$eol_text}</div>";
                  }
                }
                
                echo $our_usps_content;
                echo $payment_methods_content;
                echo $help_content;
                echo $this->getChildHtml("extra_buttons");
              
              // Non-sellable products
              
              } elseif($saleable === false) {
                ?>
                <div class="add-to-box">
                  <div class="price-info">
                    <?php
                    echo $this->getChildHtml("addto");
                    echo $help_content;
                    ?>
                  </div>
                </div>
                <?php
              }              
              echo $this->getChildHtml("sharing");              
              // if($_product->getFinalPrice() < 150 && strtolower($supplier_name) === "gastronoble") {
                // echo "<p>Deze leverancier heeft het momenteel extra druk door COVID-19, het kan zijn dat uw levertijd wordt gehaald, maar het kan ook iets uitlopen.</p>";
              // }
              ?>
            </div>
            
            <?php
            if(sizeof($anchors) > 2) {
              ?>
              <div class="add-to-cart-wrapper">
                <?php
                echo "<strong>Navigatie:</strong>";
                echo "<ul class='internal-product-nav disc-list'>";
                foreach($anchors as $key => $anchor) {
                  echo "<li><a href='#{$key}'>{$anchor}</a></li>";
                }
                echo "</ul>";
                
                if(empty($categoryUrl) === false && empty($categoryName) === false) {
                  $categoryName = str_ireplace("[V] ", null, $categoryName);
                  echo "<small>Of ga naar alle <a href='{$categoryUrl}'>{$categoryName}</a></small>";
                }
                ?>
              </div>
              <?php
            }
            ?>
            
          </div>
        </form>
        <?php
        
        // Configurable products
        if($saleable === true && $this->hasOptions()) {
          echo $this->getChildChildHtml("container2", "", true, true);
        }
        ?>
      </div>
    </div>
  </div>
  
  <div class="proleftdv">
    <?php  
    
    /* Product USPs */ ?>    
    <?php
    if(empty($hlstr) === false) {
      ?>
      <div class="my-3 py-1 pt-1 product-highlight-box">
        <span class="anchor" id="highlights"></span>
        <div class="content center">
          <?php echo "<ul class='product-highlights'>{$hlstr}</ul>"; ?>
        </div>
      </div>
      <?php
    }
    
    /* Product Tagline */
    if(empty($tagline) === false) {
      echo "<div class='product-detail-tagline px-2 py-1 my-2'>{$tagline}</div>";
    }

    /* Product Video */
    if(empty($pvideo) === false) {
      if(strstr("http", $pvideo) === false) {
        // Best way is to just store the youtube ID and build the URL
        $pvideo = "https://www.youtube-nocookie.com/embed/{$pvideo}?modestbranding=1&origin=https://www.chefstore.nl&loop=1&rel=1&hl=nl&controls=1";
      }
      ?>
      <div class="py-1">
        <span class="anchor" id="video"></span>
        <div class="content center">
          <iframe class="lazy" width="534" height="300" data-src="<?php echo $pvideo; ?>" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen style='border:0;max-width:100%;'></iframe>
        </div>
      </div>
      <?php
    }

    /* Product Description */
    if(strlen($product_description) > 10) {
      ?>
      <div class="py-1 std justify" id="product-detail-description">
        <span class="anchor" id="description"></span>
        <?php echo $product_description; ?>
      </div>
      <?php
    }

    /* Cross Sell Products */
    if(empty($_crossSellProducts) === false) { ?>
      <div class="probottomdv">
        <div class="topproducts_containter">
          <span class="anchor" id="accessoires"></span>
          <h2 class="tableftheader">Opties & Accessoires</h2>
          <?php
          $_columnCount = 4;
          $i = 0;
          ?>
          <div class="crosssell product-collateral category-products">
            <?php
            echo "<ul class='products-grid products-grid-mini'>";
              foreach($_crossSellProducts as $_product) {
                $i++;
                ?>
                <li class="item<?php if(($i-1) % $_columnCount == 0): ?> first<?php elseif($i % $_columnCount == 0): ?> last<?php endif; ?>">
                  <?php
                  $options = [
                    "skip_usps"             => false,
                    "skip_info"             => true,
                    "display"               => "mini",
                    "image_size"            => 100,
                    "_blank"                => true,
                    "prefer_rewrite_table"  => true, // Otherwise, getting ugly urls
                  ];
                  echo Mage::helper("deheerhoreca_util/util")->getProductGridHtml($_product, $this, $options);
                echo "</li>";
              }
              ?>
            </ul></div>
          <div class="clearer"></div>
        </div>
      </div>
      <?php
    }
    
    /* Alternatives */
    if(empty($alternative_products_block) === false) {
      ?>
      <span class="anchor" id="alternatives"></span>
      <div class="probottomdv">
        <?php echo $alternative_products_block; ?>
      </div>
      <?php
    }
    
    /* Product Attributes */
    if(empty($product_additional_data_block) === false) {
      ?>
      <div class="probottomdv">
        <span class="anchor" id="specs"></span>
        <div id="product_additional_data">
          <?php echo $product_additional_data_block ?>
        </div>
      </div>
      <?php
    }
    
    /* Additional Product Attributes */
    if(strlen($additional_attributes) > 10) {
      ?>
      <h2 class="tableftheader"><?php echo $this->__("Extra productinformatie");?></h2>
      <div class="probottomdv content product-specs" id="additional-attributes">
        <span class="anchor" id="additional"></span>
        <div class="std"><?php echo $additional_attributes; ?>
          <dl class="hidden"><dt>Source</dt><dd>https://www.chefstore.nl</dd></dl>
        </div>
      </div>
    <?php
    }
    ?>

    <?php /* Documents */ ?>
    <?php
    if(empty($files) === false) {
      $helper = $this->helper("staempfli_productattachment");
      $upload_dir = Mage::getBaseUrl("media").$helper::UPLOAD_DIR;
      ?>
      <div class="leftbranddv">
        <h2 class="tableftheader"><?php echo $this->__("Documenten");?></h2>
        <div class="probottomdv" id="product-documents-list">
          <span class="anchor" id="documents"></span>
          <ul class="fa-ul">
            <?php
            foreach($files as $document) {
              if(empty($document["path"])) {
                continue;
              }
              $url      = "{$upload_dir}/{$document['path']}";
              $name     = $document["title"]    ?? ($document["filename"] ?? "-");
              $filetype = $document["type"]     ?? null;
              switch($filetype) {
                case "pdf":   $fa_icon  = "fa-file-pdf-o";  break;
                default:      $fa_icon  = "fa-file-o";      break;
              }
              echo "<li style='line-height:2.5em;'>";
              echo "<a title='{$url}' class='document-link' href='{$url}' target='_blank' ><i class='fa-li fa {$fa_icon}' style='line-height:2.5em;'></i>{$name}</a>";
              echo "</li>";
            }
            ?>
          </ul>
          
        </div>
      </div>
      <?php
    }
    ?>
    
    <?php /* External Documents */ ?>
    <?php
    if(empty($external_documents_json) === false) {
      $external_documents = json_decode($external_documents_json, true);
      // printr($external_document);
      ?>
      <div class="leftbranddv">
        <h2 class="tableftheader"><?php echo $this->__("Externe Documenten");?></h2>
        <div class="probottomdv" id="product-external-documents-list">
          <span class="anchor" id="external-documents"></span>
          <ul class="fa-ul">
            <?php
            $method = "aes128";
            $iv = str_repeat("a", openssl_cipher_iv_length($method));
            
            foreach($external_documents as $external_document) {
              if(empty($external_document["url"])) {
                continue;
              }
              $url            = $external_document["url"];
              $url_encrypted  = "/file.php?id=".base64_encode(openssl_encrypt($url, $method, "wijdelengeenurls", 0, $iv));
              // $url            = openssl_decrypt($url_encrypted, $method, "wijdelengeenurls", 0, $iv);
              $name           = $external_document["title"]     ?? $external_document["url"];
              $filetype       = $external_document["filetype"]  ?? null;
              $language       = $external_document["language"]      ?? null;
              switch($filetype) {
                case "pdf":   $fa_icon  = "fa-file-pdf-o";  break;
                default:      $fa_icon  = "fa-file-o";      break;
              }
              if(empty($language) === false) {
                if(is_scalar($language)) {
                  $language = " (".strtoupper($language).")";
                } elseif(is_array($language)) {
                  $language = array_map("strtoupper", $language);
                  $language = " (".implode(", ", $language).")";
                }
              }
              echo "<li style='line-height:2.5em;'>";
              echo "<a title='{$name}' class='document-link' href='{$url_encrypted}' target='_blank' ><i class='fa-li fa {$fa_icon}' style='line-height:2.5em;'></i>{$name}{$language}<i style='margin-left: 5px; font-size: 80%; vertical-align: super;' class='fa fa-external-link' aria-hidden='true'></i></a>".PHP_EOL;
              echo "</li>";
            }
            ?>
          </ul>
        </div>
      </div>
      <?php
    }
    ?>

    <?php /* Automatic Related Products */ ?>

    <?php
    if(empty($upsell_products_block) === false) {
      ?>
      <span class="anchor" id="upsells"></span>
      <div class="probottomdv">
        <?php echo $upsell_products_block; ?>
      </div>
      <?php
    }
    ?>
    
    <?php /* Related Products */ ?>
    
    <?php
    if(empty($related_products_block) === false) {
      ?>
      <span class="anchor" id="related"></span>
      <div class="probottomdv">
        <?php echo $related_products_block; ?>
      </div>
      <?php
    }
    ?>
    
    <?php /* Brand Logo & Text */ ?>
      
    <div class="probottomdv" id="product-brand-text">
      <?php
      if(strlen($htbrand) > 10) { //sometimes it's just &nbsp;
        ?>
        <span class="anchor" id="brand"></span>
        <h3 class="tableftheader">Over <?php echo $brand_name; ?></h3>
        <div class="brand std justify"><?php echo $htbrand; ?></div>
        <?php
      }
      if(empty($brand_logo) === false) {
        echo "<div class='center'>";
        echo "<a target='_blank' title='{$brand_name}' href='/{$brand_link}'>";
        echo "<img class='lazy' alt='".ucfirst($brand)." logo' title='".ucfirst($brand)."' id='brand_logo_small' src='{$brand_logo}' /></a></div>";
      }
      ?>
    </div>
  </div>
</div>

<script>
  //<![CDATA[
  var productAddToCartForm = new VarienForm('product_addtocart_form');
  productAddToCartForm.submit = function(button, url) {
    if (this.validator.validate()) {
      var form = this.form;
      var oldUrl = form.action;

      if (url) {
         form.action = url;
      }
      var e = null;
      try {
          this.form.submit();
      } catch (e) {
      }
      this.form.action = oldUrl;
      if (e) {
          throw e;
      }

      if (button && button != 'undefined') {
          button.disabled = true;
      }
    }
  }.bind(productAddToCartForm);

  productAddToCartForm.submitLight = function(button, url){
    if(this.validator) {
      var nv = Validation.methods;
      delete Validation.methods['required-entry'];
      delete Validation.methods['validate-one-required'];
      delete Validation.methods['validate-one-required-by-name'];
      // Remove custom datetime validators
      for (var methodName in Validation.methods) {
        if (methodName.match(/^validate-datetime-.*/i)) {
          delete Validation.methods[methodName];
        }
      }
      if (this.validator.validate()) {
        if (url) {
            this.form.action = url;
        }
        this.form.submit();
      }
      Object.extend(Validation.methods, nv);
    }
  }.bind(productAddToCartForm);
  //]]>
</script>

<?php
if(function_exists("sanitizeForFilename") === false) {
  function sanitizeForFilename($string) {
    $output = mb_ereg_replace("([^\w\s\d\-_~,;\[\]\(\).])", '', $string);
    $output = mb_ereg_replace("([\.]{2,})", '', $string);
    return strtolower($output);
  }
}


/*
if($_SERVER["REMOTE_ADDR"] === "185.127.111.251") {
  echo "<pre>";
  var_dump($used_conf_attributes);
  echo "</pre>";
}
*/

function _print_configurable_table($_product) {
  $children = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null, $_product);
  $table = [];
  
  // Get a list of attributes that are used in this configurable product
  $_attributes = $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product);
  $used_conf_attributes = [];
  foreach($_attributes as $_attribute) {
    $used_conf_attributes[$_attribute["label"]] = $_attribute["attribute_code"];
  }
  
  foreach ($children as $_child) {
    $stock_data = Mage::helper("deheerhoreca_util/util")->getStockInfo($_child);
    $row = ["SKU" => $_child->getSku()];
    foreach($used_conf_attributes as $label => $code) {
      $row[$label] = $_child->getAttributeText($code);
    }
    $row["Voorraad"] = "<div class='{$stock_data['txtcltcz']}'>{$stock_data["stock_message"]}</div>";
    $table[] = $row;
  }
  
  return html_table($table);
}

function html_table(array $data): string {  
  if(sizeof($data) === 0) return "";
  
  $rows = $cells = [];
  
  $cols = array_keys(array_slice($data, 0, 1)[0]);
  
  foreach($cols as $col) {
    $cells[] = "<th>{$col}</th>";
  }
  $head = "<tr>" . implode('', $cells) . "</tr>";
  
  foreach ($data as $row) {
    $cells = [];
    foreach ($row as $cell) {
      $cells[] = "<td>{$cell}</td>";
    }
    $rows[] = "<tr>" . implode('', $cells) . "</tr>";
  }
  return "<table class='table table-striped table-border'><thead>{$head}</thead><tbody>" . implode('', $rows) . "</tbody></table>";
}
