<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */

 use Carbon\CarbonImmutable;

$_product                   = $this->getProduct();
$_helper                    = $this->helper("catalog/output");
$sku                        = _get_product_attribute($_product, "sku");
$_store                     = $_product->getStore();
$_taxHelper                 = $this->helper("tax");
$categoryIds                = $_product->getCategoryIds();
$skin                       = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);

$brand_name                 = _get_product_attribute($_product, "manufacturer");
$brand_id                   = $_product->getData("manufacturer");
$brand_logo                 = "";
$brand_slug                 = Mage::helper("deheerhoreca_util/util")->getBrandUrlSlug($brand_name);
$seo_tag                    = Mage::helper("deheerhoreca_util/util")->getUrlSlug($brand_name);
$brand_link                 = "/shop?manufacturer={$brand_id}&title={$seo_tag}";
$anchors                    = [];
$in3_minimum                = 50 / 1.21;
$in3_maximum                = 30000 / 1.21;
$billink_minimum            = 10;
$billink_maximum            = 3500;
$biller_minimum             = 25;
$biller_maximum             = 10000;
$mondu_pl_minimum           = 500;
$mondu_pl_maximum           = 10000;
$mondu_lease_minimum        = 750;
$mondu_lease_maximum        = 20000;
$grenke_lease_minimum       = 1000;
$grenke_lease_maximum       = 10000;
$show_black_friday          = false;
$javascripts                = [];
$brand_block_name           = "";
$brand                      = "";
$payment_methods_content    = "";
$max_highlighted_attributes = 12;

// Find the category this product belongs to
// @todo is this expensive?
if(empty($categoryIds) === false) {
  $_category              = Mage::getModel("catalog/category")->load($categoryIds[0]);
  $categoryUrl            = $_category->getUrl();
  $categoryName           = $_category->getName();
}

// Attributes used in multiple places
$productlabel           = _get_product_attribute($_product, "product_label");
$nofrost_method         = _get_product_attribute($_product, "ontdooisysteem");
$energy_rating          = _get_product_attribute($_product, "energy_efficiency_class_a_g");
if(empty($energy_rating) || $energy_rating === "N.v.t.") {
  $energy_rating          = _get_product_attribute($_product, "energieklasse");
}
$refrigerant            = _get_product_attribute($_product, "refrigerant");
$voltage                = _get_product_attribute($_product, "voltage");
$productTitle           = $_helper->productAttribute($_product, $_product->getName(), "name");
$subdescription         = _get_product_attribute($_product, "sub_description");
$product_title_short    = _get_product_attribute($_product, "name_short");
$pvideo                 = _get_product_attribute($_product, "product_video");
$tagline                = _get_product_attribute($_product, "tagline");
$supplier_name          = (string) _get_product_attribute($_product, "supplier");
$_price                 = $_product->getPrice(); // @todo is this used?
$_finalPrice            = $_product->getFinalPrice();
$product_description_md = trim((string) _get_product_attribute($_product, "description"));
$product_description    = "";

// Availability, Stock
$stock_data             = Mage::helper("deheerhoreca_util/util")->getStockInfo($_product);
$stock_message          = $stock_data["stock_message"];
$stock_tooltip          = $stock_data["stock_tooltip"];
$txtcltcz               = $stock_data["txtcltcz"];
$stock_qty              = $stock_data["stock_qty"];
$in_stock               = $stock_data["in_stock"];
$backorders             = $stock_data["backorders"];
$saleable               = $stock_data["saleable"];
$eol                    = $stock_data["eol"];
$manage_stock           = $stock_data["manage_stock"];
$extra_delivery_time    = $stock_data["extra_delivery_time"];
$overall_stock_status   = $stock_data["overall_stock_status"];
$txtstockdate           = $stock_data["txtstockdate"];
$levertijd              = $stock_data["levertijd"];
$levertijd_tmp_override = $stock_data["levertijd_tmp_override"];
$bestelartikel          = $stock_data["bestelartikel"]            ?? "";
$min_sale_qty           = $stock_data["min_sale_qty"];

// Fulfilment, Financials
$used_levertijd         = empty($levertijd_tmp_override) ? $levertijd : $levertijd_tmp_override;
$freeshipping_from      = (float) Mage::getStoreConfig("carriers/freeshipping/free_shipping_subtotal");
$_finalPriceInclTax     = $_taxHelper->getPrice($_product, $_finalPrice, true);

// Add +/- symbol to delivery time unless it's "op aanvraag"
if(stristr((string) $used_levertijd, "aanvraag") === false && $used_levertijd !== "1 werkdag" && empty($used_levertijd) === false) {
  $used_levertijd = "&plusmn; {$used_levertijd}";
}
if($used_levertijd === "1 werkdag") {
  $delivery_time_tooltip = "Op werkdagen voor 15:00 besteld, de volgende werkdag bezorgd. Het is in een enkel geval mogelijk dat door omstandigheden de bezorging vertraagd is. Natuurlijk houden we u altijd op de hoogte van de status van uw bestelling.";
} else {
  $delivery_time_tooltip = "We doen er alles aan om dit artikel op tijd te bezorgen. Het is in een enkel geval mogelijk dat door omstandigheden de bezorging vertraagd is. Natuurlijk houden we u altijd op de hoogte van de status van uw bestelling.";
}

/* BUYBLOCK CONTENT */

$buyblock_free_delivery_content = "";
$buyblock_free_delivery = false;

if($_finalPriceInclTax >= $freeshipping_from && $_product->isSaleable() === true && $overall_stock_status !== "eol") {
  $buyblock_free_delivery_content .= "<div class='buyblock-usp fw-normal'><strong class=green>Gratis</strong> verzending in NL en BE</div>";
  $buyblock_free_delivery = true;
}

// Stock level
$stock_message_tooltip = "";
if(empty($stock_tooltip) === false) {
  $stock_message_tooltip = "<span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='true'></i><span class='tooltiptext clztoptoolc'>{$stock_tooltip}</span></span>";
}

// Delivery time
$delivery_text = "";
if($bestelartikel === "Ja") {
  $delivery_text .= "Bestelartikel</strong><span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='true'></i><span class='tooltiptext clztoptoolc'>Dit artikel wordt op bestelling gemaakt en geleverd</span>";
} elseif($overall_stock_status === "not_sellable" || $overall_stock_status === "backorder" || $manage_stock === false) {
  if(empty($txtstockdate) === false) {
    $delivery_text .= "Verwacht: <strong>{$txtstockdate}</strong><span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='true'></i><span class='tooltiptext clztoptoolc'>Dit is de meest accurate inschatting die wij hebben. Door omstandigheden kan dit soms wijzigen.</span>";
  } elseif($manage_stock !== false) {
    $delivery_text .= "Levertijd op aanvraag<span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='true'></i><span class='tooltiptext clztoptoolc'>Spoedig weer op voorraad, maar wij hebben nog geen exacte datum. U kunt een pre-order plaatsen om het product zo snel mogelijk te krijgen.</span>";
  }
} elseif($overall_stock_status === "in_stock" && !empty($used_levertijd)) {
  $delivery_text .= "{$used_levertijd}<span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='false'></i> <span class='tooltiptext clztoptoolc'>{$delivery_time_tooltip}</span></span>";
}
if(empty($delivery_text) === false) {
  $delivery_li = "<li class='my-1'><i class='fa-li fa fa-clock-o'></i>{$delivery_text}</li>";
}

// MOQ content
$moq_li = "";
if(empty($min_sale_qty) !== true && $min_sale_qty > 1) {
  $moq_li = "<li class='my-1'><i class='fa-li fa fa-bars'></i>Ordergrootte vanaf <strong>{$min_sale_qty}</strong> stuks</li>";
}

// Qantity step content
$qs_content = "";
$qty_increments = $_product->getStockItem()->getQtyIncrements();
if($qty_increments > 0) {
  $qs_content = "<li class='my-1'><i class='fa-li fa fa-bars'></i>Wordt verkocht in stappen van <strong>".intval($qty_increments)."</strong> stuks</li>";
}

// Help content
$help_content = "<h4 class='black mt-3'>Hulp nodig?</h4><ul class='fa-ul'>
  <li class=my-1>
    <i class='fa-li fa fa-question'></i>
    <a class='glightbox4' data-gallery=q data-glightbox='effect:fade; width:600px;' href='//form.jotform.com/213136047906049?sku=".urlencode((string) $sku)."&product=".urlencode((string) $productTitle)."'>Stel een vraag</a>
  </li>
  <li class=my-1>
    <i class='fa-li fa fa-phone' title='Bellen'></i>
    <a class='glightbox4' data-gallery=c data-glightbox='effect:fade; width:600px;' href='/media/static/contact.php'>Contact opnemen</a>
  </li>
</ul>";

// Our USPs content
$our_usps = [
  "De beste prijzen",
  "Veilig online winkelen",
  "Klanten beoordelen ons met een <strong class=orange id=kiyoh_score></strong>",
  "We zitten klaar voor uw vragen",
];
$javascripts[] = "document.getElementById('kiyoh_score').innerHTML = kiyoh_score;";
if(empty($our_usps) === false) {
  $our_usps_content = "<ul class='fa-ul'>";
  foreach($our_usps as $text) {
    $our_usps_content .= "<li class='my-1'><i class='fa-li fa fa-check green'></i>{$text}</li>";
  }
  $our_usps_content .= "</ul>";
  $our_usps_content = "<h4 class='black mt-3'>Onze voordelen:</h4>{$our_usps_content}";
}

// Payment methods content
if($overall_stock_status === "in_stock" || $overall_stock_status === "backorder") {

  $payment_methods_texts  = [];

  // Lease
  if($_finalPrice >= $mondu_lease_minimum || $_finalPrice >= $grenke_lease_minimum) {
    $text = "Leasen tegen scherpe tarieven";
    $payment_methods_texts[] = "<a class='glightbox4' data-gallery=bnpl data-glightbox='effect:fade; width:600px;' href='/media/static/lease.php'>{$text}</a>";
  }

  // BNPL
  $bnpl_payment_methods   = [];  
  if($_finalPrice >= $mondu_pl_minimum && $_finalPrice <= $mondu_pl_maximum) {
    $bnpl_payment_methods[] = "Mondu";
  }  
  if($_finalPrice >= $biller_minimum && $_finalPrice <= $biller_maximum) {
    $bnpl_payment_methods[] = "Biller";
  }  
  if($_finalPrice >= $billink_minimum && $_finalPrice <= $billink_maximum) {
    $bnpl_payment_methods[] = "Billink";
  }
  if($bnpl_payment_methods !== []) {
    $text = "Betaal achteraf met ".implode(", ", $bnpl_payment_methods);
    $payment_methods_texts[] = "<a class='glightbox4' data-gallery=bnpl data-glightbox='effect:fade; width:600px;' href='/media/static/bnpl.php'>{$text}</a>";
  }

  if($_finalPrice >= $in3_minimum && $_finalPrice <= $in3_maximum) {    
    if($this->hasOptions()) {
      $text = "Betaal in <strong>3 termijnen</strong> met In3";
    } else {
      $payment = number_format($_finalPrice / 3, 2, ",", ".");
      $payment = str_replace(",00", ",-", $payment);
      $text = "Betaal in 3 termijnen van €{$payment} met In3";
    }
    $payment_methods_texts[] = "<a class='glightbox4' data-gallery=in3 data-glightbox='effect:fade; width:600px;' href='/media/static/in3.php'>{$text}</a>";
  }

  if(empty($payment_methods_texts) === false) {
    $payment_methods_content = "<ul class='fa-ul'>";
    foreach($payment_methods_texts as $text) {
      $payment_methods_content .= "<li class='my-1'><i class='fa-li fa fa-info-circle'></i>{$text}</li>";
    }
    $payment_methods_content .= "<li class='my-1'><i class='fa-li fa fa-info-circle'></i><a target='_blank' href='/tips-achteraf-betalen'>Lees alles over achteraf betalen</a></li>";
    $payment_methods_content .= "</ul>";
    $payment_methods_content = "<h4 class='black mt-3'>Betaalbaar voor iedereen!</h4>{$payment_methods_content}";
  }
}

// Buyblock EOL text
if($overall_stock_status === "eol") {
  Varien_Profiler::start("DHH_PRODUCT_DETAILVIEW_GET_EOL_REPLACEMENT_SKU");
  $eol_replacement_sku = $_product->getEolReplacementSku();
  $eol_text = "Wij helpen u graag met het vinden van een geschikt vervangend product.";
  if(empty($eol_replacement_sku) === false) {
    $_replacement_product = Mage::getResourceModel("catalog/product_collection")
      ->addFieldToFilter("sku", $eol_replacement_sku)
      ->addAttributeToSelect(["name"])
      ->addAttributeToFilter("status", ["in" => Mage_Catalog_Model_Product_Status::STATUS_ENABLED])
      ->addAttributeToFilter("visibility", ["in" => [Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH, Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG]])
      ->setPageSize(1)->getFirstItem();
    if(strlen((string) $_replacement_product->getName()) > 1) {
      $name         = _get_product_attribute($_replacement_product, "name");
      $url          = Mage::helper("deheerhoreca_util/util")->getFullProductUrlSafe($_replacement_product);
      $eol_text     = "<strong>Kijkt u naar het vervangend product:</strong><br /><a href='{$url}'>{$name}</a>";
    }
  }
  Varien_Profiler::stop("DHH_PRODUCT_DETAILVIEW_GET_EOL_REPLACEMENT_SKU");
}

// Product Documents (uploaded & external)
$suppliers_external_docs_preferred = ["bartscher", "combisteel", "diamond", "domest", "gastro-inox", "gastronoble", "emga", "hendi", "saro", "scancool", "veba"];
$suppliers_external_docs_blocked = []; // case-sensitive

if(in_array($supplier_name, $suppliers_external_docs_blocked) === false) {
  // @todo something strange is going on -- external_documents_json is not part of the product after loading
  $external_documents_json = Mage::getResourceModel("catalog/product")->getAttributeRawValue($_product->getId(), "external_documents_json", $_store->getId());

  if(empty($external_documents_json) === true || in_array(strtolower($supplier_name), $suppliers_external_docs_preferred) === false) {
    $files = Mage::getModel("staempfli_productattachment/file")
      ->getFilesByProductId($this->getProduct()->getId(), Mage::app()->getStore()->getStoreId(), false, true)
      ->getData();

    if(empty($files) === false) {
      $external_documents_json = "";
    }
  }
} else {
  $external_documents_json = "";
}

// Energy Label -- only certain values are shown as a product label
if(empty($energy_rating) === false) {
  $enclz = null;
  switch($energy_rating) {
    case "A":     $enclz = "enrgclz1";  break;
    case "B":     $enclz = "enrgclz2";  break;
    case "C":     $enclz = "enrgclz3";  break;
    case "D":     $enclz = "enrgclz4";  break;
    case "E":     $enclz = "enrgclz5";  break;
  }
}

/* Product USP icons */

$highlights = [];
$i          = 0;

// Combined dimensions
$dimension_pair_set = false;
if($i < $max_highlighted_attributes) {

  // Try Width + Depth + Height
  $codes  = ["breedte", "diepte", "hoogte"];
  $image  = "{$skin}frontend/rwd/dhh/images/measurement.svg";
  $title  = "Afmetingen (BxDxH)";
  $name   = "Afmetingen";
  $values = [];
  foreach($codes as $code) {
    $values[$code] = _get_product_attribute($_product, $code);
    if(empty($values[$code]) === false) {
      $values[$code] = (int) ($values[$code] / 10);
    } else {
      unset($values[$code]);
    }
  }
  if(sizeof($values) === sizeof($codes)) {
    $text = implode("x", $values)." cm";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
      "name"  => $name,
    ];
    $i++;
    $dimension_pair_set = true;
  }

  // Try Width + Height
  if($dimension_pair_set !== true && $i < $max_highlighted_attributes) {
    $codes  = ["breedte", "hoogte"];
    $image  = "{$skin}frontend/rwd/dhh/images/measurement.svg";
    $title  = "Afmetingen (BxL)";
    $values = [];
    foreach($codes as $code) {
      $values[$code] = _get_product_attribute($_product, $code);
      if(empty($values[$code]) === false) {
        $values[$code] = (int) ($values[$code] / 10);
      } else {
        unset($values[$code]);
      }
    }
    if(sizeof($values) === sizeof($codes)) {
      $text = implode("x", $values)." cm";
      $highlights[] = [
        "image" => $image,
        "title" => $title,
        "text"  => $text,
      ];
      $i++;
    }
  }

  // Try Width + Depth
  if($dimension_pair_set !== true && $i < $max_highlighted_attributes) {
    $codes  = ["breedte", "diepte"];
    $image  = "{$skin}frontend/rwd/dhh/images/measurement.svg";
    $title  = "Afmetingen (BxD)";
    $values = [];
    foreach($codes as $code) {
      $values[$code] = _get_product_attribute($_product, $code);
      if(empty($values[$code]) === false) {
        $values[$code] = (int) ($values[$code] / 10);
      } else {
        unset($values[$code]);
      }
    }
    if(sizeof($values) === sizeof($codes)) {
      $text = implode("x", $values)." cm";
      $highlights[] = [
        "image" => $image,
        "title" => $title,
        "text"  => $text,
      ];
      $i++;
    }
  }
}

// Diameter
if($i < $max_highlighted_attributes) {
  $code   = "diameter";
  $image  = "{$skin}frontend/rwd/dhh/images/diameter.svg";
  $title  = "Diameter";
  $text   = (int) $_product->getResource()->getAttribute($code)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => "{$text} mm",
    ];
    $i++;
  }
}

// Warranty
if($i < $max_highlighted_attributes) {
  $code   = "garantie";
  $image  = "{$skin}frontend/rwd/dhh/images/usps/guarantee.svg";
  $title  = "Garantie";
  $text   =  _get_product_attribute($_product, $code);
  if(empty($text) === false && $text !== "12 maanden") {
    $text = "{$text}";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Made in Europe
if($i < $max_highlighted_attributes) {
  $code         = "made_in_country_2code";
  $image        = "{$skin}frontend/rwd/dhh/images/usps/made_in_europe3.svg";
  $title        = "Made In";
  $value        = _get_product_attribute($_product, $code);
  $eu_countries = ["België", "Bulgarije", "Tsjechië", "Duitsland", "Denemarken",
    "Spanje", "Europese Unie", "Frankrijk", "Groot Brittanië", "Griekenland", 
    "Kroatië", "Hongarije", "Italië", "Litouwen", "Nederland", "Polen", "Portugal", "Malta",
    "Zweden", "Slovenië", "Slowakije", "Litouwen", "Oostenrijk", "Roemenië", "Cyprus",
    "Ierland", "Estland", "Finland",
  ];
  if(in_array($value, $eu_countries, true)) {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $value,
      "name"  => $title,
    ];
    $i++;
  }
}

// Lockable
if($i < $max_highlighted_attributes) {
  $code   = "afsluitbaar";
  $image  = "{$skin}frontend/rwd/dhh/images/key.svg";
  $title  = "Met Slot";
  $text   = _get_product_attribute($_product, $code);
  if($text === "Ja") {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
      "name"  => $title,
    ];
    $i++;
  }
}

// Size
if($i < $max_highlighted_attributes) {
  $code   = "size";
  $image  = "{$skin}frontend/rwd/dhh/images/size.svg";
  $title  = "Maat";
  $text   = _get_product_attribute($_product, $code);
  if($text === "Ja") {
    $text = "Afsluitbaar";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Cooling method
if($i < $max_highlighted_attributes) {
  $code   = "type_koeling";
  $image  = "{$skin}frontend/rwd/dhh/images/forced_cooling.svg";
  $title  = "Koelmethode";
  $text   = _get_product_attribute($_product, $code);
  if($text === "Geforceerd" OR $text === "Recirculatie" OR $text === "Statisch met ventilator") {
    $text = "{$text}";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Contents
if($i < $max_highlighted_attributes) {
  $code   = "inhoud_liters";
  $image  = "{$skin}frontend/rwd/dhh/images/liters.svg";
  $title  = "Inhoud";
  $text   = _get_product_attribute($_product, $code);
  if(empty($text) === false) {
    $text = round($text, 2)." liter";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Auto defrost
if($i < $max_highlighted_attributes) {
  if($nofrost_method === "Auto Defrost") {
    $highlights[] = [
      "image" => "{$skin}frontend/rwd/dhh/images/freezer.svg",
      "title" => "Ontdooisysteem",
      "text"  => $nofrost_method,
    ];
    $i++;
  }
}

// Number of shelves
if($i < $max_highlighted_attributes) {
  $code = "aantal_roosters";
  $image = "{$skin}frontend/rwd/dhh/images/shelf.svg";
  $title = "Roosters";
  $text = (int) _get_product_attribute($_product, $code);
  if(empty($text) === false) {
    $text = "{$text}";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Power (electrical)
if($i < $max_highlighted_attributes) {
  $code = "vermogen";
  $text = _get_product_attribute($_product, $code);
  $image = "{$skin}frontend/rwd/dhh/images/watt.svg";
  $title = "Vermogen (ELEK)";
  if(empty($text) === false) {
    if(ctype_alnum((string) $text) || is_numeric($text)) {
      $text = str_replace(",", ".", (string) $text);
      $text = (double) $text;
      if($text < 3) {
        $text = (int) ($text * 1000)." W";
      } else {
        $text = number_format($text, 1, ",", ".");
        $text = str_replace(",0", "", $text);
        $text = "{$text} kW";
      }
    } else {
      // For non-numbers like "2 x 3"
    }
    $highlights[] = [
      "image"   => $image,
      "title"   => $title,
      "text"    => $text,
    ];
    $i++;
  }
}

// Voltage
if($i < $max_highlighted_attributes) {
  $code   = "voltage";
  $value  = $voltage;
  $image  = "{$skin}frontend/rwd/dhh/images/volt.svg";
  $name   = "Voltage";
  $title  = "Voltage";
  if(is_array($value)) {
    $value = implode(", ", $value);
  }
  if((stripos((string) $value, "400") !== false)) {
    $title = "Let op: 400 volt apparaat";
  }
  if(empty($value) === false && strtolower((string) $value) !== "n.v.t.") {
    $highlights[] = [
      "image"   => $image,
      "name"    => $name,
      "title"   => $title,
      "text"    => $value,
    ];
    $i++;
  }
}

// Power (gas)
if($i < $max_highlighted_attributes) {
  $code   = "vermogen_kw";
  $image  = "{$skin}frontend/rwd/dhh/images/flame.svg";
  $title  = "Vermogen (GAS)";
  $text   = (float) _get_product_attribute($_product, $code);
  if($text > 0) {
    $text = number_format($text, 1, ",", ".");
    $text = str_replace(",0", "", $text);
    if(!str_contains(strtolower($text), "V")) {
      $text = "{$text} kW";
    }
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// RPM
if($i < $max_highlighted_attributes) {
  $code   = "aantal_omwentelingen_minuut";
  $image  = "{$skin}frontend/rwd/dhh/images/rpm.svg";
  $title  = "RPM";
  $text   = _get_product_attribute($_product, $code);
  if(empty($text) === false) {
    $text = "{$text}";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Sound level
if($i < $max_highlighted_attributes) {
  $code   = "geluidsniveau";
  $image  = "{$skin}frontend/rwd/dhh/images/quiet.svg";
  $title  = "Stil apparaat";
  $text   = (int) _get_product_attribute($_product, $code);
  if(empty($text) === false && $text < 50) {
    $text = "{$text} dB";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Lighting
if($i < $max_highlighted_attributes) {
  $code   = "verlichting";
  $image  = "{$skin}frontend/rwd/dhh/images/light.svg";
  $title  = "Verlichting";
  $text   = _get_product_attribute($_product, $code);
  if(empty($text) === false && $text === "Ja") {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
      "name"  => $title,
    ];
    $i++;
  }
}

// Capacity bottles
if($i < $max_highlighted_attributes) {
  $code   = "aantal_flessen";
  $image  = "{$skin}frontend/rwd/dhh/images/wine.svg";
  $title  = "Flesjes";
  $text   = (int) _get_product_attribute($_product, $code);
  if(empty($text) === false && $text !== 0) {
    $text = "{$text} X";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Capacity wine bottles
if($i < $max_highlighted_attributes) {
  $code   = "capacity_wine_bottles";
  $image  = "{$skin}frontend/rwd/dhh/images/wine.svg";
  $title  = "Aantal 75cl Wijnflessen";
  $text   = (int) _get_product_attribute($_product, $code);
  if(empty($text) === false && $text !== 0) {
    $text = "{$text} x 75cl.";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Capacity cooking zones
if($i < $max_highlighted_attributes) {
  $code   = "cooking_zones";
  $image  = "{$skin}frontend/rwd/dhh/images/stove.svg";
  $title  = "Kookzones";
  $text   = (int) _get_product_attribute($_product, $code);
  if(empty($text) === false && $text !== 0) {
    $text = "{$text} X";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Double glass
if($i < $max_highlighted_attributes) {
  $code   = "glas";
  $image  = "{$skin}frontend/rwd/dhh/images/doubleglass.svg";
  $title  = "Dubbelglas";
  $text   = _get_product_attribute($_product, $code);
  if($text === "dubbel glas") {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Refrigerant
if($i < $max_highlighted_attributes) {
  $code   = "refrigerant";
  $image  = "{$skin}frontend/rwd/dhh/images/refrigerant.svg";
  $title  = "Koelmiddel";
  $text   = $refrigerant;
  if(empty($text ) === false) {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Pallet transport
if($i < $max_highlighted_attributes) {
  $code   = "transport_type";
  $image  = "{$skin}frontend/rwd/dhh/images/usps/truck.svg";
  $name   = "Levering";
  $title  = "Wordt geleverd met een vrachtwagen";
  $value  = _get_product_attribute($_product, $code);
  $text   = "Palletvervoer";
  if($value === "Palletvervoer") {
    $highlights[] = [
      "image" => $image,
      "name"  => $name,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

// Product quantity
if($i < $max_highlighted_attributes) {
  $code   = "eenheid";
  $image  = "{$skin}frontend/rwd/dhh/images/amount.svg";
  $title  = "Aantal";
  $text   = (double) _get_product_attribute($_product, $code);
  if(empty($text) === false && $text > 1) {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text." stuks",
    ];
    $i++;
  }
}

$hlstr = null;
foreach($highlights as $key => $highlight) {
  $name = $highlight["name"] ?? $highlight["title"];
  if(empty($name) === false) $name .= ":";
  $hlstr .= "<li><span class='small gray mb-2'>{$name}</span><img class='no-transition' id='hl-{$key}' src='{$highlight["image"]}' title='{$highlight["title"]}' alt='{$highlight["title"]}' loading=lazy width=40 height=40><span class='value'>{$highlight["text"]}</span></li>".PHP_EOL;
}

// Retrieve cross sell product collection
Varien_Profiler::start("DHH_PRODUCT_DETAILVIEW_GET_CROSSSELL_SKUS");
$cross_sell_ids = $_product->getCrossSellProductIds();
if(sizeof($cross_sell_ids) > 0) {
  $_crossSellProducts = Mage::getResourceModel("catalog/product_collection")
   ->addAttributeToFilter("entity_id", ["in" => $cross_sell_ids])
   ->addAttributeToFilter("eol", ["neq" => 2075])
   ->addAttributeToSelect(DeHeerHoreca_Util_Helper_Util::getProductAttributes("listview"))
   ->setOrder("popularity", "ASC")
   ->load();
}
Varien_Profiler::stop("DHH_PRODUCT_DETAILVIEW_GET_CROSSSELL_SKUS");

$additional_attributes = Mage::helper("deheerhoreca_util/util")->markdownExtraToHtml($_product->getData("additional_attributes"));

/* PRODUCT DESCRIPTION */

// Configurable products: Print attribute/stock table
if($saleable === true && $_product->isConfigurable()) {
  $product_description .= "<h3>Varianten</h3>";
  $product_description .= "<p class='py-0'>De {$product_title_short} kent meerdere varianten. Configureer het product eenvoudig voordat je het koopt.</p>";
  $product_description .= _print_configurable_table($_product);
}

if(strlen($product_description_md) > 0) {
  $product_description .= Mage::helper("deheerhoreca_util/util")->markdownToHtmlSafe($product_description_md);
} else {
  $supplier_description = _get_product_attribute($_product, "supplier_description");
  // If the supplier_description does not contain HTML, do a nl2br()
  if(strlen((string) $supplier_description) > 0 && preg_match("/<[^<]+>/", (string) $supplier_description, $matches) == 0) {
    $supplier_description = nl2br((string) $supplier_description); // @todo fix upstream for supplier_description
  }
  $product_description .= $supplier_description;
}

// Add specific blocks to the description based on attributes
if($refrigerant === "R290" || $refrigerant === "R290a") {
  $product_description .= "<div class='py-3'>".$this->getLayout()->createBlock("cms/block")->setBlockId("productpage_refrigerant_r290")->toHtml()."</div>";
}
if($refrigerant === "R600" || $refrigerant === "R600a" || $refrigerant === "R660a") {
  $product_description .= "<div class='py-3'>".$this->getLayout()->createBlock("cms/block")->setBlockId("productpage_refrigerant_r600")->toHtml()."</div>";
}
if($refrigerant === "R454C") {
  $product_description .= "<div class='py-3'>".$this->getLayout()->createBlock("cms/block")->setBlockId("productpage_refrigerant_r454c")->toHtml()."</div>";
}
$value = $voltage;
if(is_array($value)) {
  $value = implode(" ", $value);
}
if((stripos((string) $value, "400") !== false)) {
  $product_description .= "<div class='py-3'>".$this->getLayout()->createBlock("cms/block")->setBlockId("productpage_voltage_400")->toHtml()."</div>";
}

if(strlen($product_description) === 0) {
  $product_description = "&nbsp;";
}

/* PRODUCT LINKS */

$related_products_block         = $this->getChildHtml("related_products");
$product_additional_data_block  = $this->getChildHtml("product_additional_data");
$alternative_products_block     = $this->getChildHtml("upsell_products");
if(empty($alternative_products_block) && empty($related_products_block)) {
  $upsell_products_block = $this->getLayout()->createBlock("awautorelated/blocks")->setBlockId(1)->toHtml();
}

/* ANCHOR LINKS */

if(empty($pvideo) === false)                        $anchors["video"]               = "Productvideo";
if(strlen($product_description) > 10)               $anchors["description"]         = "Productbeschrijving";
if(empty($_crossSellProducts) === false)            $anchors["accessoires"]         = "Vaak samen gekocht";
if(empty($alternative_products_block) === false)    $anchors["alternatives"]        = "Alternatieven";
if(empty($product_additional_data_block) === false) $anchors["specs"]               = "Specificaties";
if(strlen((string) $additional_attributes) > 10)             $anchors["additional"]          = "Extra Productinformatie";
if(empty($files) === false)                         $anchors["documents"]           = "Documantatie";
if(empty($external_documents_json) === false)       $anchors["external-documents"]  = "Externe Documentatie";
if(empty($upsell_products_block) === false)         $anchors["upsells"]             = "Bekijk ook eens";
if(empty($related_products_block) === false)        $anchors["related"]             = "Gerelateerde Producten";

$productlabel = Mage::helper("deheerhoreca_util/util")->auto_productlabel($_product, "detail");

/* CALCULATED/DERIVED FIELDS */

// If the backorder is expected to take >= 7 days, and we have alternatives, make a shoutout
if($stock_data["overall_stock_status"] === "backorder"
&& (empty($stock_data["stock_date_days_left"]) === true || $stock_data["stock_date_days_left"] >= 7)
&& empty($productlabel) === true
&& empty($alternative_products_block) === false) {
  $productlabel = "Alternatieven beschikbaar";
}

/* START RENDERING */

?>
<script>var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view">

  <?php /* PRODUCT IMAGES */ ?>

  <div class="proleftdv">

    <div class="product-name">
      <h1><?php echo $productTitle; ?></h1>
      <div class="float-left"><a href="<?php echo $brand_link; ?>"><?php echo $brand_name; ?></a></div>
      <?php echo $this->getReviewsSummaryHtml($_product, "short", false); ?>
    </div>

    <div class="product-img-box">
      <span class="anchor" id="photos"></span>
      <?php
        // Product label
        if(empty($productlabel) === false) {
          echo "<span class='product-label'>{$productlabel}</span>";
        }

        // Black friday
        if($show_black_friday && ($overall_stock_status === "in_stock" || $overall_stock_status === "backorder")) {
          echo "<span class='bf-banner-detail'></span>";
        }

        // Package quantity
        $package_quantity = (int) $_product->getData("eenheid");
        if($package_quantity > 1) {
          echo "<span class='product-label-right bg-blue bit-bigger'>{$package_quantity}x</span>";
        }

        // Energy rating
        if(empty($enclz) === false) {
          echo "<span class='lblenergylabel {$enclz}' title='Energielabel {$enclz}'>{$energy_rating}</span>";
        }

        echo $this->getChildHtml("media");
      ?>
    </div>
  </div>

  <div class="product-essential">
    <div id="sticky-container">
      <div class="product-shop">

        <?php /* Add to Cart Block */ ?>

        <form action="<?php echo $this->getSubmitUrl($_product, array("_secure" => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
          <?php echo $this->getBlockHtml("formkey") ?>
          <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
          <input type="hidden" name="related_product" id="related-products-field" value="" />
          <div class="prodetailtopright">

            <?php
            echo $this->getChildHtml("alert_urls");
            echo $this->getChildHtml("other");
            ?>
            <div class="add-to-cart-wrapper">
              <?php

              if($show_black_friday === true && $saleable === true && $eol !== true) {
                ?>
                <div class="info-box" style="height: auto; background-color: var(--color-antracite); color: var(--color-light-gray); border-color: var(--color-antracite); min-height: 100px; padding: .5em;">
                  <div class="info-box-inner" style="max-width: unset;">
                    <div style="float:right; margin-top: .5em;">
                      <img src="/media/wysiwyg/banners/x_2023_11_blackfriday_corner.png" alt="Black Friday 2023" title="Black Friday 2023" style="width:100px; height:auto; float:right;">
                    </div>
                    <div>
                      <strong>De beste Black Friday deals <i>zijn persoonlijk</i>:</strong><br>
                      Maak een <strong>offerte</strong> om uw eigen Black Friday Deal te maken.<br>
                      <span class="strong orange"><i>U kunt tot 16:59 Black Friday offertes indienen</i></span>
                    </div>
                  </div>
                </div>
                <?php
              }

              // Configurable products              
              if($saleable === true && $this->hasOptions()) {
                echo $this->getChildChildHtml('container1', '', true, true);
                ?>
                <div class="add-to-box">
                  <div class="price-info">
                    <?php
                      // The _clone version needs to be present for JS update to work, but we don't want it shown
                      echo "<div style='display:none;'>";
                      echo $this->getlayout()->createBlock('catalog/product_view')->setTemplate('catalog/product/view/price_clone.phtml')->toHtml();
                      echo "</div>";
                      echo $this->getPriceHtml($_product);
                      echo $this->getChildHtml("bundle_prices");
                      echo $this->getTierPriceHtml();
                    ?>
                  </div>
                  <?php
                  echo $buyblock_free_delivery_content;
                  echo $this->getChildHtml("addtocart");
                  echo $this->getChildHtml("addto");
                  ?>
                </div>
                
                <?php
                if($eol === true) {
                  echo "<div>Dit product is helaas niet meer leverbaar.</div>";
                  if(empty($eol_text) !== true) {
                    echo "<div class=eol_text>{$eol_text}</div>";
                  }
                }
                if(empty($delivery_text) !== true) {
                  echo "<div class='clzdelvlb'><span class='delivery-logo'>&nbsp;</span>{$delivery_text}</div>";
                }

                echo $our_usps_content;
                echo $payment_methods_content;
                echo $help_content;

                echo $this->getChildHtml("extra_buttons");
              }

              // All products

              echo $this->getChildHtml("product_type_data");
              echo $this->getChildHtml("extrahint");

              // Non-configurable products

              if(!$this->hasOptions()) {
                ?>
                <div class="add-to-box">
                  <div class="price-info">
                    <?php
                      echo $this->getPriceHtml($_product);
                      echo $this->getChildHtml("bundle_prices");
                      echo $this->getTierPriceHtml();
                    ?>
                  </div>
                  <?php
                  echo "<div class='{$txtcltcz}'>{$stock_message}{$stock_message_tooltip}</div>";
                  echo $buyblock_free_delivery_content;
                  echo "<ul class='fa-ul'>";
                  if(empty($delivery_li) !== true) {
                    echo $delivery_li;
                  }
                  if(empty($moq_li) !== true) {
                    echo $moq_li;
                  }
                  if(empty($qs_content) !== true) {
                    echo $qs_content;
                  }
                  echo "</ul>";
                  
                  if(strtolower($supplier_name) === "combisteel" && CarbonImmutable::now()->isBefore("2024-10-31 00:00:00")) {
                    ?>
                    <div class="card mx-auto p-2 mx-3">
                    <p class="card-text strong text-danger text-center bg-light bg-gradient"></p>
                    <img src="//images.chefstore.nl/media/wysiwyg/brands/combisteel.png?v=1&tr=w-140,c-at_max" class="card-img-top px-5" alt="Coupon Code">
                      <div class="card-body">
                        <h4 class="card-title">5% EXTRA KORTING met <span class="d-inline productdetail__discount font-monospace">HERFST24CS</span></h4>
                        <p class="card-text">Korting geldt voor alle producten van Hendi. Gebruik deze code bij het afrekenen.</p>
                        <p class="card-text mt-2 fw-light"><em>t/m 31 oktober 2024</em></p>
                      </div>
                    </div>
                    <?php
                  } else {
                    echo "<span style='display:none;'>{$supplier_name}</span>";
                  }

                  echo $this->getChildHtml("addtocart");
                  echo $this->getChildHtml("addto");
                  ?>
                </div>
                <?php
                if($eol === true) {
                  if(empty($eol_text) !== true) {
                    echo "<div class=eol_text>{$eol_text}</div>";
                  }
                }

                echo $our_usps_content;
                echo $payment_methods_content;
                echo $help_content;
                echo $this->getChildHtml("extra_buttons");

              // Non-sellable products

              } elseif($saleable === false) {
                ?>
                <div class="add-to-box">
                  <div class="price-info">
                    <?php
                    echo $this->getChildHtml("addto");
                    echo $help_content;
                    ?>
                  </div>
                </div>
                <?php
              }
              echo $this->getChildHtml("sharing");
              // if($_product->getFinalPrice() < 150 && strtolower($supplier_name) === "gastronoble") {
                // echo "<p>Deze leverancier heeft het momenteel extra druk door COVID-19, het kan zijn dat uw levertijd wordt gehaald, maar het kan ook iets uitlopen.</p>";
              // }
              ?>
            </div>

            <?php
            if(sizeof($anchors) > 2) {
              ?>
              <div class="add-to-cart-wrapper">
                <?php
                echo "<strong>Navigatie:</strong>";
                echo "<ul class='internal-product-nav disc-list'>";
                foreach($anchors as $key => $anchor) {
                  echo "<li><a href='#{$key}'>{$anchor}</a></li>";
                }
                echo "</ul>";

                if(empty($categoryUrl) === false && empty($categoryName) === false) {
                  $categoryName = str_ireplace(["[V] ", "[0] "], "", (string) $categoryName);
                  echo "<small>Of ga naar alle <a href='{$categoryUrl}'>{$categoryName}</a></small>";
                }
                ?>
              </div>
              <?php
            }
            ?>

          </div>
        </form>
        <?php

        // Configurable products
        if($saleable === true && $this->hasOptions()) {
          echo $this->getChildChildHtml("container2", "", true, true);
        }
        ?>
      </div>
    </div>
  </div>

  <div class="proleftdv">
    <?php  

    /* Product Tagline */
    if(empty($tagline) === false) {
      echo "<div class='product-detail-tagline px-2 py-1 my-2'>{$tagline}</div>";
    }

    /* Product Video */
    if(empty($pvideo) === false) { ?>
      <div class="py-1">
        <span class="anchor" id="video"></span>
        <div class="content center">
          <?php
          $pvideos = explode(";", (string) $pvideo);
          foreach($pvideos as $video_key) {
            $yt_url = Mage::helper("deheerhoreca_util/util")->build_product_video_url($pvideo);
            echo "<iframe loading=lazy width='534' height='300' src='{$yt_url}' allow='accelerometer;autoplay;encrypted-media;gyroscope;picture-in-picture' allowfullscreen style='border:0;max-width:100%;' frameborder='0'></iframe>";
          }
          ?>
        </div>
      </div>
      <?php
    }

    /* Product USPs */ ?>
    <?php
    if(empty($hlstr) === false) {
      ?>
      <div class="my-3 py-1 pt-1 product-highlight-box center">
        <span class="anchor" id="highlights"></span>
        <?php echo "<ul class='product-highlights'>{$hlstr}</ul>"; ?>
      </div>
      <?php
    }

    /* Product Description */

    if(empty($subdescription) === false && strlen((string) $subdescription) > 20 && strlen((string) $subdescription) < 500) {
      echo "<div class='std p-2 my-2 fw-600' style='background-color:#e0f6ff; border-radius:5px;'>{$subdescription}</div>";
    }

    if(strlen($product_description) > 10) {
      ?>
      <div class="py-1 std justify" id="product-detail-description">
        <span class="anchor" id="description"></span>
        <?php echo $product_description; ?>
      </div>
      <?php
    }

    /* Cross Sell Products */
    if(empty($_crossSellProducts) === false && $_crossSellProducts->getSize() > 0) {
      Varien_Profiler::start("DHH_PRODUCT_DETAILVIEW_SHOW_CROSSSELL_SKUS");
      ?>
      <div class="probottomdv">
        <div class="topproducts_containter">
          <span class="anchor" id="accessoires"></span>
          <h2 class="tableftheader">Vaak samen gekocht</h2>
          <div>Deze combinaties worden aangeraden door de fabrikant, dus dat zit goed!</div>
          <?php
          $_columnCount           = 4;
          $i                      = 0;
          $options                = [
            "skip_usps"             => false,
            "skip_info"             => true,
            "display"               => "mini",
            "image_size"            => 100,
            "_blank"                => true,
            "prefer_rewrite_table"  => true, // Otherwise, getting ugly urls
            "fast_stock"            => true,
          ];
          ?>
          <div class="crosssell product-collateral category-products">
            <ul class="products-grid products-grid-mini">
            <?php
              foreach($_crossSellProducts as $_crossSellProduct) {
                $i++;
                ?>
                <li class="item<?php if(($i-1) % $_columnCount == 0): ?> first<?php elseif($i % $_columnCount == 0): ?> last<?php endif; ?>">
                  <?php
                  Mage::helper("deheerhoreca_util/util")->getProductGridHtml($_crossSellProduct, $this, $options);
                echo "</li>";
              }
              ?>
            </ul></div>
          <div class="clearer"></div>
        </div>
      </div>
      <?php
      Varien_Profiler::stop("DHH_PRODUCT_DETAILVIEW_SHOW_CROSSSELL_SKUS");
    }

    /* Alternatives */
    if(empty($alternative_products_block) === false) {
      ?>
      <span class="anchor" id="alternatives"></span>
      <div class="probottomdv">
        <?php echo $alternative_products_block; ?>
      </div>
      <?php
    }

    /* Product Attributes */
    if(empty($product_additional_data_block) === false) {
      ?>
      <div class="probottomdv">
        <span class="anchor" id="specs"></span>
        <div id="product_additional_data">
          <?php echo $product_additional_data_block ?>
        </div>
      </div>
      <?php
    }

    /* Additional Product Attributes */
    if(strlen((string) $additional_attributes) > 10) {
      ?>
      <h2 class="tableftheader"><?php echo $this->__("Extra productinformatie");?></h2>
      <div class="probottomdv content product-specs" id="additional-attributes">
        <span class="anchor" id="additional"></span>
        <div class="std"><?php echo $additional_attributes; ?></div>
      </div>
    <?php
    }
    ?>

    <?php /* Documents */ ?>
    <?php
    if(empty($files) === false) {
      $helper = $this->helper("staempfli_productattachment");
      $upload_dir = Mage::getBaseUrl("media").$helper::UPLOAD_DIR;
      ?>
      <h2 class="tableftheader"><?php echo $this->__("Documenten");?></h2>
      <div class="probottomdv" id="product-documents-list">
        <span class="anchor" id="documents"></span>
        <ul class="fa-ul">
          <?php

          foreach($files as $document) {
            if(empty($document["path"])) {
              continue;
            }
            $url      = "{$upload_dir}/{$document['path']}";
            $name     = $document["title"]    ?? ($document["filename"] ?? "-");
            $filetype = $document["type"]     ?? null;
            $fa_icon = match ($filetype) {
              'pdf' => 'fa-file-pdf-o',
              default => 'fa-file-o',
            };
            echo "<li style='line-height:2.5em;'>";
            echo "<a title='{$url}' class='document-link' href='{$url}' target='_blank' ><i class='fa-li fa {$fa_icon}' style='line-height:2.5em;'></i>{$name}</a>";
            echo "</li>";
          }
          ?>
        </ul>
      </div>
      <?php
    }
    ?>

    <?php /* External Documents */ ?>
    <?php
    if(empty($external_documents_json) === false && $external_documents_json !== "[]") {
      $external_documents = json_decode((string) $external_documents_json, true);
      // dump($external_documents);
      ?>
      <h2 class="tableftheader"><?php echo $this->__("Externe Documenten");?></h2>
      <div class="probottomdv" id="product-external-documents-list">
        <span class="anchor" id="external-documents"></span>

        <ul class="fa-ul">
          <?php

          $method = "aes128";
          $iv = str_repeat("a", openssl_cipher_iv_length($method));

          foreach($external_documents as $external_document) {
            if(empty($external_document["url"])) {
              continue;
            }
            $url = $external_document["url"];
            if(filter_var($url, FILTER_VALIDATE_URL) === false) {
              Mage::log("{$sku} has an invalid document URL {$url}", null, "system.log", true);
            } else {
              $url_encrypted  = "/view.php?id=".base64_encode(openssl_encrypt($url, $method, "wijdelengeenurls", 0, $iv));
              // $url            = openssl_decrypt($url_encrypted, $method, "wijdelengeenurls", 0, $iv);
              $name           = $external_document["title"]     ?? $url;
              $filetype       = $external_document["filetype"]  ?? null;
              $language       = $external_document["language"]  ?? "";
              $fa_icon        = match ($filetype) {
                "pdf"           => "fa-file-pdf-o",
                default         => "fa-file-o",
              };
              if($language !== "") {
                $language       = strtoupper(" (".implode(", ", (array) $language).")");
              }
              echo "<li style='line-height:2.5em;'>";
              echo "<a title='{$name}' class='document-link' href='{$url_encrypted}' target='_blank' rel='noopener noreferrer nofollow'><i class='fa-li fa {$fa_icon}' style='line-height:2.5em;'></i>{$name}{$language}<i style='margin-left: 5px; font-size: 80%; vertical-align: super;' class='fa fa-external-link' aria-hidden='true'></i></a>".PHP_EOL;
              echo "</li>";
            }
          }

          // NG
          // $entity_id = $_product->getEntityId();
          // foreach($external_documents as $i => $external_document) {
            // if(empty($external_document["url"])) {
              // continue;
            // }
            // $url = $external_document["url"];
            // if(filter_var($url, FILTER_VALIDATE_URL) === false) {
              // Mage::log("{$sku} has an invalid document URL {$url}", null, "system.log", true);
            // } else {
              // $hash           = (string) hash("crc32", $url, false);
              // $hash           = $i; // TMP
              // $seo_name       = "seoname";
              // $document_url   = "/document/{$entity_id}/{$hash}/{$seo_name}";              
              // $name           = $external_document["title"]     ?? $url;
              // $filetype       = $external_document["filetype"]  ?? "";
              // $language       = $external_document["language"]  ?? "";
              // $fa_icon        = match($filetype) {
                // "pdf"           => "fa-file-pdf-o",
                // default         => "fa-file-o",
              // };

              // if(empty($language) === false) {
                // if(is_scalar($language)) {
                  // $language = " (".strtoupper($language).")";
                // } elseif(is_array($language)) {
                  // $language = array_map("strtoupper", $language);
                  // $language = " (".implode(", ", $language).")";
                // }
              // }
              // echo "<li style='line-height:2.5em;'>";
              // echo "<a title='{$name}' class='document-link' href='{$document_url}' target='_blank' rel='noopener noreferrer nofollow'><i class='fa-li fa {$fa_icon}' style='line-height:2.5em;'></i>{$name}{$language}<i style='margin-left: 5px; font-size: 80%; vertical-align: super;' class='fa fa-external-link' aria-hidden='true'></i></a>".PHP_EOL;
              // echo "</li>";
            // }
          // }
          ?>
        </ul>
      </div>
<?php
    }
    ?>

    <?php /* Automatic Related Products */ ?>

    <?php
    if(empty($upsell_products_block) === false) {
      ?>
      <span class="anchor" id="upsells"></span>
      <div class="probottomdv">
        <?php echo $upsell_products_block; ?>
      </div>
      <?php
    }
    ?>

    <?php /* Related Products */ ?>

    <?php
    if(empty($related_products_block) === false) {
      ?>
      <span class="anchor" id="related"></span>
      <div class="probottomdv">
        <?php echo $related_products_block; ?>
      </div>
      <?php
    }
    ?>

    <?php /* Brand Logo & Text */ ?>

    <?php
      // if(strlen($brand_block_html) > 10) { // sometimes it's just &nbsp;
        // 
        // <div class="probottomdv" id="product-brand-text">
        // <span class="anchor" id="brand"></span>
        // <h3 class="tableftheader">Over $brand_name</h3>
        // <div class="brand std justify">$brand_block_name</div>
        // 
      // }
      if(empty($brand_logo) === false) {
        echo "<div class='center'>";
        echo "<a target='_blank' title='{$brand_name}' href='/{$brand_link}'>";
        echo "<img alt='".ucfirst($brand)." logo' title='".ucfirst($brand)."' id='brand_logo_small' src='{$brand_logo}' loading=lazy></a></div>";
      }
      echo "</div>";
      ?>
  </div>
</div>
<?php

// schema.org product data -- Called here and removed from layout xml to put it in the footer
echo $this->getlayout()->createBlock("richsnippets/product")->setTemplate("tm/richsnippets/richsnippets_json.phtml")->toHtml();

?>
<script>
  //<![CDATA[
  var productAddToCartForm = new VarienForm('product_addtocart_form');
  productAddToCartForm.submit = function(button, url) {
    // if (typeof Validation !== 'function' || this.validator.validate()) {
      var form = this.form;
      var oldUrl = form.action;

      if (url) {
         form.action = url;
      }
      var e = null;
      try {
          this.form.submit();
      } catch (e) {
      }
      this.form.action = oldUrl;
      if (e) {
          throw e;
      }

      if (button && button != 'undefined') {
          button.disabled = true;
      }
    // }
  }.bind(productAddToCartForm);

  productAddToCartForm.submitLight = function(button, url){
    // if(typeof Validation !== 'function' || this.validator) {
      // var nv = Validation.methods;
      // delete Validation.methods['required-entry'];
      // delete Validation.methods['validate-one-required'];
      // delete Validation.methods['validate-one-required-by-name'];
      // // Remove custom datetime validators
      // for (var methodName in Validation.methods) {
        // if (methodName.match(/^validate-datetime-.*/i)) {
          // delete Validation.methods[methodName];
        // }
      // }
      // if (this.validator.validate()) {
        if (url) {
            this.form.action = url;
        }
        this.form.submit();
      // }
      // Object.extend(Validation.methods, nv);
    // }
  }.bind(productAddToCartForm);
  //]]>
  <?php
  if($javascripts !== []) {
    foreach($javascripts as $javascript_statement) {
      echo $javascript_statement.PHP_EOL.PHP_EOL;
    }
  }
  ?>
</script>

<?php
if(function_exists("sanitizeForFilename") === false) {
  function sanitizeForFilename($string) {
    $output = mb_ereg_replace("([^\w\s\d\-_~,;\[\]\(\).])", '', (string) $string);
    $output = mb_ereg_replace("([\.]{2,})", '', (string) $string);
    return strtolower($output);
  }
}

function _print_configurable_table($_product) {
  $children = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null, $_product);
  $table = [];

  // Get a list of attributes that are used in this configurable product
  $_attributes = $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product);
  $used_conf_attributes = [];
  foreach($_attributes as $_attribute) {
    $used_conf_attributes[$_attribute["label"]] = $_attribute["attribute_code"];
  }

  foreach ($children as $_child) {
    $stock_data = Mage::helper("deheerhoreca_util/util")->getStockInfo($_child);
    $row = ["SKU" => $_child->getSku()];
    foreach($used_conf_attributes as $label => $code) {
      $row[$label] = $_child->getAttributeText($code);
    }
    $row["Voorraad"] = "<div class='{$stock_data['txtcltcz']}'>{$stock_data["stock_message"]}</div>";
    $table[] = $row;
  }

  return html_table($table);
}

function html_table(array $data): string {  
  if(sizeof($data) === 0) return "";

  $rows = $cells = [];

  $cols = array_keys(array_slice($data, 0, 1)[0]);

  foreach($cols as $col) {
    $cells[] = "<th>{$col}</th>";
  }
  $head = "<tr>" . implode('', $cells) . "</tr>";

  foreach ($data as $row) {
    $cells = [];
    foreach ($row as $cell) {
      $cells[] = "<td>{$cell}</td>";
    }
    $rows[] = "<tr>" . implode('', $cells) . "</tr>";
  }
  return "<table class='table table-striped table-border'><thead>{$head}</thead><tbody>" . implode('', $rows) . "</tbody></table>";
}
