<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */

$htbrand          = $brand = null;
$_helper          = $this->helper('catalog/output');
$_product         = $this->getProduct();
$brand_name       = $_product->getAttributeText('manufacturer');
$brand_logo       = null;
$brand_slug       = Mage::helper("deheerhoreca_util/util")->getBrandUrlSlug($brand_name);
$brand_link       = "{$brand_slug}.html";
$_store           = $_product->getStore();
$skn              = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$anchors          = [];
$in3_minimum      = 100 / 1.21;
$in3_maximum      = 3000 / 1.21;
$billink_minimum  = 10;
$billink_maximum  = 3500;
$_taxHelper       = $this->helper('tax');

if(empty($brand_name) === false) {
  $brand = sanitizeForFilename($brand_name);
  $htbrand = $this->getLayout()->createBlock('cms/block')->setBlockId($brand)->toHtml();
  $brand_logo_file = "media/wysiwyg/brands/{$brand_slug}.png";
  if(is_file($brand_logo_file) === true) {
    $brand_logo = "/".$brand_logo_file;
  }
}

/* Get a list of Category IDs */
$categoryIds = $_product->getCategoryIds();

/* Find the category this product belongs to */
if(count($categoryIds)) {
  $firstCategoryId = $categoryIds[0];
  $_category = Mage::getModel('catalog/category')->load($firstCategoryId);
  $categoryUrl = $_category->getUrl();
  $categoryName = $_category->getName();
}

$max_highlighted_attributes = 10;

// Attributes used in multiple places
$nofrost_method       = $_product->getResource()->getAttribute("ontdooisysteem")->getFrontend()->getValue($_product);
$energy_rating        = $_product->getResource()->getAttribute('energieklasse')->getFrontend()->getValue($_product);
$shoutout             = $_product->getResource()->getAttribute('product_label')->getFrontend()->getValue($_product);
$productTitle         = $_helper->productAttribute($_product, $_product->getName(), 'name');
$product_title_short  = $_product->getResource()->getAttribute('name_short')->getFrontend()->getValue($_product);
$pvideo               = $_product->getResource()->getAttribute('product_video')->getFrontend()->getValue($_product);
$_price               = $_product->getPrice(); //Mage::getModel('catalog/product')->load($_product->getId())->getNormalPrice();
$_finalPrice          = $_product->getFinalPrice();
$tagline              = $_product->getTagline();
$supplier_name        = $_product->getAttributeText('supplier');

$additional_buyblock_content = $top_buyblock_content = $delivery_text = null;

/* Availability, Stock */
$stock_data           = Mage::helper("deheerhoreca_util/util")->getStockInfo($_product);
$stock_message        = $stock_data["stock_message"];
$txtcltcz             = $stock_data["txtcltcz"];
$stock_qty            = $stock_data["stock_qty"];
$in_stock             = $stock_data["in_stock"];
$backorders           = $stock_data["backorders"];
$saleable             = $stock_data["saleable"];
$eol                  = $stock_data["eol"];
$eol_replacement_sku  = $stock_data["eol_replacement_sku"];
$manage_stock         = $stock_data["manage_stock"];
$extra_delivery_time  = $stock_data["extra_delivery_time"];
$overall_stock_status = $stock_data["overall_stock_status"];
$txtstockdate         = $stock_data["txtstockdate"];
$levertijd            = $stock_data["levertijd"];
$bestelartikel        = $stock_data["bestelartikel"];

$freeshipping_from    = (float) Mage::getStoreConfig("carriers/freeshipping/free_shipping_subtotal");
$_finalPriceInclTax   = $_taxHelper->getPrice($_product, $_convertedFinalPrice, true);
$top_buyblock_content = null;

if($overall_stock_status === "in_stock" || $overall_stock_status === "backorder") {
  if($_finalPrice >= $in3_minimum && $_finalPrice <= $in3_maximum) {
    $payment = number_format($_finalPrice / 3, 2, ",", ".");
    $top_buyblock_content .= "<div><a data-fancybox data-touch='false' href='#info-in3' class='gray small fw-600'>Of {$payment} in drie termijnen<span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='false'></i></span></a></div>";
  }
}

if($_finalPriceInclTax >= $freeshipping_from && $_product->isSaleable() === true) {
  $top_buyblock_content .= "<div><strong class=green>Gratis</strong> bezorgd</div>";
}

if($overall_stock_status === "not_sellable" || $overall_stock_status === "backorder") {
  if(empty($txtstockdate) === false) {
    $delivery_text .= "Terug op voorraad: <strong>{$txtstockdate}</strong><span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='true'></i><span class='tooltiptext clztoptoolc'>Dit is de datum waarop de leverancier aangeeft het product weer te kunnen leveren.</span>";
  } else {
    $delivery_text .= "Terug op voorraad: Op aanvraag<span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='true'></i><span class='tooltiptext clztoptoolc'>Dit product komt spoedig weer op voorraad, maar wij hebben nog geen datum doorgekregen van de leverancier. U kunt een nabestelling (backorder) plaatsen, of contact met ons opnemen over verwachte levertijden en alternatieven.</span>";
  }
}

if($bestelartikel === "Ja") {
  $additional_buyblock_content .= "<div class='clzinstocktemp'>Bestelartikel</div>";
}

if($overall_stock_status === "in_stock") {
  $delivery_text .= "Verwachte levertijd: <strong>{$levertijd}</strong>";
  
  $delivery_text .= "<span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='false'></i> <span class='tooltiptext clztoptoolc'>Levertijden variëren per product, merk en aantal. We doen er alles aan om dit artikel op tijd te bezorgen. Het is echter in een enkel geval mogelijk dat door omstandigheden de bezorging vertraagd is. Natuurlijk houden we u altijd op de hoogte van de status van uw bestelling.</span></span>";
}

if($overall_stock_status === "in_stock" || $overall_stock_status === "backorder") {
  if($_finalPrice >= $billink_minimum && $_finalPrice <= $billink_maximum) {
    $additional_buyblock_content .= "<div class='buyblock-usp'><a data-fancybox data-touch='false' href='#info-billink' class=''>Betaal <span class='fw-600'>achteraf</span> met Billink<span class='tooltip'><i class='tooltip-icon fa fa-info-circle fa-lg' aria-hidden='false'></i></span></a></div>";
  }
}

if($overall_stock_status === "eol") {
  $eol_text             = null;
  if(empty($eol_replacement_sku) === false) {
    $replacement_product = Mage::getModel('catalog/product')->loadByAttribute('sku', $eol_replacement_sku);
    if($replacement_product !== false) {
      $name             = $_helper->productAttribute($replacement_product, $replacement_product->getName(), 'name');
      $url              = Mage::helper("deheerhoreca_util/util")->getFullProductUrlSafe($replacement_product);
      $eol_text         = "<strong>Kijkt u naar het vervangend product:</strong><br /><a href='{$url}'>{$name}</a>";
    }
  }
}

/* Product Documents */
$files = Mage::getModel('staempfli_productattachment/file')
  ->getFilesByProductId($this->getProduct()->getId(), Mage::app()->getStore()->getStoreId(), false, true)
  ->getData();

/* Energy Label */
if(strlen($energy_rating) > 0) {
  $enclz = null;
  switch($energy_rating) {
    case 'A++++': $enclz = 'enrgclz1';  break;
    case 'A+++':  $enclz = 'enrgclz2';  break;
    case 'A++':   $enclz = 'enrgclz3';  break;
    case 'A+':    $enclz = 'enrgclz4';  break;
    case 'A':     $enclz = 'enrgclz5';  break;
    case 'B':     $enclz = 'enrgclz6';  break;
  }
}

// Product USPs
$highlights = [];
$i = 0;

$dimension_pair_set = false;
if($i < $max_highlighted_attributes) {
  $id = "dimensions";
  $attribute_names = ["breedte", "diepte", "hoogte"];
  $image = "{$skn}frontend/rwd/dhh/images/measurement.svg";
  $title = "Afmetingen (b x d x h)";
  foreach($attribute_names as $attribute_name) {
    $values[$attribute_name] = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
    if(empty($values[$attribute_name]) === false) {
      $values[$attribute_name] = (int) ($values[$attribute_name] / 10);
    } else {
      unset($values[$attribute_name]);
    }
  }
  if(sizeof($values) === sizeof($attribute_names)) {
    $text = implode("x", $values)." cm";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
    $dimension_pair_set = true;
  }
}

if($dimension_pair_set !== true && $i < $max_highlighted_attributes) {
  $attribute_names = ["breedte", "hoogte"];
  $image = "{$skn}frontend/rwd/dhh/images/measurement.svg";
  $title = "Afmetingen (b x l)";
  foreach($attribute_names as $attribute_name) {
    $values[$attribute_name] = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
    if(empty($values[$attribute_name]) === false) {
      $values[$attribute_name] = (int) ($values[$attribute_name] / 10);
    } else {
      unset($values[$attribute_name]);
    }
  }
  if(sizeof($values) === sizeof($attribute_names)) {
    $text = implode("x", $values)." cm";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "diameter";
  $image = "{$skn}frontend/rwd/dhh/images/diameter.svg";
  $title = "Diameter (mm)";
  $text = (int) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => "{$text} mm",
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "afsluitbaar";
  $image = "{$skn}frontend/rwd/dhh/images/key.svg";
  $title = "Afsluitbaar";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if($text === "Ja") {
    $text = "Afsluitbaar";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "size";
  $image = "{$skn}frontend/rwd/dhh/images/size.svg";
  $title = "Maat";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if($text === "Ja") {
    $text = "Afsluitbaar";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "type_koeling";
  $image = "{$skn}frontend/rwd/dhh/images/forced_cooling.svg";
  $title = "Koelmethode";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if($text === "Geforceerd" OR $text === "Recirculatie" OR $text === "Statisch met ventilator") {
    $text = "{$text}";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "inhoud_liters";
  $image = "{$skn}frontend/rwd/dhh/images/liters.svg";
  $title = "Inhoud";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $text = round($text, 2)." liter";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $image = "{$skn}frontend/rwd/dhh/images/freezer.svg";
  $title = "Ontdooisysteem";
  if($nofrost_method === "Automatisch") {
    $nofrost_method = "Auto defrost";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "aantal_roosters";
  $image = "{$skn}frontend/rwd/dhh/images/shelf.svg";
  $title = "Aantal roosters";
  $text = (int) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $text = "{$text} roosters";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "garantie";
  $image = "{$skn}frontend/rwd/dhh/images/guarantee.svg";
  $title = "Garantietermijn";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text !== "12 maanden") {
    $text = "{$text}";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "vermogen";
  $image = "{$skn}frontend/rwd/dhh/images/watt.svg";
  $title = "Vermogen";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    if(ctype_alnum($text) || is_numeric($text)) {
      $text = str_replace(",", ".", $text);
      $text = (double) $text;
      if($text < 3) {
        $text = (int) ($text * 1000)." W";
      } else {
        $text = number_format($text, 1, ",", ".");
        $text = str_replace(",0", null, $text);
        $text = "{$text} kW";
      }
    } else {
      // For non-numbers like "2 x 3"
    }
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $code   = "voltage";
  $image  = "{$skn}frontend/rwd/dhh/images/volt.svg";
  $title  = "Voltage";
  $text   = $_product->getResource()->getAttribute($code)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $highlights[] = [
      "image"   => $image,
      "title"   => $title,
      "text"    => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "aantal_omwentelingen_minuut";
  $image = "{$skn}frontend/rwd/dhh/images/rpm.svg";
  $title = "RPM";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $text = "{$text}";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "vermogen_kw";
  $image = "{$skn}frontend/rwd/dhh/images/flame.svg";
  $title = "Vermogen (gas)";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $text = number_format($text, 1, ",", ".");
    $text = str_replace(",0", null, $text);
    if(strstr(strtolower($text), "V") === false) {
      $text = "{$text} kW";
    }
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "geluidsniveau";
  $image = "{$skn}frontend/rwd/dhh/images/quiet.svg";
  $title = "Stil apparaat";
  $text = (int) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false) {
    $text = "{$text} dB";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "verlichting";
  $image = "{$skn}frontend/rwd/dhh/images/light.svg";
  $title = "Verlichting";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text !== "Nee") {
    $text = "Verlichting";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "aantal_flessen";
  $image = "{$skn}frontend/rwd/dhh/images/wine.svg";
  $title = "Flessen";
  $text = (int) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text !== "Nee") {
    $text = "{$text} X";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "capacity_wine_bottles";
  $image = "{$skn}frontend/rwd/dhh/images/wine.svg";
  $title = "Aantal 75cl Wijnflessen";
  $text = (int) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text !== "Nee") {
    $text = "{$text} x 75cl.";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "cooking_zones";
  $image = "{$skn}frontend/rwd/dhh/images/stove.svg";
  $title = "Kookzones";
  $text = (int) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text !== "Nee") {
    $text = "{$text} X";
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "glas";
  $image = "{$skn}frontend/rwd/dhh/images/doubleglass.svg";
  $title = "Dubbel glas";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if($text === "dubbel glas") {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "refrigerant";
  $image = "{$skn}frontend/rwd/dhh/images/refrigerant.svg";
  $title = "Koelmiddel";
  $text = $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text ) === false) {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text,
    ];
    $i++;
  }
}

if($i < $max_highlighted_attributes) {
  $attribute_name = "eenheid";
  $image = "{$skn}frontend/rwd/dhh/images/amount.svg";
  $title = "Verpakkingseenheid";
  $text = (double) $_product->getResource()->getAttribute($attribute_name)->getFrontend()->getValue($_product);
  if(empty($text) === false && $text > 1) {
    $highlights[] = [
      "image" => $image,
      "title" => $title,
      "text"  => $text." stuks",
    ];
    $i++;
  }
}

$hlstr = null;
foreach($highlights as $key => $highlight) {
  $hlstr .= "<li><img class='lazy' id='hl-{$key}' data-src='{$highlight["image"]}' title='{$highlight["title"]}' /><span>{$highlight["text"]}</span></li>";
}

$_crossSellProducts = $_product->getCrossSellProducts();

$additional_attributes = $_product->getData("additional_attributes");
$additional_attributes = Mage::helper("deheerhoreca_util/util")->markdownExtraToHtml($additional_attributes);

$product_description = $this->getProduct()->getDescription();
$product_description = Mage::helper("deheerhoreca_util/util")->markdownToHtmlSafe($product_description);

if(strtolower($nofrost_method) === 'Automatisch') {
  $product_description .= '<div class="std">'.$this->getLayout()->createBlock('cms/block')->setBlockId('productpage_ontdooisysteem_automatisch')->toHtml().'</div>';
}

$code = "voltage";
$text   = $_product->getResource()->getAttribute($code)->getFrontend()->getValue($_product);
if($text === "400") {
  $product_description .= '<div class="std">'.$this->getLayout()->createBlock('cms/block')->setBlockId('productpage_aansluitspanning_400')->toHtml().'</div>';
}

$attributekoelmiddel = $_product->getResource()->getAttribute('refrigerant');
$attribute_valuekoelmiddel = $attributekoelmiddel->getFrontend()->getValue($_product);
if($attribute_valuekoelmiddel === "R290") {
  $product_description .= '<div class="std">'.$this->getLayout()->createBlock('cms/block')->setBlockId('productpage_koelmiddel_r290')->toHtml().'</div>';
}

if(empty($_crossSellProducts) === false) {
  $product_description .= "<p>De {$product_title_short} heeft één of meer door de leverancier <a href='#accessoires'>geselecteerde accessoires en/of verbruiksproducten.</a></p>";
}

if(strlen($product_description) === 0) {
  $product_description = "&nbsp;";
}

$related_products_block = $this->getChildHtml('related_products');
$product_additional_data_block = $this->getChildHtml('product_additional_data');
$alternative_products_block = $this->getChildHtml('upsell_products');
if(empty($alternative_products_block) === true) {
  $upsell_products_block = $this->getLayout()->createBlock('awautorelated/blocks')->setBlockId(1)->toHtml();
}

$anchors["photos"] = "Foto's";
if(empty($pvideo) === false)                        $anchors["video"]         = "Productvideo";
if(strlen($product_description) > 10)               $anchors["description"]   = "Beschrijving";
if(empty($_crossSellProducts) === false)            $anchors["accessoires"]   = "Accessoires en verbruiksartikelen";
if(empty($alternative_products_block) === false)    $anchors["alternatives"]  = "Alternatieven";
if(empty($product_additional_data_block) === false) $anchors["specs"]         = "Specificaties";
if(count($files) > 0)                               $anchors["documents"]     = "Documenten";
if(empty($upsell_products_block) === false)         $anchors["upsells"]       = "Bekijk ook";
if(empty($related_products_block) === false)        $anchors["related"]       = "Gerelateerde producten";
if(strlen($additional_attributes) > 10)             $anchors["additional"]    = "Extra info van de leverancier";
if(strlen($htbrand) > 10)                           $anchors["brand"]         = "Over {$brand_name}";

// if($_SERVER["REMOTE_ADDR"] === "85.144.117.179") {
  // echo "<pre>";
  // var_dump($stock_data);
  // echo "</pre>";
// }
?>

<script>var optionsPrice = {};</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view">

  <div class="product-name clearfix">
    <h1><?php echo $productTitle; ?></h1>
    <div class='float-left' style='margin-right:2em;'>
      <a href='/<?php echo $brand_link; ?>'><?php echo $brand_name; ?></a>
    </div>
    <?php echo $this->getReviewsSummaryHtml($_product, 'short', false); ?>
  </div>
  <div class="hide-until-m" style="border-top: 1px solid #dadada; padding-top: 10px;"></div>
  
  <?php /* PRODUCT IMAGES */ ?>
  
  <div class="proleftdv">
    <div class="product-img-box">
      <a class="anchor" id="photos"></a>
      <?php
        if(empty($shoutout) === false) {
          echo "<span class='lblprolistviewpg'>{$shoutout}</span>";
        }
        
        /* Energy Label */
        if(empty($enclz) === false) {
          echo "<span class='lblenergylabel {$enclz}' title='Energielabel {$enclz}'>{$energy_rating}</span>";
        }
        
        echo $this->getChildHtml('media');
      ?>
    </div>
  </div>
  
  <div class="product-essential">
    <div id="sticky-container">
      <div class="product-shop">
        
        <?php /* Add to Cart Block */ ?>
        
        <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
          <?php echo $this->getBlockHtml('formkey') ?>
          <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
          <input type="hidden" name="related_product" id="related-products-field" value="" />
          <div class="prodetailtopright clztype<?php echo $_product->getTypeId();?>">
            
            <?php
            echo $this->getChildHtml('alert_urls');
            echo $this->getChildHtml('other');

            if ($saleable === true && $this->hasOptions()) {
              echo $this->getChildChildHtml('container1', '', true, true);
            }
            
            if(empty($tagline) === false) {
              echo "<div class='product-detail-tagline'>{$tagline}</div>";
            }
            ?>

            <div class="add-to-cart-wrapper">
              <?php              
              // echo "<div class='h1 really-strong'>{$product_title_short}</div>";
              echo $this->getChildHtml('product_type_data');
              echo $this->getChildHtml('extrahint');
              if(!$this->hasOptions()) {
                ?>
                <div class="add-to-box">
                  <div class="price-info">
                    <?php
                      echo $this->getPriceHtml($_product);
                      echo $this->getChildHtml('bundle_prices');
                      echo $this->getTierPriceHtml();
                    ?>
                  </div>
                  <?php
                  echo $top_buyblock_content;
                  echo $this->getChildHtml('addtocart');
                  echo $this->getChildHtml('addto');
                  ?>
                </div>
                <div class="<?php echo $txtcltcz; ?>"><?php echo $stock_message; ?></div>
                <?php
                if($eol === true) {
                  echo "<div>Dit product is helaas niet meer leverbaar.</div>";
                }
                if(empty($eol_text) !== true) {
                  echo "<div class=eol_text>{$eol_text}</div>";
                }
                if(empty($delivery_text) !== true) {
                  echo "<div class='clzdelvlb'><span class='delivery-logo'>&nbsp;</span>{$delivery_text}</div>";
                }
                
                echo $additional_buyblock_content;
                
                echo $this->getChildHtml('extra_buttons');
              } elseif($saleable === false) { ?>
                <div class="add-to-box">
                  <?php
                  echo $this->getChildHtml('addto');
                  echo $additional_buyblock_content;
                  ?>
                </div>
                <?php
              }

              if($_product->getFinalPrice() < 150) {
                if(strtolower($supplier_name) === "gastronoble") {
                  echo "<p>Deze leverancier heeft het momenteel extra druk door COVID-19, het kan zijn dat uw levertijd wordt gehaald, maar het kan ook iets uitlopen.</p>";
                }
              }

              ?>
              <div id="company_usps">
                <div class="buyblock-usp"><span class="dark-color">Advies: <a href='tel:+31850441003'>Bel</a>, <a href='mailto:service@chefstore.nl'>e-mail</a> of <a href="javascript:$zopim.livechat.window.show();">chat</a>!</span></div>
              </div>
              <?php
              echo $this->getChildHtml('sharing');
              ?>
            </div>
            
            <?php
            if(sizeof($anchors) > 2) {
              ?>
              <div class="add-to-cart-wrapper">
                <?php
                echo "<strong>Navigatie:</strong>";
                echo "<ul class='internal-product-nav disc-list'>";
                foreach($anchors as $key => $anchor) {
                  echo "<li><a href='#{$key}'>{$anchor}</a></li>";
                }
                echo "</ul>";
                
                if(empty($categoryUrl) === false && empty($categoryName) === false) {
                  echo "<small>Of ga naar alle <a href='{$categoryUrl}'>{$categoryName}</a></small>";
                }
                ?>
              </div>
              <?php
            }
            ?>
            
          </div>
        </form>
                  
        <?php if($saleable === true && $this->hasOptions()):?>
          <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
      </div>
    </div>
  
  </div>
    
  <div class="proleftdv">
    
    <?php /* Product USPs */ ?>
    <?php
    if(empty($hlstr) === false) {
      ?>
      <div class="probottomdv">
        <a class="anchor" id="highlights"></a>
        <?php
        // An attempt to reduce the attention to sections with just 1 or 2 highlights
        if(sizeof($highlights) > 2) {
          echo "<h2>".$this->__('Highlights')."</h2>";
        }
        ?>
        <div class="content center">
          <?php echo "<ul class='product-highlights'>{$hlstr}</ul>"; ?>
        </div>
      </div>
      <?php
    }
    ?>

    <?php

    /* Product Video */
    if(empty($pvideo) === false) {
      ?>
      <div class="probottomdv">
        <a class="anchor" id="video"></a>
        <div class="content center">
          <iframe class="lazy" width="444" height="250" data-src="<?php echo $pvideo; ?>" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
      </div>
      <?php
    }

    /* Product Description */
    if(strlen($product_description) > 10) {
      ?>
      <div class="probottomdv std justify" id="product-detail-description">
        <a class="anchor" id="description"></a>
        <?php echo $product_description; ?>
      </div>
      <?php
    }
    ?>

    <?php /* Cross Sell Products */ ?>

    <?php if(empty($_crossSellProducts) === false) { ?>
      <div class="probottomdv">
        <div class="topproducts_containter">
          <a class="anchor" id="accessoires"></a>
          <h2 class="tableftheader">Gerelateerde producten en accessoires</h2>
          <?php
          $_columnCount = 4;
          $i = 0;
          if($_crossSellProducts = $_product->getCrossSellProducts()) { ?>
            <div class="crosssell product-collateral category-products">
              <?php
              echo "<ul class='products-grid products-grid-mini-narrow'>";
              foreach ($_crossSellProducts as $_product) {
                $_product = Mage::getModel('catalog/product')->load($_product->getId());
                $i++;
                ?>
                <li class="item<?php if(($i-1) % $_columnCount == 0): ?> first<?php elseif($i % $_columnCount == 0): ?> last<?php endif; ?>">
                  <?php
                  $options = [
                    "skip_usps"             => true,
                    "skip_info"             => true,
                    "display"               => "mini",
                    "image_size"            => 100,
                    "_blank"                => true,
                    "prefer_rewrite_table"  => true, // Otherwise, getting ugly urls
                  ];
                  echo Mage::helper("deheerhoreca_util/util")->getProductGridHtml($_product, $this, $options);
                echo "</li>";
              }
              ?>
            </ul></div>
            <?php
          }
          ?>
          <div class="clearer"></div>
        </div>
      </div>
      <?php
    }
    
    /* Alternatives */
    if(empty($alternative_products_block) === false) {
      ?>
      <a class="anchor" id="alternatives"></a>
      <div class="probottomdv">
        <?php echo $alternative_products_block; ?>
      </div>
      <?php
    }

    /* Product Specs */
    if(empty($product_additional_data_block) === false) {
      ?>
      <div class="probottomdv">
        <a class="anchor" id="specs"></a>
        <div id="product_additional_data">
          <?php echo $product_additional_data_block ?>
        </div>
      </div>
      <?php
    }
    ?>

    <?php /* Documents */ ?>
    <?php
    if(count($files) > 0) {
      $helper = $this->helper('staempfli_productattachment');
      $dir = Mage::getBaseUrl('media').$helper::UPLOAD_DIR;
      ?>
      <div class="leftbranddv">
        <h2 class="tableftheader"><?php echo $this->__('Documenten');?></h2>
        <div class="probottomdv" id="product-documents-list">
          <a class="anchor" id="documents"></a>
          <ul>
            <li class="tab_list_element">
              <!-- <a id="mediathek" class="headline active"><?php echo $this->__('Mediathek') ?></a> -->
              <div id="tab-mediathek" class="tabs_content">
                <?php
                  //echo "<pre>";print_r($files);echo "</pre>";
                  foreach($files as $file) {
                    $file_name = empty($file['description']) ? $file['filename'] : $file['description'];
                    echo '<div class="mediathek" style="margin-bottom: 10px">';
                    echo "<a title='{$file['filename']}' class='document-link' href=\"{$dir}/{$file['path']}\" target=\"_blank\">
                            <i class=\"fa fa-file-{$file['type']}-o fa-2x\"></i><span>{$file_name}</span>
                          </a>";
                    echo "</div>";
                  }
                ?>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <?php
    }
    ?>

    <?php /* Automatic Related Products */ ?>

    <?php
    if(empty($upsell_products_block) === false) {
      ?>
      <a class="anchor" id="upsells"></a>
      <div class="probottomdv">
        <?php echo $upsell_products_block; ?>
      </div>
      <?php
    }
    ?>
    
    <?php /* Related Products */ ?>
    
    <?php
    if(empty($related_products_block) === false) {
      ?>
      <a class="anchor" id="related"></a>
      <div class="probottomdv" id="related">
        <?php echo $related_products_block; ?>
      </div>
      <?php
    }
    ?>
    
    <?php /* Additional Attributes */ ?>
    
    <?php
    if(strlen($additional_attributes) > 10) {
      ?>
      <h2 class="tableftheader"><?php echo $this->__('Extra informatie van de fabrikant');?></h2>
      <div class="probottomdv content product-specs" id="additional-attributes">
        <a class="anchor" id="additional"></a>
        <div class="std specs-table"><?php echo $additional_attributes; ?>
          <dl class="hidden"><dt>Source</dt><dd>https://www.chefstore.nl</dd></dl>
        </div>
      </div>
    <?php
    }
    ?>
    
    <?php /* Brand Logo & Text */ ?>
      
    <div class="probottomdv" id="product-brand-text">
      <?php
      if(strlen($htbrand) > 10) { //sometimes it's just &nbsp;
        ?>
        <a class="anchor" id="brand"></a>
        <h3 class="tableftheader">Over <?php echo $brand_name; ?></h3>
        <div class="brand std justify"><?php echo $htbrand; ?></div>
        <?php
      }
      if(empty($brand_logo) === false) {
        echo "<div class='center'>";
        echo "<a target='_blank' title='{$brand_name}' href='/{$brand_link}'>";
        echo "<img class='lazy' alt='".ucfirst($brand)." logo' title='".ucfirst($brand)."' id='brand_logo_small' src='{$brand_logo}' /></a></div>";
      }
      ?>
    </div>
  </div>
</div>

<script>
  //<![CDATA[
  var productAddToCartForm = new VarienForm('product_addtocart_form');
  productAddToCartForm.submit = function(button, url) {
    if (this.validator.validate()) {
      var form = this.form;
      var oldUrl = form.action;

      if (url) {
         form.action = url;
      }
      var e = null;
      try {
          this.form.submit();
      } catch (e) {
      }
      this.form.action = oldUrl;
      if (e) {
          throw e;
      }

      if (button && button != 'undefined') {
          button.disabled = true;
      }
    }
  }.bind(productAddToCartForm);

  productAddToCartForm.submitLight = function(button, url){
    if(this.validator) {
      var nv = Validation.methods;
      delete Validation.methods['required-entry'];
      delete Validation.methods['validate-one-required'];
      delete Validation.methods['validate-one-required-by-name'];
      // Remove custom datetime validators
      for (var methodName in Validation.methods) {
        if (methodName.match(/^validate-datetime-.*/i)) {
          delete Validation.methods[methodName];
        }
      }
      if (this.validator.validate()) {
        if (url) {
            this.form.action = url;
        }
        this.form.submit();
      }
      Object.extend(Validation.methods, nv);
    }
  }.bind(productAddToCartForm);
  //]]>
</script>

<?php
if(function_exists("sanitizeForFilename") === false) {
  function sanitizeForFilename($string) {
    $output = mb_ereg_replace("([^\w\s\d\-_~,;\[\]\(\).])", '', $string);
    $output = mb_ereg_replace("([\.]{2,})", '', $string);
    return strtolower($output);
  }
}

?>
<div id="info-stock" style="display:none;" class="std">
  <img src="<?php echo $imageurl ?>" alt="<?php echo $logoAlt; ?>" title="<?php echo $logoAlt; ?>" />
  <h2><i class="fa fa-phone fa-1x" aria-hidden="true"></i>&nbsp;Contact met Chefstore.nl</h2>
  <div style="margin-top: 1em;"><strong>Sales & Advies: <a href="tel:+31850441003" title="Bel ons">+31 85 0441003</a></strong><small>&nbsp;&nbsp;Bereikbaar tijdens kantooruren</small>.</div>
  <div style="margin-top: 1em;"><strong>Klantenservice:</strong> Stuur een mail naar <a href="mailto:service@chefstore.nl" title="Klantenservice">service@chefstore.nl</a> of <a href="/service">vul direct een Serviceverzoek in</a>.</div>
  <div style="margin-top: 1em;">U kunt ook een verzoek indienen om door ons gebeld te worden, klik daarvoor <a rel="nofollow noreferrer" href="https://form.jotform.com/200604056344041" target="_blank" title="Wij bellen u">hier</a>.</div>
  <div style="margin-top: 1em;">Daarnaast zijn wij bereikbaar op de chat, zie daarvoor de knop rechtsonderin op onze website.</div>
</div>

<div id="info-billink" style="display:none;" class="std">
  <img src="<?php echo $imageurl ?>" alt="<?php echo $logoAlt; ?>" title="<?php echo $logoAlt; ?>" style="max-width:140px; height:auto;" />
  <img class="lazy" data-src="/skin/frontend/rwd/dhh/images/billink_logo.png" alt="Billink logo" title="Billink" style="max-width:140px; height:auto;" />
  <h2>🤩&nbsp;Achteraf betalen met Billink</h2>
  <h5><i>Voor zakelijk en particulier</i></h5>
  <div style="max-width: 600px;">
    <strong>Met Billink betaal je het volledige bedrag zonder rente binnen 14 dagen.</strong>
  </div>
  <div style="max-width: 600px;">
  Bestel nu online, betaal achteraf. Betalen met Billink is heel gemakkelijk. Je bestelt wat je nodig hebt en selecteert tijdens het betaalproces dat je wilt betalen met Billink. Wil je graag een zakelijke bestelling achteraf betalen? Van Billink ontvang je een handige factuur, die je vervolgens binnen 14 dagen betaalt.
  </div>
</div>

<div id="info-in3" style="display:none;" class="std">
  <img src="<?php echo $imageurl ?>" alt="<?php echo $logoAlt; ?>" title="<?php echo $logoAlt; ?>" />
  <img class="lazy center" data-src="/skin/frontend/rwd/dhh/images/in3_logo.png" alt="In3 logo" title="In3" style="max-width:140px; height:auto;" />
  <h2>🤩&nbsp;In 3 keer gespreid betalen zonder rente</h2>
  <h5><i>Voor zakelijk en particulier, tot 3000 euro inclusief BTW. Momenteel alleen in Nederland.</i></h5>
  <div style="max-width: 700px;">
    <h3>Hoe werkt In3?</h3>
    <img class="lazy center" data-src="/skin/frontend/rwd/dhh/images/in3_stappen.png" alt="In3 logo" title="In3" style="max-width:100%; height:auto;" />
  </div>
  <div class="center" style="margin-top: 20px;">
    <iframe style="max-width:100%;" width="560" height="315" src="https://www.youtube-nocookie.com/embed/9XTdoGzjefY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
  Momenteel is in3 alleen actief in Nederland maar heeft wel grote ambities om naar andere landen uit te rollen. Het eerstvolgende land waar in3 actief zal zijn is België.
</div>
