<?php
$_product             = $this->getProduct();
$_store               = $_product->getStore();
$_finalPrice          = $_product->getFinalPrice();
$_taxHelper           = $this->helper('tax');
$_convertedFinalPrice = $_store->roundPrice($_store->convertPrice($_product->getFinalPrice()));
$_finalPriceInclTax   = $_taxHelper->getPrice($_product, $_convertedFinalPrice, true);
$freeshipping_from    = (float) Mage::getStoreConfig("carriers/freeshipping/free_shipping_subtotal");
$saleable             = $_product->isSaleable();

$buttonTitle_buy      = Mage::helper('core')->quoteEscape($this->__('Kopen'));
$buttonTitle_lease    = $this->__('Lease aanvragen');
$top_buyblock_content = null;

if($_finalPriceInclTax >= $freeshipping_from && $saleable === true) {
  $top_buyblock_content .= "<div><strong class=green>Gratis</strong> bezorgd</div>";
}
?>

<div class="price-info">
  <?php
    echo $this->getPriceHtml($_product);
    echo $this->getChildHtml('bundle_prices');
    echo $this->getTierPriceHtml();
	?>
</div>
<?php

echo $top_buyblock_content;

if($_product->isSaleable()) { ?>
  <div class="add-to-cart">
    <?php
    
    /* Grouped Products */
    if(0 && !$_product->isGrouped()) {
      ?>
      <div class="qty-wrapper" style="display: none;">
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <input type="text" pattern="\d*(\.\d+)?" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty" />
      </div>
      <?php
    }
    ?>

    <div class="add-to-cart-buttons">
      <button type="button" title="<?php echo $buttonTitle_buy ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)">
        <i class="fa fa-shopping-cart" style="font-size: 1.3em; margin-right: 10px;"></i>
        <?php echo $buttonTitle_buy; ?>
      </button>
      <?php echo $this->getChildHtml('', true, true) ?>
      <?php
      $mininum_lease_price = 1000;
      if(isset($_finalPrice) && $_finalPrice >= 450) {
        ?>
        
        <script src ="https://form.jotform.com/static/feedback2.js" type="application/javascript"></script>
        <script type="application/javascript">
          var JFL_200152323289044 = new JotformFeedback({
            formId: '200152323289044',
            base: 'https://form.jotform.com/',
            windowTitle: 'Aanvraag lease',
            background: '#f08324',
            fontColor: '#FFFFFF',
            type: 'false',
            height: 600,
            width: 700,
            openOnLoad: false,
            iframeParameters: {
              'product': <?php echo json_encode($_product->getName()); ?>
            },
          });
        </script>
        
        <button type="button" title="<?php echo $buttonTitle_lease ?>" class="button btn lightbox-200152323289044" style="margin-top:1em; background-color:#2a71db !important;">
          <i class="fa fa-shopping-cart" style="font-size: 1.3em; margin-right: 10px;"></i>
          <?php echo $buttonTitle_lease; ?>
        </button>
        <?php
      }
      ?>
    </div>
  </div>
  <?php
}
