<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */

/* @var $this Mage_Catalog_Block_Product_View_Media */

$_product         = $this->getProduct();
$_helper          = $this->helper('catalog/output');

$main_image_url   = $this->helper('catalog/image')->init($_product, 'image');
$main_image_label = $this->escapeHtml($this->getImageLabel());
?>

<div class="product-image product-image-zoom">
  <div class="product-image-gallery">
    <img id="image-main" class="gallery-image visible" src="<?=$main_image_url?>" alt="<?=$main_image_label?>" title="<?=$main_image_label?>" width="300" height="300">

    <?php
    $i = 0;
    foreach ($this->getGalleryImages() as $_image) {
      if($this->isGalleryImageVisible($_image)) ?>
      <img id="image-<?=$i?>" class="gallery-image" src="<?=$this->getGalleryImageUrl($_image)?>" data-zoom-image="<?=$this->getGalleryImageUrl($_image)?>">
      <?php
      $i++;
    }
    ?>
  </div>
</div>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
  <ul class="product-image-thumbs">
    <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
    <?php if ($this->isGalleryImageVisible($_image)): ?>
    <li>
      <a class="thumb-link" href="#" title="<?=$this->escapeHtml($_image->getLabel()) ?>" data-image-index="<?=$i?>">
        <img src="<?=$this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(200)?>" width="100" height="100" alt="<?=$this->escapeHtml($_image->getLabel()) ?>">
      </a>
    </li>
    <?php endif; ?>
    <?php $i++; endforeach; ?>
  </ul>
</div>
<?php endif;
echo $this->getChildHtml('after');
