<?php

$_product = $this->getProduct();
$_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<div class="add-to-cart-sharing">
  <div style="line-height: 25px;">Deel dit product:</div>
  <ul class="sharing-links">
    <?php
    if ($this->canEmailToFriend()) { ?>
      <li>
        <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>" class="link-email-friend" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email to a Friend')) ?>">
          <i class="fa fa-envelope-o" aria-hidden="true" style="color: #929a9c;"></i>
        </a>
      </li>
    <?php
    }
    
    $_helper          = $this->helper('catalog/output');
    $_productName     = $_helper->productAttribute($_product, $_product->getName(), 'name');
    $_productImageUrl = urlencode(trim($this->helper('catalog/image')->init($_product, 'image')));
    $_productUrl      = $_product->getProductUrl();
    
    $wa_url = Mage::helper("deheerhoreca_util/util")->addParamToUrl($_productUrl, "utm_channel=social&utm_source=whatsapp_share");
    ?>
    <li>
      <a href="https://wa.me/?text=<?php echo urlencode("Gezien op Chefstore.nl: {$wa_url}") ?>" target="_blank" title="<?php echo Mage::helper('core')->quoteEscape($this->__('WhatsApp')) ?>">
        <i class="fa fa-whatsapp" aria-hidden="true" style="color: #25D366;"></i>
      </a>
    </li>
  </ul>
</div>
