<?php

/**
 * @see Mage_Catalog_Block_Product_View
 */
$_product = $this->getProduct();
$_tierPrices = $this->getTierPrices();
$_finalPriceInclTax = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice(), true);

/** @var $_catalogHelper Mage_Catalog_Helper_Data */
$_catalogHelper = Mage::helper('catalog');

$_weeeTaxAmount = Mage::helper('weee')->getAmountForDisplay($_product);
if(Mage::helper('weee')->typeOfDisplay($_product, [1, 2, 4])) {
  $_weeeTaxAttributes = Mage::helper('weee')->getProductWeeeAttributesForDisplay($_product);
}

if(count($_tierPrices) > 0) {
  echo "<div class='tier-pricing-container'>";
  echo "<strong>Groothandelskorting:</strong>";
  $class = $this->getInGrouped() ? 'tier-prices-grouped product-pricing-grouped' : 'tier-prices product-pricing';
  echo "<ul class='{$class}'>";
  
  if($this->getInGrouped()) {
    $_tierPrices = $this->getTierPrices($_product);
  }
  
  Mage::helper('weee')->processTierPrices($_product, $_tierPrices);
  
  foreach ($_tierPrices as $_index => $_price) {
    
    echo "<li class='tier-price tier-{$_index}'>";
    
    if($_catalogHelper->canApplyMsrp($_product)) {
      if($this->getInGrouped()) {
        echo $this->__('Buy %1$s for', $_price['price_qty']);
      } else {
        echo $this->__('Buy %1$s', $_price['price_qty']);
      }
    } else {
      if($this->helper('tax')->displayBothPrices()) {
        if(Mage::helper('weee')->typeOfDisplay($_product, 0)) {
          echo $this->__('Buy %1$s for %2$s (%3$s incl. tax) each', $_price['price_qty'], $_price['formated_price_incl_weee_only'], $_price['formated_price_incl_weee']);
        } elseif(Mage::helper('weee')->typeOfDisplay($_product, 1)) {
          echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_weee_only']);
          if($_weeeTaxAttributes) {
            echo "(<small>";
            echo $this->__('%1$s incl tax.', $_price['formated_price_incl_weee']);
            $separator = ' + ';
            foreach($_weeeTaxAttributes as $_attribute) {
              echo $separator;
              echo $_attribute->getName();
              echo Mage::helper('core')->currency($_attribute->getAmount());
            }
            echo "</small>)";
          }
          echo $this->__('each');
        } elseif(Mage::helper('weee')->typeOfDisplay($_product, 4)) {
          echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_weee_only']);
          if($_weeeTaxAttributes) {
            echo "(<small>";
            echo $this->__('%1$s incl tax.', $_price['formated_price_incl_weee']);
            $separator = ' + ';
            foreach($_weeeTaxAttributes as $_attribute) {
              echo $separator;
              echo $_attribute->getName();
              echo Mage::helper('core')->currency($_attribute->getAmount()+$_attribute->getTaxAmount()); 
            }
            echo "</small>)";
          }
          echo $this->__('each');
        } elseif(Mage::helper('weee')->typeOfDisplay($_product, 2)) {
          echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price']);
          if($_weeeTaxAttributes) {
            echo "(<small>";
            foreach($_weeeTaxAttributes as $_attribute) {
              echo $_attribute->getName();
              echo Mage::helper('core')->currency($_attribute->getAmount());
              }
            echo $this->__('Total incl. Tax: %1$s', $_price['formated_price_incl_weee']);
            echo "</small>)";
          }
          echo $this->__('each');
        } else {
          echo $this->__('Buy %1$s for %2$s (%3$s incl. tax) each', $_price['price_qty'], $_price['formated_price'], $_price['formated_price_incl_tax']);
        }
      } else {
        if($this->helper('tax')->displayPriceIncludingTax()) {
          if(Mage::helper('weee')->typeOfDisplay($_product, 0)) {
            echo $this->__('Buy %1$s for %2$s each', $_price['price_qty'], $_price['formated_price_incl_weee']);
          } elseif(Mage::helper('weee')->typeOfDisplay($_product, 1)) {
            echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_weee']);
            if($_weeeTaxAttributes) {
              echo "(<small>";
              $separator = '';
              foreach ($_weeeTaxAttributes as $_attribute) {
                echo $separator;
                echo $_attribute->getName();
                echo Mage::helper('core')->currency($_attribute->getAmount());
                $separator = ' + ';
              }
              echo "</small>)";
            }
            echo $this->__('each');
          } elseif(Mage::helper('weee')->typeOfDisplay($_product, 4)) {
            echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_weee']);
            if($_weeeTaxAttributes) {
              echo "(<small>";
              $separator = '';
              foreach($_weeeTaxAttributes as $_attribute) {
                echo $separator;
                echo $_attribute->getName();
                echo Mage::helper('core')->currency($_attribute->getAmount()+$_attribute->getTaxAmount());
                $separator = ' + ';
              }
              echo "</small>)";
            }
            echo $this->__('each');
          } elseif(Mage::helper('weee')->typeOfDisplay($_product, 2)) {
            echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_tax']);
            if($_weeeTaxAttributes) {
              echo "(<small>";
              foreach($_weeeTaxAttributes as $_attribute) {
                echo $_attribute->getName();
                echo Mage::helper('core')->currency($_attribute->getAmount());
              }
              echo $this->__('Total incl. Tax: %1$s', $_price['formated_price_incl_weee']);
              echo "</small>)";
            }
            echo $this->__('each');
          } else {
            echo $this->__('Buy %1$s for %2$s each', $_price['price_qty'], $_price['formated_price_incl_tax']);
          }
        } else {
          if(Mage::helper('weee')->typeOfDisplay($_product, 0)) {
            echo $this->__('Buy %1$s for %2$s each', $_price['price_qty'], $_price['formated_price_incl_weee_only']);
          } elseif(Mage::helper('weee')->typeOfDisplay($_product, 1)) {
            echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_weee_only']);
            if($_weeeTaxAttributes) {
              echo "(<small>";
              $separator = '';
              foreach($_weeeTaxAttributes as $_attribute) {
                echo $separator;
                echo $_attribute->getName();
                echo Mage::helper('core')->currency($_attribute->getAmount());
                $separator = ' + ';
              }
              echo "</small>)";
            }
            echo $this->__('each');
          } elseif(Mage::helper('weee')->typeOfDisplay($_product, 4)) {
            echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_weee_only']);
            if($_weeeTaxAttributes) {
              echo "(<small>";
              $separator = '';
              foreach($_weeeTaxAttributes as $_attribute) {
                echo $separator;
                echo $_attribute->getName();
                echo Mage::helper('core')->currency($_attribute->getAmount()+$_attribute->getTaxAmount());
                $separator = ' + ';
              }
              echo "</small>)";
            }
            echo $this->__('each');
          } elseif(Mage::helper('weee')->typeOfDisplay($_product, 2)) {
            echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price']);
            if($_weeeTaxAttributes) {
              echo "(<small>";
              foreach($_weeeTaxAttributes as $_attribute) {
                echo $_attribute->getName();
                echo Mage::helper('core')->currency($_attribute->getAmount());
              }
              echo $this->__('Total incl. Tax: %1$s', $_price['formated_price_incl_weee_only']);
              echo "</small>)";
            }
            echo $this->__('each');
          } else {
            echo $this->__('Buy %1$s for %2$s each', $_price['price_qty'], $_price['formated_price']);
          }
        } // displayPriceIncludingTax
      } // displayBothPrices
    } // Can apply MSRP

    if(!$this->getInGrouped()) {
      if(($_product->getPrice() == $_product->getFinalPrice() && $_product->getPrice() > $_price['price'])
      || ($_product->getPrice() != $_product->getFinalPrice() &&  $_product->getFinalPrice() > $_price['price'])) {
        echo " = <strong class='benefit'><span class='percent tier-{$_index}'>{$_price['savePercent']}% extra korting</span>";
      }
      echo "</strong>";
    }

    if($_catalogHelper->isShowPriceOnGesture($_product)) {
      $popupId = 'msrp-popup-' . $_product->getId() . $this->helper('core')->getRandomString(20); ?>
      <a href="#" id="<?php echo($popupId);?>"><?php echo $this->__('Click for price'); ?></a>
      <script type="text/javascript">
      <?php
        $addToCartUrl = $this->getProduct()->isSalable()
          ? $this->getAddToCartUrl($_product, array('qty' => $_price['price_qty']))
          : '';
      if(!$this->getInGrouped()) { ?>
        var newLink = {
          url: "<?php echo $addToCartUrl; ?>",
          qty: "<?php echo $_price['price_qty']?>"
        };
        <?php
      } else {
        ?>
        var newLink = {
          url: "<?php echo $addToCartUrl; ?>",
          notUseForm: true
        };
        <?php
      }
      ?>
      Catalog.Map.addHelpLink(
        $('<?php echo $popupId ?>'),
        "<?php echo $_product->getName() ?>",
        <?php echo json_encode($_price['real_price_html']) ?>,
        "<?php echo $this->helper('core')->currency($_product->getMsrp(),true,false) ?>",
        newLink
      );
      <?php
      echo "</script>";
    } else {
      echo "<span class='msrp-price-hide-message'>";
      echo $_catalogHelper->getMsrpPriceMessage($_product);
      echo "</span>";
    }
    echo "</li>";
  }
  echo "</ul></div>";
}
