<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Improved Layered Navigation
*/
?>
<?php
/**
 * @var $this Amasty_Shopby_Block_Catalog_Layer_Filter_Attribute
 */

$class = "";
if($this->getCollapsed() && !$this->getHasSelection()) {
  $class .= " no-display-current";
}
if($this->getSingleChoice()) {
  $class .= " single-choice";
}
if($this->getSortFeaturedFirst() && in_array($this->getDisplayType(), [Amasty_Shopby_Model_Source_Attribute::DT_LABELS_ONLY, Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_AND_LABELS])) {
  $class .= " sort-featured-first-".$this->getRequestValue();
}
$class = trim((string) $class);
echo "<ol class='{$class}'>";
if($this->getSortFeaturedFirst()) { ?>
  <input type="hidden" id="field_sort_featured_<?=$this->getRequestValue()?>" value="default_sort">
<?php
}

$items = $this->getItemsAsArray();

foreach($items as &$item) {
  $item["url"] = (string) ($item["url"] ?? "");
  $item["url"] = str_replace("&amp;", "&", $item["url"]); // @todo fix upstream
  // dump($url);
}
unset($item);

switch ($this->getDisplayType()) {
  case Amasty_Shopby_Model_Source_Attribute::DT_LABELS_ONLY:
    if($this->getShowSearch()) {
      echo '<li rel="search"><input type="text" class="amshopby_attr_search input-text" onkeyup="amshopby_attr_search(this)"></li>';
    }
    foreach($items as $item) {
      if(strtolower((string) $item['label']) !== "n.v.t.") {

        $count = $item["countValue"];
        if(is_numeric($count) && $count > 1000) {
          $count = "1000+";
        }
        $count = "<span class='count'>({$count})</span>";

        $label = (string) $item['label'];
        if(strlen($label) > 27) {
          $label = substr($label, 0, 24)."...";
        }

        $checkbox_html = (stripos((string) $item['css'], "amshopby-attr-selected") !== false) ? '<span class="amshopby-choice"></span>' : '';
        echo '<li'.
          (isset($item['style']) ? ' '.$item['style'] : '') .
          (isset($item['default_sort']) ? ' data-default_sort="' . $item['default_sort'] . '"': '') .
          (isset($item['featured_sort']) ? ' data-featured_sort="' . $item['featured_sort'] . '"': '') .
          ' data-text="' . htmlspecialchars((string) $item['label']) . '"> ' .
          '<a class="'.$item['css'].'"' . $item['rel'] . ' href="'.$item['url'].'" data-config=\''.$item['data-config'].'\' title="'. $item['label'] .'" rel="nofollow">'. $label . $count . '</a>'.$checkbox_html.'</li>'.PHP_EOL;
      }
    }
  break;

  case Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_ONLY:
    echo '<li>';
    foreach($items as $item) {
      if(isset($item['image_hover']) && $item['image_hover'] != '') {
        echo '<img src="' . $item['image_hover'] . '" style="display: none;">';
        $onHover = 'onmouseover=this.src="' . $item['image_hover'] . '"'; 
        $onHover .= ' onmouseout=this.src="' . $item['image'] . '"';
      } else {
        $onHover = '';
      }
      echo '<a '.$item['style'].$item['rel'].' class="'.$item['css'].'" href="'.$item['url'].'" data-config=\' '.$item['data-config'].'\' ><img src="'.$item['image'].'" ' . $onHover . ' title="'. $item['label'] .'" alt="'. $item['label'] .'"></a>';

    }
    echo '</li>';
  break;

  case Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_AND_LABELS:
    if($this->getShowSearch()){
      echo '<li rel="search"><input type="text" class="amshopby_attr_search"></li>';
    }
    foreach($items as $item) {
      $count = $item['count'];
      if(is_numeric($count) && $count > 1000) {
        $count = "1000+";
      }
      echo '<li '.$item['style'].
				(isset($item['default_sort']) ? ' data-default_sort="' . $item['default_sort'] . '"': '') .
				(isset($item['featured_sort']) ? ' data-featured_sort="' . $item['featured_sort'] . '"': '') .
				' data-text="' . htmlspecialchars((string) $item['label']) . '"><a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'" data-config=\' '.$item['data-config'].'\' >';

      if(isset($item['image_hover']) && $item['image_hover'] != '') {
        echo '<img src="' . $item['image_hover'] . '" style="display: none;">';
        $onHover = 'onmouseover=this.src="' . $item['image_hover'] . '"'; 
        $onHover .= ' onmouseout=this.src="' . $item['image'] . '"';
      } else {
        $onHover = '';
      }

      if(!empty($item['image'])){
        echo '<img src="'.$item['image'].'" ' . $onHover . ' title="'. $item['label'] .'" alt="'. $item['label'] .'">';
      }
      echo $item['label'] . $count . '</a>' . '</li>';
    }
  break;

  case Amasty_Shopby_Model_Source_Attribute::DT_DROPDOWN:
    echo '<li><select onchange="if(this.value) window.location.href = this.value" class="amshopby-select amshopby-ajax-select">';
    echo '<option value="'.$this->getRemoveUrl().'" data-config=\' '.$this->getRemoveOptionConfig().' \'>'.Mage::helper('amshopby')->__('Selecteer ...').'</option>';
    foreach($items as $item) {
      $count = $item['count'];
      if(is_numeric($count) && $count > 1000) {
        $count = "1000+";
      }
      echo '<option '.$item['css'] . $item['rel'] . ' value="'.$item['url'].'" data-config=\' '.$item['data-config'].'\'>'. $item['label'] . $count . '</option>';
    }
    echo '</select></li>';
  break;

  case Amasty_Shopby_Model_Source_Attribute::DT_LABELS_IN_2_COLUMNS:
    $size  = sizeof($items);
    $half  =  ceil($size/2);

    echo '<li>';
    echo '<div class="amshopby-column">';
    for ($i = 0; $i < $half; $i++) {
      $item = $items[$i];
      $count = $item['count'];
      if(is_numeric($count) && $count > 1000) {
        $count = "1000+";
      }
      echo '<a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'" data-text="' . htmlspecialchars((string) $item['label']) . '" data-config=\' '.$item['data-config'].'\' >'. $item['label'] . $count . '</a>' . '<br>';
    }
    echo '</div>';
    echo '<div class="amshopby-column">';
    for ($i = $half; $i < $size; $i++) {
      $item = $items[$i];
      $count = $item['count'];
      if(is_numeric($count) && $count > 1000) {
        $count = "1000+";
      }
      echo '<a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'" data-text="' . htmlspecialchars((string) $item['label']) . '" data-config=\' '.$item['data-config'].'\'   >'. $item['label'] . $count . '</a>' . '<br>';
    }
    echo '</div>';
    echo '</li>';
  break;
}

if($this->getShowLessMore() && in_array($this->getDisplayType(), [
    Amasty_Shopby_Model_Source_Attribute::DT_LABELS_ONLY,
    Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_ONLY,
    Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_AND_LABELS,
  ])) {
  $total = count($items);
  $short = $this->getMaxOptions();
  $countSelectedOptions = $this->getCountSelectedOptions();

  $add = $countSelectedOptions > $short ? $total - $countSelectedOptions : $total - $short;
  if($add > 0) {
    $text = sprintf($this->__('Meer opties'), $add);
    echo "<li class='amshopby-clearer'><a id='amshopby-more-{$this->getRequestValue()}' class='amshopby-more' href='#'>{$text}</a></li>";
  }
  $text = $this->__('Minder opties');
  echo "<li class='amshopby-clearer'><a id='amshopby-less-{$this->getRequestValue()}' class='amshopby-less' href='#' style='display:none'>{$text}</a></li>";
} 
?>
</ol>
