<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */

$_displayType         = $this->getDisplayType();
$_multiselectEnabled  = Mage::helper('amshopby')->getCategoriesMultiselectMode();
// $_showCount           = !$this->getData('hide_counts');
$_showCount           = false; // Too expensive
$_maxOptions          = max(0, Mage::getStoreConfig('amshopby/category_filter/categories_max_options'));

if(Amasty_Shopby_Model_Catalog_Layer_Filter_Category::DT_ADVANCED != $_displayType) {
  $_items = $this->getItems();
  foreach($_items as $item) {
    if($item->getIsSelected()) {
      $_maxOptions = 0;
      break;
    }
  }
}

$renderedItemsCount = 0;
$_toggleClasses = ' amshopby-cat-toggle amshopby-cat-toggle-hidden';
$highest_level = 0;

?>
<ol <?php if ($this->getCollapsed() && !$this->getHasSelection()) echo 'class="no-display-current"'?>  >
<?php if (in_array($_displayType, array(
      Amasty_Shopby_Model_Catalog_Layer_Filter_Category::DT_DEFAULT, 
      Amasty_Shopby_Model_Catalog_Layer_Filter_Category::DT_WSUBCAT,
    ))): ?>
  <?php foreach ($_items as $_item):
    $level          = $_item->getLevel();
    $highest_level  = max($highest_level, $level);
    // if($_item->getLevel() < 1) {
      // continue;
    // }
    if($_item->getLevel() > 2) {
      continue;
    }
    $count = $_item->getCount();
    if($count > 1000) {
      $count = "1000+";
    }
    $label = trim(str_replace("[V]", "", $_item->getLabel())); // DHH CORE HACK
    $title = $label;
    if(strlen($label) > 29) {
      $label = substr($label, 0, 27)."..";
    }
    $class = 'amshopby-cat-level-'.max(0, $_item->getLevel());
    if ($_multiselectEnabled) {
      $class .= ' amshopby-cat-multi';
      $class .= ($_item->getIsSelected() ? ' amshopby-cat-multiselected' : '');
    }
    if ($_maxOptions && $renderedItemsCount++ >= $_maxOptions) {
      $class .= $_toggleClasses;
    }
    $a_class = "";
    if($_item->getLevel() === 1) {
      $a_class .= "amshopby-cat-selected";
    }
    ?>
    <li class="<?php echo $class ?>">
      <?php
      if ($_item->getIsSelected()) {
        if ($_multiselectEnabled) {
          echo '<a class="amshopby-attr {$a_class}" href="'.$this->urlEscape($_item->getUrl())  .'" data-config = \''. $_item->getApplyData() .' \' title="'.$title.'">';
        }
        echo $label;
        if ($_showCount && $count) {
          ?><span class="count">(<?php echo $count ?>)</span><?php
        }
        if ($_multiselectEnabled) {
          echo '</a>';
        }
      } else {
        ?>
        <a class="amshopby-cat <?php echo $a_class ;?>" href="<?php echo $this->urlEscape($_item->getUrl()) ?>" data-config=' <?php echo $_item->getApplyData(); ?>' title="<?php echo $title; ?>">
          <?php
          echo $label;
          if ($_showCount && $count) {
            ?><span class="count">(<?php echo $count; ?>)</span><?php
          }
          ?>
        </a>
      <?php } ?>
    </li>
  <?php endforeach ?>
<?php elseif (Amasty_Shopby_Model_Catalog_Layer_Filter_Category::DT_STATIC2LVL == $_displayType): ?>
  <?php foreach ($_items as $_item): ?>
    <?php
      $level          = $_item->getLevel();
      $highest_level  = max($highest_level, $level);
      $additional     = $_item->getIsFolded() ? 'style="display:none"' : '';

      $class    = 'amshopby-cat-level-'.$level;
      if (1 != $level){
        $class .= ' amshopby-cat-parentid-'.$_item->getParentId();
      } else {
        $renderedItemsCount++;
      }
      if ($_maxOptions && $renderedItemsCount > $_maxOptions) {
        $class .= $_toggleClasses;
      }

      $showIcon = (1 == $level && $_item->getHasChildren());
      $withoutIcon = (1 == $level && !$_item->getHasChildren());
      $icon = ($_item->getIsChildSelected()) ? 'minus': 'plus';
    ?>
    <li class="<?php echo $class?> static-2-level <?php echo ($withoutIcon) ? 'without-icon': '';?>" <?php echo $additional?>>
      <?php if ($showIcon): ?><span id="amshopby-cat-id-<?php echo $_item->getId()?>" class="amshopby-plusminus <?php echo $icon?>"></span><?php endif ?>
      <a <?php if ($_item->getIsSelected()):?>class="amshopby-cat-selected"<?php endif?> href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $label ?></a>
      <?php if ($_showCount && $count):?>
        <span class="count">(<?php echo $count ?>)</span>
      <?php endif;?>
    </li>
  <?php endforeach ?>
<?php elseif (Amasty_Shopby_Model_Catalog_Layer_Filter_Category::DT_DROPDOWN == $_displayType): ?>
  <li class="amshopby-category-select">
    <select onchange="if (this.value) window.location.href = value" class="amshopby-select">
      <!-- uncomment to show Filter name in the dropdown <option value=""><?php echo $this->getName() ?></option>-->
      <option value="">&nbsp;</option>
      <?php foreach ($_items as $_item): ?>
      <option  value="<?php echo $this->urlEscape($_item->getUrl()) ?>">
        <?php echo $label ?>
        <?php if ($_showCount && $count):?>
          <span class="count">(<?php echo $count ?>)</span>
        <?php endif;?>
      </option>
      <?php endforeach ?>
    </select>
  </li>
  <?php elseif (Amasty_Shopby_Model_Catalog_Layer_Filter_Category::DT_ADVANCED == $_displayType): ?>
    <li class="amshopby-advanced">
      <ol>
        <?php
        $advancedBlock = Mage::getSingleton('core/layout')
          ->createBlock('amshopby/advanced')
          ->setToggleClasses($_toggleClasses);
        $advancedBlock->setFilterModel($this->getFilterModel());
        // Prevent caching like it done in Magento code
        echo $advancedBlock->getHtml();
        $_maxOptions = $advancedBlock->getMaxOptions();
        $renderedItemsCount = $advancedBlock->getRenderedItemsCount();
        ?>
      </ol>
    </li>
  <?php endif ?>
<?php
  $add = $renderedItemsCount - $_maxOptions;
  if ($add > 0 && $_maxOptions > 0) {
    $text = sprintf($this->__('View %d More'), $add);
    echo '<li class="amshopby-clearer amshopby-cat-level-'.$highest_level.'"><a id="amshopby-category-more" href="#">'.$text.'</a></li>';
    echo '<li class="amshopby-clearer amshopby-cat-level-'.$highest_level.'"><a id="amshopby-category-less" href="#" style="display:none">'.$this->__('Show Less').'</a></li>';
  }
?>
</ol>
