<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
$_filters = $this->getActiveFilters();
if(!empty($_filters)) {
  $_removeTxt = Mage::helper('catalog')->__('Remove This Item');
  echo "<div class='amshopby-active-filters'>";
  echo "<div class='mb-2'><span class='h2 strong blue'>Actieve Filters</span></div>";
  echo "<div class='currently'>";
  echo "<ol>";
  foreach($_filters as $_filter) {
    if($_filter->hasData('children')) {
      $value = [];
      foreach($_filter->getData('children') as $child) {
        $value[] = $child['label'];
      }
    } else {
      $value = (array) $_filter->getLabel();
    }
    $label = Mage::helper('catalog')->__($_filter->getName());
    // var_dump($label);
    echo "<li class='mb-3'>";
    echo "<a href='{$_filter->getRemoveUrl()}' class='btn-remove' title='{$_removeTxt}'></a>";
    echo "<span class='label strong me-1'>{$label}:</span>";
    if(is_array($value)) {
      echo "<ul class='indented-disc'><li>".implode("</li><li>", $value)."</li></ul>";
    } else {
      echo $value;
    }
    echo "</li>";
  }
  echo "</ol>";
  echo "</div>";
  echo "<div class='actions'><a class='float-left' href='{$this->getParentBlock()->getClearUrl()}'>Filters verwijderen</a></div>";
  echo "</div>";
}
