<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php $_removeTxt = Mage::helper('catalog')->__('Remove This Item') ?>
<?php if (!empty($_filters)): ?>
  <ul>
    <?php foreach ($_filters as $_filter):?>
      <li>
        <?php if ($_filter->hasData('children')): ?>
          <?php foreach ($_filter->getData('children') as $child): ?>
            <span class="multiselect-child">
              <?php echo $child['label']  ?>
              <a href="<?php echo $child['url'] ?>" class="btn-remove-inline" title="<?php echo $_removeTxt ?>"></a>
              <span class="label strong"><?php echo Mage::helper('catalog')->__($_filter->getName()) ?>:</span>
            </span>
          <?php endforeach ?>
        <?php else: ?>
          <a href="<?php echo $_filter->getRemoveUrl() ?>" class="btn-remove" title="<?php echo $_removeTxt ?>"></a>
          <span class="label strong"><?php echo Mage::helper('catalog')->__($_filter->getName()) ?>:</span>
          <?php echo $_filter->getLabel() ?>
        <?php endif ?>
      </li>
    <?php endforeach; ?>
  </ul>
  <div class="actions">
    <a href="<?php echo $this->getParentBlock()->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a>
  </div>
<?php endif; ?>
