<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */

/** @var Amasty_Shopby_Block_Subcategories $this */
/** @var Mage_Catalog_Model_Resource_Category_Collection|Mage_Catalog_Model_Resource_Category_Flat_Collection $subcategories */
$subcategories = $this->getSubcategories();

$media_url = Mage::getBaseUrl('media');
$media_path = Mage::getBaseDir('media');
echo '<div style="clear: both;"></div>';
if ($subcategories->getSize()) {
  echo '<ul class="category-grid">';
  foreach($subcategories as $category) {
    $haschild       = true;
    $category       = Mage::getModel('catalog/category')->load($category->getId());
    $categoryName   = $category->getName();
    $image          = $category->getImage();
    $measurements   = null;
    $img_url        = "{$media_url}/catalog/category/{$image}";
    $img_path       = "{$media_path}/catalog/category/{$image}";
    
    if(is_file($img_path) === true) {
      try {
        $meta = getimagesize($img_path);
        $measurements = $meta[3];
      } catch (Exception $e) {
        $image = null;
        Mage::log("Error while trying to getimagesize() on {$img_file}: ".$e->getMessage(), null, 'system.log', true);
      }
    } else {
      $image = null;
    }
    ?>
    <li>
      <a href="<?php echo $category->getUrl() ?>" title='<?php echo $categoryName; ?>'>
        <?php if(empty($image) === false) echo "<img class='category-thumb' src='{$img_url}' alt='{$categoryName}' title='{$categoryName}' {$measurements} />"; ?>
        <strong><?php echo $categoryName; ?></strong>
      </a>
    </li>
    <?php
  }
  echo "</ul>";
}
