<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */

/** @var Amasty_Shopby_Block_Subcategories $this */
/** @var Mage_Catalog_Model_Resource_Category_Collection|Mage_Catalog_Model_Resource_Category_Flat_Collection $subcategories */
$subcategories = $this->getSubcategories();

$media_url = Mage::getBaseUrl('media');
$media_path = Mage::getBaseDir('media');
echo '<div style="clear: both;"></div>';
if ($subcategories->getSize()) {
  echo '<ul class="products-grid-anchor">';
  foreach($subcategories as $cat) {
    $haschild = true;
    $category = Mage::getModel('catalog/category')->load($cat->getId());
    $categoryName = $category->getName();
    $image = $category->getImage();
    $measurements = null;
    $url = $this->escapeUrl($cat->getFilteredUrl()? $cat->getFilteredUrl(): $cat->getUrl());
    
    if(empty($image) === true) {
      $image = "category_placeholder.png";
      $measurements = "height=130 width=246";
    }
    
    if(is_file($img_file) === true) {
      try {
        $meta = getimagesize($img_file);
        $measurements = $meta[3];
      } catch (Exception $e) {
        $image = "category_placeholder.png";
        $measurements = "height=130 width=246";
        Mage::log("Error while trying to getimagesize() on {$img_file}: ".$e->getMessage(), null, 'system.log', true);
      }
    }
    
    $img_url = "{$media_url}catalog/category/{$image}";
    $img_path = "{$media_path}catalog/category/{$image}";    
    ?>
    <li class="item big-tile highlight-hover">
      <a href="<?php echo $url; ?>">
        <div class="imwrapcat">
          <?php
          echo "<img class='center category-thumb' src='{$img_url}' alt='{$categoryName}' title='{$categoryName}' />";
          ?>
        </div>
        <strong class="float-left uppercase center bold"><?php echo $categoryName; ?></strong>
        <i class="float-right fa fa-arrow-right" aria-hidden="true"></i>
      </a>
    </li>
    <?php
  }
  echo "</ul>";
}
