<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */

$category_thumbs_actual       = 140;

/** @var Amasty_Shopby_Block_Subcategories $this */
/** @var Mage_Catalog_Model_Resource_Category_Collection|Mage_Catalog_Model_Resource_Category_Flat_Collection $subcategories */
$subcategories = $this->getSubcategories();

echo '<div style="clear: both;"></div>';

// require_once MAGENTO_ROOT."/app/code/local/DeHeerHoreca/Util/Helper/Util.php";

// $carct = Mage::registry("current_category");
// // $allowed_children = array_diff($carct->getChildren(), EXCLUDED_CATEGORY_IDS);
// $allowed_children = $carct->getChildren();
// $subcategories = $carct->getCollection()
  // ->addIdFilter($allowed_children)
  // ->addAttributeToSelect("url_key")
  // ->addAttributeToSelect("name")
  // ->addAttributeToSelect("all_children")
  // ->addAttributeToSelect("is_anchor")
  // ->addAttributeToSelect("image")
  // ->addAttributeToFilter("is_active", 1)
  // ->setOrder("position", Varien_Db_Select::SQL_ASC)
  // ->joinUrlRewrite();
// // $subcategories->addAttributeToSelect("image");

if($subcategories->count() > 1) {
  $media_path = Mage::getBaseDir('media');
  
  echo "<ul class='grid-shadow-tiles-text'>".PHP_EOL;
    
  // Logic copied to amasty/amshopby/subcategories.phtml
  $category_thumbs_dimensions = $category_thumbs_actual * 1.5;
  
  foreach($subcategories as $i => $subcategory) {
    if(in_array($subcategory->getId(), EXCLUDED_CATEGORY_IDS) !== false) {
      continue;
    }
    $haschild           = true;
    $category_name      = Mage::helper("deheerhoreca_util/util")->cleanCategoryName($subcategory->getName());
    $category_name_safe = htmlspecialchars($category_name);
    $image              = $subcategory->getImage();
    $category_url       = $subcategory->getUrl();
    $img_path           = "{$media_path}/catalog/category/{$image}";
    $resized_img_name   = $category_thumbs_dimensions."_{$subcategory->getId()}.".pathinfo($img_path, PATHINFO_EXTENSION);;
    $resized_img_path   = Mage::getBaseDir(Mage_Core_Model_Store::URL_TYPE_MEDIA).DS."catalog/category/resized".DS.$resized_img_name;
    $resized_img_url    = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."catalog/category/resized".DS.$resized_img_name;
    $lazy               = ($i < 5) ? "loading=lazy " : "";
    
    if(is_file($resized_img_path) === false && is_file($img_path) === true) {
      $imageObj = new Varien_Image($img_path);
      $imageObj->constrainOnly(true);
      $imageObj->keepAspectRatio(true);
      $imageObj->keepFrame(true);
      $imageObj->backgroundColor([255, 255, 255]);
      $imageObj->resize($category_thumbs_dimensions, $category_thumbs_dimensions);
      $imageObj->save($resized_img_path);
    }
    echo "<li style='max-width: 180px;'>";
    echo "<a href='{$category_url}' title='{$category_name_safe}'>";
    if(empty($image) === false) {
      echo "<img class='trans-opacity' src='{$resized_img_url}' alt='{$category_name}' title='{$category_name}' {$lazy}height='{$category_thumbs_actual}' width='{$category_thumbs_actual}'>";
    }
    echo "<strong>{$category_name}</strong>";
    echo "</a></li>".PHP_EOL;
  }
  echo "</ul>".PHP_EOL;
  if($haschild === true) {
    echo "<style>#sidebar-nav {display: block;}</style>";
  }
}
