; Note: Mixed config between .user.ini, php.ini and Plesk. .user.ini and php.ini are preferred over Plesk.
;
; Only INI settings with the modes PHP_INI_PERDIR, PHP_INI_USER and PHP_INI_ALL will be recognized in .user.ini-style INI files.
; @see https://www.php.net/manual/en/ini.list.php

; suhosin.session.encrypt                                  = Off
max_execution_time                                        = 1800
session.auto_start                                        = Off
; suhosin.session.cryptua                                   = Off
session.cookie_samesite                                   = Lax
session.cookie_secure                                     = 1
display_errors                                            = Off
display_startup_errors                                    = Off
error_log                                                 = php_error.log
error_reporting                                           = E_ALL & ~E_DEPRECATED & ~E_STRICT
expose_php                                                = Off
open_basedir                                              = 

; https://haydenjames.io/set-monitor-phps-realpath_cache_size-correctly/
realpath_cache_size                                       = 1M
realpath_cache_ttl                                        = 300

[opcache]
; https://github.com/loekvangool/deheerhoreca-operations/edit/master/magento/magento1_opcache.md
; https://gist.github.com/rohankhudedev/1a9c0a3c7fb375f295f9fc11aeb116fe
; https://www.php.net/manual/en/opcache.configuration.php
; opcache.max_accelerated_files: find . -iname \*.php | wc -l 19184
opcache.error_log                                         = php_opcache_error.log
opcache.log_verbosity_level                               = 1
opcache.memory_consumption                                = 128
opcache.interned_strings_buffer                           = 16
opcache.max_accelerated_files                             = 32531
opcache.validate_timestamps                               = 0
opcache.revalidate_freq                                   = 600
opcache.validate_root                                     = 0

; Suspecting that enabling this creates issues with not-found classes after clearing opcache:
opcache.enable_file_override                              = 0

opcache.max_wasted_percentage                             = 15
opcache.huge_code_pages                                   = 1
opcache.file_cache                                        = /dev/shm/openmage/php-opcache
; opcache.jit                                               = tracing ; From PHP 8.4
opcache.jit                                               = 1255
opcache.jit_buffer_size                                   = 32M

[mysqlnd]
mysqlnd.collect_statistics                                = Off
mysqlnd.collect_memory_statistics                         = Off

[php-fpm-pool-settings]
; https://serverfault.com/questions/1025518/php-fpm-nginx-issue-runs-fine-for-a-hours-then-maxes-fpm-children-in-a-matter
; One second less than max_execution_time
request_terminate_timeout                                 = 1799
; https://support.plesk.com/hc/en-us/articles/13303705093783-How-to-configure-the-PHP-FPM-plugin-of-360-Monitoring-on-a-Plesk-server
pm.status_path                                            = /fpm-status

[elastic-apm]
elastic_apm.enabled                                       = 1
elastic_apm.log_level_syslog                              = WARNING
elastic_apm.log_level_stderr                              = WARNING
elastic_apm.service_name                                  = openmage-php
elastic_apm.server_timeout                                = 2s
elastic_apm.transaction_max_spans                         = 50
elastic_apm.verify_server_cert                            = false
elastic_apm.span_compression_enabled                      = true
elastic_apm.profiling_inferred_spans_enabled              = false
elastic_apm.profiling_inferred_spans_sampling_interval    = 100ms
elastic_apm.profiling_inferred_spans_min_duration         = 100ms

# By default skip breaking of metrics, enable when interested in seeing performance details:
elastic_apm.breakdown_metrics                             = false

; Required certain admin actions
max_input_vars                                            = 10000
