; Note: Mixed config between .user.ini, php.ini and Plesk. .user.ini and php.ini are preferred over Plesk.
;
; - etc/php-plesk.ini: To be put into "Additional directives" in Plesk
;
; Only INI settings with the modes PHP_INI_PERDIR, PHP_INI_USER and PHP_INI_ALL will be recognized in .user.ini-style INI files.
; @see https://www.php.net/manual/en/ini.list.php

; suhosin.session.encrypt                                = off
max_execution_time                                      = 1800
session.auto_start                                      = off
suhosin.session.cryptua                                 = off
session.cookie_samesite                                 = Lax
session.cookie_secure                                   = 1
log_errors_max_len                                      = 0
error_log                                               = /var/www/vhosts/chefstore.nl/logs/deheerhoreca-magento/php_error.log
expose_php                                              = Off

; https://haydenjames.io/set-monitor-phps-realpath_cache_size-correctly/
open_basedir                                            = 
realpath_cache_size                                     = 1M
realpath_cache_ttl                                      = 300

[opcache]
; https://github.com/loekvangool/deheerhoreca-operations/edit/master/magento/magento1_opcache.md
; https://gist.github.com/rohankhudedev/1a9c0a3c7fb375f295f9fc11aeb116fe
; https://www.php.net/manual/en/opcache.configuration.php
; opcache.max_accelerated_files: find . -iname \*.php | wc -l 19184
opcache.error_log                                       = /var/www/vhosts/chefstore.nl/logs/deheerhoreca-magento/php_opcache.log
opcache.log_verbosity_level                             = 2
opcache.memory_consumption                              = 64
opcache.interned_strings_buffer                         = 12
opcache.max_accelerated_files                           = 32531
opcache.validate_timestamps                             = 0
opcache.revalidate_freq                                 = 300
opcache.validate_root                                   = 0
opcache.enable_file_override                            = 1
opcache.max_wasted_percentage                           = 15
opcache.huge_code_pages                                 =1
; Needs investigation: opcache.revalidate_path          =0

[mysqlnd]
mysqlnd.collect_statistics                              = Off
mysqlnd.collect_memory_statistics                       = Off

[php-fpm-pool-settings]
; https://serverfault.com/questions/1025518/php-fpm-nginx-issue-runs-fine-for-a-hours-then-maxes-fpm-children-in-a-matter
; One second less than max_execution_time
request_terminate_timeout                               = 1799
; https://support.plesk.com/hc/en-us/articles/13303705093783-How-to-configure-the-PHP-FPM-plugin-of-360-Monitoring-on-a-Plesk-server
pm.status_path                                          = /fpm-status

; Necessary for cart2quote, but incompatible with Elastic APM
; zend_extension                                        = ioncube_loader_lin_7.4.so ; does not work

[elastic-apm]
elastic_apm.service_name                                = "deheerhoreca-openmage"
elastic_apm.server_timeout                              = 10s
elastic_apm.transaction_max_spans                       = 250
elastic_apm.verify_server_cert                          = 0
elastic_apm.log_level_syslog                            = "WARNING"
elastic_apm.log_level_stderr                            = "WARNING"
