log_errors                                                = On
max_execution_time                                        = 7200
memory_limit                                              = 4g
error_reporting                                           = E_ALL & ~E_DEPRECATED & ~E_STRICT
error_log                                                 = php_error.log
open_basedir                                              = 
expose_php                                                = Off

; This is only for CLI, so we display errors:
display_errors                                            = On
display_startup_errors                                    = On

; https://haydenjames.io/set-monitor-phps-realpath_cache_size-correctly/
realpath_cache_size                                       = 1M
realpath_cache_ttl                                        = 600

; Sometimes we have big stuff. Also needs to be added to open_basedir
upload_tmp_dir                                            = /tmp_intel
sys_temp_dir                                              = /tmp_intel

[opcache]
; https://github.com/loekvangool/deheerhoreca-operations/edit/master/magento/magento1_opcache.md
; https://gist.github.com/rohankhudedev/1a9c0a3c7fb375f295f9fc11aeb116fe
; https://www.php.net/manual/en/opcache.configuration.php
;
; - find . -iname \*.php | wc -l => 19184 | But in practice, the growth stalls around ±6500 keys.
;   - opcache.max_accelerated_files:
; - If disabled, existing cached files using the same include_path will be reused.
;   Thus, if a file with the same name is elsewhere in the include_path, it won't be found.
;   - opcache.revalidate_path:
; - To prevent OPcache validating timestamps of files, all of these are needed.
;   - opcache.file_update_protection=0
;   - opcache.max_file_size=0
;   - opcache.validate_timestamps=Off:
; - Enabling this creates issues with not-found classes after clearing opcache.
;   - opcache.enable_file_override=Off
; - To prevent possible conflicts with files with the same name in different directories.
;   - opcache.use_cwd=On
;
opcache.enable_cli                                        = 1
opcache.enable_file_override                              = Off
opcache.error_log                                         = php_opcache_error.log
opcache.file_cache                                        =
opcache.file_cache_consistency_checks                     = Off
opcache.file_cache_only                                   = Off
opcache.file_update_protection                            = 2
opcache.huge_code_pages                                   = On
opcache.interned_strings_buffer                           = 64
opcache.log_verbosity_level                               = 1
opcache.max_accelerated_files                             = 16229
opcache.max_file_size                                     = 0
opcache.max_wasted_percentage                             = 15
opcache.memory_consumption                                = 196
opcache.revalidate_freq                                   = 0
opcache.revalidate_path                                   = On
opcache.save_comments                                     = On
opcache.use_cwd                                           = On
opcache.validate_root                                     = Off
opcache.validate_timestamps                               = On

; JIT creates segfaults etc. and is of little benefit < PHP 8.3
; opcache.jit                                               = tracing ; From PHP 8.4
opcache.jit                                               = Off
opcache.jit_buffer_size                                   = 0

[mysqlnd]
mysqlnd.collect_statistics                                = Off
mysqlnd.collect_memory_statistics                         = Off

[elastic-apm]
elastic_apm.enabled                                       = Off
elastic_apm.server_url                                    = https://rum.chefstore.nl:8200
elastic_apm.log_file                                      = php_apm_error.log
elastic_apm.log_level                                     = Off
elastic_apm.log_level_file                                = ERROR
elastic_apm.log_level_syslog                              = Off
elastic_apm.log_level_stderr                              = Off
elastic_apm.service_name                                  = openmage-php
elastic_apm.server_timeout                                = 30s
elastic_apm.transaction_max_spans                         = 50
elastic_apm.verify_server_cert                            = Off
elastic_apm.span_compression_enabled                      = On
elastic_apm.profiling_inferred_spans_enabled              = Off
elastic_apm.stack_trace_limit                             = 25
elastic_apm.capture_errors                                = On
elastic_apm.breakdown_metrics                             = Off
elastic_apm.disable_instrumentations                      = "DB"
elastic_apm.transaction_ignore_urls                       = "/media/fbminify/*,/media/catalog/*"

; If APCu is enabled, enable it for CLI as well (for cronjobs)
apc.enable_cli                                            = On
apc.enabled                                               = On
apc.entries_hint                                          = 16384
apc.gc_ttl                                                = 3600
apc.serializer                                            = igbinary
apc.shm_size                                              = 128M
apc.ttl                                                   = 3600
apc.use_request_time                                      = On
