log_errors                                              = On
max_execution_time                                      = 7200
memory_limit                                            = 4g
display_errors                                          = Off
display_startup_errors                                  = Off
error_reporting                                         = E_ALL & ~E_DEPRECATED & ~E_STRICT
open_basedir                                            = 

; https://haydenjames.io/set-monitor-phps-realpath_cache_size-correctly/
realpath_cache_size                                     = 1M
realpath_cache_ttl                                      = 300

; Sometimes we have big stuff. Also needs to be added to open_basedir
upload_tmp_dir                                          = /tmp_intel
sys_temp_dir                                            = /tmp_intel
open_basedir                                            = 

[mysqlnd]
mysqlnd.collect_statistics                              = Off
mysqlnd.collect_memory_statistics                       = Off

[elastic-apm]
; # Elastic APM 1.12.0 on PHP 8.1 -- BROKEN?
elastic_apm.enabled                                     = 0
elastic_apm.log_level_syslog                            = WARNING
elastic_apm.log_level_stderr                            = WARNING
elastic_apm.service_name                                = deheerhoreca-openmage-cli
elastic_apm.server_timeout                              = 10s
elastic_apm.transaction_max_spans                       = 100
elastic_apm.verify_server_cert                          = 0
