log_errors                                              = 1
memory_limit                                            = 4g
display_errors                                          = 0
display_startup_errors                                  = 0
error_reporting                                         = E_ALL & ~E_DEPRECATED & ~E_STRICT
open_basedir                                            = 

; https://haydenjames.io/set-monitor-phps-realpath_cache_size-correctly/
realpath_cache_size                                     = 1M
realpath_cache_ttl                                      = 300

open_basedir                                            = 

[opcache]
; OPCache -- @see https://stackoverflow.com/questions/25044817/zend-opcache-opcache-enable-cli-1-or-0-what-does-it-do
; opcache.file_cache: sudo mkdir -p /tmp/opcache/deheerhoreca-intel && sudo chmod -R 777 /tmp/opcache/deheerhoreca-intel
; opcache.max_accelerated_files: find . -iname \*.php | wc -l
; opcache.file_cache_only: Keep this on 0, tools command do not work if 1
; opcache.file_cache_fallback: Windows only
; opcache.interned_strings_buffer: 12 is too low, "Warning Interned string buffer overflow"
opcache.enable                                          = 1
opcache.enable_cli                                      = 1
opcache.error_log                                       = php_opcache_error.log
opcache.fast_shutdown                                   = 1
opcache.interned_strings_buffer                         = 64
opcache.file_cache                                      = 
opcache.file_cache_only                                 = 0
opcache.file_cache_consistency_checks                   = 0
opcache.file_update_protection                          = 2
opcache.huge_code_pages                                 = 1
opcache.log_verbosity_level                             = 1
opcache.memory_consumption                              = 96
opcache.max_accelerated_files                           = 32531
; opcache.revalidate_freq                                 = 2
opcache.validate_permission                             = 0
opcache.validate_root                                   = 0
opcache.validate_timestamps                             = 1
opcache.max_wasted_percentage                           = 15

[mysqlnd]
mysqlnd.collect_statistics                              = Off
mysqlnd.collect_memory_statistics                       = Off

[elastic_apm]
elastic_apm.enabled                                     = 1
elastic_apm.service_name                                = openmage
elastic_apm.verify_server_cert                          = 0
elastic_apm.log_file                                    = php_apm_error.log
elastic_apm.log_level_stderr                            = WARNING
elastic_apm.log_level_syslog                            = WARNING
elastic_apm.server_timeout                              = 2s
elastic_apm.span_compression_enabled                    = true
elastic_apm.stack_trace_limit                           = 25
elastic_apm.capture_errors                              = true
elastic_apm.transaction_max_spans                       = 50
elastic_apm.breakdown_metrics                           = false
elastic_apm.disable_instrumentations                    = "DB"
