<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2020] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category  Ophirah
 * @package   Qquoteadv
 * @copyright   Copyright (c) 2020 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license   https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 *
 *
 * This is the template file of the form fields.
 * The file is rendered two times:
 *    1. Shipping details
 *    2. Billing details
 * $formType will contain 'shipping' or 'billing'. The fields will contain the ID referring to this form type.
 *
 * @block Ophirah_Qquoteadv_Block_Form_Address
 */

/** @var Ophirah_Qquoteadv_Block_Form_Address $this */
/** @var Ophirah_Qquoteadv_Block_Qquoteaddress $parent */

$parent = $this->getParentBlock();
$formType = $this->getFormType();
$customerForCustomerIsEnabled = Mage::helper('qquoteadv')->customerForCustomerIsEnabled();
?>

<!-- ADDRESS START -->
<div id="<?= $this->getMainDiv() ?>" style="<?php //echo $this->getMainDivAllowToShow() ?>">
  <!-- ADDRESS DETAILS START -->
  <h3>Adresgegevens</h3>
  <p class="address-description"><?= $this->__($this->getAddressDescription()) ?></p>
  <!-- ADDRESS DETAILS END   -->

  <p class="address-selection">
    <?php if($parent->isCustomerLoggedIn() && !$customerForCustomerIsEnabled): ?>
    <!-- ADDRESS DROP DOWN START -->
    <?= Mage::helper('sales')->__('Select an address') ?>
    <?php //echo $this->getFieldRequiredSpan($this->getRequiredAddress()) ?>
  <p><?= $this->getListOfAddresses() ?></p>
  <!-- ADDRESS DROP DOWN END   -->
  <?php endif ?>
  </p>

  <!-- ADDRESS INPUT FORM START  -->
  <table style="<?php if(!$customerForCustomerIsEnabled): ?> display:none; <?php endif ?>" id="qquote-tbl-<?= $formType ?>" cellspacing='3' cellpadding='3' border="0" width="100%">
    <?php if (($parent->getPrefixSettings() != 0) || ($parent->getGenderSettings() != 0)): ?>
    <tr>
      <td class="left">
        <?php if($parent->getGenderSettings() != 0): ?>
        <input type='radio' value="1" name='<?= $this->getAddedFieldName() ?>[gender]' id='<?= $this->getAddedFieldName() ?>:gender' style="width: auto;" class="input-radio">
        <label for="<?= $this->getAddedFieldName() ?>:gender">De heer</label>
        <br>
        <input type='radio' value="2" name='<?= $this->getAddedFieldName() ?>[gender]' id='<?= $this->getAddedFieldName() ?>:gender' style="width: auto;" class="input-radio">
        <label for="<?= $this->getAddedFieldName() ?>:gender">Mevrouw</label>
        <br>
        <input type='radio' value="3" name='<?= $this->getAddedFieldName() ?>[gender]' id='<?= $this->getAddedFieldName() ?>:gender' style="width: auto;" class="input-radio">
        <label for="<?= $this->getAddedFieldName() ?>:gender">Anders</label>
        <?php endif ?>
      </td>
      <td class="p5">
        <?php if($parent->getPrefixSettings() != 0): ?>
        <label for="<?= $this->getAddedFieldName() ?>:prefix"><?= Mage::helper('sales')->__('Prefix') ?></label>
        <?= $this->getFieldRequiredSpan($parent->getPrefixSettings()) ?>
        <input type='text' value="<?= $parent->getValue('prefix', $formType) ?>" name='<?= $this->getAddedFieldName() ?>[prefix]' id='<?= $this->getAddedFieldName() ?>:prefix' class="<?= $this->getFieldRequiredClass($parent->getPrefixSettings()) ?> input-text">
        <?php endif ?>
      </td>
    </tr>
    <?php endif ?>
    <tr>
      <td class="left">
        <label for="<?= $this->getAddedFieldName() ?>:firstname"><?= Mage::helper('sales')->__('First Name') ?></label>
        <?= $this->getFieldRequiredSpan(true) ?>
        <input type='text' autocomplete="given-name" value="<?= $parent->getValue('firstname', $formType) ?>" name='<?= $this->getAddedFieldName() ?>[firstname]' id='<?= $this->getAddedFieldName() ?>:firstname' class="<?= $this->getFieldRequiredClass(true) ?> input-text">
      </td>
      <td class="p5">
        <label for="<?= $this->getAddedFieldName() ?>:lastname"><?= Mage::helper('sales')->__('Last Name') ?></label>
        <?= $this->getFieldRequiredSpan(true) ?>
        <input type='text' value="<?= $parent->getValue('lastname', $formType) ?>" name='<?= $this->getAddedFieldName() ?>[lastname]' id='<?= $this->getAddedFieldName() ?>:lastname' class="<?= $this->getFieldRequiredClass(true) ?> input-text">
      </td>
    </tr>
    <?php if (($parent->getMiddlenameSettings() != 0) || ($parent->getSuffixSettings() != 0)): ?>
    <tr>
      <td class="left">
        <?php if($parent->getMiddlenameSettings() != 0): ?>
        <label for="<?= $this->getAddedFieldName() ?>:middlename"><?= Mage::helper('sales')->__('Middle Name') ?></label>
        <?= $this->getFieldRequiredSpan($parent->getMiddlenameSettings()) ?>
        <input type='text' autocomplete="additional-name" value="<?= $parent->getValue('middlename', $formType) ?>" name='<?= $this->getAddedFieldName() ?>[middlename]' id='<?= $this->getAddedFieldName() ?>:middlename' class="<?= $this->getFieldRequiredClass($parent->getMiddlenameSettings()) ?> input-text">
        <?php endif ?>
      </td>
      <td class="p5">
        <?php if($parent->getSuffixSettings() != 0): ?>
        <label for="<?= $this->getAddedFieldName() ?>:suffix"><?= Mage::helper('sales')->__('Suffix') ?></label>
        <?= $this->getFieldRequiredSpan($parent->getSuffixSettings()) ?>
        <input type='text' autocomplete="honorific-suffix" value="<?= $parent->getValue('suffix', $formType) ?>" name='<?= $this->getAddedFieldName() ?>[suffix]' id='<?= $this->getAddedFieldName() ?>:suffix' class="<?= $this->getFieldRequiredClass($parent->getSuffixSettings()) ?> input-text">
        <?php endif ?>
      </td>
    </tr>
    <?php endif ?>
    <tr>
      <td class="left">
        <?php if($parent->getPhoneSettings() != 0): ?>
        <label for="<?= $this->getAddedFieldName() ?>:telephone"><?= Mage::helper('sales')->__('Telephone') ?></label>
        <?= $this->getFieldRequiredSpan($parent->getPhoneSettings()) ?>
        <input type='text' autocomplete="tel" value="<?= $parent->getValue('telephone', $formType) ?>" name='<?= $this->getAddedFieldName() ?>[telephone]' id='<?= $this->getAddedFieldName() ?>:telephone' class="<?= $this->getFieldRequiredClass($parent->getPhoneSettings()) ?> input-text">
        <?php endif ?>
      </td>
      <td class="p5">
        <?php
        if($parent->getCompanySettings() != 0): ?>
        <label for="<?= $this->getAddedFieldName() ?>:company"><?= Mage::helper('sales')->__('Company') ?></label>
        <?= $this->getFieldRequiredSpan($parent->getCompanySettings()) ?>
        <input type='text' autocomplete="organization" value="<?= $parent->getValue('company', $formType) ?>" name='<?= $this->getAddedFieldName() ?>[company]' id='<?= $this->getAddedFieldName() ?>:company' class="<?= $this->getFieldRequiredClass($parent->getCompanySettings()) ?> input-text">
        <?php endif ?>
      </td>
    </tr>
    <tr>
      <td class="left">
        <?php if($parent->getVatTaxSettings() != 0): ?>
        <label for="<?= $this->getAddedFieldName() ?>:vat_id"><?= Mage::helper('customer')->__('VAT Number') ?></label>
        <?= $this->getFieldRequiredSpan($parent->getVatTaxSettings()) ?>
        <input type='text' value="<?= $parent->getValue('vat_id', 'billing') ?>" name='<?= $this->getAddedFieldName() ?>[vat_id]' id='<?= $this->getAddedFieldName() ?>:vat_id' class="<?= $this->getFieldRequiredClass($parent->getVatTaxSettings()) ?> input-text">
        <?php endif ?>
      </td>
      <td class="p5">
      </td>
    </tr>
    <tr>
      <td class="left">
        <label for="<?= $this->getAddedFieldName() ?>:street1">Straat en huisnummer</label>
        <?= $this->getFieldRequiredSpan(true) ?>
        <?php for($i = 0; $i < $this->helper('customer/address')->getStreetLines(); $i++): ?>
        <?php
        if($i === 0) $placeholder = "Straat";
        if($i === 1) $placeholder = "Huisnummer";
        ?>
        <input onfocus="" type='text' autocomplete="<?=$formType?> address-line<?= ($i+1) ?>" value="<?= $parent->getValue('street' , $formType, $i) ?>" name='<?= $this->getAddedFieldName() ?>[street][<?= $i ?>]' id='<?= $this->getAddedFieldName() ?>:street<?=$i?>' placeholder='<?= $placeholder ?>' class="<?= $this->getFieldRequiredClass(!(bool)$i) ?> input-text street">
        <?php endfor ?>
      </td>
      <td class="p5 input-select">
        <label for="<?= $this->getAddedFieldName() ?>:country"><?= Mage::helper('sales')->__('Country') ?></label>
        <?= $this->getFieldRequiredSpan(true) ?>
        <?php $value = $parent->getValue('country_id', $formType);
        if (empty($value)) {
          $value = null;
        } ?>
        <?= Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect(
          $value,
          $this->getAddedFieldName().'[country_id]',
          $this->getAddedFieldName() . ':country',
          Mage::helper('sales')->__('Country'));
        ?>
      </td>
    </tr>
    <tr>
      <td class="left">
        <label for="<?= $this->getAddedFieldName() ?>:postcode"><?= Mage::helper('sales')->__('Zip/Postal Code') ?></label>
        <?= $this->getFieldRequiredSpan(true) ?>
        <input onfocus="" type='text' autocomplete="postal-code" value="<?= $parent->getValue('postcode', $formType) ?>" name='<?= $this->getAddedFieldName() ?>[postcode]' id='<?= $this->getAddedFieldName() ?>:postcode' class="<?= $this->getFieldRequiredClass(true) ?> input-text w224">
      </td>
      <td class="p5">
        <?php if ($parent->getStateSettings() > 0) { ?>
        <label for="<?= $this->getAddedFieldName() ?>:region_id" id="<?= $this->getAddedFieldName() ?>:country-state-label"><?= Mage::helper('sales')->__('State/Province') ?></label>
        <?= $this->getFieldRequiredSpan($this->getStateSettings()) ?>
        <select name='<?= $this->getAddedFieldName() ?>[region_id]' id='<?= $this->getAddedFieldName() ?>:region_id' title="<?= Mage::helper('sales')->__('State/Province') ?>" class="<?= $this->getFieldRequiredClass($this->getStateSettings()) ?> validate-select w224" style="display:none;">
          <option value=""><?= $parent->getValue('region_id', $formType) ?></option>
        </select>
        <input onfocus="" type="text" name='<?= $this->getAddedFieldName() ?>[region]' id='<?= $this->getAddedFieldName() ?>:region' value="<?= $parent->getValue('region', $formType) ?>" title="<?= Mage::helper('sales')->__('State/Province') ?>" class="<?= $this->getFieldRequiredClass($this->getStateSettings()) ?>  input-text w224" style="display:none;">
        <?php } else { ?>
        <input name='<?= $this->getAddedFieldName() ?>[region_id]' id='region_id' title="<?= Mage::helper('sales')->__('State/Province') ?>" type="hidden">
        <?php } ?>
      </td>
    </tr>
    <tr>
      <td class="left">
        <label for="<?= $this->getAddedFieldName() ?>:city"><?= Mage::helper('sales')->__('City') ?></label>
        <?= $this->getFieldRequiredSpan(true) ?>
        <input onfocus="" type='text' value="<?= $parent->getValue('city', $formType) ?>" name='<?= $this->getAddedFieldName() ?>[city]' id='<?= $this->getAddedFieldName() ?>:city' class="required-entry input-text w224">
      </td>
    </tr>
  </table>
  <br>
  <!-- END ADDRESS INPUT FORM -->
  <!-- EXTRA SHIPPING INFORMATION START -->
  <?php
  echo $this->getChildHtml('qquote.shipping.request');
  echo $this->getChildHtml('qquote.shipping.list');
  ?>
  <!-- EXTRA SHIPPING INFORMATION END -->
</div>
<!-- ADDRESS END -->

<?php if ($parent->getStateSettings() > 0) { ?>
<script>
new RegionUpdater('<?= $this->getAddedFieldName() ?>:country', '<?= $this->getAddedFieldName() ?>:region', '<?= $this->getAddedFieldName() ?>:region_id', <?= $this->helper('directory')->getRegionJson() ?>);
$('<?= $this->getAddedFieldName() ?>:region_id').addClassName('w224');
</script>
<?php } ?>
