<?php

$_links = $this->getLinks();
$_count = count($_links);                      /* Add or Remove Account Left Navigation Links Here - */

unset($_links['tags']);                        /* My Tags */
unset($_links['invitations']);                 /* My Invitations */
unset($_links['wishlist']);                    /* Wishlist */
unset($_links['enterprise_customerbalance']);  /* Store Credit */
unset($_links['OAuth Customer Tokens']);       /* My Applications */
unset($_links['enterprise_reward']);           /* Reward Points */
unset($_links['giftregistry']);                /* Gift Registry */
unset($_links['downloadable_products']);       /* My Downloadable Products */
unset($_links['recurring_profiles']);          /* Recurring Profiles */
unset($_links['billing_agreements']);          /* Billing Agreements */
unset($_links['enterprise_giftcardaccount']);  /* Gift Card Link */
?>

<div class="block block-account">
  <div class="block-title">
    <strong><span><?= $this->__('My Account'); ?></span></strong>
  </div>
  <div class="block-content">
    <ul>
      <?php $_index = 1; ?>
      <?php $_count = count($_links); ?>
      <?php foreach ($_links as $_link): ?>
      <?php $_last = ($_index++ >= $_count); ?>
      <?php if ($this->isActive($_link)): ?>
      <li class="current<?= ($_last ? ' last' : '') ?>"><a href="<?= $_link->getUrl() ?>"><strong><?= $_link->getLabel() ?></strong></a></li>
      <?php else: ?>
      <li<?= ($_last ? ' class="last"' : '') ?>><a href="<?= $_link->getUrl() ?>"><?= $_link->getLabel() ?></a></li>
        <?php endif; ?>
        <?php endforeach; ?>
        <li class="current strong">
          <a href="//service.chefstore.nl" target="_blank"><?= $this->__('Klantenservice'); ?></a>
        </li>
        <li class="current strong">
          <a href="<?= Mage::getUrl('customer/account/logout'); ?>"><?= $this->__('Uitloggen'); ?></a>
        </li>
    </ul>
  </div>
</div>
