<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Block_Adminhtml_Customer_Sales_Order_Address_Form_Renderer_Vat extends Mage_Adminhtml_Block_Customer_Sales_Order_Address_Form_Renderer_Vat
{
	/**
	 * Retrieve validate button block
	 *
	 * @return Mage_Adminhtml_Block_Widget_Button
	 */
	public function getValidateButton()
	{
		if (is_null($this->_validateButton)) {
			/** @var $form Varien_Data_Form */
			$form = $this->_element->getForm();

			$vatElementId = $this->_element->getHtmlId();

			$countryElementId = $form->getElement('country_id')->getHtmlId();

			$validateUrl = Mage::getUrl('adminhtml/euvat/validateSingleAddress', array('_secure'=>true));

			$groupSuggestionMessage = Mage::helper('customer')->__('The customer is currently assigned to Customer Group %s.')
				. ' ' . Mage::helper('customer')->__('Would you like to change the Customer Group for this order?');

			$vatValidateOptions = Mage::helper('core')->jsonEncode(array(
				'vatElementId' => $vatElementId,
				'countryElementId' => $countryElementId,
				'groupIdHtmlId' => 'group_id',
				'validateUrl' => $validateUrl,
				'vatValidMessage' => Mage::helper('customer')->__('The VAT ID is valid. The current Customer Group will be used.'),
				'vatValidAndGroupChangeMessage' => Mage::helper('customer')->__('Based on the VAT ID, the customer would belong to the Customer Group %s.')
					. "\n" . $groupSuggestionMessage,
				'vatInvalidMessage' => Mage::helper('customer')->__('The VAT ID entered (%s) is not a valid VAT ID. The customer would belong to Customer Group %s.')
					. "\n" . $groupSuggestionMessage,
				'vatValidationFailedMessage'    => Mage::helper('customer')->__('There was an error validating the VAT ID. The customer would belong to Customer Group %s.')
					. "\n" . $groupSuggestionMessage,
				'vatErrorMessage' => Mage::helper('customer')->__('There was an error validating the VAT ID.')
			));

			$optionsVarName = $this->getJsVariablePrefix() . 'VatParameters';

			$beforeHtml = '<script type="text/javascript">var ' . $optionsVarName . ' = ' . $vatValidateOptions	. ';</script>';

			$afterHtml = '<div id="response_'.$vatElementId.'" style="margin-top:1em"></div>';

			$this->_validateButton = $this->getLayout()->createBlock('adminhtml/widget_button')->setData(array(
				'label'       => Mage::helper('customer')->__('Validate VAT Number'),
				'before_html' => $beforeHtml,
				'after_html'  => $afterHtml,
				'onclick'     => 'order.validateVat(' . $optionsVarName . ')'
			));
		}
		return $this->_validateButton;
	}
}
