<?php
$abstractBlock  = $this->helper('awautorelated')->getAbstractProductBlock();
$collection     = $this->getCollection();
$_columnCount   = 3;
$i              = 0;
$max_items      = $_columnCount;

if(!empty($collection)) {
  Mage::getModel('cataloginventory/stock')->addItemsToProducts($collection); ?>
  <div id="autorelated-products" class="product-collateral category-products">
    <h2 class='tableftheader'>Bekijk ook eens</h2>
    <ul class='products-grid products-grid-mini'><?php
      foreach($collection as $_product) {
        if($i === $max_items) break;
        $i++; ?>
        <li class="item"><?php
          $options = [
            "image_size"              => 125,
            "_blank"                  => false,
            "use_short_product_names" => true,
            "display"                 => "mini",
            "skip_actions"            => true,
          ];
          echo Mage::helper("deheerhoreca_util/util")->getProductGridHtml($_product, $abstractBlock, $options); ?>
        </li><?php
      } ?>
    </ul>
  </div><?php
}
