<?php
/**
 * Magmodules.eu - http://www.magmodules.eu
 *
 * NOTICE OF LICENSE
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magmodules.eu so we can send you a copy immediately.
 *
 * @category    Magmodules
 * @package     Magmodules_Sooqr
 * @author      Magmodules <info@magmodules.eu>
 * @copyright   Copyright (c) 2019 (http://www.magmodules.eu)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/*** DHH THIS FILE IS NOT USED IT SEEMS...
STRANGE BUG THAT CAUSES THIS FILE TO BE IGNORED, INSTEAD app\design\frontend\rwd\dhh\template\catalogsearch\form.mini.phtml IS USED

2023-03-02 This file is used after all
*/

$catalogSearchHelper = $this->helper('catalogsearch');
// DHH: Removing URL from form because some users submitted it
// <form id="search_mini_form" action="<? php echo $catalogSearchHelper->getResultUrl() ? >" method="get">
$placeholder = "Waar ben je naar op zoek?";
$sooqr_options = $this->getSooqrOptions();
?>
<form id="search_mini_form">
  <div class="input-box">
    <input id="search" type="search" name="<?=$catalogSearchHelper->getQueryParamName()?>" value="<?=$catalogSearchHelper->getEscapedQueryText()?>" class="input-text" placeholder="<?=$placeholder?>">
  </div>
  <?php if ($this->multiSearch()): ?>
    <script>
      var _wssq = _wssq || [];
      _wssq.push(['_load', {'suggest': <?=json_encode($this->getSooqrOptions())?>}]);
      _wssq.push(['suggest._setPosition', 'screen-middle']);
      _wssq.push(['suggest._setLocale', '<?=$this->getSooqrLanguage()?>']);
      <?php if (!$this->isTrackingEnabled()) { ?>
        _wssq.push(['suggest._disableTracking']);
      <?php } ?>
    </script>
    <script>
      var _wssq = _wssq || [];
      _wssq.push(['_load', {'suggest': <?=json_encode($this->getSooqrOptions('second'))?>}]);
      _wssq.push(['suggest2._setPosition', 'screen-middle']);
      _wssq.push(['suggest2._setLocale', '<?=$this->getSooqrLanguage()?>']);
      <?php if (!$this->isTrackingEnabled()): ?>
        _wssq.push(['suggest2._disableTracking']);
      <?php endif; ?>
      (function () {
        var ws = document.createElement('script');
        ws.type = 'text/javascript';
        ws.async = true;
        ws.src = '//' + '<?=$this->getSooqrScriptUri()?>';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ws, s);
      })();
    </script>
  <?php
  // Code below is the one that is active
  else:
  ?>
    <script>
      var _wssq = _wssq || [];
      var setResizeFunction = false;
      var sooqrAccount = '<?=$sooqr_options["account"]?>';
      _wssq.push(['_load', {'suggest': <?=json_encode($sooqr_options)?>}]);
      _wssq.push(['suggest._setPosition', 'screen-middle', {
        top: 0
      }]);
      _wssq.push(['suggest._setLocale', '<?=$this->getSooqrLanguage()?>']);
      _wssq.push(['suggest._excludePlaceholders', '<?=$placeholder?>']);
      <?php if (!$this->isTrackingEnabled()) { ?>
        _wssq.push(['suggest._disableTracking']);
      <?php } ?>
      _wssq.push(['suggest._bindEvent', 'open', function() {
        if (!setResizeFunction) {
          $jQ(window).resize(function() {
            if ($jQ('.sooqrSearchContainer-' + sooqrAccount).is(':visible')) {
              websight.sooqr.instances['SQ-' + sooqrAccount].positionContainer(null, null, true);
            }
          });
          setResizeFunction = true;
        }
      }]);
      (function() {
        var ws = document.createElement('script');
        ws.type = 'text/javascript';
        ws.async = true;
        ws.src = '//' + '<?=$this->getSooqrScriptUri()?>';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ws, s);
      })();
    </script>
  <?php endif; ?>
</form>
