<?php

require_once __DIR__."/dhhfpc_conf.php";

$formKeyPlaceholder = '<!-- fpc form_key_placeholder -->';

// Outqualification
$write_cache = true;
$read_cache = true;

$totalItemsInCart = Mage::helper('checkout/cart')->getItemsCount();
if($totalItemsInCart > 0) {
  $write_cache = false;
  $read_cache = false;
}
if(Mage::getSingleton('customer/session')->isLoggedIn()) {
  $write_cache = false;
  $read_cache = false;
}
if(isset($_GET['nofpc'])) {
  $write_cache = false;
  $read_cache = false;
}
if(isset($_GET['refreshfpc'])) {
  $write_cache = true;
  $read_cache = false;
}
if(DHH_FPC_ENABLED === false) {
  $write_cache = false;
  $read_cache = false;
}
if($_SERVER['REQUEST_METHOD'] !== 'GET') {
  $write_cache = false;
  $read_cache = false;
}

$_cacheKey = null;
if($read_cache === true || $write_cache === true) {
  $cache_key_input = Mage::helper('core/url')->getCurrentUrl();
  $cache_key_input = str_replace("?refreshfpc", null, $cache_key_input);
  $_cacheKey = 'QUICKNDIRTYFPC' . md5($cache_key_input);
}

if(headers_sent() === FALSE) {
  $r = "-r";
  $w = "-w";
  if($write_cache === true) $w = "+w";
  if($read_cache === true) $r = "+r";
  header("qnd-fpc-settings: {$r} {$w}");
}

$_html = null;

if($read_cache === true) {
  // Check if there is a cached version:
  $_html = Mage::app()->getCache()->load($_cacheKey);

  // Handle form_key (CSRF protection)
  if($_html) {
    $formKey = Mage::getSingleton('core/session')->getFormKey();
    if($formKey) {
      $_html = str_replace($formKeyPlaceholder, $formKey, $_html);
    }
  }
}

if(strlen($_html) > 0) {
  if(headers_sent() === FALSE) {
    $bytes = strlen($_html);
    header("retrieved-quickndirtyfpc: {$_cacheKey}, {$bytes} bytes");
  }
  echo $_html;
} else {
  ob_start();

  // Just include the parent file
  require_once __DIR__."/../../../default/template/page/".basename(__FILE__);

  $_html = ob_get_clean();

  if($write_cache === true) {

    // Handle form_key (CSRF protection)
    $formKey = Mage::getSingleton('core/session')->getFormKey();
    if ($formKey) {
      $_html_normalized = str_replace($formKey, $formKeyPlaceholder, $_html);
    }

    Mage::app()->getCache()->save($_html_normalized, $_cacheKey, ["quickndirtyfpc"]);

    if(headers_sent() === FALSE) {
      $bytes = strlen($_html_normalized);
      header("saved-quickndirtyfpc: {$_cacheKey}, {$bytes} bytes");
    }
  }

  echo $_html;
}
