<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Block_Adminhtml_Sales_Order_View_Additional extends Mage_Adminhtml_Block_Sales_Order_View_Info {

	/**
	 * Return array of additional account data
	 * Value is option style array
	 *
	 * @return array
	 */
	public function getCustomerAccountData()
	{
		$accountData = array();

		/* @var $config Mage_Eav_Model_Config */
		$config     = Mage::getSingleton('eav/config');
		$entityType = 'customer';
		$customer   = Mage::getModel('customer/customer');
		foreach ($config->getEntityAttributeCodes($entityType) as $attributeCode) {
			/* @var $attribute Mage_Customer_Model_Attribute */
			$attribute = $config->getAttribute($entityType, $attributeCode);
			if( (!$attribute->getIsVisible() || $attribute->getIsSystem())
			    && $attributeCode !== 'taxvat'
			) {
				continue;
			}
			$orderKey   = sprintf('customer_%s', $attribute->getAttributeCode());
			$orderValue = $this->getOrder()->getData($orderKey);
			if ($orderValue != '') {
				$customer->setData($attribute->getAttributeCode(), $orderValue);
				$dataModel  = Mage_Customer_Model_Attribute_Data::factory($attribute, $customer);
				$value      = $dataModel->outputValue(Mage_Customer_Model_Attribute_Data::OUTPUT_FORMAT_HTML);
				$sortOrder  = $attribute->getSortOrder() + $attribute->getIsUserDefined() ? 200 : 0;
				$sortOrder  = $this->_prepareAccountDataSortOrder($accountData, $sortOrder);
				$accountData[$sortOrder] = array(
					'label' => $attribute->getFrontendLabel(),
					'value' => $this->escapeHtml($value, array('br'))
				);
			}
		}

		ksort($accountData, SORT_NUMERIC);

		return $accountData;
	}

}