<?php
/**
 * ||GEISSWEB| Invoice Auto Send
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL:
 * https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @category    Geissweb
 * @package     Geissweb_InvoiceAutoSend
 * @copyright   Copyright (c) 2015-2017 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

if( Mage::helper('core')->isModuleEnabled('Fooman_EmailAttachments') ) {
    class Geissweb_InvoiceAutoSend_Model_Email_Template_MailerRewrite extends Fooman_EmailAttachments_Model_Core_Email_Template_Mailer {}
} else {
    class Geissweb_InvoiceAutoSend_Model_Email_Template_MailerRewrite extends Mage_Core_Model_Email_Template_Mailer {}
}