<?php
/**
 * ||GEISSWEB| Invoice Auto Send
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL:
 * https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @category    Geissweb
 * @package     Geissweb_InvoiceAutoSend
 * @copyright   Copyright (c) 2015-2017 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_InvoiceAutoSend_Model_Email_Template_Mailer extends Geissweb_InvoiceAutoSend_Model_Email_Template_MailerRewrite //Mage_Core_Model_Email_Template_Mailer
{
    protected $emailTemplate;

    /**
     * Adds PDF Attachment
     * @param $pdf
     * @param $filename
     *
     * @throws Zend_Pdf_Exception
     */
    public function addPdf($pdf, $filename='invoice.pdf')
    {
        $file = $pdf->render();
        $this->emailTemplate = Mage::getModel('core/email_template');
        $attachment = $this->emailTemplate->getMail()->createAttachment($file);
        $attachment->type = 'application/pdf';
        $attachment->filename = $filename;
    }

    /**
     * Add attachment to email
     *
     * @param string $file
     * @param string $filename
     */
    public function addAttachment($file, $filename){

        //Mage::log('Adding attach @ Mailer: '.$filename);
        /** @var $emailTemplate Mage_Core_Model_Email_Template */
        if ($this->emailTemplate) {
            $emailTemplate = $this->emailTemplate;
        } else {
            $emailTemplate = Mage::getModel('core/email_template');
        }

        $mp = new Zend_Mime_Part($file);
        $mp->encoding = Zend_Mime::ENCODING_BASE64;
        $mp->type = 'application/pdf';
        $mp->disposition = Zend_Mime::DISPOSITION_ATTACHMENT;
        $mp->filename = $filename;

        $emailTemplate->getMail()->addAttachment($mp);
    }


    /**
     * Send all emails from email list
     * @see self::$_emailInfos
     *
     * @return Mage_Core_Model_Email_Template_Mailer
     */
    public function send()
    {
        //Compat with Fooman
        $isFooman = false;
        if(Mage::helper('core')->isModuleEnabled('Fooman_EmailAttachments')) {
            $isFooman = true;
            $helper = Mage::helper('emailattachments');
        }

        /** @var $emailTemplate Mage_Core_Model_Email_Template */
        if ($this->emailTemplate) {
            $emailTemplate = $this->emailTemplate;
        } else {
            $emailTemplate = Mage::getModel('core/email_template');
        }

        // Send all emails from corresponding list
        while (!empty($this->_emailInfos))
        {
            $emailInfo = array_pop($this->_emailInfos);

            if($isFooman) {
                $helper->debug('NEW EMAIL------------------------------------------');
                $helper->debug($emailInfo->getToNames());
                $this->dispatchAttachEvent($emailTemplate, $emailInfo);
            }

            // Handle "Bcc" recipients of the current email
            $emailTemplate->addBcc($emailInfo->getBccEmails());
            $emailTemplate->setQueue($this->getQueue());
            // Set required design parameters and delegate email sending to Mage_Core_Model_Email_Template
            $emailTemplate->setDesignConfig(array('area' => 'frontend', 'store' => $this->getStoreId()))
                ->sendTransactional(
                    $this->getTemplateId(),
                    $this->getSender(),
                    $emailInfo->getToEmails(),
                    $emailInfo->getToNames(),
                    $this->getTemplateParams(),
                    $this->getStoreId()
                );
        }
        return $this;
    }

}