<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_IndexController extends Mage_Core_Controller_Front_Action
{

    public function indexAction()
    {
		$do_validation = false;
		$customer_vat_id = false;
		$validator = Mage::getSingleton("euvatgrouper/validation_vies");

		$address_type = $this->getRequest()->getParam('address_type');
		if(!$address_type || $address_type == '') $address_type = 'billing';
		$validator->setAddressType($address_type);

		$address_id = $this->getRequest()->getParam('address_id');
		$validator->setAddressId($address_id);

        if ($this->getRequest()->getParam('taxvat') != "") {
            $customer_vat_id = Mage::helper('euvatgrouper')->cleanCustomerVatId($this->getRequest()->getParam('taxvat'));

        } elseif (is_array($this->getRequest()->getParam('billing'))) {
            $param = $this->getRequest()->getParam('billing');
            $customer_vat_id = Mage::helper('euvatgrouper')->cleanCustomerVatId($param['taxvat']);
        }

        if($customer_vat_id != false)
        {
            $validator->setUserTaxvat($customer_vat_id);
            $do_validation = true;
        }

        try {
	        if ($do_validation)
	        {
		        $validator->setUserCc(strtoupper(substr($validator->getUserTaxvat(), 0, 2)));
		        $validator->setUserNr(substr($validator->getUserTaxvat(), 2));

		        $validator->validate();
		        $result = $validator->getResult();
		        $this->getResponse()->setBody(Mage::helper('core')->jsonEncode($result));

	        }

	        if($this->getRequest()->getParam('vatid') == "removed")
	        {
		        $result = Mage::helper('euvatgrouper')->assignDefault($address_id, $address_type);
		        $this->getResponse()->setBody(Mage::helper('core')->jsonEncode($result));
	        }
        } catch(Exception $e) {
        	Mage::logException($e);
        }



    }

	public function getLoaderSrcAction()
	{
		$skin_path = $this->getLayout()->createBlock('core/text')->getSkinUrl('images/opc-ajax-loader.gif', array('_secure'=>true));
		$this->getResponse()->setBody(Mage::helper('core')->jsonEncode( $skin_path ));
	}

}
?>