<?php

$store = Mage::app()->getStore();
$store_name = $store->getFrontendName();

if($_product = Mage::registry('current_product')) {
  $product_image = $_product->getImageUrl();
  $product_url = Mage::helper("deheerhoreca_util/util")->getFullProductUrl($_product);
  
  if(is_array($crumbs) && sizeof($crumbs) > 2 && isset($crumbs["product"]) === true) {
    unset($crumbs["product"]);
  }
}

$currentUrl = Mage::helper('core/url')->getCurrentUrl();

/* Pre-processing */
if(is_array($crumbs) && sizeof($crumbs) > 0) {
  foreach($crumbs as $_crumbName => $_crumbInfo) {
    if(strlen($_crumbInfo['title']) < 1) {
      $crumbs[$_crumbName]['title'] = $crumbs[$_crumbName]['label'];
    }
    if($crumbs[$_crumbName]['first']) {
      $crumbs[$_crumbName]['label'] = $store_name;
    }
    if($crumbs[$_crumbName]['last'] && strlen($crumbs[$_crumbName]['link']) < 1) {
      $crumbs[$_crumbName]['link'] = $currentUrl;
    }
  }
}

if (Mage::helper('richsnippets')->snippetsEnabled()) {
  $snippetsType = Mage::getStoreConfig('richsnippets/general/snippetsType');
  if ($snippetsType == '0') { //if JSON enabled
    $position = 1;

    $dataBreadcrumbs = array();
    $dataBreadcrumbs['@context']    = "http://schema.org";
    $dataBreadcrumbs['@type']       = "BreadcrumbList";
    $dataBreadcrumbs['itemListElement'] = [];
    if($crumbs && is_array($crumbs)) {
      foreach($crumbs as $_crumbName => $_crumbInfo) {
        $dataBreadcrumbs['itemListElement'][$position - 1]['@type']         = 'ListItem';
        $dataBreadcrumbs['itemListElement'][$position - 1]['position']      = $position;
        $dataBreadcrumbs['itemListElement'][$position - 1]['item']['name']  = $_crumbInfo['label'];
        if($_crumbName === "product" && isset($product_image)) {
          $dataBreadcrumbs['itemListElement'][$position - 1]['item']['@id']   = $product_url;
          $dataBreadcrumbs['itemListElement'][$position - 1]['item']['image'] = $product_image;
        } else {
          $dataBreadcrumbs['itemListElement'][$position - 1]['item']['@id']   = $_crumbInfo['link'];
        }
        $position++;
      }
    }
    
    if($crumbs && is_array($crumbs) && sizeof($crumbs) > 1) {
      echo '<div class="breadcrumbs">';
        echo '<ul>';
        $n = sizeof($crumbs);
        $i = 0;
        foreach($crumbs as $_crumbName => $_crumbInfo) {
          $css_classes = (substr($_crumbName, 0, 8) === "category") ? "category " : null;
          $label = $this->escapeHtml($_crumbInfo['label']);
          $title = $this->escapeHtml($_crumbInfo['title']);
          echo "<li class='{$css_classes}{$_crumbName}'>";
          
          if($n > 2 && $_crumbName === "product") {
            continue;
          }
          
          if($_crumbInfo['link'] && ($_crumbInfo['last'] !== true || $_product)) {
            echo "<a title='{$title}' class='button btn-cart' href='{$_crumbInfo['link']}'>{$label}</a>";
          } else {
            echo "<strong>{$label}</strong>";
          }
          if($i < $n-1) {
            echo '<i class="fa fa-angle-right breadcrumb-separator" aria-hidden="true"></i>';
          }
          echo "</li>";
          $i++;
        }
        echo '</ul>';
      echo '</div>';
    }
    ?>
    
    <?php if(sizeof($dataBreadcrumbs['itemListElement']) >0 ) { ?>
    <script type="application/ld+json">
      <?php echo Mage::helper('core')->jsonEncode($dataBreadcrumbs); ?>
    </script>
    <?php } ?>

    <?php
  } elseif ($snippetsType == '1') {
    if($crumbs && is_array($crumbs)) { ?>
      <div class="breadcrumbs">
        <ul itemscope itemtype="http://schema.org/BreadcrumbList">
          <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
            <li class="<?php echo $_crumbName ?>"
              <?php if($_crumbInfo['link']): ?>
                itemprop="itemListElement"
                itemscope
                itemtype="http://schema.org/ListItem"
              <?php endif; ?>
            >
            <?php if($_crumbInfo['link']): ?>
              <a itemprop="item"
                href="<?php echo $_crumbInfo['link'] ?>"
                title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>"
              ><span itemprop="name"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></span
              ></a>
            <?php elseif($_crumbInfo['last']): ?>
              <strong><?php echo $this->htmlEscape($_crumbInfo['label']) ?></strong>
            <?php else: ?>
              <?php echo $this->htmlEscape($_crumbInfo['label']) ?>
            <?php endif; ?>
            <?php if(!$_crumbInfo['last']): ?>
              <span>/ </span>
            <?php endif; ?>
            </li>
          <?php endforeach; ?>
        </ul>
      </div>
    <?php
    }
  }
}
