<?php
if(Mage::helper('richsnippets')->snippetsEnabled() && Mage::getStoreConfig('richsnippets/general/snippetsType') == '0') {
  $_product      = Mage::registry("current_product");
  $json         = "";
  $cache_key    = "tm_richsnippets_product_json_{$_product->getId()}";
  
  if(DeHeerHoreca_Fpc_Helper_Data::is_read_cache_enabled(true, true, "tm_richsnippets")) {
    $json = Mage::app()->getCache()->load($cache_key);
    if(empty($json)) {
      DeHeerHoreca_Fpc_Helper_Data::log("MISS {$cache_key}");
    } else {
      DeHeerHoreca_Fpc_Helper_Data::log("HIT {$cache_key}");
      echo "<script type=\"application/ld+json\">{$json}</script>";
      return;
    }
  }
  
  $json = $this->getJsonSnippetsProduct();
  if(isset($_SERVER['MAGE_IS_DEVELOPER_MODE'])) {
    $json = json_encode(json_decode((string) $json), JSON_PRETTY_PRINT); // During development
  }
  echo "<script type=\"application/ld+json\">{$json}</script>".PHP_EOL;
  
  if(DeHeerHoreca_Fpc_Helper_Data::is_write_cache_enabled(true, true, "tm_richsnippets")) {
    $supplier_sys_upper = strtoupper((string) preg_replace("/\s+/", "", (string) _get_product_attribute($_product, "supplier")));
    $cache_tags = ["DHH_TM_RICHSNIPPETS", "DHH_PRODUCT_{$_product->getId()}", "PRODUCT_{$_product->getId()}", "DHH_SUPPLIER_{$supplier_sys_upper}"];
    if(Mage::app()->getCache()->save($json, $cache_key, $cache_tags, 86400 * 7)) {
      DeHeerHoreca_Fpc_Helper_Data::log("SAVED {$cache_key}");
    }
  }
}
