<?php
$_shipment = $this->getShipment();
$_order  = $this->getOrder();

if($_shipment && $_order): ?>
  <?php $_items = $_order->getAllItems() ?>
  <?php $_itemCount = count($_items) ?>
  <table class="items" cellpadding="0" cellspacing="0" border="0">
    <thead>
      <tr>
        <th class="cell-name align-left">Artikel</th>
        <th class="cell-name align-center">SKU</th>
        <th class="cell-name align-center">Aantal</th>
      </tr>
    </thead>

    <?php $i=0; foreach ($_shipment->getAllItems() as $_item): ?>
    <?php if($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
      <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach; ?>

  </table>
<?php
endif;
