<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2020] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2020 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

$qty = $this->getTotalQty() ?? 0;
?>
<!-- header_miniquote_start -->
<span class="header-miniquote">
  
  <a href="<?php echo Mage::getUrl("qquoteadv/index/"); ?>" data-target-element="#header-quote" class="skip-quote <?php if ($qty <= 0): ?> no-count<?php endif; ?> top-link" title="Lease en Offerte Winkelwagen">
    <i class="fa fa-calculator fa-2x fa-fw"></i>
    <?php if($qty > 0) {
      /* This used to be a div (not allowed in HTML validator) */ ?>
      <span class="header__quote-count-badge js-header__cart-articles-count" data-acte-cart-icon-articles-count="0"><?php echo $qty; ?></span>
    <?php } ?>
  </a>
  <?php /* This used to be a div (not allowed in HTML validator) */
  // <span id="header-quote" class="block skip-content">
      // echo $this->getChildHtml("miniquote_content");
      // Disabled for performance
      // echo Mage::app()->getLayout()
        // ->createBlock("qquoteadv/checkout_miniquote_miniquote")
        // ->setTemplate("qquoteadv/checkout/quote/miniquote/miniquoteitems.phtml")
        // ->toHtml();
  // </span>
  ?>
</span>

<!-- header_miniquote_end -->
