<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2020] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2020 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

$_quoteQty = $this->getTotalQty();
if(empty($_quoteQty)) {
  $_quoteQty = 0;
}
?>
<!-- header_miniquote_start -->

<span class="header-miniquote">
  <a href="<?php echo Mage::getUrl('qquoteadv/index/'); ?>" data-target-element="#header-quote" class="skip-link skip-quote <?php if ($_quoteQty <= 0): ?> no-count<?php endif; ?> top-link" title="Lease en Offerte Winkelwagen">
    <i class="fa fa-calculator"></i>
    <span class="label"><?php echo $this->__('Quote'); ?></span>
    <span class="header__count-badge js-header__cart-articles-count"><?php echo $_quoteQty; ?></span>
  </a>
  
  <div id="header-quote" class="block skip-content">
    <?php
      // echo $this->getChildHtml("miniquote_content");
      echo Mage::app()->getLayout()
        ->createBlock("qquoteadv/checkout_miniquote_miniquote")
        ->setTemplate("qquoteadv/checkout/quote/miniquote/miniquoteitems.phtml")
        ->toHtml();
    ?>
  </div>
</span>

<!-- header_miniquote_end -->
