<?php

/**
 * Shoping cart sidebar
 *
 * @var Mage_Checkout_Block_Cart_Minicart $this
 */
?>

<?php
$_cartQty = $this->getSummaryCount();
if(empty($_cartQty)) {
  $_cartQty = 0;
}
?>
<div id="minicart-error-message" class="minicart-message"></div>
<div id="minicart-success-message" class="minicart-message"></div>

<div class="minicart-wrapper">

  <p class="block-subtitle">
    <?php echo $this->__('Recently added item(s)') ?>
    <a class="close skip-link-close" onClick="hidedark()" href="#" title="<?php echo $this->quoteEscape($this->__('Close')); ?>">
      <i class="fa fa-times" aria-hidden="true"></i>
    </a>
  </p>

  <?php $_items = $this->getRecentItems() ?>
  <?php $countItems = count($_items); ?>
  <?php if($countItems): ?>
    <div>
      <ul id="cart-sidebar" class="mini-products-list">
        <?php foreach($_items as $_item): ?>
          <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach; ?>
      </ul>
    </div>
    <script type="text/javascript">
      truncateOptions();
      decorateList('cart-sidebar', 'none-recursive');
      $j('document').ready(function() {
        var minicartOptions  = {
          formKey:       "<?php echo $this->getFormKey();?>"
        }
        var Mini = new Minicart(minicartOptions);
        Mini.init();
      });
    </script>

    <div id="minicart-widgets">
      <?php echo $this->getChildHtml('cart_promotion') ?>
    </div>
    <div class="block-content">
      <p class="subtotal">
        <?php if ($this->canApplyMsrp()): ?>
          <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
        <?php else: ?>
          <span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
          <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
            <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
          <?php endif; ?>
        <?php endif; ?>
      </p>
    </div>
    
    <div class="minicart-actions">
      <button type="button" title="Ga door naar afrekenen" class="button btn-proceed-checkout btn-checkout" onclick="window.location='<?php echo $this->getUrl('checkout/cart'); ?>';">
        <span>Bekijk winkelmandje</span>
        <span class="float-right big" style="margin: 0 1em;">
          <i class="fa fa-chevron-right"></i>
        </span>
      </button>
    </div>

  <?php else: ?>
    <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>

  <?php endif ?>
</div>
