<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */

$_columnCount = 5;
$i = 0;

if($this->getItemCount()) { ?>
<div class="crosssell product-collateral category-products">
  <?php
  echo "<span class=h3>".$this->__('Based on your selection, you may be interested in the following items:')."</span><hr>";
  echo "<ul class='products-grid products-grid-mini'>";
  foreach ($this->getItems() as $_product) {
    $i++;
    ?>
    <li class="item<?php if(($i-1) % $_columnCount == 0): ?> first<?php elseif($i % $_columnCount == 0): ?> last<?php endif; ?>">
      <?php
      $options = [
        "skip_usps"     => true,
        "skip_info"     => true,
        "display"       => "mini",
        "image_size"    => 125,
        "_blank"        => true,
      ];
      echo Mage::helper("deheerhoreca_util/util")->getProductGridHtml($_product, $this, $options);
    echo "</li>";
  }
  ?>
</ul></div>
<?php }

/* Bargains */

$i = 0;

$supplier_ids = getCartSupplierIDs();
$product_ids  = getCartProductIDs();

$collection = Mage::getModel('catalog/product')
  ->getCollection()
  ->addAttributeToSelect('*')
  ->addFieldToFilter([['attribute' => 'bargain', 'eq' => true]])
  ->addAttributeToFilter('supplier', ['in' => $supplier_ids])
  ->addAttributeToFilter('entity_id', ['nin' => $product_ids])
  ->addAttributeToFilter('status', ['eq' => Mage_Catalog_Model_Product_Status::STATUS_ENABLED])
  ->addOrder('name', 'ASC')
  ->setPageSize(10)
  ->setCurPage(1)
  ->load();

if($collection->getSize() > 0) { ?>
<div class="crosssell product-collateral category-products">
  <?php
  echo "<span class=h3>".$this->__('Hardlopers:')."</span><hr>";
  echo "<ul class='products-grid products-grid-mini'>";
  foreach ($collection->getItems() as $_product) {
    $i++;
    ?>
    <li class="item<?php if(($i-1) % $_columnCount == 0): ?> first<?php elseif($i % $_columnCount == 0): ?> last<?php endif; ?>">
      <?php
      $options = [
        "skip_usps"     => true,
        "skip_info"     => true,
        "display"       => "mini",
        "image_size"    => 125,
        "_blank"        => true,
      ];
      echo Mage::helper("deheerhoreca_util/util")->getProductGridHtml($_product, $this, $options);
    echo "</li>";
  }
  ?>
</ul></div>
<?php }

function getCartSupplierIDs() {
  $quote = Mage::helper('checkout/cart')->getCart()->getQuote();
  $suppliers = [];
  foreach($quote->getAllItems() as $item) {
    $suppliers[] = $item->getProduct()->getData('supplier');
  }

  return array_unique($suppliers);
}

function getCartProductIDs() {
  $quote = Mage::helper('checkout/cart')->getCart()->getQuote();
  $array = [];
  foreach($quote->getAllItems() as $item) {
    $array[] = $item->getProduct()->getData('entity_id');
  }

  return array_unique($array);
}
