<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */

$_columnCount = 4;
$i            = 0;
$store        = Mage::app()->getStore();

if($this->getItemCount()) { ?>
<div class="crosssell product-collateral category-products">
  <?php
  echo "<h2 class='black'>".$this->__("Based on your selection, you may be interested in the following items:")."</h2><hr>";
  echo "<ul class='products-grid products-grid-mini'>";
  foreach ($this->getItems() as $_product) {
    $i++;
    ?>
    <li class="item<?php if(($i-1) % $_columnCount == 0): ?> first<?php elseif($i % $_columnCount == 0): ?> last<?php endif; ?>">
      <?php
      $options = [
        "skip_usps"     => true,
        "skip_info"     => true,
        "display"       => "mini",
        "image_size"    => 125,
        "_blank"        => true,
      ];
      echo Mage::helper("deheerhoreca_util/util")->getProductGridHtml($_product, $this, $options);
    echo "</li>";
  }
  ?>
  </ul>
</div>
<?php }

// Bargains

// NOTICE: Flat table feature are be disabled in the cart altogether
// @see Mage_Catalog_Helper_Product_Flat->_forceFlatStatus

// if(_dhh_debug()) {
  // $productFlatHelper = Mage::helper('catalog/product_flat');
  // var_dump("<br>\$productFlatHelper->isFlatCollectionDisabled(): ".$productFlatHelper->isFlatCollectionDisabled());
  // // $productFlatHelper->resetFlatCollection();
  // // var_dump("<br>\$productFlatHelper->isFlatCollectionDisabled(): ".$productFlatHelper->isFlatCollectionDisabled());
  // // $productFlatHelper->disableFlatCollection();
  // // var_dump("<br>\$productFlatHelper->isFlatCollectionDisabled(): ".$productFlatHelper->isFlatCollectionDisabled());
  // $productFlatHelper->enableFlatCollection(true);
  // var_dump("<br>\$productFlatHelper->isFlatCollectionDisabled(): ".$productFlatHelper->isFlatCollectionDisabled());
// }

$supplier_ids = getCartSupplierIDs();
$product_ids  = getCartProductIDs();
$attributes   = DeHeerHoreca_Util_Helper_Util::getProductAttributes("listview");
$_products    = Mage::getModel("catalog/product")
  ->getCollection()
  ->addAttributeToSelect($attributes)
  // ->addFieldToFilter([["attribute" => "bargain", "eq" => "1"]])    // testing without bargain
  ->addAttributeToFilter("supplier", ["in" => $supplier_ids])
  ->addAttributeToFilter("entity_id", ["nin" => $product_ids])
  ->addAttributeToFilter("eol", ["nin" => "2075"])
  ->addAttributeToFilter("status", ["eq" => Mage_Catalog_Model_Product_Status::STATUS_ENABLED])
  ->addAttributeToFilter("price", ["from" => 10, "to" => 200])
  ->addAttributeToFilter("small_image", ["notnull" => true])          // Do not suggest products without image
  ->setFlag("require_stock_items", true)
  ->addAttributeToFilter("stock_status", ["eq" => "2746"])            // Cheaper way to get probably in-stock items
  ->addOrder("popularity", "ASC")
  ->setPageSize(12)
  ->setCurPage(1)
  ->setStore($store)
  ->addStoreFilter($store)
  ;

// Only show in stock SKUs
// Expensive way to get probably in-stock items
// Mage::getSingleton("cataloginventory/stock")->addInStockFilterToCollection($_products);

// if(_dhh_debug()) {
  // var_dump("<br>\$_products->isEnabledFlat(): ".$_products->isEnabledFlat());
  // $_products->load();
  // printr(_dhh_getselect($_products));
  // var_dump($productFlatHelper->isFlatCollectionDisabled());
  // $productFlatHelper->resetFlatCollection();
  // var_dump($productFlatHelper->isFlatCollectionDisabled());
// }

$i = 0;
if($_products->getItems()) {
  $options = [
    "skip_usps"     => false,
    "display"       => "mini",
    "image_size"    => 125,
    "_blank"        => true,
  ];
  echo '<div class="crosssell product-collateral category-products">';
  echo "<h2>".$this->__("Hardlopers:")."</h2><hr>";
  echo "<ul class='products-grid products-grid-mini products-grid-mini-wide'>";
  foreach($_products->getItems() as $_product) {
    $i++;
    ?>
    <li class="item<?php if(($i-1) % $_columnCount == 0): ?> first<?php elseif($i % $_columnCount == 0): ?> last<?php endif; ?>">
      <?php
      echo Mage::helper("deheerhoreca_util/util")->getProductGridHtml($_product, $this, $options);
    echo "</li>";
  }
  ?>
</ul></div>
<?php }

function getCartSupplierIDs() {
  $quote = Mage::helper("checkout/cart")->getCart()->getQuote();
  $suppliers = [];
  foreach($quote->getAllItems() as $item) {
    $suppliers[] = $item->getProduct()->getData("supplier");
  }

  return array_unique($suppliers);
}

function getCartProductIDs() {
  $quote = Mage::helper("checkout/cart")->getCart()->getQuote();
  $array = [];
  foreach($quote->getAllItems() as $item) {
    $array[] = $item->getProduct()->getData("entity_id");
  }

  return array_unique($array);
}
