<?php
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */

$_cartQty = $this->getSummaryCount();
if(empty($_cartQty)) {
  $_cartQty = 0;
}
?>

<!-- header_minicart_start -->
<a href="<?php echo $this->helper('checkout/cart')->getCartUrl(); ?>" data-target-element="#header-cart" class="skip-link skip-cart <?php if($_cartQty <= 0): ?>no-count<?php endif; ?>" title="Winkelwagen">
  <i class="fa fa-shopping-cart fa-2x fa-fw" style="font-size: 2.5em;"></i>
  <div class="header__count-badge js-header__cart-articles-count" data-acte-cart-icon-articles-count="0">
    <?php echo $_cartQty; ?>
  </div>
</a>

<div class="header-minicart">
  <div id="header-cart" class="block block-cart skip-content">
    <!-- header_sidebar_start -->
    <?php
    echo Mage::app()->getLayout()->createBlock('checkout/cart_sidebar')->setTemplate("checkout/cart/minicart/items.phtml")->toHtml();
    ?>
    <!-- header_sidebar_end -->
  </div>
</div>
<!-- header_minicart_end -->
