<?php

declare(strict_types=1);

$helper = Mage::helper("eke_ogmeta");
if (!$helper->isOgMetaEnabled()) {
    return;
}
$image = $helper->getOgImage();
$siteName = $helper->getSiteName();

// DHH: Supress errors since the image might not exist
$imageAttr = @getimagesize($image);
?>
<meta property="og:locale" content="nl_NL">
<meta property="og:locale:alternate" content="nl_BE">
<meta property="og:title" content="<?=$this->getLayout()->getBlock('head')->getTitle()?>">
<meta property="og:site_name" content="<?=$helper->getSiteName()?>">
<meta property="og:type" content="article">
<meta property="og:url" content="<?=$this->helper('core/url')->getCurrentUrl()?>">
<meta property="og:image" content="<?=$image?>">
<meta property="og:image:type" content="<?=$imageAttr['mime'] ?? "" ?>">
<meta property="og:image:width" content="<?=$imageAttr[0] ?? "" ?>">
<meta property="og:image:height" content="<?=$imageAttr[1] ?? "" ?>">
<meta property="og:image:alt" content="<?=$this->getLayout()->getBlock('head')->getTitle()?>">
<meta property="og:description" content="<?=$this->getLayout()->getBlock('head')->getDescription()?>">
<meta name="twitter:card" content="summary">
