<?php
$helper = Mage::helper("eke_ogmeta");
if (!$helper->isOgMetaEnabled()) {
    return;
}
$image = $helper->getOgImage();
$siteName = $helper->getSiteName();

/*
 * DHH CORE HACK: we must supress errors since the image might not exist
 */
//$imageAttr = getimagesize($image);
$imageAttr = @getimagesize($image);
?>

<!-- OG META Data -->
<meta property="og:title" content="<?php echo $this->getLayout()->getBlock('head')->getTitle(); ?>" />
<meta property="og:site_name" content="<?php echo $siteName; ?>" />
<meta property="og:type" content="product.group" />
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl(); ?>" />
<meta property="og:description" content="<?php echo $this->getLayout()->getBlock('head')->getDescription(); ?>" />
<meta property="og:image" content="<?php echo $image; ?>" />
<meta property="og:image:type" content="<?php echo $imageAttr['mime']; ?>" />
<meta property="og:image:width" content="<?php echo $imageAttr[0]; ?>" />
<meta property="og:image:height" content="<?php echo $imageAttr[1]; ?>" />
<?php if ($helper->getFacebookAppId()) { ?>
<meta property="fb:app_id" content="<?php echo $helper->getFacebookAppId(); ?>"/>
<?php } ?>
