<?php

declare(strict_types=1);

$helper = Mage::helper("eke_ogmeta");

if(!$helper->isOgMetaEnabled()) {
  return;
}

?>
<meta property="og:locale" content="nl_NL">
<meta property="og:locale:alternate" content="nl_BE">
<meta property="og:title" content="<?=$this->getLayout()->getBlock('head')->getTitle()?>">
<meta property="og:site_name" content="<?=$helper->getSiteName()?>">
<meta property="og:type" content="website">
<meta property="og:url" content="<?=$this->helper('core/url')->getCurrentUrl()?>">
<meta property="og:image" content="https://images.chefstore.nl/skin/frontend/rwd/dhh/images/logo-chefstore.ts1741106066.min.svg">
<meta property="og:image:type" content="image/svg+xml">
<meta property="og:image:width" content="416">
<meta property="og:image:height" content="80">
<meta property="og:image:alt" content="Chefstore.nl: Álles voor de Chef">
<meta property="og:description" content="<?=$this->getLayout()->getBlock('head')->getDescription()?>">
