<?php

$product    = Mage::registry("current_product");
$cache_key  = "eke_ogmeta_product_".$product->getId();
$cached     = Mage::app()->loadCache($cache_key);

// if(_dhh_debug()) {
  // printr("key: {$cache_key}");
// }

if(empty($cached) === false) {
  echo unserialize($cached);
} else {

  // ------------ START REGULAR FLOW
  $helper = Mage::helper("eke_ogmeta");

  if(!$helper->isOgMetaEnabled()) {
    return;
  }

  $siteName = $helper->getSiteName();  
  $imageFile = "media/catalog/product".$product->getSmallImage();

  if(strlen($product->getSmallImage()) < 1) {
    $imageFile = $helper->getOgImage();
  }

  $imageAttr = ["mime" => null, 0 => null, 1 => null];
  if(is_file($imageFile) === true) {
    @$imageAttr = getimagesize($imageFile);
  }
  $productVideo = $product->getResource()->getAttribute("product_video")->getFrontend()->getValue($product);

  if($helper->isProductShortEnabled()) {
    $productDescription = htmlentities(strip_tags($product->getShortDescription()));
  } else {
    $productDescription = htmlentities(strip_tags($product->getDescription()));
  }

  // Fallback for when there is no description
  if(strlen($productDescription) < 10) {
    $productDescription = htmlentities($product->getName());
  }

  // Remove newlines, trim, limit to 200 chars
  $productDescription   = substr(trim(preg_replace("/\s\s+/", ";", $productDescription)), 0, 200);
  $product_url          = Mage::helper("deheerhoreca_util/util")->getFullProductUrlSafe($product);
  $stock_data           = Mage::helper("deheerhoreca_util/util")->getStockInfo($product, $_helper);
  $overall_stock_status = $stock_data["overall_stock_status"];

  $availability = null;
  switch($overall_stock_status) {
    case "in_stock":
      $availability = "instock";
      break;
    case "backorder":
      $availability = "backorder";
      break;
    case "not_sellable":
      $availability = "out of stock";
      break;
    case "eol":
      $availability = "discontinued";
      break;
  }
  
  $html = PHP_EOL;
  $html .= '<meta property="og:title" content="'.$this->getLayout()->getBlock("head")->getTitle().'">'.PHP_EOL;
  $html .= '<meta property="og:site_name" content="'.$siteName.'">'.PHP_EOL;
  $html .= '<meta property="og:type" content="product">'.PHP_EOL;
  $html .= '<meta property="og:availability" content="'.$availability.'">'.PHP_EOL;
  $html .= '<meta property="og:url" content="'.$product_url.'">'.PHP_EOL;
  $html .= '<meta property="og:image" content="'.$product->getImageUrl().'">'.PHP_EOL;
  $html .= '<meta property="og:image:type" content="'.$imageAttr['mime'].'">'.PHP_EOL;
  $html .= '<meta property="og:image:width" content="'.$imageAttr[0].'">'.PHP_EOL;
  $html .= '<meta property="og:image:height" content="'.$imageAttr[1].'">'.PHP_EOL;
  $html .= '<meta property="og:image:alt" content="'.$this->getLayout()->getBlock("head")->getTitle().'">'.PHP_EOL;
  $html .= '<meta property="og:description" content="'.$productDescription.'">'.PHP_EOL;
  if($helper->getFacebookAppId()) {
    $html .= '<meta property="fb:app_id" content="'.$helper->getFacebookAppId().'">'.PHP_EOL;
  }
  $html .= '<meta property="og:price:amount" content="'.Mage::registry("product")->getFinalPrice().'">'.PHP_EOL;
  $html .= '<meta property="og:price:currency" content="'.Mage::app()->getStore()->getCurrentCurrencyCode().'">'.PHP_EOL;
  if(empty($productVideo) === false) {
    $productVideo = Mage::helper("deheerhoreca_util/util")->build_product_video_url($productVideo);
    $html .= "<meta property='og:video' content='{$productVideo}'>".PHP_EOL;
  }
  
  // ------------ STOP REGULAR FLOW
  
  echo $html;

  // Store in Magento cache
  Mage::app()->saveCache(serialize($html), $cache_key, ["eke_ogmeta_product"], 10);
}
