<?php

$helper = Mage::helper("eke_ogmeta");
if(!$helper->isOgMetaEnabled()) {
  return;
}

$_product      = Mage::registry("current_product");
$html         = "";
$cache_key    = "eke_ogmeta_product_{$_product->getId()}";

// Serve from cache

if(Mage::helper("deheerhoreca_fpc/data")->is_read_cache_enabled(true, true, "eke_ogmeta")) {
  $html = Mage::app()->getCache()->load($cache_key);
  if(empty($html)) {
    DeHeerHoreca_Fpc_Helper_Data::log("MISS {$cache_key}");
  } else {
    DeHeerHoreca_Fpc_Helper_Data::log("HIT {$cache_key}");
    echo $html;
    return;
  }
}

// Serve fresh

$dhh_sku              = (string) $_product->getSku();
$siteName             = (string) $helper->getSiteName();
$page_title           = (string) $this->getLayout()->getBlock("head")->getTitle();
$final_price          = number_format($_product->getFinalPrice(), 2);
$product_url          = Mage::helper("deheerhoreca_util/util")->getFullProductUrlSafe($_product);
$stock_data           = Mage::helper("deheerhoreca_util/util")->getStockInfo($_product, ["fastmode" => true]);
$overall_stock_status = $stock_data["overall_stock_status"] ?? "";
// $product_image        = (string) $_product->getImageUrl();
$productVideo         = (string) _get_product_attribute($_product, "product_video");

$image_attr           = [];
$image_raw            = (string) $_product->getImage();
if(!empty($image_raw) && $image_raw !== "no_selection") {
  $media_dir        = Mage::getBaseDir(Mage_Core_Model_Store::URL_TYPE_MEDIA);
  $image_path       = "{$media_dir}/catalog/product{$_product->getData("image")}";
  $media_url        = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
  $image_url        = "{$media_url}catalog/product{$_product->getData("image")}";
  $cdn_img_options  = [
    "fs_path"         => $image_path,
    "url"             => $image_url,
    "url_only"        => true,
    "cm"              => "pad_resize",
    "width"           => 2048,
    "height"          => 2048,
    "add_mod_time"    => true,
    "relative_url"    => false,
    // @todo move to named transformation omcatprddtlf
  ];
  $image_url = Mage::helper("deheerhoreca_util/util")->_cdn_img($cdn_img_options);
  
  if(is_file($image_path)) {
    try {
      $image_attr = getimagesize($image_path);
    } catch(Exception $e) {
      $image_attr = [];
      Mage::logException($e);
      Mage::log("{$dhh_sku} getimagesize() failed during eke_ogmeta: ".var_export($image_path, true), Zend_Log::ERR, "system.log", true);
    }
  } else {
    Mage::log("{$dhh_sku} Product image does not exist during eke_ogmeta: ".var_export($image_path, true), Zend_Log::ERR, "system.log", true);
  }
}

if(empty($image_url)) {
  $image_url = $helper->getOgImage();
}

// Remove newlines, trim, limit to 200 chars
$productDescription = (string) Mage::helper("deheerhoreca_util/util")->_get_product_description($_product);
if($productDescription !== "") {
  $productDescription = htmlentities(strip_tags($productDescription));
  $productDescription = substr(trim((string) preg_replace("/\s\s+/", ";", $productDescription)), 0, 200);
}

$availability = match($overall_stock_status) {
  "in_stock"      => "in_stock",
  "backorder"     => "backorder",
  "not_sellable"  => "out of stock",
  "eol"           => "discontinued",
  default         => "invalid",
};

if($availability === "invalid") {
  Mage::log("{$dhh_sku} Has invalid value availability=".var_export($overall_stock_status, true), Zend_Log::ERR, "system.log", true);
  $availability = "out of stock";
}

$html = <<<EOT
  <meta property="og:locale" content="nl_NL">
  <meta property="og:locale:alternate" content="nl_BE">
  <meta property="og:title" content="{$page_title}">
  <meta property="og:site_name" content="{$siteName}">
  <meta property="og:type" content="product">
  <meta property="og:availability" content="{$availability}">
  <meta property="og:url" content="{$product_url}">
  <meta property="og:image:url" content="https:{$image_url}">
  <meta property="og:image:alt" content="{$page_title}">
  <meta property="og:image:width" content="2048">
  <meta property="og:image:height" content="2048">
  <meta property="og:description" content="{$productDescription}">
  <meta property="og:price:amount" content="{$final_price}">
  <meta property="og:price:currency" content="EUR">
EOT;

$html .= PHP_EOL;

if($image_attr !== []) {
  if(isset($image_attr['mime'])) $html .= '  <meta property="og:image:type" content="'.$image_attr['mime'].'">'.PHP_EOL;
  // if(isset($image_attr[0]))      $html .= '  <meta property="og:image:width" content="'.$image_attr[0].'">'.PHP_EOL;
  // if(isset($image_attr[1]))      $html .= '  <meta property="og:image:height" content="'.$image_attr[1].'">'.PHP_EOL;
  unset($image_attr);
}

if(!empty($productVideo)) {
  if($productVideo = Mage::helper("deheerhoreca_util/util")->build_product_video_url($productVideo)) {
    $html .= "  <meta property='og:video' content='{$productVideo}'>".PHP_EOL;
    $html .= "  <meta property='og:video:secure_url' content='{$productVideo}'>".PHP_EOL;
    unset($productVideo);
  }
}

echo $html;

// Store in cache
if(DeHeerHoreca_Fpc_Helper_Data::is_write_cache_enabled(true, true, "eke_ogmeta")) {
  if(Mage::app()->getCache()->save($html, $cache_key, ["DHH_EKE_OGMETA"], 86400 * 7)) {
    DeHeerHoreca_Fpc_Helper_Data::log("SAVED {$cache_key}");
  }
}
