<?php

$helper = Mage::helper("eke_ogmeta");
if(!$helper->isOgMetaEnabled()) {
  return;
}

$product    = Mage::registry("current_product");
$html       = "";
$cache_key  = "eke_ogmeta_product_{$product->getId()}_";
$cache_tags = ["eke_ogmeta"];

if(Mage::helper("deheerhoreca_fpc/data")->is_read_cache_enabled(true, true, "eke_ogmeta")) {
  $html = Mage::app()->getCache()->load($cache_key);
  if(empty($html) === true) {
    DeHeerHoreca_Fpc_Helper_Data::log("MISS {$cache_key}, ".strlen((string) $html)." chars");
  }
}

if(empty($html) === false) {
  DeHeerHoreca_Fpc_Helper_Data::log("HIT {$cache_key}, ".strlen((string) $html)." chars");
  echo unserialize($html);
} else {
  
  // ------------ START REGULAR FLOW  
  $siteName = $helper->getSiteName();
  $imageFile = "";
  if(!empty($product->getSmallImage())) {
    $imageFile = "media/catalog/product".$product->getSmallImage();
  }
  
  $imageAttr = [];
  if(strlen($imageFile) > 0 && is_file($imageFile) === true) {
    try {
      $imageAttr = getimagesize($imageFile);
    } catch(Exception $e) {
      $imageAttr = [];
      Mage::logException($e);
      $msg = "{$product->getSku()} getimagesize() failed on file ".var_export($imageFile, true);
      Mage::log($msg, Zend_Log::NOTICE, "system.log", true);
    }
  } else {
    if(strlen($imageFile) > 0) {
      $msg = "{$product->getSku()} Product image does not exist: ".var_export($imageFile, true);
      Mage::log($msg, Zend_Log::NOTICE, "system.log", true);
    }
    $imageFile = $helper->getOgImage();
  }
  
  $productVideo = $product->getResource()->getAttribute("product_video")->getFrontend()->getValue($product);
  
  $productDescription = Mage::helper("deheerhoreca_util/util")->_get_product_description($product);
  if(strlen((string) $productDescription) > 0) {
    $productDescription = htmlentities(strip_tags((string) $productDescription));
  }
  
  // Remove newlines, trim, limit to 200 chars
  $productDescription   = substr(trim((string) preg_replace("/\s\s+/", ";", (string) $productDescription)), 0, 200);
  $product_url          = Mage::helper("deheerhoreca_util/util")->getFullProductUrlSafe($product);
  $stock_data           = Mage::helper("deheerhoreca_util/util")->getStockInfo($product);
  $overall_stock_status = $stock_data["overall_stock_status"];
  
  $availability = null;
  switch($overall_stock_status) {
    case "in_stock":
      $availability = "instock";
      break;
    case "backorder":
      $availability = "backorder";
      break;
    case "not_sellable":
      $availability = "out of stock";
      break;
    case "eol":
      $availability = "discontinued";
      break;
  }
  
  $html = "";
  $html .= '<meta property="og:locale" content="nl_NL">'.PHP_EOL;
  $html .= '<meta property="og:locale:alternate" content="nl_BE">'.PHP_EOL;
  $html .= '<meta property="og:title" content="'.$this->getLayout()->getBlock("head")->getTitle().'">'.PHP_EOL;
  $html .= '<meta property="og:site_name" content="'.$siteName.'">'.PHP_EOL;
  $html .= '<meta property="og:type" content="product">'.PHP_EOL;
  $html .= '<meta property="og:availability" content="'.$availability.'">'.PHP_EOL;
  $html .= '<meta property="og:url" content="'.$product_url.'">'.PHP_EOL;
  $html .= '<meta property="og:image" content="'.$product->getImageUrl().'">'.PHP_EOL;
  if($imageAttr !== []) {
    if(isset($imageAttr['mime'])) $html .= '<meta property="og:image:type" content="'.$imageAttr['mime'].'">'.PHP_EOL;
    if(isset($imageAttr[0]))      $html .= '<meta property="og:image:width" content="'.$imageAttr[0].'">'.PHP_EOL;
    if(isset($imageAttr[1]))      $html .= '<meta property="og:image:height" content="'.$imageAttr[1].'">'.PHP_EOL;
  }
  $html .= '<meta property="og:image:alt" content="'.$this->getLayout()->getBlock("head")->getTitle().'">'.PHP_EOL;
  $html .= '<meta property="og:description" content="'.$productDescription.'">'.PHP_EOL;
  $html .= '<meta property="og:price:amount" content="'.Mage::registry("product")->getFinalPrice().'">'.PHP_EOL;
  $html .= '<meta property="og:price:currency" content="'.Mage::app()->getStore()->getCurrentCurrencyCode().'">'.PHP_EOL;
  if(empty($productVideo) === false) {
    $productVideo = Mage::helper("deheerhoreca_util/util")->build_product_video_url($productVideo);
    $html .= "<meta property='og:video' content='{$productVideo}'>".PHP_EOL;
    $html .= "<meta property='og:video:secure_url' content='{$productVideo}'>".PHP_EOL;
  }
  
  // ------------ STOP REGULAR FLOW
  
  echo $html;
  
  // Store in Magento cache
  if(Mage::helper("deheerhoreca_fpc/data")->is_write_cache_enabled(true, true, "eke_ogmeta")) {
    if(Mage::app()->getCache()->save(serialize($html), $cache_key, $cache_tags, 86400 * 7)) {
      DeHeerHoreca_Fpc_Helper_Data::log("SAVED {$cache_key}, ".strlen($html)." chars");
    }
  }
}
