<?php
$tx_name        = (string) (Mage::helper("deheerhoreca_util/util")->get_apm_transaction_name() ?? "unknown");
$env            = (string) (ini_get("elastic_apm.environment") ?? "unknown");
$body_class     = (string) $this->getBodyClass();
$current_route  = (string) $this->getRequest()->getRouteName();
?>
<!DOCTYPE html>
<html lang="<?=$this->getLang();?>" id="top" class="no-js" itemscope itemtype="http://schema.org/WebPage" data-environment="<?=$env?>" data-transaction="<?=$tx_name?>" data-route="<?=$current_route?>">
  <head>
    <?=$this->getChildHtml('head')?>
  </head>
  <body class="<?=$body_class?>">
    <?=$this->getChildHtml('after_body_start')?>
    <div class="wrapper">
      <?=$this->getChildHtml('global_notices')?>
      <div class="page">
        <?=$this->getChildHtml('header')?>
        <div class="main-container col2-left-layout">
          <div class="main">
            <?=$this->getChildHtml('breadcrumbs')?>
            <?php // This left_first block will display above the main content on smaller viewports?>
            <?php if($_tmp = $this->getChildHtml('left_first')):?>
            <div class="col-left sidebar col-left-first"><?=$_tmp?></div>
            <?php endif;?>
            <div class="col-main">
              <!-- core_messages_start -->
              <?=$this->getChildHtml('global_messages')?>
              <!-- core_messages_end -->
              <?=$this->getChildHtml('content')?>
            </div>
            <?php if($_tmp = $this->getChildHtml('left')):?>
              <div class="col-left sidebar"><?=$_tmp?></div>
            <?php endif;?>
          </div>
        </div>
        <?=$this->getChildHtml('footer_before')?>
        <?=$this->getChildHtml('footer')?>
        <?=$this->getChildHtml('global_cookie_notice')?>
        <?=$this->getChildHtml('before_body_end')?>
      </div>
    </div>
    <?=$this->getAbsoluteFooter()?>
    <?=\Chefstore\Html::writeJsStatements()?>
  </body>
</html>
