<!DOCTYPE html>
<html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js" itemscope itemtype="http://schema.org/WebPage">
  <head>
    <?php echo $this->getChildHtml('head') ?>
  </head>
  <body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    <?php echo $this->getChildHtml('after_body_start') ?>
    <div class="wrapper">
      <?php echo $this->getChildHtml('global_notices') ?>
      <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col2-left-layout">
        
          <ul class="messages" style="box-sizing: border-box; max-width: 1170px; width: 100%; margin: .5em auto; font-weight: 600;">
            <li class="success-msg">
              <ul>
                <li><span>Prokoeling.nl heet vanaf nu Chefstore.nl. Alles blijft hetzelfde, behalve de naam!</span></li>
              </ul>
            </li>
          </ul>
        
          <div class="main">
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            <?php // This left_first block will display above the main content on smaller viewports ?>
            <?php if ($_leftContent = $this->getChildHtml('left_first')): ?>
            <div class="col-left sidebar col-left-first"><?php echo $_leftContent;   ?></div>
            <?php endif; ?>
            <div class="col-main">
              <!-- core_messages_start -->
              <?php echo $this->getChildHtml('global_messages') ?>
              <!-- core_messages_end -->
              <?php echo $this->getChildHtml('content') ?>
            </div>
            <div class="col-left sidebar"><?php echo $this->getChildHtml('left') ?></div>
          </div>
        </div>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
      </div>
    </div>
    <?php echo $this->getAbsoluteFooter() ?>
  </body>
</html>
