<script>
  var lazyLoadInstance = new LazyLoad({
    elements_selector: ".lazy"
  });
</script>

<?php
$apm_transaction = Mage::app()->getFrontController()->getAction()->getFullActionName();
?>
<div class="footer-wrapper grid-inside" id="footer-wrapper">
  <div class="footermidwrap">
    <div class="footer grid">
      <?php
        echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_middle_left')->toHtml();
      ?>
    </div>
  </div>
  <div class="footer grid">
    <div class="row footer-last-row">
      <div class="col-1-2">
        <div class="footer-last-row__item footer__menu-item footer__menu-item--gray">
          Alle prijzen in euro's inclusief BTW. Gratis verzending vanaf €150,-
        </div>
      </div>
      <div class="col-1-3 footer__column--big-left-pd"></div>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@elastic/apm-rum/dist/bundles/elastic-apm-rum.umd.min.js" crossorigin defer></script>
<script>
  window.onload = function () {
    var hostName = window.location.host;
    var parts = hostName.split(".");
    var sub = parts[0];
    var apm_env = "production";
    if(sub === "dev") {
      apm_env = "development";
    }
    
    elasticApm.init({
      serviceName: "prokoeling",
      serverUrl: "https://rum." + parts[1] + ".nl:8200",
      environment: apm_env,
      pageLoadTransactionName: "<?php echo $apm_transaction; ?>"
    });
  };
</script>

<?php
$logoSrc = Mage::getStoreConfig('design/header/logo_src');
$logoAlt = Mage::getStoreConfig('design/header/logo_alt');
$imageurl = $this->getSkinUrl($logoSrc);
?>

<div id="modal" style="display:none;">
  <img id="main-logo" src="<?php echo $imageurl ?>" alt="<?php echo $logoAlt; ?>" title="<?php echo $logoAlt; ?>" />
  <h2><i class="fa fa-phone fa-1x" aria-hidden="true"></i>&nbsp;Contact met Chefstore.nl</h2>
  <div style="margin-top: 1em;"><strong>Sales & Advies: <a href="tel:+31850441003" title="Bel ons">+31 85 0441003</a></strong><small>&nbsp;&nbsp;Bereikbaar tijdens kantooruren</small>.</div>
  <div style="margin-top: 1em;"><strong>Klantenservice:</strong> Stuur een mail naar <a href="mailto:service@chefstore.nl" title="Klantenservice">service@chefstore.nl</a> of <a href="/service">vul direct een Serviceverzoek in</a>.</div>
  <div style="margin-top: 1em;">U kunt ook een verzoek indienen om door ons gebeld te worden, klik daarvoor <a rel="nofollow noreferrer" href="https://form.jotform.com/200604056344041" target="_blank" title="Wij bellen u">hier</a>.</div>
  <div style="margin-top: 1em;">Daarnaast zijn wij bereikbaar op de chat, zie daarvoor de knop rechtsonderin op onze website.</div>
</div>
