<?php

declare(strict_types=1);

$html = <<<EOT
    <!-- footer_start -->
    <footer>
      <div class="footer-wrapper grid-inside" id="footer-wrapper">
        <div class="footermidwrap blanc">
          <div class="footer grid" id="footer-grid">
            <div class="row justify-content-center mb-4 pb-2 text-center footer-quick-links">
              <div class="col">
                <a href="/onderdelen.html"><h3 class="orange">Onderdelen</h3></a>
              </div>
              <div class="col">
                <a href="//service.chefstore.nl"><h3 class="orange">Klantenservice</h3></a>
              </div>
              <div class="col">
                <a href="/customer/account/login/"><h3 class="orange">Dashboard</h3></a>
              </div>
            </div>
            <div class="mt-4">
              <div class="row justify-content-center align-items-center g-3 row-cols-2 row-cols-sm-4 text-center footer-awards-row">
                <div class="col d-flex justify-content-center align-items-center">
                  <img class="img-fluid" src="//images.chefstore.nl/media/wysiwyg/banners/fd-gazelle-2023-small.ts1741106066.png?tr=h-52,q-85,c-at_max" width="104" height="52" alt="Chefstore.nl is FD Gazelle 2023!" loading="lazy" fetchpriority="low">
                </div>
                <div class="col d-flex justify-content-center align-items-center">
                  <img class="img-fluid" src="//images.chefstore.nl/media/wysiwyg/banners/fd-gazelle-2024-small.ts1741106066.png?tr=h-52,q-85,c-at_max" width="104" height="52" alt="Chefstore.nl is FD Gazelle 2024!" loading="lazy" fetchpriority="low">
                </div>
                <div class="col d-flex justify-content-center align-items-center">
                  <img class="img-fluid" src="//images.chefstore.nl/media/wysiwyg/banners/fd-gazelle-2025.ts1731107036.png?tr=h-52,q-85,c-at_max" width="113" height="52" alt="Chefstore.nl is FD Gazelle 2025!"  loading="lazy" fetchpriority="low">
                </div>
                <div class="col d-flex justify-content-center align-items-center">
                  <img class="img-fluid" src="//images.chefstore.nl/media/wysiwyg/banners/2025_ft1000.ts1741106066.png?tr=h-52,q-85,c-at_max" width="68" height="52" alt="1000 Fastest Growing Companies 2025"  loading="lazy" fetchpriority="low">
                </div>
              </div>
            </div>
            <div class="row my-4 footer-links-row">
              <div class="col-6 col-sm-6 col-xl-3">
                <a class="strong" href="/merken.html">
                  <h3>Merken</h3>
                </a>
                <ul>
                  <li class="pb-1"><a href="/l/merken/arktic.html">Arktic</a></li>
                  <li class="pb-1"><a href="/l/merken/buffalo.html">Buffalo</a></li>
                  <li class="pb-1"><a href="/l/merken/combisteel.html">Combisteel</a></li>
                  <li class="pb-1"><a href="/l/merken/diamond.html">Diamond</a></li>
                  <li class="pb-1"><a href="/l/merken/hendi.html">Hendi</a></li>
                  <li class="pb-1"><a href="/l/merken/liebherr-professional.html">Liebherr</a></li>
                  <li class="pb-1"><a href="/l/merken/maxima.html">Maxima</a></li>
                  <li class="pb-1"><a href="/l/merken/polar.html">Polar</a></li>
                  <li class="pb-1"><a href="/l/merken/saro.html">Saro</a></li>
                  <li class="pb-1"><a href="/l/merken/tefcold.html">Tefcold</a></li>
                  <li class="pb-1"><a class="strong" href="/merken.html"><strong>Alle Merken</strong></a></li>
                </ul>
              </div>
              <div class="col-6 col-sm-6 col-xl-3">
                <a class="strong" href="/alle-series.html">
                  <h3>Series</h3>
                </a>
                <ul>
                  <li class="pb-1"><a href="/shop?brand_series=2892&title=Bartscher-Silversteam">Bartscher Silverstream</a></li>
                  <li class="pb-1"><a href="/shop?brand_series=3318&title=Combisteel-Energy">Combisteel Energy Line</a></li>
                  <li class="pb-1"><a href="/shop?brand_series=2611&title=Combisteel-Pro-700">Combisteel Pro 700</a></li>
                  <li class="pb-1"><a href="/shop?brand_series=2780&title=Dynamic-Dynamix">Dynamic Dynamix</a></li>
                  <li class="pb-1"><a href="/shop?brand_series=2695&title=Gastro-M-650">Gastro M 650</a></li>
                  <li class="pb-1"><a href="/shop?brand_series=2726&title=Hendi-Kitchen-Line">Hendi Kitchen Line</a></li>
                  <li class="pb-1"><a href="/shop?brand_series=2727&title=Hendi-Profi-Line">Hendi Profi Line</a></li>
                  <li class="pb-1"><a href="/shop?brand_series=3901&title=Liebherr-Premium">Liebherr Premium</a></li>
                  <li class="pb-1"><a href="/shop?brand_series=2693&title=Polar-G-serie">Polar G-Serie</a></li>
                  <li class="pb-1"><a href="/shop?brand_series=2691&title=Polar-U-serie">Polar U-Serie</a></li>
                  <li class="pb-1"><a class="strong" href="/alle-series.html"><strong>Alle Series</strong></a></li>
                </ul>
              </div>
              <div class="col-12 col-sm-6 col-xl-3 text-center text-sm-start">
                <a href="/over">
                  <h3>Over Chefstore.nl</h3>
                </a>
                <ul>
                  <li class="pb-1"><a href="/blog">Blog</a></li>
                  <li class="pb-1"><a href="/contact">Contact</a></li>
                  <li class="pb-1"><a href="//service.chefstore.nl">Veelgestelde vragen</a></li>
                  <li class="pb-1"><a href="/tips-achteraf-betalen">Achteraf betalen</a></li>
                  <li class="pb-1"><a href="/service">Nieuw Serviceverzoek</a></li>
                  <li class="pb-1"><a href="/algemene-voorwaarden">Algemene voorwaarden</a></li>
                  <li class="pb-1"><a href="/retourneren">Retourbeleid</a></li>
                  <li class="pb-1"><a href="/feedback">Feedback & Bezwaar</a></li>
                  <li class="pb-1"><a href="/privacy-policy">Privacy</a></li>
                  <li class="pb-1"><a href="/linkpartners">Linkpartners</a></li>
                </ul>
              </div>
              <div class="col-12 col-sm-6 col-xl-3 center" style="overflow:hidden; min-width:0;">
                <valued-widget layout="badges" align="center"></valued-widget>
              </div>
            </div>
            <div class="row justify-content-center my-2">
              <div class="col-auto h-stack text-center">
                <a href="//www.instagram.com/chefstore.nl/" title="Instagram" target="_blank" rel="nofollow noreferrer noopener me">
                  <i class="fa-2x fa fa-instagram" aria-hidden="true"></i></a>
                <a href="//www.facebook.com/Chefstorenl-233543287886724/" title="Facebook" target="_blank" rel="nofollow noreferrer noopener me">
                  <i style="padding: 0 .5em" class="fa-2x fa fa-facebook-official" aria-hidden="true"></i></a>
                <a href="//www.linkedin.com/company/chefstore-nl/" title="LinkedIn" target="_blank" rel="nofollow noreferrer noopener me">
                  <i class="fa-2x fa fa-linkedin" aria-hidden="true"></i></a>
              </div>
            </div>
          </div>
        </div>
        <div class="pt-4">
          <img class="center" src="//images.chefstore.nl/skin/frontend/rwd/dhh/images/logo-chefstore.ts1741106066.min.svg" alt="Chefstore.nl" title="Chefstore.nl" height="40" width="208" loading="lazy" fetchpriority="low">
        </div>
        <div class="text-center py-1 h3 blue">
          <em>&#193;lles voor de Chef</em>
        </div>
        <div class="text-center py-3 fw-light small">
          Groothandel voor professionele horeca-artikelen. Wij zijn horeca-experts voor horeca-professionals en enthousiaste thuis-chefs. Bij Chefstore.nl bestel je premium keukenapparatuur en non-food producten voor de horeca branche, waaronder keukens, cafetaria's, snackbars, kwalitaria's, cateraars en hotels. Vraag een offerte aan voor n&#243;g betere deals.
        </div>
        <div class="text-center py-2 small footer-policy-links">
          <a class="mx-4" href="/algemene-voorwaarden">Algemene voorwaarden</a>
          <a class="mx-4" href="/privacy-policy">Privacy</a>
        </div>
        <div class="text-center pt-2 pb-5 fw-light small">© 2017 - 2026 Chefstore.nl | Amsterdam, Nederland | KvK: 69637717</div>
      </div>
    </footer>
    <script async type="module">import '/skin/assets/glightbox/dist/js/glightbox.ts1741106066.min.js'; const lightbox = GLightbox({}); var lightboxInlineIframe = GLightbox({ selector: '.glightbox4' });</script>
    <script async type="module" id="ze-snippet" src="//static.zdassets.com/ekr/snippet.js?key=6a6d58da-d9c1-4d6a-98f5-5873329abca0"></script>
    <script defer src="//static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"token":"aa45f67d65b64446beda8aca0bfd6f98"}'></script>
    <!-- footer_end -->
EOT;

echo $html;

if(getOmDhhFpcHelper()->is_write_cache_enabled(true, true, "footer_html")) {
  DeHeerHoreca_Fpc_Helper_Data::saveToCacheDeferred(DHH_FPC_FOOTER_KEY, $html, ["DHH_CMS"], 86400 * 7, minifyHtml: true);
}
