<?php
$html = <<<EOT
<!-- footer_start -->
<div class="footer-wrapper grid-inside" id="footer-wrapper">
  <div class="footermidwrap blanc">
    <div class="footer grid" id="footer-grid">
      <div class="pb-4 text-center">
        <a href="//www.instagram.com/chefstore.nl/" title="Instagram" target="_blank" rel="nofollow noreferrer noopener">
        <i class="fa-3x fa fa-instagram" aria-hidden="true"></i></a>
        <a href="//www.facebook.com/Chefstorenl-233543287886724/" title="Facebook" target="_blank" rel="nofollow noreferrer noopener">
        <i style="padding: 0 .5em" class="fa-3x fa fa-facebook-official" aria-hidden="true"></i></a>
        <a href="//www.linkedin.com/company/chefstore-nl/" title="LinkedIn" target="_blank" rel="nofollow noreferrer noopener">
        <i class="fa-3x fa fa-linkedin" aria-hidden="true"></i></a>
        <img class="ms-3" src="//images.chefstore.nl/media/wysiwyg/banners/2023_fd_gazellen_small.ts1741106066.png?tr=h-42,q-85,c-at_max" height=42 style="display:inline;" alt="Chefstore is FD Gazelle 2023!">
      </div>
      <div class="column">
        <div class="col-1-4">
          <h3>Merken</h3>
          <ul>
            <li class="pb-1"><a href="/shop?manufacturer=54&title=">Combisteel</a></li>
            <li class="pb-1"><a href="/shop?manufacturer=1619&title=Hendi">Hendi</a></li>
            <li class="pb-1"><a href="/shop?manufacturer=1074&title=Bartscher">Bartscher</a></li>
            <li class="pb-1"><a href="/shop?manufacturer=2753&title=Gamko">Gamko</a></li>
            <li class="pb-1"><a href="/shop?manufacturer=192&title=EcoFrost">EcoFrost</a></li>
            <li class="pb-1"><a href="/shop?manufacturer=4132&title=Tefcold">Tefcold</a></li>
            <li class="pb-1"><a href="/shop?manufacturer=4128&title=Maxima">Maxima</a></li>
            <li class="pb-1"><a href="/shop?manufacturer=162&title=Saro">Saro</a></li>
            <li class="pb-1"><a href="/shop?manufacturer=53&title=Polar">Polar</a></li>
            <li class="pb-1"><a class="strong" href="/merken.html"><strong>Alle Merken</strong></a></li>
          </ul>
        </div>
        <div class="col-1-4">
          <h3>Series</h3>
          <ul>
            <li class="pb-1"><a href="/shop?brand_series=2892&title=Bartscher-Silversteam">Bartscher Silverstream</a></li>
            <li class="pb-1"><a href="/shop?brand_series=3318&title=Combisteel-Energy">Combisteel Energy Line</a></li>
            <li class="pb-1"><a href="/shop?brand_series=2611&title=Combisteel-Pro-700">Combisteel Pro 700</a></li>
            <li class="pb-1"><a href="/shop?brand_series=2780&title=Dynamic-Dynamix">Dynamic Dynamix</a></li>
            <li class="pb-1"><a href="/shop?brand_series=2695&title=Gastro-M-650">Gastro M 650</a></li>
            <li class="pb-1"><a href="/shop?brand_series=2726&title=Hendi-Kitchen-Line">Hendi Kitchen Line</a></li>
            <li class="pb-1"><a href="/shop?brand_series=2727&title=Hendi-Profi-Line">Hendi Profi Line</a></li>
            <li class="pb-1"><a href="/shop?brand_series=2692&title=Polar-C-serie">Polar C-Serie</a></li>
            <li class="pb-1"><a href="/shop?brand_series=2693&title=Polar-G-serie">Polar G-Serie</a></li>
            <li class="pb-1"><a href="/shop?brand_series=2691&title=Polar-U-serie">Polar U-Serie</a></li>
            <li class="pb-1"><a class="strong" href="/alle-series.html"><strong>Alle Series</strong></a></li>
          </ul>
        </div>
        <div class="col-1-4">
          <a href="/over"><h3>Over Chefstore.nl</h3></a>
          <ul>
            <li class="pb-1"><a href="/blog">Blog</a></li>
            <li class="pb-1"><a href="/contact">Contact</a></li>
            <li class="pb-1"><a href="/tips-achteraf-betalen">Achteraf betalen</a></li>
            <li class="pb-1"><a href="/klantenservice">Klantenservice</a></li>
            <li class="pb-1"><a href="/service">Nieuw Serviceverzoek</a></li>
            <li class="pb-1"><a href="/algemene-voorwaarden">Algemene voorwaarden</a></li>
            <li class="pb-1"><a href="/retourneren">Retourbeleid</a></li>
            <li class="pb-1"><a href="/feedback">Feedback & Bezwaar</a></li>
            <li class="pb-1"><a href="/privacy-policy">Privacy</a></li>
            <li class="pb-1"><a href="/linkpartners">Linkpartners</a></li>
          </ul>
        </div>
        <div class="col-1-4 center">
          <h3>Klanten over Chefstore.nl:</h3>
          <a href="//www.kiyoh.com/reviews/1044049/chefstore?from=widget&lang=nl" target="_blank" rel="nofollow noreferrer noopener">
            <img id="kiyoh-image" src="//images.chefstore.nl/media/wysiwyg/kiyoh_96.ts1741106066.svg?tr=w-300,q-85,c-at_max" alt="Chefstore.nl Reviews" class="small center" style="height:100%; width:100%" loading="lazy">
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="pt-4">
    <img class="center" src="/skin/frontend/rwd/dhh/images/logo-chefstore.ts1741106066.min.svg" alt="Chefstore.nl" title="Chefstore.nl" height="40" width="208" loading="lazy">
  </div>
  <div class="text-center py-1 h3 blue"><em>Alles voor de Chef</em></div>
  <div class="text-center py-3">Non-food horeca groothandel voor hotels, restaurants, bedrijfskantines, scholen, catering, gemeentes, grootkeukens en caf&eacute;'s</div>
  <div class="text-center py-2">
    <a class="mx-4" href="/algemene-voorwaarden">Algemene voorwaarden</a>
    <a class="mx-4" href="/privacy-policy">Privacy</a>
  </div>
  <div class="text-center pt-2 pb-5">© 2017 - 2025 Chefstore.nl | Amsterdam, Nederland | KvK: 69637717</div>
</div>

<script type="module">
  import '/skin/assets/glightbox/dist/js/glightbox.ts1741106066.min.js';
  const lightbox = GLightbox({touchNavigation: true});
  var lightboxInlineIframe = GLightbox({
    selector: '.glightbox4',
    touchNavigation: false,
    keyboardNavigation: false,
    preload: false
  });
</script>

<script async type="module">
  !function(e,t,n){var r=e.createElement(t),a=e.getElementsByTagName(t)[0];r.src="/js/ext-elastic-apm-rum.umd.ts1741106066.min.js",r.onload=function(){elasticApm.init(n)},a.parentNode.insertBefore(r,a)}(document,"script",{serviceName:"openmage",serverUrl:"//rum.chefstore.nl:8200",environment:document.querySelector("html").dataset.environment,pageLoadTransactionName:document.querySelector("html").dataset.transaction});
</script>

<script id="ze-snippet" src="//static.zdassets.com/ekr/snippet.js?key=6a6d58da-d9c1-4d6a-98f5-5873329abca0"></script>
<!-- footer_end -->
EOT;
echo $html;

// @todo replace with APCu?
$key = DHH_FPC_FOOTER_KEY; // "DHH_CMS_FOOTER"
if(Mage::helper("deheerhoreca_fpc/data")->is_write_cache_enabled(true, true, "footer_html")) {
  if(Mage::app()->getCache()->save($html, $key , ["DHH_CMS"], 24 * 3600)) {
    DeHeerHoreca_Fpc_Helper_Data::log("Cache: SAVED {$key}, ".strlen($html)." chars");
  }
} else {
  DeHeerHoreca_Fpc_Helper_Data::log("Cache: NOT SAVED {$key}, ".strlen($html)." chars");
}
