<?php

declare(strict_types=1);

/*
- @see https://speakerdeck.com/csswizardry/get-your-head-straight
- @see https://fishpig.co.uk/magento/optimisation/remove-default-magento-javascript/
<!-- <link rel="preload" href="/skin/frontend/rwd/dhh/fonts/opensans/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWuU6F.woff2" as="font" type="font/woff2"> -->
<!-- <link rel="preload" href="/skin/frontend/rwd/dhh/fonts/opensans/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS-muw.woff2" as="font" type="font/woff2"> -->
- /js/ext-translator.js has to be updated manually and loaded after getCssJsHtml()!
  Regenerate: <?php // echo $this->helper("core/js")->getTranslatorScript(); ?>
*/

$page_title = Mage::helper("deheerhoreca_util/util")->cleanCategoryName((string) $this->getTitle());

?>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?=$page_title?></title>
<script src="/js/ext-jquery.ts1741106066.min.js"></script>
<script src="/js/ext-prototype.ts1741106066.min.js"></script>
<script src="/js/ext-scriptaculous-builder.ts1741106066.min.js"></script>
<script src="/js/ext-scriptaculous-effects.ts1741106066.min.js"></script>
<script src="/js/ext-jquery-ui.ts1741106066.min.js"></script>
<script src="/js/ext-jquery.ui.touch-punch.ts1741106066.min.js"></script>
<?=$this->getCssJsHtml()?>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/skin/frontend/rwd/dhh/fonts/font-awesome-4.7.0/css/font-awesome.ts1741106066.min.css" media="print" onload="this.media='all'">
<link rel="stylesheet" href="/skin/assets/glightbox/dist/css/glightbox.ts1741106066.min.css" media="print" onload="this.media='all'">
<?=$this->getChildHtml()?>
<script src="/js/ext-translator.js" defer></script>
<?=$this->getIncludes()?>
<meta name="description" content="<?=htmlspecialchars((string) $this->getDescription())?>">
<meta name="keywords" content="<?=htmlspecialchars((string) $this->getKeywords())?>">
<meta name="robots" content="<?=htmlspecialchars((string) $this->getRobots())?>">
<meta name="theme-color" content="#fff">
<meta name="application-name" content="Chefstore.nl">
<meta name="apple-mobile-web-app-title" content="Chefstore.nl">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="shortcut icon" href="/favicon.ico">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<?php // FUCKS with lighthouse score: https://github.com/GoogleChrome/lighthouse/issues/9505  <link rel="manifest" href="/site.webmanifest"> ?>
