<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
//echo $this->getLayout()->createBlock("cms/block")->setBlockId("header_top")->toHtml();

if(Mage::getSingleton("customer/session")->isLoggedIn()) {
  $account_url = $this->helper("customer")->getAccountUrl();
} else {
  $account_url = Mage::getUrl("customer/account/login");
}
?>
<header id="header" class="page-header header grid-inside scrlng">
  <div id="page-header-container" class="page-header-container grid-old">
    <div class="header__inside">
      <div class="skip-links headerrightcontents">
        <a class="main-logo" href="/"><img id="main-logo" src="<?php echo $this->getLogoSrcSmall(); ?>" alt="<?php echo $this->getLogoAlt() ?>" title="<?php echo $this->getLogoAlt() ?>" height="40" width="208"></a>
        <div id="header-search" ><?php echo $this->getChildHtml("topSearch") ?></div>
        <div class="account-cart-wrapper">
          <span class="ms-2"><a data-fancybox data-type="iframe" href="/media/static/contact.php" class="fancybox btn btn-primary toplink-phone skip-phone top-link"><i class="fa fa-phone fa-2x fa-fw" title="Bellen"></i></a></span>
          <span class="ms-2"><a href="<?php echo Mage::getUrl("customer/account"); ?>" class="skip-account top-link" title="Account"><i class="fa fa-user-circle fa-2x fa-fw"></i></a></span>
          <span class="ms-2"><?php echo $this->getChildHtml("miniquote_head"); ?></span>
          <span class="ms-2"><?php echo $this->getChildHtml("minicart_head"); ?></span>
        </div>
      </div>
    </div>
  </div>

  <div id="header-nav" class="skip-content">
    <?php echo $this->getChildHtml("topMenu") ?>
  </div>
  <?php
  
  // echo $this->getLayout()->createBlock("cms/block")->setBlockId("header_top")->toHtml();
  
  // Action-specific marketing messages
  $action = Mage::app()->getFrontController()->getAction()->getFullActionName();
  
  $top_messages = [
    "left"        => null,
    "center"      => null,
    "right"       => null,
  ];
  
  switch($action) {
    case "catalog_product_view":
    case "catalog_category_view":
    case "firecheckout_index_index":
    case "checkout_cart_index":
    case "cms_index_index":
    case "qquoteadv_index_index":
    default:
      // $top_messages["left"]   = "<a href='/shop?manufacturer=2753'>Nieuw in het assortiment: <strong>Gamko</strong></a>";
      // $top_messages["left"]   = "Achteraf betalen met <a href='/qquoteadv/index/'><strong>Biller</strong></a>, <strong>AfterPay</strong>, <strong>In3</strong></a>";
      $top_messages["left"]   = "5% korting op Gastro-Inox met code <strong>GASTROINOX5</strong>";
      $top_messages["center"] = "<a href='/promoties.html'><strong>SALE</strong></a>";
      $top_messages["right"]  = "<a href='/qquoteadv/index/'>Maak een <strong>offerte</strong> voor lease of koop</a>";
      break;
  }
  ?>
  <div class="clzinfopagetop">
    <div class="pageinfotpinner">
      <span class="d-none d-xl-block align-left float-left"><?php echo $top_messages["left"]; ?></span>
      <span class="align-center"><?php echo $top_messages["center"]; ?></span>
      <span style="width:33%;" class="d-none d-xl-block align-right float-right"><?php echo $top_messages["right"]; ?></span>
    </div>
  </div>
  <?php
  
  echo $this->getChildHtml("topContainer");
  ?>
</header>
