<?php

require_once __DIR__."/../dhhfpc_conf.php";

$_cacheKey = "QUICKNDIRTYFPC-topmenu";

$static_file = "./media/static/topmenu.html";

// Outqualification
$write_cache = true;
$read_cache = true;

if(isset($_GET['nofpc'])) {
  $write_cache = false;
  $read_cache = false;
}
if(isset($_GET['refreshfpc'])) {
  $write_cache = true;
  $read_cache = false;
}
if(DHH_FPC_ENABLED === false) {
  $write_cache = false;
  $read_cache = false;
}

$_html = null;

if($read_cache === true) {
  $_html = Mage::app()->getCache()->load($_cacheKey);
}

if(strlen($_html) > 0 === FALSE) {
  $_html = $this->getHtml('level-top');
  if($write_cache === true) {
    Mage::app()->getCache()->save($_html, $_cacheKey, ["quickndirtyfpc"]);
  }
}

?>

<nav id="nav" class="grid-old">
  <div class="navhdwrap">
    <ol id="top-nav" class="nav-primary" style="float: left;">
      <?php
      
      //if(is_file($static_file) === false) {
      //  file_put_contents($static_file, $_html);
        echo $_html;
      //}
      
      ?>
    </ol>
  </div>
</nav>

<?php
//if(is_file($static_file)) {
//  echo '<script type="text/javascript">jQuery(document).ready(function(){jQuery(\'#top-nav\').load("/media/static/topmenu.html");});</script>';
//}
