<?php

// require_once __DIR__."/../dhh_fpc.conf.php";

// $_cacheKey = "QUICKNDIRTYFPC-cms_block-topmenu";

// // $static_file = "./media/static/topmenu.html";

// // Outqualification
// $write_cache = true;
// $read_cache = true;

// if(isset($_GET['nofpc'])) {
  // $write_cache = false;
  // $read_cache = false;
// }
// if(isset($_GET['refreshfpc'])) {
  // $write_cache = true;
  // $read_cache = false;
// }
// if(DHH_FPC_ENABLED === false) {
  // $write_cache = false;
  // $read_cache = false;
// }

// $_html = null;

// // print_r("Cache Key: {$_cacheKey}");

// if($read_cache === true) {
  // $_html = Mage::app()->getCache()->load($_cacheKey);
// } else {
  // // print_r("<br />Menu cache: NO CACHE");
// }

// if(strlen($_html) > 0 === false) {
  $_html = $this->getHtml('level-top');
  // // print_r("<br />Menu cache: MISS");
  // if($write_cache === true) {
    // Mage::app()->getCache()->save($_html, $_cacheKey, ["quickndirtyfpc"], 86400);
  // }
// } else {
  // // print_r("<br />Menu cache: HIT");
// }

?>

<nav id="nav" class="grid-old navhdwrap">
  <a href="#header-nav" class="skip-link skip-nav no-decoration">
    <i class="fa fa-bars fa-2x"></i>
    <span class="label">Menu</span>
  </a>
  <ol id="top-nav" class="nav-primary" style="float: left;">
    <?php
    echo $_html;
    ?>
  </ol>
</nav>

<?php
//if(is_file($static_file)) {
//  echo '<script type="text/javascript">jQuery(document).ready(function(){jQuery(\'#top-nav\').load("/media/static/topmenu.html");});</script>';
//}
