/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

var euvatResult;


/**
 * Validates the Number and takes care of other actions
 *
 * @param vatNumber AB123456789
 * @param op_mode SINGLE or MULTI
 * @param address_type billing or shipping
 * @param address_id int
 * @param doUpdateCountry bool
 * @param field_id string
 */
var validateVat = function(vatNumber, op_mode, address_type, address_id, doUpdateCountry, field_id)
{
    if(typeof(address_id) === 'undefined' || address_id === 'undefined') {
        address_id = 0;
    }
    if(typeof(doUpdateCountry) === 'undefined') {
        doUpdateCountry = false;
    }
    if(typeof(gw_auto_set_country) === 'number' && gw_auto_set_country === 1) {
        doUpdateCountry = true;
    }
    var updateNumberWithCountry = false;
    if(typeof(field_id) !== 'undefined') {
        updateNumberWithCountry = true;
    }

    try
    {
        if( typeof(vatNumber) === "string" )
        {
            vatNumber = vatNumber.replace(/[\W_]/g, "").toUpperCase().trim();

            // Try to get country from select if VAT number does not contain country
            if( vatNumber.length > 0 && !vatNumber.match(new RegExp('^[A-Z][A-Z]')))
            {
                var elementIds = ['country', 'country_id'];
                if(address_type === 'billing') {
                    elementIds.push('billing:country_id');
                } else if(address_type === 'shipping') {
                    elementIds.push('shipping:country_id');
                }
                var selectCountry;
                elementIds.forEach(function(id) {
                    if(document.body.contains(document.getElementById(id))) {
                        selectCountry = $(id).getValue();
                        if(selectCountry === 'GR') {
                            selectCountry = 'EL';
                        }
                    }
                });
                if(typeof(selectCountry) === 'string') {
                    vatNumber = selectCountry+vatNumber.trim();
                    if(updateNumberWithCountry) {
                        $(field_id).setValue(vatNumber);
                        if(address_type === 'billing'
                            && document.body.contains(document.getElementById('shipping:vat_id'))
                        ) {
                            $('shipping:vat_id').setValue(vatNumber);
                        }
                    }
                }
            }

            // Do validation of the value on online service
            if( vatNumber.match(new RegExp('^[A-Z][A-Z]')))
            {
                new Ajax.Request(gw_vat_check_url, {
                    method: 'post',
                    parameters: 'taxvat='+vatNumber+ '&op_mode='+op_mode+ '&address_type='+address_type+ '&address_id='+address_id,
                    onLoading: function () {
                        switch (op_mode) {
                            case 'SINGLE':
                                $('vatLoader').show();
                                break;
                            case 'MULTI':
                                $(address_type + ':vatLoader').show();
                                break;
                        }
                        if ($('advice-validate-vatnumber-billing:vat_id')) {
                            $('advice-validate-vatnumber-billing:vat_id').remove();
                        }
                        if ($('advice-validate-vatnumber-shipping:vat_id')) {
                            $('advice-validate-vatnumber-shipping:vat_id').remove();
                        }
                        if ($('advice-validate-vatnumber:vat_id')) {
                            $('advice-validate-vatnumber:vat_id').remove();
                        }
                    },
                    onComplete: function () {
                        switch (op_mode) {
                            case 'SINGLE':
                                $('vatLoader').hide();
                                break;
                            case 'MULTI':
                                $(address_type + ':vatLoader').hide();
                                break;
                        }
                        if (gw_osc_integration !== '') {
                            handleOSC();
                        }
                    },
                    onSuccess: function (transport) {
                        // Evaluate validation result
                        euvatResult = transport.responseText.evalJSON();
                        var output = '<ul class="vat_validation-messages" style="margin-top:5px;">';

                        if (euvatResult.vat_is_valid === true && typeof(euvatResult.faultstring) === "undefined") {
                            output += '<li class="success-msg">';
                            output += (Translator.translate('Your VAT-ID is valid.'));
                            output += ' ';

                            if (euvatResult.is_vat_free === true) {
                                output += (Translator.translate('We have identified you as EU business customer, you can order VAT-exempt in our shop now.'));
                            } else if (euvatResult.is_vat_free === false) {
                                output += (Translator.translate('We have identified you as business customer.'));
                            }
                            output += '</li>';
                            output += '</ul>';

                        } else if (euvatResult.vat_is_valid === false && typeof(euvatResult.faultstring) === "undefined") {
                            output += '<li class="error-msg">';
                            output += (Translator.translate('Your VAT-ID is invalid, please check the syntax.'));
                            output += '</li></ul>';
                        } else {
                            output += '<li class="notice-msg">';
                            switch (euvatResult.faultstring) {
                                case "INVALID_INPUT":
                                case "Invalid_input":
                                    output += (Translator.translate('The given VAT-ID is invalid, please check the syntax. If this error remains please contact us directly to register a customer account with exempt from taxation with us.'));
                                    break;
                                case "SERVICE_UNAVAILABLE":
                                case "SERVER_BUSY":
                                case "GLOBAL_MAX_CONCURRENT_REQ":
                                    output += (Translator.translate('Currently the European VIES service is unavailable, but you can proceed with your registration and validate later from your customer account management.'));
                                    break;
                                case "MS_UNAVAILABLE":
                                case "MS_MAX_CONCURRENT_REQ":
                                case "TIMEOUT":
                                    output += (Translator.translate('Currently the member state service is unavailable, we could not validate your VAT-ID to issue an VAT exempt order. Anyhow you can proceed with your registration and validate later in your customer account.'));
                                    break;
                                default:
                                    output += (Translator.translate('There was an error processing your request. If this error remains please contact us directly to register a customer account with exempt from taxation with us.'));
                                    break;
                            }
                            output += '</li></ul>';
                        }

                        // Validation output
                        switch (op_mode) {
                            case 'SINGLE':
                                $('checkrsp').update(output);
                                break;
                            case 'MULTI':
                                $(address_type + ':checkrsp').update(output);
                                break;
                            default:
                                break;
                        }

                        if(doUpdateCountry) // Update country when different from VAT country
                        {
                            var elementIds = ['country', 'country_id'];
                            if(address_type === 'billing') {
                                elementIds.push('billing:country_id');
                            } else if(address_type === 'shipping') {
                                elementIds.push('shipping:country_id');
                            }

                            elementIds.forEach(function(id) {
                                if(document.body.contains(document.getElementById(id))
                                    && $F(id) !== euvatResult.country_id
                                ) {
                                    $$('select[id="'+id+'"] option').each(function (o) {
                                        if (o.readAttribute('value') === euvatResult.country_id ) {
                                            if(gw_auto_set_country_customer_confirm === 1
                                                && confirm(Translator.translate('The country prefix of the VAT number is different from the selected address country. Should we set the address country automatically?'))
                                            ) {
                                                o.selected = true;
                                                fireEvent($(id), 'change');
                                            } else if(gw_auto_set_country_customer_confirm === 0) {
                                                o.selected = true;
                                                fireEvent($(id), 'change');
                                            }

                                        }
                                    });
                                }
                            });
                        }
                    },
                    onFailure: function () {
                        switch (op_mode) {
                            case 'SINGLE':
                                $('checkrsp').update('<ul><li class="error-msg">' + Translator.translate('There was an error processing your request. If this error remains please contact us directly to register a customer account with exempt from taxation with us.') + '</li></ul>');
                                break;
                            case 'MULTI':
                                $(address_type + ':checkrsp').update('<ul><li class="error-msg">' + Translator.translate('There was an error processing your request. If this error remains please contact us directly to register a customer account with exempt from taxation with us.') + '</li></ul>');
                                break;
                        }
                    }
                });//endajax

            } else if( vatNumber === "") {

                new Ajax.Request(gw_vat_check_url, {
                    method:'post',
                    parameters:'vatid=removed'+'&address_type='+address_type+'&address_id='+address_id,
                    onComplete: function () {
                        switch (op_mode) {
                            case 'SINGLE':
                                $('vatLoader').hide();
                                $('checkrsp').update();
                                break;
                            case 'MULTI':
                                $(address_type + ':vatLoader').hide();
                                $(address_type+':checkrsp').update();
                                break;
                        }
                        if (gw_osc_integration !== '') {
                            handleOSC();
                        }
                    }
                });//endajax

            } else {
                switch(op_mode) {
                    case 'SINGLE':
                        $('checkrsp').update('<ul>' +
                            '<li class="notice-msg">'+Translator.translate('Please enter your VAT-ID including the ISO-3166 two letter country code.')+'</li>' +
                            '</ul>');
                        break;
                    case 'MULTI':
                        $(address_type+':checkrsp').update('<ul>' +
                            '<li class="notice-msg">'+Translator.translate('Please enter your VAT-ID including the ISO-3166 two letter country code.')+'</li>' +
                            '</ul>');
                        break;
                }
            }
        }

    } catch (error) {
        console.log("Error during VAT number validation: "+error);
    }

};

var vatValidation = function() {
    var op_mode = 'SINGLE';
    this.field_id = 'vat_id';
    this.prefix = '';
    this.address_id = 0;
    this.doUpdateCountry = false;

    this.setOpMode = function ()
    {
        if( document.body.contains(document.getElementById('billing:vat_id'))) {
            this.field_id = 'vat_id';
            this.prefix = 'billing:';
            op_mode = 'MULTI';
        } else if( document.body.contains(document.getElementById('billing:taxvat'))) {
            this.field_id = 'taxvat';
            this.prefix = 'billing:';
            op_mode = 'MULTI';
        }
    };

    this.setListener = function()
    {
        var field_id;
        var shipping_field_id;
        var address_id = this.address_id;
        var doUpdateCountry = this.doUpdateCountry;

        // Add listener for default/billing VAT ID
        if( document.body.contains(document.getElementById('billing:'+this.field_id)) ) {
            field_id = 'billing:'+this.field_id;
        } else if( document.body.contains(document.getElementById(this.field_id)) ) {
            field_id = this.field_id;
        }
        if($(field_id)) {
            $(field_id).observe('blur', function(e) {
                this.value = this.value.replace(/[\W_]/g, "").toUpperCase().trim();
                validateVat(this.value, op_mode, 'billing', address_id, doUpdateCountry, field_id);
            });
        }


        // Add listener for shipping VAT ID
        if( op_mode === 'MULTI' && document.body.contains(document.getElementById('shipping:'+this.field_id)) ){
            shipping_field_id = 'shipping:'+this.field_id;
            if($(shipping_field_id)) {
                $(shipping_field_id).observe('blur', function(e) {
                    this.value = this.value.replace(/[\W_]/g, "").toUpperCase().trim();
                    validateVat(this.value, op_mode, 'shipping', address_id, doUpdateCountry, shipping_field_id);
                });
            }
        }

        if(typeof(Validation) === 'function')
        {
            if(gw_require_valid_vat === 1 || gw_require_valid_vat === 3)
            {
                if($(field_id)) $(field_id).addClassName('require-valid-vat');
                if($(shipping_field_id)) $(shipping_field_id).addClassName('require-valid-vat');

                Validation.add('require-valid-vat', Translator.translate('A valid VAT number is required.'), function(fieldValue){
                    if(typeof(euvatResult) === 'object') {
                        if(euvatResult.vat_is_valid === true) {
                            return true;
                        }
                    }
                    return false;
                });

            } else if(gw_require_valid_vat === 4) {

                if($(field_id)) $(field_id).addClassName('require-valid-vat-if-filled');
                if($(shipping_field_id)) $(shipping_field_id).addClassName('require-valid-vat-if-filled');

                Validation.add('require-valid-vat-if-filled',
                    Translator.translate('Please provide a valid VAT number or leave the field empty.'),
                    function(fieldValue) {
                        if(fieldValue.length <= 0) {
                            return true;
                        }
                        if(typeof(euvatResult) === 'object') {
                            if(euvatResult.vat_is_valid === true) {
                                return true;
                            }
                        } else {
                            return false;
                        }
                });
            }

        }

    };

    this.addFormValidation = function()
    {

    };

    this.addResponseFields = function(gw_loader_src)
    {
        this.wait_message = '<img class="v-middle" title="'+Translator.translate('Please wait while we validate your VAT-ID')+'" alt="'+Translator.translate('Please wait while we validate your VAT-ID')+'" src="'+ gw_loader_src +'">' +
                            '<span> '+Translator.translate('Please wait while we validate your VAT-ID')+'</span></div>';

        switch(op_mode)
        {
            case 'SINGLE':
                if( document.body.contains(document.getElementById(this.prefix+this.field_id)) ) {
                    $(this.prefix+this.field_id).insert({
                        after: '<div id="vatLoader">' +
                        this.wait_message +
                        '<div id="checkrsp"></div>'
                    });
                    $('vatLoader').hide();
                }
            break;

            case 'MULTI':
                if( document.body.contains(document.getElementById('billing:'+this.field_id)) ) {
                    $('billing:'+this.field_id).insert({
                        after: '<div id="billing:vatLoader">' +
                        this.wait_message +
                        '<div id="billing:checkrsp"></div>'
                    });
                    $('billing:vatLoader').hide();
                }

                if( document.body.contains(document.getElementById('shipping:'+this.field_id)) )
                {
                    $('shipping:'+this.field_id).insert({
                        after: '<div id="shipping:vatLoader">' +
                            this.wait_message +
                            '<div id="shipping:checkrsp"></div>'
                    });
                    $('shipping:vatLoader').hide();
                }

            break;
        }
    };

    this.getParams = function(url)
    {
        var parts = url.split('/').slice(1);
        if( url.indexOf("customer/address/edit/id") !== -1 ) {
            this.address_id = parts[parts.length-2];
            this.doUpdateCountry = true;
        }
    };

};


/**
 * Prepare VAT Validation on page load
 */
document.observe("dom:loaded", function()
{
    if(gw_vat_validation_enabled === 1)
    {
        var vatValidator = new vatValidation();
        vatValidator.setOpMode();
        vatValidator.getParams(location.pathname);
        vatValidator.setListener();
        vatValidator.addResponseFields(gw_loader_src);
    }
});

/**
 * Thanks to http://stackoverflow.com/users/561731/neal
 */
var Queue = (function(){
    function Queue() {};
    Queue.prototype.running = false;
    Queue.prototype.queue = [];

    Queue.prototype.add_function = function(callback) {
        var _this = this;
        this.queue.push(function(){
            var finished = callback();
            if(typeof finished === "undefined" || finished) { _this.next(); }
        });
        if(!this.running) { this.next(); }
        return this;
    };

    Queue.prototype.next = function(){
        this.running = false;
        var shift = this.queue.shift();
        if(shift) { this.running = true; shift(); }
    };
    return Queue;
})();

function gwIdSel( elementId ) {
    return "#" + elementId.replace( /(:|\.|\[|\]|,)/g, "\\$1" );
}


//Handle OSC integrations
var handleOSC = function(result)
{
    var queue = new Queue;
    switch(gw_osc_integration)
    {
        case 'CUSTOM_INTEGRATION':
            if(typeof(gweuvat_custom_integration) === 'function') {
                queue.add_function(function(){
                    gweuvat_custom_integration();
                });
            }
            break;
        case 'ADVANCED_CHECKOUT':
            if(typeof(oscheckout)==='object') {
                queue.add_function(function(){
                    oscheckout.saveAddress(true, true, true);
                });
            }
            break;
        case 'AHEADWORKS_CHECKOUT':
            if (typeof(AWOnestepcheckoutCoreUpdater) !== "undefined" && typeof(awOSCAddress) !== 'undefined') {
                queue.add_function(function(){
                    AWOnestepcheckoutCoreUpdater.startRequest(awOSCAddress.addressChangedUrl);
                });
                queue.add_function(function(){
                    awOSCAddress.onAddressChanged();
                });
            }
            break;
        case 'AMASTY_CHECKOUT':
            if(typeof(updateCheckout)==='function') {
                updateCheckout();
            }
            break;
        case 'APPTHA_CHECKOUT':
            if (typeof(AjaxupdateShippingandPayment) === 'function')
            {
                queue.add_function(function(){
                    AjaxupdateShippingandPayment();
                });
            }
            break;
        case 'DRAGONFROOT_CHECKOUT':
            if(typeof(window.jQuery.dragonfroot.onestepcheckout) === 'function') {
                window.jQuery.dragonfroot.onestepcheckout.prototype._updateLocation(null, 'billing_shipping');
            }
            break;
        case 'ECOMDEV_CHECKOUT':
            if (typeof(review) === 'object') review.load();
            break;
        case 'ECOMTEAM_CHECKOUT':
            if (typeof(EasyCheckout) !== 'undefined') {
                EasyCheckout.instance.addressChangedEvent();
            }
            break;
        case 'GOMAGE_CHECKOUT':
            if (typeof(checkout) === 'object') {
                checkout.submit(checkout.getFormData(), 'get_totals');
            }
            break;
        case 'ONESTEP_CHECKOUT':
            if (typeof(document.getElementById('onestepcheckout-form')) === "object")
            {
                if(typeof(get_save_billing_function) === "function") {
                    queue.add_function(function(){
                        get_save_billing_function(gw_idev_url_save_billing, gw_idev_url_set_methods, true, true)();
                    });
                }
                if(typeof(jQuery) === 'function') {
                    queue.add_function(function(){
                        jQuery('#checkout-payment-method-load dt input:checked').click();
                    });
                }
            }
            break;
        case 'IWD_CHECKOUT':
            if (typeof(IWD) === 'object' && typeof(IWD.OPC.Checkout) === 'object') {
                queue.add_function(function(){
                    IWD.OPC.Checkout.reloadShippingsPayments();
                });
                queue.add_function(function(){
                    IWD.OPC.Checkout.pullReview();
                });
            } else if(typeof(checkout) === 'object') {
                queue.add_function(function(){
                    checkout.update();
                });
            }
            break;
        case 'FACILE_CHECKOUT':
            if(typeof(checkout) === 'object') {
                checkout.update();
            }
            break;
        case 'FME_CHECKOUT':
            if (typeof(document.getElementById('onestepcheckout-form')) !== "undefined") {
                billing.saveCountry();
            }
            break;
        case 'VINAGENTO_CHECKOUT':
            if (typeof(onestepcheckout) === 'object') {
                onestepcheckout.reloadReview();
            }
            break;
        case 'TM_CHECKOUT':
            if (typeof(FireCheckout) === 'function'
                && typeof(checkout) === 'object'
            ){
                setTimeout(function(){
                    var sameAsBilling = $('shipping:same_as_billing');
                    if (!sameAsBilling || (sameAsBilling && sameAsBilling.checked)) {
                        queue.add_function(function () {
                            checkout.update(checkout.urls.billing_address);
                        });
                    } else {
                        queue.add_function(function () {
                            checkout.update(checkout.urls.shipping_address);
                        });
                    }
                    queue.add_function(function(){
                        checkout.update(checkout.urls.shopping_cart);
                    });
                }, 200);
            }
            break;
        case 'MAGESTORE_CHECKOUT':
            if (typeof(document.getElementById('checkout-review-load')) !== "undefined")
            {
                $$('select[name="billing[country_id]"] option').each(function (o) {
                    if (o.readAttribute('value') === response.country_id) {
                        o.selected = true;
                    }
                });
                $$('select[name="shipping[country_id]"] option').each(function (o) {
                    if (o.readAttribute('value') === response.country_id) {
                        o.selected = true;
                    }
                });
                save_address_information(save_address_url,true,true,true); // url, update shipping, update payment methods, update totals
            }
            break;
        case 'MGS_OSCHECKOUT':
            if(typeof(checkout) === 'object') {
                checkout.loadReview();
            }
            break;
        case 'MGKOS_OSCHECKOUT':
            if(typeof(checkout) === 'object') {
                checkout.update({'payment-method': 1, 'shipping-method': 1, 'review': 1});
            }
            break;
        case 'NEXTBITS_CHECKOUTNEXT':
            if (typeof(checkoutnext) !== 'undefined') {
                checkoutnext.reloadReview();
            }
            break;
        case 'CMSMART_CHECKOUT':
            if (typeof(document.getElementById('onepage-form')) !== "undefined" && typeof(updateQtyProduct)==='function') {
                updateQtyProduct();
            }
            break;
        case 'MAGEMART_QUICKCHECKOUT':
            ajaxSaveBillShipData(ajaxSaveBillShipInfoUrl);
            break;
        case 'OLEGNAX_OPC':
            if(typeof(olegnaxOSCAddress) === 'object') {
                olegnaxOSCAddress.addressChangedEvent()
            }
            break;
        case 'OCODEWIRE_ONESTEPCHECKOUT':
            get_save_billing_function(document.location.href + 'ajax/billing_details', document.location.href + 'ajax/set_methods_separate')();
            break;
        case 'KALLYAS_OPC':
            if (typeof(checkout) === 'object')
            {
                checkout.update();
            }
            break;
        case 'UNI_OPC':
            if (typeof(checkout) === 'object')
            {
                billingStep.save();
            }
            break;
        case 'MAGEBAY_OPC':
            if(typeof(jQuery) === 'function')
            {
                var url = jQuery('#mst-address-request').val()+'load/update_shipping_review_index';
                jQuery.ajax({
                    type: "POST",
                    url: url,
                    data: 'refesh=refesh',
                    cache: false,
                    beforeSend:  function() {
                        jQuery('.load_review').show();
                        jQuery('#checkout-review-table-wrapper').css('opacity','0.5');
                    },
                    success: function(html){
                        var _json=jQuery.parseJSON(html);
                        jQuery('.load_review ').hide();
                        jQuery('#checkout-review-table-wrapper').css('opacity','1');
                        jQuery('#checkout-review-load').html(_json.info);
                    },
                    complete: function(data){}
                });
            }

            break;
        case 'MAGEGIANT_OPC':
            if (typeof(giantOSCAddress) === 'object')
            {
                giantOSCAddress.onAddressChanged();
            }
            break;
        case 'MAGEDRIVE_OSC':
            if (typeof(save_address_information) === 'function')
            {
                save_address_information(save_address_url);
            }
            break;
        case 'MAGEWORLD_OPC':
            if(typeof(view_onestep_billing) === 'object') {
                view_onestep_billing.hdlChangeCountry();
            }
            break;
        case 'LOTUSBREATH_OSC':
            if(typeof(jQuery) === 'function' && typeof(jQuery.lotusbreath) === 'object')
            {
                var yesRadio = $('billing:use_for_shipping_yes');
                var noRadio = $('billing:use_for_shipping_no');
                if(yesRadio.checked === true) {
                    yesRadio.click();
                } else {
                    noRadio.click();
                }
            }
            break;
        case 'WP_OPC':
            if(typeof(updateTotalView) === 'function')
            {
                queue.add_function(function(){
                    updateTotalView();
                });
            }
            break;
        case 'TYPOSTORES_OPC':
            if(typeof(jQuery) === 'function' && typeof(jQuery('#checkoutSteps').onestepcheckout('instance')) === 'object') {
                jQuery('#checkoutSteps').onestepcheckout('instance')._updateLocation();
            }
            break;
        case '': default: break;
    }
};