/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

AdminOrder.prototype.validateVat = AdminOrder.prototype.validateVat.wrap(function(parentMethod, parameters) // Wraps method of concrete instance
{
    var params = {
        country: $(parameters.countryElementId).value,
        vat: $(parameters.vatElementId).value,
        op_mode: 'SINGLE'
    };
    params.country_prefix = params.vat.substr(0, 2);

    if(params.vat === "") {
        alert(Translator.translate('Please declare a VAT number before validating.'));
        return;
    }

    if(!params.vat.match(new RegExp('^[A-Z][A-Z]'))) {
        alert(Translator.translate('Please put the VAT number including the country prefix.'));
        return;
    }

    if( $(parameters.vatElementId).id === 'order-billing_address_vat_id' ) {
        params.address_type = 'billing';
    } else {
        params.address_type = 'shipping';
    }

    if(params.country !== params.country_prefix) {
        var countrySelect = $$('#order-'+params.address_type+'_address_country_id');
        alert(Translator.translate('The selected address country ('+countrySelect[0].value+') does not match the VAT number country prefix ('+params.country_prefix+'). Please set the correct address country.'));
        return;
    }

    if (this.storeId !== false) {
        params.store_id = this.storeId;
    }

    var currentCustomerGroupId = $(parameters.groupIdHtmlId).value;
    var response_field = 'response_'+$(parameters.vatElementId).id;

    if(typeof(address_id) == 'undefined') {
        params.address_id = 0;
    }

    new Ajax.Request(parameters.validateUrl, {
        parameters:'taxvat='+params.vat+'&op_mode='+params.op_mode+'&address_type='+params.address_type+'&address_id='+params.address_id,
        onLoading:function () {
            $(response_field).hide();
        },
        onComplete:function () {
            $(response_field).show();
        },
        onSuccess: function(transport) {
            var response = transport.responseText.evalJSON();
            var output = '<div class="vat_response">';
            var groupChangeRequired = false;
            var message;

            if (response.vat_is_valid === true ) {
                output += (Translator.translate('The VAT-ID is valid.'));
                output += '</div>';
                message = parameters.vatValidMessage;

            } else if (response.vat_is_valid === false ) {
                output += (Translator.translate('The VAT-ID is invalid.'));
                output += '</div>';
                message = parameters.vatInvalidMessage;
            }

            if(typeof(response.faultstring) != "undefined") {
                switch (response.faultstring) {
                    case "INVALID_INPUT":
                        output += (Translator.translate('The VAT-ID is invalid, please check the syntax.'));
                        break;
                    case "SERVICE_UNAVAILABLE":
                    case "SERVER_BUSY":
                        output += (Translator.translate('Currently the European VIES service is unavailable.'));
                        break;
                    case "MS_UNAVAILABLE":
                    case "TIMEOUT":
                        output += (Translator.translate('Currently the member state service is unavailable.'));
                        break;
                    default:
                        output += (Translator.translate('There was an error processing your request.'));
                        break;
                }
                output += '</div>';
                message = parameters.vatValidationFailedMessage;
            }
            $(response_field).update(output);

            if (currentCustomerGroupId !== response.group) {
                message = parameters.vatValidAndGroupChangeMessage;
                groupChangeRequired = true;
            }
            if(groupChangeRequired) {
                this.processCustomerGroupChange(parameters.groupIdHtmlId, message, response.group);
            }

        }.bind(this)
    });

});