<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */

if($this->canShowBlock()): ?>
<?php $filters = Mage::getSingleton("catalog/layer")->getState()->getFilters(); ?>
<div class="block block-layered-nav<?php if (!$this->getLayer()->getState()->getFilters()): ?> block-layered-nav--no-filters<?php endif; ?>">
  <?php if(empty($filters) !== true) { ?>
    <div class="block-title">
      <strong><span>Huidige filters:</span></strong>
    </div>
  <?php
  }
  ?>
  <div class="block-content toggle-content">
    <?php echo $this->getStateHtml(); ?>    
    <?php if($this->canShowOptions()): ?>
      <p class="block-subtitle block-subtitle--filter"><?php echo $this->__('Filter') ?></p>
      <dl id="narrow-by-list">
        <?php $_filters = $this->getFilters() ?>
        <?php foreach ($_filters as $_filter): ?>
        <?php if($_filter->getItemsCount()): ?>
          <dt><?php echo $this->__($_filter->getName()) ?></dt>
          <dd><?php echo $_filter->getHtml() ?></dd>
        <?php endif; ?>
        <?php endforeach; ?>
      </dl>
      <script>decorateDataList('narrow-by-list')</script>
    <?php endif; ?>
  </div>
</div>
<?php endif; ?>
