<?php

// @todo find out if this file is being used

$show_toolbar     = false;
$_columnCount     = 4;
$displaySize      = 200;
$_imgSize         = 1 * $displaySize;

// Some helpers
$_helper = $this->helper("catalog/output");
$storeId = Mage::app()->getStore()->getId();
$catalog = $this->getLayout()->createBlock("catalog/product_list")->setStoreId($storeId);

// Get all products that are marked as featured
$_productCollection = Mage::getModel("catalog/product")->getCollection();
$_productCollection->addAttributeToSelect("featured");
$_productCollection->addFieldToFilter([["attribute" => "featured", "eq" => true]],))->addOrder("name", "ASC");

/*
 * Bugfix: Using require_stock_items there was a bug that lead
 * to wrong stock info on listview during flat index rebuild.
 * addItemsToProducts() seems to add stock data correctly even during a reindex
 *
 * However, with addItemsToProducts() we are missing essential stock data like
 * manage_stock, leading to wrong results.
 *
 * We now use both as an experiment...
 */
$_productCollection->setFlag('require_stock_items', true);
Mage::getModel('catalogInventory/stock')->addItemsToProducts($_productCollection);

$_collectionSize = $_productCollection->count();

$productBlock = $this->getLayout()->createBlock("catalog/product_price");

if(0) {
  
  
  
  
  
  
  
  
  
  
  
  
  
} else {
  
  ?>
  
  <div class="category-products asdf" style="clear: both;">
    <ul class="products-grid products-grid--max-4-col" id="featured-products-list">
      <li class="item">
        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
          <img id="product-collection-image-<?php echo $_product->getId(); ?>"
               src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
               alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        </a>
        <?php
          $garentiim = $_product->getAttributeText('garantie');
          if($garentiim == '24 maanden'){
           ?>
           <img src="/skin/frontend/rwd/dhh/images/garantieicon.png" title="2 jaar garantie!" alt="2 jaar garantie!" class="lbl24gran" width=67 height=67 />
           <?php
          }
        ?>
        <div class="product-info">
          <div class="info">
          <ul>
            <?php
            $cats = $_product->getCategoryIds();
            $catid = '';
            foreach($cats as $category_id) {
              $catid = $category_id;
              break;
            }

            $attribute_value = $_product->getAttributeText('manufacturer');
            if($attribute_value != ''){
              echo '<li>'.$attribute_value.'</li>';
            } else {
              echo '<li>&nbsp;</li>';
            }
            ?>
           </ul>
          </div>
          <?php echo $productBlock->getPriceHtml($_product, true); ?>
          <div class="actions">
            <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
            <div class="more-inform"><a href="<?php echo $_product->getProductUrl() ?>">Meer informatie <i class="fa fa-angle-right"></i></a></div>
            <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span>+<i class="fa fa-shopping-cart"></i></span></span></button>
            <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
            <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
            <?php else: ?>
           <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <ul class="add-to-links">
              <?php if($this->helper('wishlist')->isAllow()) : ?>
              <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
              <?php endif; ?>
              <?php if(false && $_compareUrl=$this->getAddToCompareUrl($_product)): ?>
              <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
              <?php endif; ?>
            </ul>
          </div>
      </div>
      </li>
      <?php endforeach; ?>
    </ul>
  </div>
}
