<?php
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>

<form id="search_mini_form asdf" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
  <div class="input-box">
    <label><?php echo $this->__('Search:') ?>
      <input id="search" type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text required-entry" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" placeholder="<?php echo $this->quoteEscape($this->__('Search entire store here...')) ?>" />
    </label>
    <button type="submit" title="<?php echo $this->quoteEscape($this->__('Search')) ?>" class="button search-button">
      <i class="fa fa-search"></i> <?php //echo $this->__('Search') ?>
    </button>
  </div>

  <div id="search_autocomplete" class="search-autocomplete"></div>
  <script type="text/javascript">
  //<![CDATA[
    var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
    searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
  //]]>
  </script>
</form>
