<?php if ($this->isPossibleFireCheckout()):?>
  <button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">
    <span style="color: #fff; font-weight: 600;">
      <i class="fa fa-shopping-cart" style="font-size: 1.3em; margin-right: 10px; color: #fff;"></i>
      <?php echo $this->__('Proceed to Checkout') ?>
    </span>
  </button>
<?php endif?>
