<?php if ($this->isPossibleFireCheckout()):?>
  <button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>"
  class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?>
  no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?>
  onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">
    <span>
      <?php echo $this->__('Proceed to Checkout') ?>
    </span>
    <span class="float-right big" style="margin: 0 1em;">
      <i class="fa fa-chevron-right"></i>
    </span>
  </button>
<?php endif?>
