<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Adminhtml_Vat_SetupController extends Mage_Adminhtml_Controller_Action
{
    public function indexAction()
    {
        $this->_title(Mage::helper('euvatgrouper')->__('EU VAT Enhanced'))->_title(Mage::helper('euvatgrouper')->__('Setup'));
        $this->loadLayout()->_setActiveMenu('system')->renderLayout();
    }

    public function setupAction()
    {
        try {

            $post = $this->getRequest()->getPost();
            if(empty($post))
            {
                Mage::getSingleton('adminhtml/session')->addError( $this->__('Invalid form data.') );
                $this->_redirect('*/*');

            } else {

                $setup = Mage::getModel('euvatgrouper/setup_tax')->runSetup($post);
                if($setup)
                {
                    Mage::getSingleton('adminhtml/session')->addSuccess($this->__('EU VAT Enhanced Setup completed successfully. Please now apply your settings.'));
                    $this->_redirect('adminhtml/system_config/edit/section/euvatgrouper');
                } else {
                    $this->_redirect('*/*');
                }
            }

        } catch (Exception $e) {
            Mage::getSingleton('adminhtml/session')->addError($e->getMessage());
        }
    }

    public function skipAction()
    {
        Mage::getModel('euvatgrouper/setup_tax')->setIsInstalled();
        Mage::getSingleton('adminhtml/session')->addNotice($this->__('Automated Setup has been skipped. Please apply your settings now.'));
        $this->_redirect('adminhtml/system_config/edit/section/euvatgrouper');
    }

    /**
     * @return bool
     */
    public function _isAllowed()
    {
        return true;
    }

}