<?php

/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_GoogleAnalytics_Block_Ga $this */
$_helper = $this->helper('googleanalytics');
if(!$this->helper('core/cookie')->isUserNotAllowSaveCookie()):
  if($_helper->isUseAnalytics4()):
    $_gaAccountId = $_helper->getAccountId()
    // The script loads from Google Tag Manager, but we cannot disable this module entirely due
    // to the generation of the dataLayer events
    // <script async src="https://www.googletagmanager.com/gtag/js?id=< ?= $_gaAccountId ? >"></script>
    ?>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      <?= $this->_getPageTrackingCode($_gaAccountId) ?>
      <?= $this->_getEnhancedEcommerceDataForAnalytics4() ?>
    </script><?php
  endif;
endif;
