<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Block_System_Info extends Mage_Adminhtml_Block_System_Config_Form_Fieldset
{
	public function render(Varien_Data_Form_Element_Abstract $element)
	{

		$html = '
					<tr>
						<td class="label">Extension Version</td>
						<td class="value">'.Mage::getConfig()->getNode('modules/Geissweb_Euvatgrouper')->version.'</td>
						<td></td>
					</tr>
					<tr>
						<td class="label">Links</td>
						<td class="value">
						    <a href="https://www.geissweb.de/docs/" target="_blank">'.$this->__('Documentation').'</a> |
						    <a href="https://www.geissweb.de/knowledge-base.html" target="_blank">'.$this->__('Knowledge Base').'</a> |
						     <a href="'.$this->getUrl('adminhtml/vat_setup').'">'.$this->__('Run setup again').'</a>
                        </td>
						<td></td>
					</tr>

		';
		return $html;
	}

}
