<?php
/**
 * ||GEISSWEB| Invoice Auto Send
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL:
 * https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @category    Geissweb
 * @package     Geissweb_InvoiceAutoSend
 * @copyright   Copyright (c) 2015-2017 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_InvoiceAutoSend_Model_Invoice extends Geissweb_InvoiceAutoSend_Model_InvoiceRewrite
{
    /**
     * Send email with invoice data
     *
     * @param boolean $notifyCustomer
     * @param string  $comment
     *
     * @return Mage_Sales_Model_Order_Invoice
     * @throws Exception
     */
    public function sendEmail($notifyCustomer = true, $comment = '')
    {
        $order = $this->getOrder();
        $storeId = $order->getStore()->getId();

        if (!Mage::helper('sales')->canSendNewInvoiceEmail($storeId)) {
            return $this;
        }
        // Get the destination email addresses to send copies to
        $copyTo = $this->_getEmails(self::XML_PATH_EMAIL_COPY_TO);
        $copyMethod = Mage::getStoreConfig(self::XML_PATH_EMAIL_COPY_METHOD, $storeId);
        // Check if at least one recepient is found
        if (!$notifyCustomer && !$copyTo) {
            return $this;
        }

        // Start store emulation process
        $appEmulation = Mage::getSingleton('core/app_emulation');
        $initialEnvironmentInfo = $appEmulation->startEnvironmentEmulation($storeId);

        try {
            // Retrieve specified view block from appropriate design package (depends on emulated store)
            $paymentBlock = Mage::helper('payment')->getInfoBlock($order->getPayment())
                ->setIsSecureMode(true);
            $paymentBlock->getMethod()->setStore($storeId);
            $paymentBlockHtml = $paymentBlock->toHtml();
        } catch (Exception $exception) {
            // Stop store emulation process
            $appEmulation->stopEnvironmentEmulation($initialEnvironmentInfo);
            throw $exception;
        }

        // Stop store emulation process
        $appEmulation->stopEnvironmentEmulation($initialEnvironmentInfo);

        // Retrieve corresponding email template id and customer name
        if ($order->getCustomerIsGuest()) {
            $templateId = Mage::getStoreConfig(self::XML_PATH_EMAIL_GUEST_TEMPLATE, $storeId);
            $customerName = $order->getBillingAddress()->getName();
        } else {
            $templateId = Mage::getStoreConfig(self::XML_PATH_EMAIL_TEMPLATE, $storeId);
            $customerName = $order->getCustomerName();
        }

        $mailer = Mage::getModel('core/email_template_mailer');
        if ($notifyCustomer) {
            $emailInfo = Mage::getModel('core/email_info');
            $emailInfo->addTo($order->getCustomerEmail(), $customerName);
            if ($copyTo && $copyMethod == 'bcc') {
                // Add bcc to customer email
                foreach ($copyTo as $email) {
                    $emailInfo->addBcc($email);
                }
            }
            $mailer->addEmailInfo($emailInfo);
        }

        // Email copies are sent as separated emails if their copy method is 'copy' or a customer should not be notified
        if ($copyTo && ($copyMethod == 'copy' || !$notifyCustomer)) {
            foreach ($copyTo as $email) {
                $emailInfo = Mage::getModel('core/email_info');
                $emailInfo->addTo($email);
                $mailer->addEmailInfo($emailInfo);
            }
        }

	    $isFmeFieldsManager = false;
	    if(Mage::helper('core')->isModuleEnabled('FME_Fieldsmanager')) {
		    $isFmeFieldsManager = true;
		    $fieldmanagerObject = new Varien_Object();
		    if($additionalData = Mage::getModel('fieldsmanager/fieldsmanager')->GetFMData($order->getEntityId(),'orders',1)){
			    $fieldmanagerObject->setData($additionalData);
		    }
		    $html ='';
		    if(count($fieldmanagerObject->getData())){
			    $html = '<table border="0">';
			    $additionalData=Mage::getModel('fieldsmanager/fieldsmanager')->GetFMData($this->getEntityId(), 'orders' , false);
			    foreach ($additionalData as $info):
				    $html .= '<tr><td style="font-size:12px; line-height:10px; text-align: left; padding: 7px 9px 9px 9px;" width="165"><label style="font-weight:bold;">'. $info['label'] . '</label></td>';
				    $html .= '<td style="font-size:12px; line-height:10px; text-align: left; padding: 7px 9px 9px 9px;">'. $info['value'] .'</td></tr>';
			    endforeach;
			    $html .= '</table>';
		    }
		    $fieldmanagerObject->setData('html',$html);
	    }

        // Set all required params and send emails
        $mailer->setSender(Mage::getStoreConfig(self::XML_PATH_EMAIL_IDENTITY, $storeId));
        $mailer->setStoreId($storeId);
        $mailer->setTemplateId($templateId);
        $mailer->setTemplateParams(array(
                'order'        => $order,
                'invoice'      => $this,
                'comment'      => $comment,
                'billing'      => $order->getBillingAddress(),
                'payment_html' => $paymentBlockHtml,
                'fieldsmanager' => ($isFmeFieldsManager) ? $fieldmanagerObject : null
            )
        );

        try {
        	$fileNameTemplate = Mage::helper('invoiceautosend')->getFileNameTemplate();
        	$fileName = str_replace('{increment_id}', $this->getIncrementId(), $fileNameTemplate);
            $pdf = Mage::getModel('sales/order_pdf_invoice')->getPdf(array($this));
            $mailer->addPdf($pdf, $fileName);

        } catch (Exception $e) {
            Mage::logException($e);
        }

        $mailer->send();
        $this->setEmailSent(true);
        $this->_getResource()->saveAttribute($this, 'email_sent');

        return $this;
    }

}