<?php
/**
 * ||GEISSWEB| Invoice Auto Send
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL:
 * https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @category    Geissweb
 * @package     Geissweb_InvoiceAutoSend
 * @copyright   Copyright (c) 2015-2017 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_InvoiceAutoSend_Model_Observer
{
	public function salesOrderInvoiceSaveAfter($observer)
	{
		try {
			/**
			 * @var $invoice Mage_Sales_Model_Order_Invoice
			 */
			$invoice = $observer->getEvent()->getInvoice();
            $pm = $invoice->getOrder()->getPayment()->getMethod();
            $included = Mage::helper('invoiceautosend')->getIncludedPaymentMethods();

			if($invoice->getEmailSent() == null && in_array($pm, $included))
			{
				$invoice->sendEmail(true);
			}

		} catch (Mage_Core_Exception $e) {
			Mage::logException($e);
		}
	}
}