<fieldset class="form-list">
  <?php $_code=$this->getMethodCode() ?>
  <ul id="payment_form_<?php echo $_code ?>" style="display:none">
    <li>
      <div class="input-box">
        <img src="<?php echo Mage::getBaseUrl('media') . 'paysafecash/paysafecash.png'; ?>" alt="paysafecash">
      </div>
      <?php echo $this->__('PAY WITH CASH: Generate a barcode and go to a <a href="https://www.paysafecash.com/pos" target="blank">payment point near you</a> to complete the payment.') ?>
      <div style="padding: .5em 0;">Back to cash! Betaal nu gemakkelijk <strong>tot maximaal € 1.000,- per bestelling</strong> met cash.</div>
    </li>
  </ul>
</fieldset>
