<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Block_Adminhtml_Customer_Sales_Order_Create_Form_Account extends Mage_Adminhtml_Block_Sales_Order_Create_Form_Account
{
	/**
	 * Prepare Form and add elements to form
	 *
	 * @return Mage_Adminhtml_Block_Sales_Order_Create_Form_Account
	 */
	protected function _prepareForm()
	{
		/* @var $customerModel Mage_Customer_Model_Customer */
		$customerModel = Mage::getModel('customer/customer');

		/* @var $customerForm Mage_Customer_Model_Form */
		$customerForm   = Mage::getModel('customer/form');
		$customerForm->setFormCode('adminhtml_checkout')
			->setStore($this->getStore())
			->setEntity($customerModel);

		// prepare customer attributes to show
		$attributes     = array();

		// add system required attributes
		foreach ($customerForm->getSystemAttributes() as $attribute) {
			/* @var $attribute Mage_Customer_Model_Attribute */
			if ($attribute->getIsRequired()) {
				$attributes[$attribute->getAttributeCode()] = $attribute;
			}
		}

		/*
		if ($this->getQuote()->getCustomerIsGuest()) {
			unset($attributes['group_id']);
		}
		*/

		// add user defined attributes
		foreach ($customerForm->getUserAttributes() as $attribute) {
			/* @var $attribute Mage_Customer_Model_Attribute */
			$attributes[$attribute->getAttributeCode()] = $attribute;
		}

		$fieldset = $this->_form->addFieldset('main', array());

		$this->_addAttributesToForm($attributes, $fieldset);

		$this->_form->addFieldNameSuffix('order[account]');
		$this->_form->setValues($this->getFormValues());

		return $this;
	}

}
