<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL:
 * http://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (http://www.geissweb.de)
 * @license     http://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Block_Adminhtml_Report_Orders_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    protected $_countTotals = true;

    protected $_callbackCount = 1;

    public function __construct()
    {
        parent::__construct();
        $this->setId('euvatreportOrdersGrid');
        $this->setDefaultDir('ASC');
        $this->setSaveParametersInSession(true);
        $this->setPagerVisibility(false);
	    $this->prepareForm();

	    $this->setCollection(new Varien_Data_Collection());
        $this->setTemplate('euvatgrouper/euvat_report.phtml');
    }

	protected function _prepareLayout()
	{
		parent::_prepareLayout();
		$this->unsetChild('reset_filter_button');
		$this->unsetChild('search_button');
	}

    public function prepareForm()
    {
        $form = new Varien_Data_Form(array(
            'id' => 'test',
            'action' => $this->getUrl('adminhtml/vatreport_orders', array('year' => $this->getRequest()->getParam('year'))),
            'method' => 'post'
        ));
        $form->setUseContainer(true);

        $form->addField('year', 'select', array(
            'label'     => Mage::helper('euvatgrouper')->__('Year'),
            'name'      => 'year',
            'onchange' => '',
            'values' => Mage::helper('euvatgrouper/admin')->getYearRange(),
        ));

        $form->addField('period', 'select', array(
            'label'     => Mage::helper('euvatgrouper')->__('Period'),
            'name'      => 'period',
            'onchange' => '',
            'values' => Mage::helper('euvatgrouper/admin')->getMonthsArray(),
        ));

        $post = $this->getRequest()->getPost();
        if($post) {
            $this->setPost($post);
            $form->setValues($post);
        } else {
            $form->setValues(array(
                'year' => date("Y"),
                'period' => 'yy'
            ));
        }

        $form->addField('submit', 'submit', array(
            'class'      => 'scalable task submit form-button',
            'value' => Mage::helper('euvatgrouper')->__('Show Report'),
        ));

        $this->setForm($form);
    }

    protected function _prepareCollection()
    {
    	/** @var Mage_Sales_Model_Entity_Order_Collection $ordersCollection */
        $ordersCollection = Mage::getModel('sales/order')->getCollection()
            ->addFieldToSelect(array('entity_id', 'status', 'created_at', 'billing_address_id', 'shipping_address_id',
	            'tax_amount', 'increment_id', 'base_grand_total'))
            ->addFieldToFilter(array('status', 'status'),
                array(
                    array('eq' => 'complete'),
                    //array('eq' => 'processing')
                )
            );

        $post = $this->getRequest()->getPost();
        if($post) {

            $year = $post['year'];
            $period = $post['period'];

            switch($period)
            {
                case '01':case '02':case '03':case '04':case '05':case '06':
                case '07':case '08':case '09':case '10':case '11':case '12':
	                $gtEq = array('gteq'=>"$year-$period-01");
	                $ltEq = array('lteq'=>"$year-".($period+1)."-01");
	                break;
                case '1q':
                    $gtEq = array('gteq'=>$year."-01-01");
                    $ltEq = array('lteq'=>$year."-04-01");
                    break;
                case '2q':
                    $gtEq = array('gteq'=>$year."-04-01");
                    $ltEq = array('lteq'=>$year."-07-01");
                    break;
                case '3q':
                    $gtEq = array('gteq'=>$year."-07-01");
                    $ltEq = array('lteq'=>$year."-10-01");
                    break;
                case '4q':
                    $gtEq = array('gteq'=>$year."-10-01");
                    $ltEq = array('lteq'=>($year+1)."-01-01");
                    break;
                case 'yy':
                default:
                    $gtEq = array('gteq'=>$year."-01-01");
                    $ltEq = array('lteq'=>$year."-12-31");
                    break;
            }

        } else {
            $gtEq = array('gteq'=>date("Y")."-01-01");
            $ltEq = array('lteq'=>date("Y")."-12-31");
        }

        $ordersCollection
            ->addFieldToFilter('created_at', $gtEq)
            ->addFieldToFilter('created_at', $ltEq);

        $basedOn = (Mage::helper('euvatgrouper')->getVatBasedOn() != 'origin') ?
	        Mage::helper('euvatgrouper')->getVatBasedOn() : 'billing';


        $ordersCollection->getSelect()->join(
            array('order_address' => Mage::getConfig()->getTablePrefix().'sales_flat_order_address'),
            'order_address.entity_id = main_table.'.$basedOn.'_address_id',
	        array('vat_id', 'country_id', 'vat_request_id', 'vat_request_date'));

        $euCountries = Mage::helper('euvatgrouper')->getEuCountries();
        $merchantCountry = array(Mage::helper('euvatgrouper')->getMerchantCountryId());
        $countries = array_diff($euCountries, $merchantCountry);

        $ordersCollection->addFieldToFilter('vat_id', array('neq'=>''));
        $ordersCollection->addFieldToFilter('country_id', array('in'=>$countries));
        $ordersCollection->addFieldToFilter('tax_amount', array('lteq'=>0));
        $ordersCollection->setOrder('created_at', 'ASC');
        //$ordersCollection->getSelect()->group('vat_id');

	    Mage::getSingleton('euvatgrouper/resource_iterator_batched')->walk(
		    $ordersCollection,
		    array($this, 'prepareDataCallback')
	    );
	    //$ordersCollection->load();
	    //$this->setCollection($ordersCollection);

	    unset($ordersCollection, $euCountries, $merchantCountry, $countries);
        return parent::_prepareCollection();
    }

    public function prepareDataCallback($order)
    {
	    $invoice = $order->getInvoiceCollection()->getFirstItem();
	    $data = array(
	    	'id' => $this->_callbackCount,
		    'order_date' => $order->getCreatedAt(),
		    'order_increment_id' => $order->getIncrementId(),
		    //'order_address' => $order->getCompany().", ".$order->getFirstname()." ".$order->getLastname().", ".$order->getStreet().", ".$order->getPostcode().", ".$order->getCity(),
		    'invoice_date' => $invoice->getCreatedAt(),
		    'invoice_increment_id' => $invoice->getIncrementId(),
		    'vat_id' => strtoupper(str_replace(array(" ", "."), "", $order->getVatId())),
		    'net_sum' => (float)$order->getBaseGrandTotal(),
		    //'gross_sum' => (float)$order->getBaseGrandTotal(),
		    //'tax_amount' => (float)$order->getTaxAmount(),
		    'country' => $order->getCountryId(),
		    'vat_request_id' => $order->getVatRequestId(),
		    'vat_request_date' => $order->getVatRequestDate()
	    );

	    $item = new Varien_Object();
	    $item->setData($data);
	    $this->getCollection()->addItem($item);
	    unset($order, $item, $data, $invoice);
	    $this->_callbackCount++;
    }

    protected function _prepareColumns()
    {
	    $this->addColumn('id', array(
		    'header' => Mage::helper('euvatgrouper')->__('#'),
		    'align' => 'left',
		    'sortable' => false,
		    'filter' => false,
		    'index' => 'id'
	    ));

        $this->addColumn('order_date', array(
            'header' => Mage::helper('euvatgrouper')->__('Order Date'),
            'align' => 'left',
            'sortable' => false,
            'filter' => false,
            'index' => 'order_date'
        ));

        $this->addColumn('order_increment_id', array(
            'header' => Mage::helper('euvatgrouper')->__('Order Increment ID'),
            'align' => 'left',
            'sortable' => false,
            'filter' => false,
            'index' => 'order_increment_id'
        ));

        /*
	    $this->addColumn('order_address', array(
		    'header' => Mage::helper('euvatgrouper')->__('Order Address'),
		    'align' => 'left',
		    'sortable' => false,
		    'filter' => false,
		    'index' => 'order_address'
	    ));
        */

        $this->addColumn('invoice_date', array(
            'header' => Mage::helper('euvatgrouper')->__('Invoice Date'),
            'align' => 'left',
            'sortable' => false,
            'filter' => false,
            'index' => 'invoice_date'
        ));

        $this->addColumn('invoice_increment_id', array(
            'header' => Mage::helper('euvatgrouper')->__('Invoice Increment ID'),
            'align' => 'left',
            'sortable' => false,
            'filter' => false,
            'index' => 'invoice_increment_id'
        ));

        $this->addColumn('country', array(
            'header' => Mage::helper('euvatgrouper')->__('Country'),
            'align' => 'left',
            'sortable' => false,
            'filter' => false,
            'index' => 'country'
        ));

        $this->addColumn('vat_id', array(
            'header' => Mage::helper('euvatgrouper')->__('VAT number'),
            'align' => 'left',
            'sortable' => false,
            'filter' => false,
            'index' => 'vat_id'
        ));

        $this->addColumn('vat_request_id', array(
            'header' => Mage::helper('euvatgrouper')->__('Request Identifier'),
            'align' => 'left',
            'sortable' => false,
            'filter' => false,
            'index' => 'vat_request_id'
        ));
        $this->addColumn('vat_request_date', array(
            'header' => Mage::helper('euvatgrouper')->__('Request Date'),
            'align' => 'left',
            'sortable' => false,
            'filter' => false,
            'index' => 'vat_request_date'
        ));

        $this->addColumn('net_sum', array(
            'header' => Mage::helper('euvatgrouper')->__('Net Sum'),
            'align' => 'right',
            'sortable' => false,
            'filter' => false,
            'index' => 'net_sum'
        ));

        $this->addExportType('*/*/exportCsv', Mage::helper('euvatgrouper')->__('CSV'));
        $this->addExportType('*/*/exportXml', Mage::helper('euvatgrouper')->__('XML'));

        parent::_prepareColumns();
    }



    public function getTotals()
    {
        $totals = new Varien_Object();
        return $totals;
    }


    public function getRowUrl($row)	{return false;}


    /**
     * Retrieve a file container array by grid data as CSV
     *
     * Return array with keys type and value
     *
     * @param $fileName
     *
     * @return array
     */
    public function getXmlFile($fileName)
    {
        $this->_isExport = true;
        $this->_prepareGrid();

        $io = new Varien_Io_File();

        $path = Mage::getBaseDir('var') . DS . 'export' . DS;
        $file = $path . DS . $fileName;

        $io->setAllowCreateFolders(true);
        $io->open(array('path' => $path));
        $io->streamOpen($file, 'w+');
        $io->streamLock(true);
        $io->streamWrite($this->getXml());
        $io->streamUnlock();
        $io->streamClose();

        return array(
            'type'  => 'filename',
            'value' => $file,
            'rm'    => true // can delete file after use
        );
    }

    /**
     * @return string
     */
    public function getXml()
    {
        $this->_isExport = true;
        $this->_prepareGrid();
        $indexes = array();
        foreach ($this->_columns as $column) {
            if (!$column->getIsSystem()) {
                $indexes[] = $column->getIndex();
            }
        }
        $xml = '<?xml version="1.0" encoding="UTF-8"?>';
        $xml.= '<items>';
        foreach ($this->getCollection() as $item) {
            $xml.= $item->toXml($indexes);
        }
        if ($this->getCountTotals())
        {
            $xml.= $this->getTotals()->toXml($indexes);
        }
        $xml.= '</items>';
        return $xml;
    }
}
