<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

/**
 * Class Geissweb_Euvatgrouper_Model_Resource_Iterator_Batched
 *
 * Batched Iterator (c) https://gist.github.com/kalenjordan/5483065
 */
class Geissweb_Euvatgrouper_Model_Resource_Iterator_Batched extends Varien_Object
{
	const DEFAULT_BATCH_SIZE = 50;

	/**
	 * @param $collection Varien_Data_Collection
	 * @param array $itemCallback
	 * @param array $batchCallback
	 * @param int $batchSize
	 */
	public function walk($collection, array $itemCallback, array $batchCallback, $batchSize = null)
	{
		if (!$batchSize) {
			$batchSize = self::DEFAULT_BATCH_SIZE;
		}

		$collection->setPageSize($batchSize);

		$currentPage = 1;
		$pages = $collection->getLastPageNumber();

		do {
			$collection->setCurPage($currentPage);
			$collection->load();
			foreach ($collection as $item) {
				call_user_func($itemCallback, $item);
			}

			call_user_func($batchCallback);

			$currentPage++;
			$collection->clear();

		} while ($currentPage <= $pages);

	}
}