<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Model_System_Config_Source_Oscintegration {

	/**
	 * Options getter
	 * @return array
	 */
	public function toOptionArray()
	{
		return array(
            array('value' => '', 'label' => Mage::helper('euvatgrouper')->__('-- NONE --')),
			array('value' => 'CUSTOM_INTEGRATION', 'label' => Mage::helper('euvatgrouper')->__('Custom Integration by GEISSWEB')),
            array('value' => 'ADVANCED_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('Advancedcheckout.com')),
            array('value' => 'AHEADWORKS_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('Aheadworks OnePageCheckout')),
            array('value' => 'AMASTY_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('Amasty OnePageCheckout')),
            array('value' => 'APPTHA_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('Apptha OneStepCheckout')),
            array('value' => 'CMSMART_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('CMSMart OneStepCheckout')),
			array('value' => 'DRAGONFROOT_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('Dragonfroot OneStepCheckout')),
            array('value' => 'ECOMDEV_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('EcomDev CheckItOut')),
            array('value' => 'ECOMTEAM_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('Ecommerceteam EasyCheckout')),
			array('value' => 'FACILE_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('Facile Checkout')),
            array('value' => 'FME_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('FME OneStepCheckout')),
            array('value' => 'GOMAGE_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('GoMage LightCheckout')),
            array('value' => 'IWD_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('IWD One Step/Page Checkout')),
            array('value' => 'KALLYAS_OPC', 'label' => Mage::helper('euvatgrouper')->__('Kallyas OnePageCheckout')),
            array('value' => 'LOTUSBREATH_OSC', 'label' => Mage::helper('euvatgrouper')->__('Lotus Breath OneStepCheckout')),
            array('value' => 'MAGEBAY_OPC', 'label' => Mage::helper('euvatgrouper')->__('MageBay OPC')),
            array('value' => 'MAGEGIANT_OPC', 'label' => Mage::helper('euvatgrouper')->__('MageGiant OPC')),
            array('value' => 'MAGESTORE_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('MageStore OneStepCheckout')),
            array('value' => 'MAGEMART_QUICKCHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('Magemart Quickcheckout')),
            array('value' => 'MAGEDRIVE_OSC', 'label' => Mage::helper('euvatgrouper')->__('Magedrive OneStepCheckout')),
			array('value' => 'MAGEWORLD_OPC', 'label' => Mage::helper('euvatgrouper')->__('MageWorld OneStepCheckout')),
			array('value' => 'MGKOS_OSCHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('MGKOS OneStepCheckout')),
			array('value' => 'MGS_OSCHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('MGS Oscheckout')),
            array('value' => 'NEXTBITS_CHECKOUTNEXT', 'label' => Mage::helper('euvatgrouper')->__('Nextbits CheckoutNext')),
            array('value' => 'OCODEWIRE_ONESTEPCHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('Ocodewire OneStepCheckout')),
			array('value' => 'ONESTEP_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('IDEV OneStepCheckout')),
            array('value' => 'OLEGNAX_OPC', 'label' => Mage::helper('euvatgrouper')->__('Olegnax OneStepCheckout')),
            array('value' => 'TM_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('TemplatesMaster FireCheckout')),
			array('value' => 'TYPOSTORES_OPC', 'label' => Mage::helper('euvatgrouper')->__('Typostores OneStepCheckout')),
            array('value' => 'UNI_OPC', 'label' => Mage::helper('euvatgrouper')->__('Unicode ExpressCheckout')),
            array('value' => 'VINAGENTO_CHECKOUT', 'label' => Mage::helper('euvatgrouper')->__('Vinagento Oscheckout')),
            array('value' => 'WP_OPC', 'label' => Mage::helper('euvatgrouper')->__('WebAndPeople OnePageCheckout')),
		);
	}
}