<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Model_System_Config_Source_Validationperiod {

    const EVERY_LOGIN = 0;
    const EVERY_MONTH = 1;
    const EVERY_THREE_MONTHS = 3;
    const EVERY_SIX_MONTHS = 6;
    const EVERY_YEAR = 12;


    /**
     * Options getter
     * @return array
     */
    public function toOptionArray()
    {
        return array(
            array('value' => self::EVERY_LOGIN, 'label' => Mage::helper('euvatgrouper')->__('On every login')),
            array('value' => self::EVERY_MONTH, 'label' => Mage::helper('euvatgrouper')->__('Every month')),
            array('value' => self::EVERY_THREE_MONTHS, 'label' => Mage::helper('euvatgrouper')->__('Every 3 months')),
            array('value' => self::EVERY_SIX_MONTHS, 'label' => Mage::helper('euvatgrouper')->__('Every 6 months')),
            array('value' => self::EVERY_YEAR, 'label' => Mage::helper('euvatgrouper')->__('Every year')),
        );
    }
}