<?php
/**
 * @category  design
 * @package   rwd_default
 * @copyright Copyright (c) 2006-2020 Magento, Inc. (http://www.magento.com)
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

$_orders = $this->getOrders();
?>
<div class="box-account box-recent">
  <div class="box-head">
    <h2><?php echo $this->__('Recent Orders') ?></h2>
    <?php if(sizeof($_orders->getItems()) > 0): ?><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('View All') ?></a><?php endif; ?>
  </div>
<?php if(sizeof($_orders->getItems()) > 0): ?>
  <table class="data-table orders" id="my-orders-table">
    <colgroup>
      <col style="width:10%">
      <col style="width:10%">
      <col style="width:40%">
      <col style="width:10%">
      <col style="width:15%">
      <col style="width:15%">
    </colgroup>
    <thead>
      <tr>
        <th><?php echo $this->__('Order #') ?></th>
        <th><?php echo $this->__('Date') ?></th>
        <th><?php echo $this->__('Ship To') ?></th>
        <th><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
        <th><?php echo $this->__('Status') ?></th>
        <th>Acties</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($_orders as $_order): ?>
        <tr>
          <td><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $_order->getRealOrderId() ?></a></td>
          <td class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></td>
          <td><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
          <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
          <td><em><?php echo $_order->getStatusLabel() ?></em></td>
          <td class="view nobr">
            <a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
            <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
              <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
            <?php endif ?>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
<?php else: ?>
  <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>
