<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2017 X.commerce, Inc. and affiliates (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */

$_helper      = $this->helper('catalog/output');
$_category    = $this->getCurrentCategory();

$brand_name   = strtolower($_category->getName());
$brand_slug   = Mage::helper("deheerhoreca_util/util")->getBrandUrlSlug($brand_name);
$brand_logo   = "/media/wysiwyg/brands/prokoeling.png";

$htbrand      = null;

if(empty($brand_name) === false) {
  $brand = sanitizeForFilename($brand_name);
  $htbrand = $this->getLayout()->createBlock('cms/block')->setBlockId($brand)->toHtml();
  $brand_logo_file = "media/wysiwyg/brands/{$brand_slug}.png";
  if(is_file($brand_logo_file) === true) {
    $brand_logo = "/".$brand_logo_file;
  }
}

// Mixed mode = shop by brand
if($this->isMixedMode()) {
  
  $ctdesc_h1 = "Bekijk ons complete ".$_helper->categoryAttribute($_category, $_category->getName(), 'name')." assortiment";
  
  echo "<div class='ctdesc'>";
  echo "<img class='float-right' alt='".ucfirst($brand)." logo' title='".ucfirst($brand)."' id='brand_logo_small' src='{$brand_logo}' />";
  echo "<h1>{$ctdesc_h1}</h1>";
  echo $htbrand.$this->getCmsBlockHtml();
  echo "</div>";
  define("CTDESC_H1_SENT", true);
}

echo $this->getMessagesBlock()->toHtml();

if($this->isContentMode()) {
  echo $this->getCmsBlockHtml();
} elseif($this->isMixedMode()) {
  echo $this->getProductListHtml();
} else {
  echo $this->getProductListHtml();
}
