<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2017 X.commerce, Inc. and affiliates (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */

// Mixed mode = shop by brand
// Mixed mode = "products and static block"
if($this->isMixedMode()) {
  
  $_category            = $this->getCurrentCategory();
  $brand_name           = strtolower($_category->getName());
  
  if(empty($brand_name) === false) {
    $brand                = sanitizeForFilename($brand_name);  
    $brand_slug           = Mage::helper("deheerhoreca_util/util")->getBrandUrlSlug($brand_name);
    $brand_logo_file      = "media/wysiwyg/brands/{$brand_slug}.png";
    if(is_file($brand_logo_file) === true) {
      $brand_logo         = "/".$brand_logo_file;
    }
    
    // Optional block BRAND is shown above the category tiles
    $brand_block_name     = $brand;
    $brand_block_html     = $this->getLayout()->createBlock("cms/block")->setBlockId($brand_block_name)->toHtml();
    
    // Optional block shopbybrand-BRAND is shown below the category tiles
    $extra_block_name     = "shopbybrand-{$brand}";
  }
  
  $brand_name           = $this->helper("catalog/output")->categoryAttribute($_category, $_category->getName(), "name");
  $ctdesc_h1            = "Bekijk ons <span class='orange'>{$brand_name}</span> assortiment";
}

// Shop by brand series
elseif(isset($_GET["manufacturer"]) && is_numeric($_GET["manufacturer"])) {
  $singleton_prod = Mage::getSingleton('catalog/product')
    ->setStoreId(Mage::app()->getStore()->getId())
    ->setData("manufacturer", $_GET["manufacturer"]); 
  $value = $singleton_prod->getAttributeText("manufacturer");
  $ctdesc_h1 = "Bekijk ons <span class='orange'>{$value}</span> assortiment";
  
  // Guess the brand and try to find a logo
  if(empty($value) === false) {
    $brand                = sanitizeForFilename($value);  
    $brand_slug           = Mage::helper("deheerhoreca_util/util")->getBrandUrlSlug($brand_name);
    $brand_logo_file      = "media/wysiwyg/brands/{$brand_slug}.png";
    if(is_file($brand_logo_file) === true) {
      $brand_logo         = "/".$brand_logo_file;
    }
  }
  
  // Optional block BRAND_SERIES is shown above the category tiles
  $extra_block_name = "brand_series_{$brand_series}";
}

// Shop by brand series
elseif(isset($_GET["brand_series"]) && is_numeric($_GET["brand_series"])) {
  $singleton_prod = Mage::getSingleton('catalog/product')
    ->setStoreId(Mage::app()->getStore()->getId())
    ->setData("brand_series", $_GET["brand_series"]); 
  $value = $singleton_prod->getAttributeText("brand_series");
  $ctdesc_h1 = "Bekijk ons <span class='orange'>{$value}</span> assortiment";
  
  // Guess the brand and try to find a logo
  if(empty($value) === false) {
    $brand_name           = strtok($value, " ");
    if(empty($brand_name) === false) {
      $brand                = sanitizeForFilename($brand_name);  
      $brand_slug           = Mage::helper("deheerhoreca_util/util")->getBrandUrlSlug($brand_name);
      $brand_logo_file      = "media/wysiwyg/brands/{$brand_slug}.png";
      if(is_file($brand_logo_file) === true) {
        $brand_logo         = "/".$brand_logo_file;
      }
    }
  }
  
  // Optional block BRAND_SERIES is shown above the category tiles
  $extra_block_name = "brand_series_{$brand_series}";
}

// Display some HTML if we have it
$extra_block_html = "";
if(empty($extra_block_name) === false) {
  $extra_block_html = $this->getLayout()->createBlock("cms/block")->setBlockId($extra_block_name)->toHtml();
}
echo "<div class='ctdesc std'>";
if(empty($brand_logo) === false) {
  echo "<img class='float-right' alt='".htmlspecialchars($brand_name)." logo' id='brand_logo_small' src='{$brand_logo}'>";
}
if(empty($ctdesc_h1) === false) {
  echo "<div id='cat-text'>";
  echo "<h1>{$ctdesc_h1}</h1>{$brand_block_html}{$this->getCmsBlockHtml()}{$extra_block_html}";
  echo "</div>";
  define("CTDESC_H1_SENT", true);
}
echo "</div>";

echo $this->getMessagesBlock()->toHtml();

if($this->isContentMode()) {
  echo $this->getCmsBlockHtml();
} else {
  echo $this->getProductListHtml();
}
