<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2017 X.commerce, Inc. and affiliates (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */

// Category ID 2 means in root category, therefore not in a regular category
$at_root_category = (intval(Mage::registry('current_category')->getId()) === 2);

$brand_slug = ""; // Needs to exist

// Mixed mode = shop by brand
// Mixed mode = "products and static block"
if($this->isMixedMode()) {
  $_category    = $this->getCurrentCategory();
  $brand_name   = strtolower((string) $_category->getName());
  
  if(!empty($brand_name)) {
    $brand                = sanitize_alphanumeric($brand_name);  
    $brand_slug           = Mage::helper("deheerhoreca_util/util")->getBrandUrlSlug($brand_name);
    $brand_logo_file      = "media/wysiwyg/brands/{$brand_slug}.png";
    if(is_file($brand_logo_file)) {
      $brand_logo         = "/".$brand_logo_file;
    }
    $top_block_name       = $brand;                 // Optional block BRAND is shown above the category tiles
    $extra_block_name     = "shopbybrand-{$brand}"; // Optional block shopbybrand-BRAND is shown below the category tiles
  }
  $brand_name   = $this->helper("catalog/output")->categoryAttribute($_category, $_category->getName(), "name");
  $ctdesc_h1    = "Bekijk ons <span class='orange'>{$brand_name}</span> assortiment";
  // $this->getLayout()->getBlock('head')->setTitle("{$brand_name}"); // Too late for this
  $title = Mage::getStoreConfig('design/head/title_prefix')." Shop {$brand_name} ".Mage::getStoreConfig('design/head/title_suffix');
  \Chefstore\Html::addEncodedJsStatement("document.title=".json_encode($title));
}

// Shop by brand
elseif($at_root_category && isset($_GET["manufacturer"]) && is_numeric($_GET["manufacturer"])) {
  $singleton_prod = Mage::getSingleton('catalog/product')
    ->setStoreId(Mage::app()->getStore()->getId())
    ->setData("manufacturer", $_GET["manufacturer"]); 
  $brandHuman = $singleton_prod->getAttributeText("manufacturer");
  $ctdesc_h1 = "";
  
  // Guess the brand and try to find a logo
  if(!empty($brandHuman)) {
    $ctdesc_h1            = "Bekijk ons <span class='orange'>{$brandHuman}</span> assortiment";
    $brand_name           = $brandHuman;
    $brand_name           = sanitize_alphanumeric($brand_name);
    $brand_slug           = Mage::helper("deheerhoreca_util/util")->getBrandUrlSlug($brand_name);
    $brand_logo_file      = "media/wysiwyg/brands/{$brand_slug}.png";
    if(is_file($brand_logo_file)) {
      $brand_logo         = "/{$brand_logo_file}";
    }
  }
  // $this->getLayout()->getBlock('head')->setTitle("{$brandHuman}"); // Too late for this
  $title = Mage::getStoreConfig('design/head/title_prefix')." Shop {$brandHuman} ".Mage::getStoreConfig('design/head/title_suffix');
  \Chefstore\Html::addEncodedJsStatement("document.title=".json_encode($title));
  
  // Optional block shopbybrand-BRAND is shown above the category tiles
  $top_block_name     = "shopbybrand-{$brand_slug}-top";
  
  // Optional block shopbybrand-BRAND is shown below the category tiles
  $bottom_html_block  = "shopbybrand-{$brand_slug}";
}

// Shop by brand series
elseif($at_root_category && isset($_GET["brand_series"]) && is_numeric($_GET["brand_series"])) {
  $singleton_prod = Mage::getSingleton('catalog/product')
    ->setStoreId(Mage::app()->getStore()->getId())
    ->setData("brand_series", $_GET["brand_series"]); 
  $value = $singleton_prod->getAttributeText("brand_series");
  $ctdesc_h1 = "Bekijk ons <span class='orange'>{$value}</span> assortiment";
  $brand_series_slug = sanitize_alphanumeric($value);
  
  // Guess the brand and try to find a logo
  if(!empty($value)) {
    $brand_name           = strtok($value, " ");
    if(!empty($brand_name)) {
      $brand                = sanitize_alphanumeric($brand_name);  
      $brand_slug           = Mage::helper("deheerhoreca_util/util")->getBrandUrlSlug($brand_name);
      $brand_logo_file      = "media/wysiwyg/brands/{$brand_slug}.png";
      if(is_file($brand_logo_file)) {
        $brand_logo         = "/{$brand_logo_file}";
      }
    }
  }
  
  // Optional block BRAND_SERIES is shown above the category tiles
  $brand_series_slug = sanitize_alphanumeric($value, "_");
  $top_block_name = "brand_series_{$brand_series_slug}";
}

// Display some HTML if we have it
$top_block_html = "";
if(!empty($top_block_name)) {
  $top_block_html = $this->getLayout()->createBlock("cms/block")->setBlockId($top_block_name)->toHtml();
}
$extra_block_html = "";
if(!empty($extra_block_name)) {
  $extra_block_html = $this->getLayout()->createBlock("cms/block")->setBlockId($extra_block_name)->toHtml();
}

if(empty($brand_logo) === false || empty($ctdesc_h1) === false) {
  echo "<div class='ctdesc std'>";
  if(empty($brand_logo) === false) {
    echo "<img class='float-right' alt='".htmlspecialchars((string) $brand_name)." logo' id='brand_logo_small' src='{$brand_logo}'>";
  }
  if(empty($ctdesc_h1) === false) {
    echo "<div id='cat-text'>";
    echo "<h1>{$ctdesc_h1}</h1>{$top_block_html}{$this->getCmsBlockHtml()}{$extra_block_html}";
    echo "</div>";
    define("CTDESC_H1_SENT", true);
  }
  echo "</div>";
}

echo $this->getMessagesBlock()->toHtml();

if($this->isContentMode()) {
  echo $this->getCmsBlockHtml();
} else {
  echo $this->getProductListHtml();
}

// Bottom HTML block -- Best for large SEO content
if(!empty($bottom_html_block)) {
  echo "<div class='ctdesc std'>";
  echo $this->getLayout()->createBlock("cms/block")->setBlockId($bottom_html_block)->toHtml();
  echo "</div>";
}
