<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

/* @var $installer Mage_Customer_Model_Entity_Setup */
$installer = $this;
$installer->startSetup();

if (version_compare(Mage::getVersion(), '1.4.2', '>='))
{
    $attributes = array('vat_trader_name', 'vat_trader_address');
    foreach($attributes as $attribute)
    {
        $attrib = Mage::getSingleton('eav/config')->getAttribute('customer_address', $attribute);
        if($attrib instanceof Mage_Eav_Model_Entity_Attribute_Abstract) {
            $attrib->setData('used_in_forms', array('adminhtml_customer', 'adminhtml_checkout'));
            $attrib->save();
        }
    }
}

$installer->endSetup();