<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information: support@geissweb.de
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

/* @var $installer Mage_Customer_Model_Entity_Setup */
$installer = $this;
$installer->startSetup();

$table_sales_quote_address = $this->getTable('sales/quote_address');
$table_sales_order_address = $this->getTable('sales/order_address');

$data = array('type'=>Varien_Db_Ddl_Table::TYPE_TEXT,'length'=>255,'nullable'=> true,'comment'=>'Trader Name');
$data2 = array('type'=>Varien_Db_Ddl_Table::TYPE_TEXT,'length'=>255,'nullable'=> true,'comment'=>'Trader Address');

$installer->getConnection()->addColumn($table_sales_quote_address, 'vat_trader_name', $data);
$installer->getConnection()->addColumn($table_sales_quote_address, 'vat_trader_address', $data2);

$installer->endSetup();