<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2020] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2020 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

if (!Mage::helper('qquoteadv')->isEnabled()) return '';

$_product             = $this->getProduct();
$hideCartButton       = false;
$hideQuoteButton      = Mage::helper('qquoteadv')->hideQuoteButton($_product);
$buttonTitle_lease    = $this->__('Lease Aanvragen');
$action               = $this->helper('qquoteadv/catalog_product_data')->getAddToQuoteAction($_product->getId());
$mininum_lease_price  = 450;
$_finalPrice          = $_product->getFinalPrice();

if (Mage::getConfig()->getModuleConfig('Ophirah_Not2Order')->is('active', 'true') && $_product->getData('quotemode_conditions') > 0) {
  $hideCartButton     = Mage::helper('not2order')->autoHideCartButton($hideQuoteButton);
}

if($_product->getData('allowed_to_quotemode') == 1 && $hideQuoteButton === false && $_product->getStockItem()->getIsInStock()) {
  if (!$_product->isGrouped() && (!$_product->isSaleable() || $hideCartButton === true)) {
    ?>
    <div class="qty-wrapper">
      <label for="qty"><?php echo Mage::helper('catalog')->__('Qty:'); ?></label>
      <input type="text" pattern="\d*" name="qty" id="qty" maxlength="12"
        value="<?php echo max($this->getProductDefaultQty() * 1, 1) ?>"
        title="<?php echo Mage::helper('catalog')->__('Qty') ?>" class="input-text qty"/>
    </div>
}
  <?php } ?>

  <button type="button" title="<?php echo Mage::helper('qquoteadv')->__("Add to Quote"); ?>" class="button btn-cart btn-quote button-smaller" onclick="<?php echo $action; ?>">
    <?php echo Mage::helper('qquoteadv')->__("Add to Quote"); ?>
  </button>
<?php
  if(isset($_finalPrice) && $_finalPrice >= $mininum_lease_price) {
    ?>
    <button type="button" title="<?php echo $buttonTitle_lease ?>" class="button btn-lease btn button-smaller" onclick="<?php echo $action; ?>">
      <?php echo $buttonTitle_lease; ?>
    </button>
    <?php
  }
}
